// 英语世界 - 场景与剧情对话数据
// 核心玩法：真实场景连续对话，一步步完成整个任务链
// 多轮光顾：每个场景由多次"光顾"（visits）组成，每轮一个剧情线，通关一轮解锁下一轮
// 每步含：店员台词（多随机变体）+ 任务提示 + 3 选项 + 关键语块（phrase）+ 订单可视化素材（adds）

const SCENES = [
  {
    id: "cafe",
    name: "咖啡店",
    nameEn: "Coffee Shop",
    emoji: "☕",
    iconId: "coffee",
    cover: "☕🥐🍰",
    theme: "cafe",
    accent: "#9a5f36",
    accentSoft: "#f6e4d4",
    deco: "🎶",
    deco2: "🫧",
    intro: "你走进一家咖啡店，店员微笑着看向你。跟着引导，完成一次完整的英文点单吧！",
    orderLabel: "🧾 你的订单",
    items: [
      { id: "coffee",   en: "coffee",       zh: "咖啡",   phon: "/ˈkɒfi/",   emoji: "☕", sent: "I'd like a cup of coffee." },
      { id: "latte",    en: "latte",        zh: "拿铁",   phon: "/ˈlɑːteɪ/", emoji: "🥛", sent: "A latte with milk, please." },
      { id: "tea",      en: "tea",          zh: "茶",     phon: "/tiː/",     emoji: "🍵", sent: "Green tea is healthy." },
      { id: "juice",    en: "orange juice", zh: "橙汁",   phon: "/ˈɒrɪndʒ dʒuːs/", emoji: "🧃", sent: "Fresh orange juice, please." },
      { id: "cake",     en: "cake",         zh: "蛋糕",   phon: "/keɪk/",    emoji: "🍰", sent: "This cake is so sweet." },
      { id: "croissant",en: "croissant",    zh: "牛角包", phon: "/ˈkrwæsɒ̃/",emoji: "🥐", sent: "The croissant is crispy." },
      { id: "cookie",   en: "cookie",       zh: "曲奇",   phon: "/ˈkʊki/",   emoji: "🍪", sent: "I love chocolate cookies." },
      { id: "muffin",   en: "muffin",       zh: "玛芬",   phon: "/ˈmʌfɪn/",  emoji: "🧁", sent: "A blueberry muffin, please." },
      { id: "sandwich", en: "sandwich",     zh: "三明治", phon: "/ˈsænwɪdʒ/",emoji: "🥪", sent: "A cheese sandwich for lunch." },
      { id: "cup",      en: "cup",          zh: "杯子",   phon: "/kʌp/",     emoji: "🍵", sent: "My cup is empty." },
      { id: "menu",     en: "menu",         zh: "菜单",   phon: "/ˈmenjuː/", emoji: "📋", sent: "Can I see the menu?" },
      { id: "barista",  en: "barista",      zh: "咖啡师", phon: "/bəˈriːstə/",emoji: "🧑‍🍳", sent: "The barista makes great coffee." },
      // 第 2 轮（下午茶）新词
      { id: "friend",   en: "friend",       zh: "朋友",   phon: "/frend/",   emoji: "🧑‍🤝‍🧑", sent: "I'm here with my friend." },
      { id: "plate",    en: "plate",        zh: "盘子",   phon: "/pleɪt/",   emoji: "🍽️", sent: "Can we get a plate to share?" },
      { id: "fork",     en: "fork",         zh: "叉子",   phon: "/fɔːk/",    emoji: "🍴", sent: "Could I have a fork?" },
      { id: "table",    en: "table",        zh: "桌子",   phon: "/ˈteɪbl/",  emoji: "🪑", sent: "A table for two, please." },
      { id: "slice",    en: "slice",        zh: "一片",   phon: "/slaɪs/",   emoji: "🔪", sent: "A slice of chocolate cake." },
      // 第 3 轮（赶时间早餐）新词
      { id: "line",     en: "line",         zh: "队伍",   phon: "/laɪn/",    emoji: "🚶", sent: "The line is so long." },
      { id: "order",    en: "order",        zh: "点单",   phon: "/ˈɔːdə/",   emoji: "📝", sent: "Can I order quickly?" },
      { id: "rush",     en: "rush",         zh: "匆忙",   phon: "/rʌʃ/",     emoji: "🏃", sent: "I'm in a rush this morning." },
      { id: "bagel",    en: "bagel",        zh: "贝果",   phon: "/ˈbeɪɡl/",  emoji: "🥯", sent: "A bagel with cream cheese." },
      // 第 4 轮（特别定制）新词
      { id: "syrup",    en: "syrup",        zh: "糖浆",   phon: "/ˈsɪrəp/",  emoji: "🍯", sent: "Less syrup, please." },
      { id: "shot",     en: "shot",         zh: "一份浓缩", phon: "/ʃɒt/",   emoji: "⚡", sent: "Add an extra shot, please." },
      { id: "sweet",    en: "sweet",        zh: "甜的",   phon: "/swiːt/",   emoji: "🍬", sent: "Not too sweet, please." },
      { id: "iced",     en: "iced",         zh: "冰的",   phon: "/aɪst/",    emoji: "🧊", sent: "An iced latte sounds good." },
      { id: "name",     en: "name",         zh: "名字",   phon: "/neɪm/",    emoji: "🏷️", sent: "Can I get a name for the cup?" },
      // 第 5 轮（出错投诉）新词
      { id: "mistake",  en: "mistake",      zh: "错误",   phon: "/mɪˈsteɪk/", emoji: "❌", sent: "There's a mistake with my order." },
      { id: "receipt",  en: "receipt",      zh: "小票",   phon: "/rɪˈsiːt/",  emoji: "🧾", sent: "Here's your receipt." },
      { id: "replacement", en: "replacement", zh: "替换/重做", phon: "/rɪˈpleɪsmənt/", emoji: "🔄", sent: "Could I get a replacement?" },
      { id: "apology",  en: "apology",      zh: "道歉",   phon: "/əˈpɒlədʒi/", emoji: "🙏", sent: "My apologies for the mix-up!" },
      { id: "spill",    en: "spill",        zh: "洒出",   phon: "/spɪl/",    emoji: "💦", sent: "Oops, the coffee spilled!" },
      // 第 6 轮（问推荐忌口）新词
      { id: "recommend",en: "recommend",    zh: "推荐",   phon: "/ˌrekəˈmend/", emoji: "👍", sent: "What do you recommend?" },
      { id: "allergic", en: "allergic",     zh: "过敏的", phon: "/əˈlɜːdʒɪk/", emoji: "⚠️", sent: "I'm allergic to nuts." },
      { id: "difference",en: "difference",  zh: "区别",   phon: "/ˈdɪfrəns/", emoji: "🔍", sent: "What's the difference?" },
      { id: "nut",      en: "nut",          zh: "坚果",   phon: "/nʌt/",     emoji: "🥜", sent: "Does this contain nuts?" },
      { id: "soy",      en: "soy milk",     zh: "豆奶",   phon: "/sɔɪ mɪlk/", emoji: "🌱", sent: "I'll try soy milk today." },
      // 第 7 轮（咖啡文化）新词
      { id: "wifi",     en: "Wi-Fi",        zh: "无线网络", phon: "/ˈwaɪfaɪ/", emoji: "📶", sent: "Could I get the Wi-Fi password?" },
      { id: "restroom", en: "restroom",     zh: "洗手间", phon: "/ˈrestruːm/", emoji: "🚻", sent: "Where's the restroom?" },
      { id: "tall",     en: "tall",         zh: "中杯",   phon: "/tɔːl/",    emoji: "🥛", sent: "A tall latte, please." },
      { id: "grande",   en: "grande",       zh: "大杯",   phon: "/ˈɡrɑːndeɪ/", emoji: "🍶", sent: "Grande is the large size." },
      { id: "tip",      en: "tip",          zh: "小费",   phon: "/tɪp/",     emoji: "💰", sent: "Should I leave a tip?" },
      // 第 8 轮（会员优惠）新词
      { id: "rewards",  en: "rewards card", zh: "积分卡", phon: "/rɪˈwɔːdz kɑːd/", emoji: "💳", sent: "Do you have a rewards card?" },
      { id: "point",    en: "point",        zh: "积分",   phon: "/pɔɪnt/",   emoji: "⭐", sent: "You earn points on every drink." },
      { id: "giftcard", en: "gift card",    zh: "礼品卡", phon: "/ˈɡɪft kɑːd/", emoji: "🎁", sent: "Can I pay with a gift card?" },
      { id: "deal",     en: "deal",         zh: "优惠",   phon: "/diːl/",    emoji: "🏷️", sent: "Is there a deal on today?" },
      { id: "save",     en: "save",         zh: "省（钱）", phon: "/seɪv/",  emoji: "💰", sent: "You save two dollars with the deal." },
    ],
    // 多轮光顾：每轮一个剧情线，通关一轮解锁下一轮
    visits: [
      {
        id: "v1",
        title: "第 1 次光顾 · 经典点单",
        titleEn: "Classic Order",
        emoji: "☕",
        desc: "第一次来！学最基础的问候和点单句式。",
        reward: { en: "barista", zh: "你完成了一次完整的英文点单！☕" },
        steps: [
          {
            npcLines: [
              "Good morning! Welcome to Sunny Café. How are you today?",
              "Hi there, welcome in! How's it going today?",
              "Morning! Welcome to Sunny Café — how are you doing?",
            ],
            npcZh: "早上好！欢迎来到 Sunny 咖啡店。你今天怎么样？",
            task: "先和店员打个招呼，礼貌地回应",
            options: [
              { text: "I'm good, thank you! How are you?", ok: true,  tip: "礼貌回应 + 回问对方，完美的寒暄！" },
              { text: "Give me coffee.",                   ok: false, tip: "太直接啦，先友好问候会更有礼貌" },
              { text: "I don't know.",                     ok: false, tip: "店员在问你今天如何，可以回答 I'm good" },
            ],
            phrase: { en: "I'm good, thank you. How are you?", zh: "我很好，谢谢。你呢？", note: "万能寒暄回应：回答+回问，一来一回最自然" },
          },
          {
            npcLines: [
              "I'm doing great, thanks! What can I get for you today?",
              "Doing well, thanks! What'll it be today?",
              "Glad to hear! So, what can I get started for you?",
            ],
            npcZh: "我很好，谢谢！今天想来点什么？",
            task: "点一杯拿铁",
            options: [
              { text: "I'd like a latte, please.",    ok: true,  tip: "I'd like... 是最常用的礼貌点单句式！" },
              { text: "I want eat latte.",            ok: false, tip: "喝的用 drink，latte 前不用 eat" },
              { text: "Latte!!!",                     ok: false, tip: "加上 I'd like a ... please 更礼貌" },
            ],
            phrase: { en: "I'd like a ___, please.", zh: "我想要一个……", note: "点单万能句式：饮料食物都能套，比 I want 礼貌得多" },
            adds: [{ emoji: "☕", label: "Latte", wordId: "latte" }],
          },
          {
            npcLines: [
              "Great choice! What size would you like? We have small, medium, and large.",
              "Nice pick! What size — small, medium, or large?",
              "Good taste! Which size can I get you? Small, medium, or large?",
            ],
            npcZh: "好选择！您要什么杯型？我们有小杯、中杯和大杯。",
            task: "要一个大杯",
            options: [
              { text: "A large one, please.",       ok: true,  tip: "large = 大杯，small/medium = 小杯/中杯" },
              { text: "A big big one.",             ok: false, tip: "杯型标准说法是 large，不是 big big" },
              { text: "Give me the biggest cup!",   ok: false, tip: "店员提供的是 small / medium / large 三种" },
            ],
            phrase: { en: "A large one, please.", zh: "要大杯的", note: "large/medium/small 点单三连，加 one 指代饮品更地道" },
            adds: [{ emoji: "📏", label: "Large", badge: true }],
          },
          {
            npcLines: [
              "Large latte, got it. Would you like that with whole milk, skim milk, or oat milk?",
              "Large latte coming up! For the milk — whole, skim, or oat?",
              "One large latte! And which milk would you like? We have whole, skim, and oat.",
            ],
            npcZh: "大杯拿铁，记下了。您要全脂奶、脱脂奶还是燕麦奶？",
            task: "选燕麦奶",
            options: [
              { text: "Oat milk, please.",            ok: true,  tip: "oat milk 燕麦奶，现在很多咖啡店的流行选择" },
              { text: "Milk of oat I want.",          ok: false, tip: "语序不对，直接说 oat milk 就好" },
              { text: "I don't drink milk tea.",      ok: false, tip: "店员问的是选哪种奶，不是奶茶" },
            ],
            phrase: { en: "Oat milk, please.", zh: "要燕麦奶", note: "选奶直接说奶名+please：whole / skim / oat milk" },
            adds: [{ emoji: "🌾", label: "Oat", badge: true }],
          },
          {
            npcLines: [
              "Oat milk it is. Would you like anything to eat? Our croissants are fresh out of the oven!",
              "Oat milk, great! Anything to eat with that? The croissants just came out of the oven!",
              "Nice! And can I tempt you with something to eat? Fresh croissants, just baked!",
            ],
            npcZh: "燕麦奶拿铁。要不要来点吃的？我们的牛角包刚出炉！",
            task: "来一个牛角包",
            options: [
              { text: "A croissant sounds great, I'll take one.", ok: true,  tip: "I'll take one = 我要一个，地道说法" },
              { text: "I want eat croissant one.",                ok: false, tip: "说 I'll take a croissant 就好" },
              { text: "No hungry.",                               ok: false, tip: "想拒绝可以说 No, thanks. 但这次来一个吧" },
            ],
            phrase: { en: "I'll take one.", zh: "我要一个", note: "对方刚提过的东西，用 one 指代即可，简洁地道" },
            adds: [{ emoji: "🥐", label: "Croissant", wordId: "croissant" }],
          },
          {
            npcLines: [
              "Excellent! So that's a large oat milk latte and a croissant. Anything else?",
              "Perfect! So we've got a large oat milk latte and a croissant — anything else for you?",
              "Great! That's a large oat latte plus a croissant. Can I get you anything else?",
            ],
            npcZh: "好嘞！一个大杯燕麦奶拿铁和一个牛角包。还需要别的吗？",
            task: "确认不用了",
            options: [
              { text: "That's all, thank you.",   ok: true,  tip: "That's all = 就这些，点单收尾必备" },
              { text: "Nothing nothing.",         ok: false, tip: "更自然的说法是 That's all / That's it" },
              { text: "Give me everything.",      ok: false, tip: "哈哈那要花好多钱，说 That's all 即可" },
            ],
            phrase: { en: "That's all, thank you.", zh: "就这些，谢谢", note: "点单收尾句：店员问 Anything else? 的标准回答" },
          },
          {
            npcLines: [
              "Perfect. Your total is seven dollars fifty.",
              "Alright, that'll be seven fifty.",
              "Great! So your total comes to seven dollars fifty.",
            ],
            npcZh: "完美。您一共消费 7 美元 50 美分。",
            task: "用卡付款",
            options: [
              { text: "Can I pay by card?",            ok: true,  tip: "pay by card 刷卡付款，也可以说 by credit card" },
              { text: "I pay with my card money.",     ok: false, tip: "自然说法是 pay by card 或 with my card" },
              { text: "Here is my card, take it!",     ok: false, tip: "可以说 Can I pay by card? 更礼貌清楚" },
            ],
            phrase: { en: "Can I pay by card?", zh: "可以刷卡吗？", note: "付款方式问法：by card / in cash / with my phone" },
            adds: [{ emoji: "💳", label: "Paid $7.50", badge: true }],
          },
          {
            npcLines: [
              "Of course, card is fine... Approved! Here's your receipt. For here or to go?",
              "Sure thing... approved! Here you go. Is that for here or to go?",
              "No problem... all set! Receipt's in the bag. Are you staying in or taking it to go?",
            ],
            npcZh: "当然可以，刷卡没问题……扣款成功！这是您的小票。您在这儿吃还是带走？",
            task: "选择带走",
            options: [
              { text: "To go, please.",            ok: true,  tip: "to go = 外带；堂食说 for here" },
              { text: "I go with coffee.",         ok: false, tip: "外带的固定说法是 to go" },
              { text: "Take it to my home.",       ok: false, tip: "店员问堂食还是外带，回答 to go 即可" },
            ],
            phrase: { en: "To go, please.", zh: "带走，谢谢", note: "咖啡店灵魂拷问 For here or to go? 的标准答案" },
            adds: [{ emoji: "🥡", label: "To go", badge: true }],
          },
          {
            npcLines: [
              "No problem, I'll get that ready for you. Oh, would you like a cookie? It's on the house today!",
              "You got it! Oh wait — would you like a free cookie? It's on the house today!",
              "Sure thing! Hey, one more thing — can I offer you a cookie? On the house!",
            ],
            npcZh: "没问题，我帮您准备。对了，要来块曲奇吗？今天免费赠送！",
            task: "开心地接受免费曲奇",
            options: [
              { text: "Wow, thank you so much!",   ok: true,  tip: "on the house = 店家免费赠送，接受并道谢" },
              { text: "Free? Why?",                ok: false, tip: "这是店家的好意，开心说谢谢就好" },
              { text: "I no want cookie.",         ok: false, tip: "免费的好意，Why not? Thank you! 更友好" },
            ],
            phrase: { en: "Thank you so much!", zh: "非常感谢！", note: "接受好意时的热情道谢，so much 加强感谢程度" },
            adds: [{ emoji: "🍪", label: "Cookie 🆓", wordId: "cookie" }],
          },
          {
            npcLines: [
              "You're welcome! Here you go — one large oat milk latte, a croissant, and a cookie. Enjoy!",
              "My pleasure! Here's everything — large oat latte, croissant, and a cookie. Enjoy your day!",
              "Anytime! One large oat milk latte, one croissant, one cookie — all yours. Enjoy!",
            ],
            npcZh: "不客气！给您——大杯燕麦奶拿铁、牛角包和曲奇。请慢用！",
            task: "接过餐点并感谢",
            options: [
              { text: "Thank you! Have a nice day!",  ok: true,  tip: "Have a nice day! 告别必备祝福语" },
              { text: "Bye bye shop.",               ok: false, tip: "说 Have a nice day / See you 更自然" },
              { text: "Money good bye.",             ok: false, tip: "哈哈，简单说 Thank you! Have a nice day!" },
            ],
            phrase: { en: "Have a nice day!", zh: "祝你有美好的一天！", note: "离店告别祝福，店员对你说的也可以回赠给他" },
          },
        ],
      },
      {
        id: "v2",
        title: "第 2 次光顾 · 下午茶",
        titleEn: "Afternoon Tea",
        emoji: "🍰",
        desc: "带朋友来喝下午茶！学招待他人和堂食用语。",
        reward: { en: "cake", zh: "你完成了一次愉快的英文下午茶！🍰" },
        steps: [
          {
            npcLines: [
              "Hey, welcome back! Nice to see you again. Who's this with you today?",
              "Oh hi, welcome back! I see you brought someone along today!",
              "Welcome back! And who's your friend here?",
            ],
            npcZh: "嗨，又见面啦！很高兴再见到你。今天这位是？",
            task: "介绍一下你的朋友",
            options: [
              { text: "This is my friend, Lily. We're here for afternoon tea.", ok: true,  tip: "This is my friend... 介绍人的标准句式" },
              { text: "She is friend person.",                                   ok: false, tip: "介绍人用 This is my friend + 名字" },
              { text: "Look, friend!",                                           ok: false, tip: "更自然：This is my friend, Lily" },
            ],
            phrase: { en: "This is my friend, ___.", zh: "这是我的朋友……", note: "介绍人的万能句：This is + 名字，适用于任何场合" },
            adds: [{ emoji: "🧑‍🤝‍🧑", label: "With Lily", badge: true }],
          },
          {
            npcLines: [
              "Hi Lily, welcome! A table for two then? We have a nice spot by the window.",
              "Nice to meet you, Lily! A table for two? There's a lovely window seat open.",
              "Welcome, Lily! Table for two, right? The window spot just freed up.",
            ],
            npcZh: "你好 Lily，欢迎！两位是吗？我们有个靠窗的好位置。",
            task: "要一张两人桌",
            options: [
              { text: "Yes, a table for two, please. The window seat sounds great.", ok: true,  tip: "a table for two = 两人桌，用餐人数直接说" },
              { text: "Two people table give.",                                     ok: false, tip: "说 a table for two, please" },
              { text: "We sit where?",                                              ok: false, tip: "先礼貌要桌：a table for two, please" },
            ],
            phrase: { en: "A table for two, please.", zh: "请给我们一张两人桌", note: "for + 人数：for one / for three 都可以" },
            adds: [{ emoji: "🪑", label: "Window Table", badge: true }],
          },
          {
            npcLines: [
              "Perfect, right this way. Here are the menus. Take your time — what can I start you off with?",
              "Great choice! Follow me. Here's the menu — anything to drink first?",
              "This way please! Menu's right here. What would you two like to drink?",
            ],
            npcZh: "完美，这边请。这是菜单。慢慢看——先来点什么喝的？",
            task: "先看菜单，点一壶茶",
            options: [
              { text: "Could we look at the menu first? And a pot of tea for two, please.", ok: true,  tip: "a pot of tea = 一壶茶，下午茶经典" },
              { text: "Menu me see.",                                                     ok: false, tip: "说 Could we see the menu, please?" },
              { text: "Tea tea two.",                                                     ok: false, tip: "更自然：A pot of tea for two, please" },
            ],
            phrase: { en: "Could we see the menu, please?", zh: "我们可以看下菜单吗？", note: "Could we...? 比 Can we 更客气，用餐常用" },
            adds: [{ emoji: "🍵", label: "Tea for Two", wordId: "tea" }],
          },
          {
            npcLines: [
              "A pot of tea coming up! Now, for treats — our chocolate cake and blueberry muffins are very popular today.",
              "One pot of tea, got it! For something sweet, the chocolate cake and muffins are crowd favorites.",
              "Great pick! And for treats? Today's stars are the chocolate cake and the blueberry muffins.",
            ],
            npcZh: "一壶茶马上来！甜点方面——我们的巧克力蛋糕和蓝莓玛芬今天很受欢迎。",
            task: "点一块巧克力蛋糕和一个玛芬",
            options: [
              { text: "A slice of chocolate cake and a blueberry muffin, please.", ok: true,  tip: "a slice of cake = 一块蛋糕，slice 是切件的量词" },
              { text: "One cake and one muffin thing.",                            ok: false, tip: "蛋糕用量词 slice：a slice of cake" },
              { text: "Cake us two sweet.",                                        ok: false, tip: "说 A slice of chocolate cake, please" },
            ],
            phrase: { en: "A slice of ___, please.", zh: "请给我一块……", note: "蛋糕/披萨等切件食物都用 slice" },
            adds: [{ emoji: "🍰", label: "Choco Cake", wordId: "cake" }, { emoji: "🧁", label: "Muffin", wordId: "muffin" }],
          },
          {
            npcLines: [
              "Excellent choices! Would you like that cake on a plate to share, or two separate plates?",
              "Nice! Should I bring the cake on one plate to share, or put it on two plates?",
              "Great taste! One plate to share, or two plates — what works for you two?",
            ],
            npcZh: "好选择！蛋糕要一个盘子分享，还是两个盘子分开？",
            task: "要两个盘子分开装",
            options: [
              { text: "Two separate plates, please. And could we get a fork each?", ok: true,  tip: "separate = 分开的；a fork each = 每人一把叉子" },
              { text: "Plate two make.",                                            ok: false, tip: "说 Two separate plates, please" },
              { text: "One plate is enough, we eat hands.",                         ok: false, tip: "吃蛋糕还是用叉子吧：a fork each" },
            ],
            phrase: { en: "Two separate plates, please.", zh: "请给我们两个分开的盘子", note: "separate 表达\"分开的\"，分餐、分单都用它" },
            adds: [{ emoji: "🍽️", label: "Plates ×2", wordId: "plate" }, { emoji: "🍴", label: "Forks ×2", wordId: "fork" }],
          },
          {
            npcLines: [
              "Of course! I'll bring those right over. Now, would you like anything else? Some fresh orange juice perhaps?",
              "You got it, forks and plates coming right up! Anything else? The fresh-squeezed orange juice is lovely today.",
              "No problem at all! I'll grab those. Can I tempt you with anything else? We have fresh orange juice.",
            ],
            npcZh: "当然！马上送来。还需要别的吗？来点鲜榨橙汁怎么样？",
            task: "加一杯橙汁",
            options: [
              { text: "Sure, one orange juice for my friend, please.", ok: true,  tip: "for my friend 帮朋友点，贴心表达" },
              { text: "Juice yes friend.",                            ok: false, tip: "说 One orange juice, please" },
              { text: "No more water.",                               ok: false, tip: "店员推荐的是 juice，直接说要不要" },
            ],
            phrase: { en: "One ___ for my friend, please.", zh: "给我的朋友来一份……", note: "帮别人点单：for + 人，体贴又地道" },
            adds: [{ emoji: "🧃", label: "OJ for Lily", wordId: "juice" }],
          },
          {
            npcLines: [
              "One orange juice it is! So that's a pot of tea, chocolate cake, a muffin, and an OJ. Anything else?",
              "Great! So we've got the tea, cake, muffin, and juice. Can I get you anything more?",
              "Perfect! Tea, cake, muffin, and orange juice — all set. Anything else for you two?",
            ],
            npcZh: "一杯橙汁！那么总共是一壶茶、巧克力蛋糕、一个玛芬和一杯橙汁。还要别的吗？",
            task: "确认就这些",
            options: [
              { text: "That's everything, thank you!",  ok: true,  tip: "That's everything = 就这些了，确认收尾" },
              { text: "All all done we.",              ok: false, tip: "自然说法：That's everything, thank you" },
              { text: "Maybe yes maybe no.",           ok: false, tip: "确定一下就好：That's everything!" },
            ],
            phrase: { en: "That's everything, thank you.", zh: "就这些了，谢谢", note: "点单收尾第二式：everything 比 all 更常用" },
          },
          {
            npcLines: [
              "Wonderful! Your total is twelve dollars. How would you like to pay?",
              "Great! That comes to twelve dollars altogether. Card or cash?",
              "All set! Twelve dollars even — how are you paying today?",
            ],
            npcZh: "很好！您一共消费 12 美元。您想怎么付款？",
            task: "这次用现金付款",
            options: [
              { text: "I'll pay in cash. Here you go.",  ok: true,  tip: "in cash 现金；Here you go 递钱时的经典说法" },
              { text: "Money paper now.",                ok: false, tip: "说 I'll pay in cash" },
              { text: "Card no have.",                   ok: false, tip: "直接说 I'll pay in cash 就好" },
            ],
            phrase: { en: "I'll pay in cash.", zh: "我付现金", note: "in cash 现金 / by card 刷卡，二选一" },
            adds: [{ emoji: "💵", label: "Paid $12", badge: true }],
          },
          {
            npcLines: [
              "Thank you! I'll bring everything to your table in just a minute. Enjoy your afternoon tea!",
              "Thanks so much! Everything will be at your table shortly. Enjoy, you two!",
              "Perfect, thanks! Your order will be right out. Have a lovely afternoon!",
            ],
            npcZh: "谢谢！餐点马上送到你们桌上。祝你们下午茶愉快！",
            task: "感谢并期待用餐",
            options: [
              { text: "Thank you so much! We're really looking forward to it.",  ok: true,  tip: "look forward to = 期待，表达愉快心情" },
              { text: "Ok bye now.",                                            ok: false, tip: "店员会送餐到桌，说 Thank you 就好" },
              { text: "Fast fast bring.",                                       ok: false, tip: "更礼貌：We're looking forward to it!" },
            ],
            phrase: { en: "We're looking forward to it.", zh: "我们很期待！", note: "look forward to + 名词，期待任何好事都能用" },
          },
          {
            npcLines: [
              "Enjoy your tea and cake, you two! Just wave if you need anything else. Have a lovely afternoon!",
              "Hope you two enjoy everything! Wave me over if you need anything. Have a great afternoon!",
              "It was lovely serving you both! Give me a shout if you need anything at all!",
            ],
            npcZh: "两位请慢慢享用！需要什么随时招呼我。祝你们下午愉快！",
            task: "礼貌道别",
            options: [
              { text: "Thank you! You too, have a lovely afternoon!",  ok: true,  tip: "You too! 把祝福回赠给对方，超地道" },
              { text: "Bye bye tea woman.",                           ok: false, tip: "说 Thank you! You too! 就很好" },
              { text: "Go away now.",                                 ok: false, tip: "哈哈不礼貌啦，说 You too!" },
            ],
            phrase: { en: "You too!", zh: "你也是！", note: "收到祝福后原句回赠：Have a nice day! — You too!" },
          },
        ],
      },
      {
        id: "v3",
        title: "第 3 次光顾 · 赶时间早餐",
        titleEn: "Morning Rush",
        emoji: "🥯",
        desc: "早上赶时间！学快节奏简化点单和排队用语。",
        reward: { en: "sandwich", zh: "你在高峰期高效完成了英文点单！🏃" },
        steps: [
          {
            npcLines: [
              "Morning! Whoa, it's busy today — the line's out the door. What can I get you?",
              "Good morning! Sorry about the wait, we're slammed this morning. What'll it be?",
              "Morning morning! Busy rush today, huh? What can I get started for you?",
            ],
            npcZh: "早上好！哇今天人真多——队伍都排到门口了。您要什么？",
            task: "理解排队情况，礼貌点单",
            options: [
              { text: "Good morning! I'm in a bit of a rush — can I order quickly?", ok: true,  tip: "in a rush = 赶时间，礼貌说明情况" },
              { text: "Hurry up, I'm late!",                                         ok: false, tip: "对店员发脾气不礼貌，说明情况即可" },
              { text: "Why so many people?",                                         ok: false, tip: "先说明自己赶时间：I'm in a rush" },
            ],
            phrase: { en: "I'm in a rush.", zh: "我赶时间", note: "礼貌告知赶时间，对方会加快或简化流程" },
            adds: [{ emoji: "🏃", label: "In a Rush", badge: true }],
          },
          {
            npcLines: [
              "No worries, I've got you! Quick and easy — what can I get you?",
              "You got it, let's make this fast! What'll it be?",
              "Say no more! Quick order coming right up — what would you like?",
            ],
            npcZh: "没问题，包在我身上！快点来——您要什么？",
            task: "快速点一杯咖啡",
            options: [
              { text: "Just a coffee, please. That's all.",  ok: true,  tip: "Just a coffee = 就一杯咖啡，简化点单第一式" },
              { text: "Coffee coffee fast fast.",           ok: false, tip: "说 Just a coffee, please 就好" },
              { text: "The everything breakfast.",           ok: false, tip: "赶时间就点简单的：Just a coffee" },
            ],
            phrase: { en: "Just a ___, please.", zh: "就一个……就好", note: "just 强调\"只要这个\"，快节奏点单神器" },
            adds: [{ emoji: "☕", label: "Coffee", wordId: "coffee" }],
          },
          {
            npcLines: [
              "One coffee, easy! And for food — our breakfast sandwiches and bagels are grab-and-go. Interested?",
              "Coffee it is! We've also got grab-and-go breakfast — sandwiches and bagels. Want one?",
              "Great! And hey, our breakfast sandwiches and bagels are ready to grab. Anything for the road?",
            ],
            npcZh: "一杯咖啡，简单！吃的方面——我们的早餐三明治和贝果都是即拿即走的。来一个吗？",
            task: "来一个贝果",
            options: [
              { text: "A bagel with cream cheese, please.",  ok: true,  tip: "bagel 贝果 + cream cheese 奶油奶酪，经典搭配" },
              { text: "Bread circle one.",                   ok: false, tip: "那个圈圈面包叫 bagel" },
              { text: "I no eat morning.",                   ok: false, tip: "早餐很重要！来一个 bagel 吧" },
            ],
            phrase: { en: "A bagel with ___, please.", zh: "一个配……的贝果", note: "with + 配料：点三明治/贝果的搭配表达" },
            adds: [{ emoji: "🥯", label: "Bagel", wordId: "bagel" }],
          },
          {
            npcLines: [
              "Great choice! The bagels are right here by the register — you can grab one yourself. Which one?",
              "Good pick! Bagels are self-serve right here. Which one would you like?",
              "Nice! Bagel's are grab-and-go, right in front of you. Pick any one you like!",
            ],
            npcZh: "好选择！贝果就在收银台旁边——您可以自己拿。要哪个？",
            task: "选一个贝果",
            options: [
              { text: "I'll take this sesame one, thank you!",  ok: true,  tip: "sesame 芝麻，指着自己要的那个说 this one" },
              { text: "That one there yes.",                    ok: false, tip: "更完整：I'll take this one, thank you" },
              { text: "You choose for me no.",                  ok: false, tip: "自己选一个，用 I'll take this one" },
            ],
            phrase: { en: "I'll take this one.", zh: "我要这个", note: "指着实物点单：this one / that one，快节奏必备" },
            adds: [{ emoji: "🥯", label: "Sesame Bagel", badge: true }],
          },
          {
            npcLines: [
              "Sesame bagel, nice! So that's a coffee and a bagel — anything else, or is that it?",
              "Great pick! One coffee, one sesame bagel. Anything else for you?",
              "Got it, sesame bagel! Coffee plus bagel — that everything?",
            ],
            npcZh: "芝麻贝果，好！一杯咖啡加一个贝果——还要别的吗，就这些？",
            task: "赶时间，确认就这些",
            options: [
              { text: "That's it, thanks! I'm in a rush, remember?",  ok: true,  tip: "That's it = 就这些，比 That's all 更简短随意" },
              { text: "More thing maybe no yes.",                    ok: false, tip: "赶时间就果断：That's it, thanks!" },
              { text: "Wait wait wait.",                             ok: false, tip: "想好了再点，现在说 That's it" },
            ],
            phrase: { en: "That's it, thanks.", zh: "就这些，谢谢", note: "That's it 比 That's all 更口语化，快节奏常用" },
          },
          {
            npcLines: [
              "Got it! That'll be five twenty-five. Card or cash — whichever's faster for you!",
              "All set! Five twenty-five total. However you're paying, let's make it quick!",
              "That's five twenty-five! And don't worry, we'll have you out of here in no time!",
            ],
            npcZh: "明白！一共 5 美元 25 美分。刷卡还是现金——哪个快用哪个！",
            task: "快速付款",
            options: [
              { text: "Card, please. Here you go.",  ok: true,  tip: "赶时间时直接说 Card, please. 简洁有效" },
              { text: "Money now fast.",             ok: false, tip: "说 Card, please 或 Cash, please" },
              { text: "You take money later.",       ok: false, tip: "先付款哦：Card, please" },
            ],
            phrase: { en: "Card, please.", zh: "刷卡，谢谢", note: "快节奏简化版：付款方式 + please，一词搞定" },
            adds: [{ emoji: "💳", label: "Paid $5.25", badge: true }],
          },
          {
            npcLines: [
              "All done! Your coffee will be ready at the end of the counter in just a sec. Grab-and-go!",
              "Perfect! Coffee's coming right up at the pickup counter. Grab it and go!",
              "You're all set! Coffee'll be at the end counter in a moment — grab and go!",
            ],
            npcZh: "搞定！您的咖啡马上在吧台末端备好。拿了就走！",
            task: "取餐并告别",
            options: [
              { text: "Great, thank you so much! Have a good one!",  ok: true,  tip: "Have a good one! 美式随性告别语，超地道" },
              { text: "Where coffee me wait?",                      ok: false, tip: "店员说了吧台末端，直接道谢取餐即可" },
              { text: "Bye, no thank you.",                         ok: false, tip: "再忙也要说 thank you！" },
            ],
            phrase: { en: "Have a good one!", zh: "祝你愉快！", note: "美式口语告别：比 Have a nice day 更简短随性" },
          },
          {
            npcLines: [
              "You too! Oh — one more thing. Can I get a name for the cup? We call it out when it's ready!",
              "Have a good one! Wait — can I grab a name for the cup? We'll call it when ready!",
              "Same to you! Quick — what name for the cup? We'll shout it out in a sec!",
            ],
            npcZh: "你也是！对了——杯子上要写名字吗？好了我们会叫号！",
            task: "告诉店员你的名字",
            options: [
              { text: "It's Alex. A-L-E-X. Thank you!",  ok: true,  tip: "报名字 + 拼一遍，咖啡店经典场景！" },
              { text: "I am name yes.",                  ok: false, tip: "直接说 It's + 你的名字" },
              { text: "No name needed bye.",             ok: false, tip: "配合一下嘛，说 It's Alex" },
            ],
            phrase: { en: "It's ___. (spelling it out)", zh: "是……（拼出名字）", note: "报名字用 It's + 名字，复杂的名字顺手拼一遍" },
            adds: [{ emoji: "🏷️", label: "Cup: Alex", wordId: "name" }],
          },
          {
            npcLines: [
              "Alex, got it! We'll call you in just a moment. Thanks for stopping by — see you tomorrow?",
              "Perfect, Alex! Give us one minute. Thanks for rushing in with us today!",
              "Alex it is! We'll have that ready in no time. Thanks for bearing with the rush!",
            ],
            npcZh: "Alex，记下了！马上叫您。谢谢光顾——明天还来吗？",
            task: "友好收尾",
            options: [
              { text: "See you tomorrow! Thanks again!",  ok: true,  tip: "常客式告别，简短友好" },
              { text: "Maybe never know.",               ok: false, tip: "更友好：See you tomorrow!" },
              { text: "Coffee now where.",               ok: false, tip: "稍等一下就好，先友好道别" },
            ],
            phrase: { en: "See you tomorrow!", zh: "明天见！", note: "常客式告别：固定光顾 + 熟络感满分" },
          },
        ],
      },
      {
        id: "v4",
        title: "第 4 次光顾 · 特别定制",
        titleEn: "Custom Order",
        emoji: "🧊",
        desc: "成为熟客！学进阶定制：糖度、浓缩、冰饮。",
        reward: { en: "iced", zh: "你已经是能流利定制咖啡的熟客了！🧊" },
        steps: [
          {
            npcLines: [
              "Well hello! Back again — you're becoming a regular! What can I make for you today?",
              "Hey, look who's back! Our new regular! What's the order today?",
              "Welcome back, friend! I should start memorizing your order at this point! What'll it be?",
            ],
            npcZh: "哟，又来啦！你都快成常客了！今天给您做点什么？",
            task: "以熟客身份打招呼点单",
            options: [
              { text: "Hey! I'd like to try something different today — maybe an iced latte?", ok: true,  tip: "iced latte 冰拿铁，试试 something different 换换口味" },
              { text: "Same old same old.",                                                     ok: false, tip: "这次换个新花样，试试 iced latte" },
              { text: "You know what I want.",                                                  ok: false, tip: "店员会猜错哦，还是自己说吧" },
            ],
            phrase: { en: "I'd like to try something different.", zh: "我想试试不一样的", note: "try something different 换口味万能句" },
          },
          {
            npcLines: [
              "Ooh, switching it up! An iced latte it is. Now — any customizations? You strike me as someone who knows their coffee!",
              "Nice change! One iced latte coming up. Any special requests? You look like a coffee pro!",
              "Love it! Iced latte, great choice. So how do you like it — any customizations?",
            ],
            npcZh: "换口味啦！冰拿铁是吧。要定制吗？你看着就很懂咖啡！",
            task: "要求少糖",
            options: [
              { text: "Yes — not too sweet, please. Just a little syrup.", ok: true,  tip: "not too sweet 少糖；syrup 糖浆" },
              { text: "Sugar no sugar yes.",                             ok: false, tip: "说 Not too sweet, please" },
              { text: "Sweet like candy.",                               ok: false, tip: "太甜啦，健康点：Not too sweet" },
            ],
            phrase: { en: "Not too sweet, please.", zh: "不要太甜", note: "not too + 形容词 = 适中要求：not too hot / not too cold" },
            adds: [{ emoji: "🍬", label: "Less Sweet", badge: true, wordId: "sweet" }, { emoji: "🍯", label: "Light Syrup", wordId: "syrup" }],
          },
          {
            npcLines: [
              "Light syrup, got it! And how about the espresso — our standard is two shots, but we can adjust. More or less?",
              "Noted, light syrup! For the espresso — standard is two shots. Want more or less kick?",
              "You got it! Two shots is our usual. Should I add an extra shot, or keep it standard?",
            ],
            npcZh: "少糖，记下！浓缩咖啡方面——标准是两份，但可以调整。多加还是减少？",
            task: "加一份浓缩",
            options: [
              { text: "Could you add an extra shot, please? I need the energy today.", ok: true,  tip: "a shot = 一份浓缩；extra shot 加一份" },
              { text: "Coffee strong very much.",                                     ok: false, tip: "说 Add an extra shot, please" },
              { text: "No coffee only milk.",                                          ok: false, tip: "拿铁里是有浓缩的，加一份更提神" },
            ],
            phrase: { en: "Could you add an extra shot?", zh: "能加一份浓缩吗？", note: "add an extra... 加量定制：extra shot / extra syrup 通用" },
            adds: [{ emoji: "⚡", label: "+1 Shot", wordId: "shot" }],
          },
          {
            npcLines: [
              "Extra shot for the energy boost — bold choice! Anything else? Whipped cream, drizzle, extra ice?",
              "One extra shot, coming up! Any other customizations? Whipped cream, caramel drizzle, extra ice?",
              "Love it! Extra shot it is. What else can I do for you — whipped cream or extra ice, maybe?",
            ],
            npcZh: "加一份浓缩提提神——有魄力！还要别的吗？奶油、淋酱、多加冰？",
            task: "要多加冰",
            options: [
              { text: "Extra ice, please. It's such a hot day!", ok: true,  tip: "extra ice 多加冰，冰饮定制常见" },
              { text: "Ice ice many.",                          ok: false, tip: "说 Extra ice, please" },
              { text: "Hot day yes me too.",                    ok: false, tip: "回应之后记得提要求：Extra ice, please" },
            ],
            phrase: { en: "Extra ice, please.", zh: "请多加冰", note: "extra + 配料 = 多加：extra ice / extra foam 咖啡定制通用" },
            adds: [{ emoji: "🧊", label: "Extra Ice", wordId: "iced" }],
          },
          {
            npcLines: [
              "Extra ice it is! One iced latte, light syrup, three shots, extra ice. Shall I ring that up?",
              "Perfect! So — iced latte, light on the syrup, triple shot, extra ice. Ready to check out?",
              "Got it all! Iced latte, light syrup, extra shot, extra ice. Should I total that up for you?",
            ],
            npcZh: "多加冰！一杯冰拿铁、少糖、三份浓缩、多加冰。可以结账了吗？",
            task: "确认订单",
            options: [
              { text: "That's perfect, yes please!",  ok: true,  tip: "确认定制订单无误，That's perfect 满分回答" },
              { text: "Yes no maybe.",               ok: false, tip: "确认一下：That's perfect, yes!" },
              { text: "Too much coffee.",            ok: false, tip: "刚定的单没错就好，说 That's perfect" },
            ],
            phrase: { en: "That's perfect, yes please!", zh: "完全正确，好的！", note: "复述订单后确认：perfect 表示\"完全符合\"" },
          },
          {
            npcLines: [
              "Alright, your total is six seventy-five. Paying with your usual card?",
              "Great! Six seventy-five altogether. Same card as always?",
              "All set — six seventy-five. The usual payment method?",
            ],
            npcZh: "好的，一共 6 美元 75 美分。还是用您常用的那张卡？",
            task: "确认刷卡",
            options: [
              { text: "Yes, the usual, please. Thank you!",  ok: true,  tip: "the usual = 老样子，熟客专属表达！" },
              { text: "Card card card.",                    ok: false, tip: "说 Yes, the usual, please" },
              { text: "What is usual?",                     ok: false, tip: "店员记得你的习惯，回答 Yes, the usual" },
            ],
            phrase: { en: "The usual, please.", zh: "老样子，谢谢", note: "熟客暗号：the usual = 我常点/常用的那个" },
            adds: [{ emoji: "💳", label: "Paid $6.75", badge: true }],
          },
          {
            npcLines: [
              "...Approved! And can I get the name for the cup? Alex, right? I remembered!",
              "...All done! Name for the cup — it's Alex, isn't it? I've got a good memory for regulars!",
              "...Perfect! Let me guess — Alex for the cup? I remember my regulars!",
            ],
            npcZh: "……扣款成功！杯子上的名字——是 Alex 对吧？我记得！",
            task: "对店员的记性表示惊喜",
            options: [
              { text: "Wow, you remembered! Yes, it's Alex. Impressive!",  ok: true,  tip: "对店员的用心表示欣赏，good memory 表达" },
              { text: "Yes Alex how you know.",                           ok: false, tip: "更热情：You remembered! Impressive!" },
              { text: "Stalker!",                                        ok: false, tip: "哈哈不是啦，这是优质服务：You remembered!" },
            ],
            phrase: { en: "You remembered!", zh: "你居然记得！", note: "惊喜+欣赏：别人记得你的细节时的高情商回应" },
            adds: [{ emoji: "🏷️", label: "Cup: Alex", wordId: "name" }],
          },
          {
            npcLines: [
              "Ha! I try! Your drink will be ready at the counter in a minute. Thanks for being such a great regular, Alex!",
              "Haha, I do my best! One minute at the counter. We love having you as a regular, Alex!",
              "Just part of the service! Drink's coming up shortly. You're one of our favorites, Alex!",
            ],
            npcZh: "哈！尽力而为！您的饮品一分钟内在吧台备好。谢谢你这样的好常客，Alex！",
            task: "感谢并告别",
            options: [
              { text: "Thank you! It's always a pleasure coming here. See you soon!",  ok: true,  tip: "It's always a pleasure 表达对店铺的喜爱" },
              { text: "Ok bye coffee place.",                                        ok: false, tip: "更热情：See you soon!" },
              { text: "Whatever bye.",                                               ok: false, tip: "对好服务表达感谢：Thank you! See you soon!" },
            ],
            phrase: { en: "It's always a pleasure.", zh: "always 很开心（来这里）", note: "表达对商家的喜爱：熟客的高情商金句" },
          },
          {
            npcLines: [
              "Same here! See you soon, Alex — your iced latte's on the counter. Enjoy!",
              "The pleasure's ours! See you around, Alex! Drink's up — enjoy your day!",
              "Right back at you! Your drink's ready, Alex. Catch you next time!",
            ],
            npcZh: "我们也是！回头见，Alex——你的冰拿铁在吧台上了。慢走！",
            task: "完成最后一轮光顾",
            options: [
              { text: "See you! Enjoy the rest of your day!",  ok: true,  tip: "完美收尾，四轮光顾全部完成！" },
              { text: "Bye forever now.",                     ok: false, tip: "常客不说 forever，说 See you!" },
              { text: "Coffee mine give.",                    ok: false, tip: "餐在吧台，道别后去取就好" },
            ],
            phrase: { en: "See you!", zh: "回头见！", note: "简短随性的告别，熟客之间最常用" },
          },
        ],
      },
      {
        id: "v5",
        title: "第 5 次光顾 · 出错了怎么办",
        titleEn: "When Things Go Wrong",
        emoji: "❌",
        desc: "订单出错了！学礼貌地指出问题并解决——外语社交的最高段位。",
        reward: { en: "replacement", zh: "你学会了用英语优雅地解决问题！🛠️" },
        steps: [
          {
            npcLines: [
              "Hey Alex! The usual spot's open. What can I get you today?",
              "Hi there, Alex! Back again I see. What'll it be?",
              "Welcome back, Alex! What can I start for you today?",
            ],
            npcZh: "嘿 Alex！老位置还空着。今天来点什么？",
            task: "点一杯普通拿铁",
            options: [
              { text: "A regular latte, please.", ok: true,  tip: "regular = 普通的/常规的，熟客简洁点法" },
              { text: "Latte one normal yes.",    ok: false, tip: "说 A regular latte, please" },
              { text: "Coffee milk hot.",         ok: false, tip: "拿铁直接说 latte 就好" },
            ],
            phrase: { en: "A regular ___, please.", zh: "一份常规的……", note: "regular 表示\"标准的、不定制\"的，点单超实用" },
            adds: [{ emoji: "☕", label: "Latte" }],
          },
          {
            npcLines: [
              "One regular latte! That'll be four fifty. Card or cash?",
              "Regular latte, got it! Four fifty altogether. How are you paying?",
              "One latte coming up — four fifty. Cash or card today?",
            ],
            npcZh: "一杯普通拿铁！一共 4 美元 50 美分。刷卡还是现金？",
            task: "付款并等待",
            options: [
              { text: "Card, please. Thank you!",  ok: true,  tip: "简洁付款 + 道谢，标准操作" },
              { text: "Money give now you.",      ok: false, tip: "说 Card, please 或 Cash, please" },
              { text: "Pay later ok?",            ok: false, tip: "咖啡店要先付款哦" },
            ],
            phrase: { en: "Card, please.", zh: "刷卡，谢谢", note: "快节奏付款：方式 + please 一词搞定" },
            adds: [{ emoji: "💳", label: "Paid $4.50", badge: true }],
          },
          {
            npcLines: [
              "All done! Your latte will be right up. Have a seat and I'll bring it over!",
              "Perfect! Take a seat — your drink will be right out!",
              "You're all set! Grab a seat and your latte will find you!",
            ],
            npcZh: "好了！您的拿铁马上就好。请坐，我给您送过去！",
            task: "坐下等待",
            options: [
              { text: "Great, thank you!",  ok: true,  tip: "简单道谢入座" },
              { text: "I stand forever.",   ok: false, tip: "店员说可以坐，回答 Great, thanks 就好" },
              { text: "Run away now.",     ok: false, tip: "咖啡还没好呢，先坐下等" },
            ],
            phrase: { en: "Great, thank you!", zh: "好的，谢谢！", note: "万能轻量回应：接受任何安排的百搭句" },
          },
          {
            npcLines: [
              "Here's your latte, Alex! Enjoy!",
              "One latte for Alex! Here you go!",
              "Latte's up! There you go, Alex!",
            ],
            npcZh: "您的拿铁，Alex！请慢用！",
            task: "发现上错单了（这是热牛奶，不是拿铁）",
            options: [
              { text: "Excuse me, I think there's a mistake with my order. This is hot milk, not a latte.", ok: true,  tip: "Excuse me + I think 委婉指出错误的标准开场" },
              { text: "You wrong! This bad! Change!",                                                        ok: false, tip: "太冲了！用 Excuse me, I think there's a mistake 委婉表达" },
              { text: "(默默喝掉热牛奶)",                                                                      ok: false, tip: " politely 说出来，店员会马上帮你解决" },
            ],
            phrase: { en: "Excuse me, I think there's a mistake with my order.", zh: "不好意思，我的订单好像出错了", note: "投诉黄金开场：I think 缓冲语气，坚定不失礼" },
            adds: [{ emoji: "❌", label: "Wrong Order", badge: true }],
          },
          {
            npcLines: [
              "Oh no, you're absolutely right — that's steamed milk! I'm so sorry about that!",
              "Oh my goodness, you're right! I totally mixed up the cups. My apologies!",
              "You're totally right — I grabbed the wrong cup! So sorry about that!",
            ],
            npcZh: "哎呀，您说得对——这是热牛奶！非常抱歉！",
            task: "接受道歉并请店员重做",
            options: [
              { text: "No worries, it happens! Could I get a replacement?",  ok: true,  tip: "No worries, it happens 宽容回应 + 请求重做，高情商" },
              { text: "Yes you should be sorry!",                           ok: false, tip: "得理不饶人啦，说 No worries, it happens" },
              { text: "Free coffee for apology!",                           ok: false, tip: "先礼貌请求重做：Could I get a replacement?" },
            ],
            phrase: { en: "No worries, it happens.", zh: "没关系，难免的", note: "被道歉后的高情商回应：瞬间化解尴尬" },
            adds: [{ emoji: "🔄", label: "Remaking", badge: true }],
          },
          {
            npcLines: [
              "Thank you for being so understanding! I'll make you a fresh latte right away — on the house, of course!",
              "You're too kind! Fresh latte coming right up — and it's on us this time!",
              "Really appreciate it! A fresh one, on the house — won't be a minute!",
            ],
            npcZh: "谢谢您的理解！我马上给您做一杯新的——当然，免费赠送！",
            task: "感谢店员的处理",
            options: [
              { text: "Oh, that's very kind of you. Thank you so much!",  ok: true,  tip: "That's very kind of you 感谢好意的地道表达" },
              { text: "Good, as you should.",                           ok: false, tip: " graciously 接受：That's very kind of you!" },
              { text: "Money back all!",                                ok: false, tip: "店员已免费重做，道谢即可" },
            ],
            phrase: { en: "That's very kind of you.", zh: "你人真好", note: "感谢好意的固定句： kindness 专用高情商回应" },
          },
          {
            npcLines: [
              "(A moment later) Oh no — Alex, I'm so sorry! I knocked over your fresh latte! What a disaster!",
              "(One minute later) Oh no, Alex! I just spilled your new latte everywhere! I'm so sorry!",
              "(Just now) Alex, disaster! Your fresh latte — I spilled it! My apologies!",
            ],
            npcZh: "（片刻后）哎呀——Alex，太抱歉了！我刚把您的新拿铁打翻了！真是的！",
            task: "宽容回应第二失误并再等一杯",
            options: [
              { text: "Oh no! Well, third time's the charm, right? Take your time.",  ok: true,  tip: "幽默化解 + Third time's the charm 谚语，高级社交技巧" },
              { text: "You are very bad worker.",                                     ok: false, tip: "幽默比指责更有效：Third time's the charm!" },
              { text: "I drink air now.",                                              ok: false, tip: "哈哈，再等一杯：Take your time" },
            ],
            phrase: { en: "Third time's the charm.", zh: "第三次准成！（谚语）", note: "英语谚语：幽默化解连续失误的气氛" },
            adds: [{ emoji: "💦", label: "Spill #2", badge: true }],
          },
          {
            npcLines: [
              "Ha! You're the best, Alex. Here — fresh latte, extra care taken, plus a free croissant for your trouble!",
              "Haha, you're amazing! Here's your latte — made with extra love — and a croissant for your patience!",
              "You're a saint, Alex! One perfect latte, plus a croissant on us for putting up with us today!",
            ],
            npcZh: "哈！您人真好 Alex。给——新鲜拿铁，这次格外小心，外加免费牛角包补偿您！",
            task: "接受补偿并感谢",
            options: [
              { text: "You've more than made up for it. Thank you!",  ok: true,  tip: "more than make up for it = 补偿得足足的，高级表达" },
              { text: "OK fine this time.",                         ok: false, tip: "更 warmly：You've more than made up for it!" },
              { text: "Croissant not enough.",                      ok: false, tip: "店员已诚意补偿，友好收尾" },
            ],
            phrase: { en: "You've more than made up for it.", zh: "你的补偿绰绰有余了", note: "make up for = 弥补；more than 加强：非常到位" },
            adds: [{ emoji: "☕", label: "Fresh Latte" }, { emoji: "🥐", label: "Croissant 🆓", wordId: "croissant" }],
          },
          {
            npcLines: [
              "You're wonderful, Alex. Sorry again for the chaos — enjoy your latte and croissant!",
              "Thanks for your patience today, Alex! Enjoy the latte and the croissant!",
              "You're the best customer ever! Enjoy everything, and see you soon!",
            ],
            npcZh: "您真是太好了 Alex。再次为今天的混乱道歉——请享用拿铁和牛角包！",
            task: "友好收尾，完成出错处理挑战",
            options: [
              { text: "It was an adventure! See you next time!",  ok: true,  tip: "把失误说成 adventure，幽默收官" },
              { text: "Never coming back.",                      ok: false, tip: "今天处理得很愉快，幽默收尾更好" },
              { text: "Bye bad coffee day.",                    ok: false, tip: "轻松道别：See you next time!" },
            ],
            phrase: { en: "It was an adventure!", zh: "真是段奇遇！", note: "幽默总结：把小波折说成 adventure，情商满分" },
          },
        ],
      },
      {
        id: "v6",
        title: "第 6 次光顾 · 问推荐与忌口",
        titleEn: "Recommendations & Allergies",
        emoji: "👍",
        desc: "菜单看不懂？朋友对坚果过敏？学\"问推荐\"和\"问忌口\"两大生存技能。",
        reward: { en: "recommend", zh: "你掌握了让母语者替你说话的魔法句子！✨" },
        steps: [
          {
            npcLines: [
              "Morning, Alex! Ooh, you look curious today. Something on your mind?",
              "Hey Alex! You've got a question face on. What's up?",
              "Hi there, Alex! You look like a man with a mission. What can I do for you?",
            ],
            npcZh: "早上好 Alex！哟，你今天一脸好奇。有什么想法？",
            task: "说明想尝试新品",
            options: [
              { text: "I want to try something new. What do you recommend?",  ok: true,  tip: "What do you recommend? 让店员替你介绍，学习者杀手锏" },
              { text: "New thing what is good you tell.",                    ok: false, tip: "问推荐用 What do you recommend?" },
              { text: "Surprise me with anything edible.",                   ok: false, tip: "直接问推荐更清楚：What do you recommend?" },
            ],
            phrase: { en: "What do you recommend?", zh: "你推荐什么？", note: "最聪明的学习者句子：让对方热情输出，你只需听和选" },
          },
          {
            npcLines: [
              "Ooh, great question! Our new drink is the honey lavender latte — it's flying off the shelves! But first, any allergies I should know about?",
              "Love that you asked! The honey lavender latte is our new star! Quick question though — any allergies?",
              "Great timing! We just launched a honey lavender latte. Before I rave about it — do you have any allergies?",
            ],
            npcZh: "好问题！我们的新品是蜂蜜薰衣草拿铁——卖得超火！不过先问下，您有过敏吗？",
            task: "告知坚果过敏",
            options: [
              { text: "Yes, I'm allergic to nuts. Does anything here contain nuts?",  ok: true,  tip: "allergic to + 过敏原，安全攸关的表达" },
              { text: "Nut problem me have.",                                       ok: false, tip: "说 I'm allergic to nuts" },
              { text: "All food fine for me.",                                      ok: false, tip: "如果真的过敏一定要说清楚！" },
            ],
            phrase: { en: "I'm allergic to ___.", zh: "我对……过敏", note: "安全刚需句：餐厅/咖啡店必备用语" },
            adds: [{ emoji: "⚠️", label: "Nut Allergy", badge: true, wordId: "allergic" }],
          },
          {
            npcLines: [
              "Thanks for telling me! Good news — the lavender latte is totally nut-free. But I'd steer you away from the almond croissant obviously!",
              "Appreciate the heads up! The lavender latte has zero nuts. But definitely skip the almond croissant!",
              "Good to know! The lavender latte is nut-free, but the almond croissant is obviously off the table!",
            ],
            npcZh: "幸好您说了！好消息——薰衣草拿铁完全不含坚果。但杏仁牛角包您肯定要避开啦！",
            task: "追问饮品的区别",
            options: [
              { text: "What's the difference between the lavender latte and a regular latte?",  ok: true,  tip: "What's the difference between A and B? 比较万能句" },
              { text: "Lavender latte vs latte, explain everything.",                        ok: false, tip: "用 What's the difference between...and...?" },
              { text: "They are same or not?",                                               ok: false, tip: "更地道：What's the difference between them?" },
            ],
            phrase: { en: "What's the difference between ___ and ___?", zh: "……和……有什么区别？", note: "比较问法万能句：菜单、商品、概念都能问" },
          },
          {
            npcLines: [
              "Great question! The lavender one has dried lavender and honey — it's more floral and aromatic. The regular latte is just espresso and milk, more classic.",
              "So the lavender latte has dried lavender petals and honey — floral notes! Regular latte is just the classic espresso and milk.",
              "The difference: lavender latte has honey and dried lavender — floral and fragrant. Regular is the pure espresso-milk classic.",
            ],
            npcZh: "好问题！薰衣草拿铁加了干薰衣草和蜂蜜——花香更浓郁。普通拿铁就是浓缩加牛奶，更经典。",
            task: "听起来不错，点它",
            options: [
              { text: "That sounds lovely. I'll try the lavender latte, please!",  ok: true,  tip: "That sounds lovely + 决定点它，自然承接推荐" },
              { text: "OK give the flower coffee.",                              ok: false, tip: "说 I'll try the lavender latte, please" },
              { text: "Regular latte boring, flower one good.",                   ok: false, tip: "更自然：That sounds lovely. I'll try it!" },
            ],
            phrase: { en: "That sounds lovely. I'll try it!", zh: "听起来不错，我试试！", note: "接受推荐的承接句：夸一句 + 决定尝试" },
            adds: [{ emoji: "💜", label: "Lavender Latte", badge: true }],
          },
          {
            npcLines: [
              "Excellent choice! Now, what milk would you like? We have whole, skim, oat, and a new option — soy milk!",
              "Great pick! For milk — whole, skim, oat, or our new soy milk?",
              "Nice! Which milk today? Whole, skim, oat, or the new soy milk?",
            ],
            npcZh: "好选择！要什么奶？我们有全脂、脱脂、燕麦，还有新选择——豆奶！",
            task: "试试豆奶",
            options: [
              { text: "Let's go with soy milk — I haven't tried it here yet!",  ok: true,  tip: "Let's go with... 轻松选定，口语感十足" },
              { text: "Soy bean water yes.",                                   ok: false, tip: "说 soy milk, please" },
              { text: "Milk all same to me.",                                  ok: false, tip: "试试新品：Let's go with soy milk!" },
            ],
            phrase: { en: "Let's go with ___.", zh: "就要……吧", note: "口语化选择：Let's go with + 选择，轻快自然" },
            adds: [{ emoji: "🌱", label: "Soy Milk", badge: true, wordId: "soy" }],
          },
          {
            npcLines: [
              "Soy milk it is! Oh — since you like trying new things, want to add a pump of vanilla syrup? It pairs beautifully with lavender.",
              "Soy milk, great! Hey, want a pump of vanilla syrup? It goes amazing with the lavender!",
              "Nice! One more idea — a pump of vanilla syrup with the lavender? Chef's kiss!",
            ],
            npcZh: "豆奶！对了——您既然爱尝鲜，要不要加一泵香草糖浆？和薰衣草是绝配。",
            task: "礼貌地拒绝加糖浆",
            options: [
              { text: "That's tempting, but I'll pass this time. Keeping it simple!",  ok: true,  tip: "I'll pass this time = 这次先不了，礼貌拒绝" },
              { text: "No! Bad idea!",                                              ok: false, tip: "太生硬，说 I'll pass this time" },
              { text: "You decide my life.",                                       ok: false, tip: "自己做主：That's tempting, but I'll pass" },
            ],
            phrase: { en: "That's tempting, but I'll pass.", zh: "挺心动的，但这次算了", note: "礼貌拒绝三连：肯定诱惑 + but + I'll pass" },
          },
          {
            npcLines: [
              "Totally understand — simple is good! So that's one lavender latte with soy milk. Anything to eat? The lemon loaf is also nut-free!",
              "No problem at all! One lavender soy latte. And for food — the lemon loaf is nut-free too!",
              "Simple it is! One lavender latte, soy milk. The lemon loaf is safe for you, by the way — no nuts!",
            ],
            npcZh: "完全理解——简单最好！那么一杯豆奶薰衣草拿铁。要吃的吗？柠檬蛋糕也不含坚果！",
            task: "要一块柠檬蛋糕",
            options: [
              { text: "A slice of lemon loaf, please. Thanks for checking the nuts!",  ok: true,  tip: "感谢店员记得你的过敏——细心值得肯定" },
              { text: "Lemon bread one, go.",                                        ok: false, tip: "说 A slice of lemon loaf, please" },
              { text: "Cake yes if safe.",                                           ok: false, tip: "店员已确认安全，直接点：A slice, please" },
            ],
            phrase: { en: "Thanks for checking!", zh: "谢谢你帮我确认！", note: "对细心服务表示感谢：check 在此指\"核查\"" },
            adds: [{ emoji: "🍋", label: "Lemon Loaf", badge: true }],
          },
          {
            npcLines: [
              "My pleasure — safety first! Your total is six twenty-five.",
              "Of course! Always happy to check. Six twenty-five altogether!",
              "No problem at all! That'll be six twenty-five.",
            ],
            npcZh: "我的荣幸——安全第一！您一共消费 6 美元 25 美分。",
            task: "付款",
            options: [
              { text: "Here you go. Thank you!",  ok: true,  tip: "Here you go 递卡时的经典搭配" },
              { text: "Money take please.",      ok: false, tip: "递卡说 Here you go" },
              { text: "Pay when drink ready.",   ok: false, tip: "先付款，说 Here you go" },
            ],
            phrase: { en: "Here you go.", zh: "给你", note: "递东西万能句：递卡、递钱、递物品都适用" },
            adds: [{ emoji: "💳", label: "Paid $6.25", badge: true }],
          },
          {
            npcLines: [
              "Thank you! Your lavender latte and lemon loaf will be ready in a jiffy. Enjoy, and thanks for letting me recommend!",
              "Thanks a lot! Everything'll be up shortly. It was fun recommending — enjoy!",
              "Perfect! Drink and loaf coming right up. Glad I could introduce you to something new!",
            ],
            npcZh: "谢谢！您的薰衣草拿铁和柠檬蛋糕马上就好。请慢用，谢谢让我推荐！",
            task: "感谢推荐，完成本轮",
            options: [
              { text: "Best recommendation ever — I'll be back for it! Thank you!",  ok: true,  tip: "肯定推荐 + 表达回头意向，温暖收尾" },
              { text: "OK bye recommend man.",                                     ok: false, tip: "更热情：Best recommendation ever!" },
              { text: "We will see if good.",                                      ok: false, tip: "先表达期待：I'll be back for it!" },
            ],
            phrase: { en: "I'll be back for it!", zh: "我会再回来买的！", note: "回头客承诺：对推荐最好的肯定" },
          },
        ],
      },
      {
        id: "v7",
        title: "第 7 次光顾 · 咖啡文化深潜",
        titleEn: "Coffee Culture",
        emoji: "📚",
        desc: "读懂菜单黑话、连上 Wi-Fi、找到洗手间——还有小费文化的秘密。",
        reward: { en: "grande", zh: "你已经能看懂精品咖啡店的菜单了！📖" },
        steps: [
          {
            npcLines: [
              "Hey Alex! You're staring at the menu pretty hard. Anything I can decode for you?",
              "Hi Alex! That's quite the intense menu stare. Need a translator?",
              "Morning, Alex! The menu's not going anywhere. What's got you puzzled?",
            ],
            npcZh: "嘿 Alex！你盯着菜单看得好认真。需要我给您解码点什么吗？",
            task: "问 flat white 和卡布奇诺的区别",
            options: [
              { text: "Yes! What exactly is a flat white? How is it different from a cappuccino?",  ok: true,  tip: "How is it different from...? 专业追问句式" },
              { text: "Flat white menu mystery explain now.",                                   ok: false, tip: "用 What exactly is...? 提问更清晰" },
              { text: "White coffee flat why?",                                                  ok: false, tip: "问法：What exactly is a flat white?" },
            ],
            phrase: { en: "What exactly is ___?", zh: "……到底是什么？", note: "exactly 强调追问细节：菜单黑话解码器" },
          },
          {
            npcLines: [
              "Great question! A flat white has less steamed milk than a latte, but more than a cappuccino — it's silkier and stronger. Cappuccino is equal parts espresso, milk, and foam.",
              "Ooh, deep cut! Flat white: less milk than latte, more than cappuccino — silky and strong. Cappuccino: perfectly equal thirds!",
              "Love this question! Flat white sits between latte and cappuccino — silky but strong. Cappuccino is the classic one-third-one-third-one-third!",
            ],
            npcZh: "好问题！Flat white 的奶比拿铁少、比卡布奇诺多——更丝滑也更有咖啡味。卡布奇诺则是浓缩、牛奶、奶泡各三分之一。",
            task: "表示理解，再问杯型黑话",
            options: [
              { text: "Got it, thanks! And can I ask — what do tall and grande mean on your menu?",  ok: true,  tip: "Got it 表示听懂了；追问杯型黑话" },
              { text: "Words confusing still me.",                                               ok: false, tip: "先说 Got it, thanks! 再追问" },
              { text: "All cups same size secret?",                                              ok: false, tip: "问法：What do tall and grande mean?" },
            ],
            phrase: { en: "Got it, thanks!", zh: "懂了，谢谢！", note: "确认理解 + 追问的完美衔接：Got it 是听力理解的信号灯" },
          },
          {
            npcLines: [
              "Ha, coffee shop secret language! Tall is our medium, grande is large, and venti is extra-large. It's Italian-inspired sizing!",
              "Ah, the lingo! Tall means medium, grande means large, venti is the giant one. Fancy Italian vibes!",
              "The size code! Tall = medium, grande = large, venti = extra-large. All Italian-flavored!",
            ],
            npcZh: "哈，咖啡店黑话！Tall 是中杯、grande 是大杯、venti 是超大杯。意大利风情的杯型！",
            task: "用黑话点单",
            options: [
              { text: "Love it! I'll have a tall flat white then — medium, right?",  ok: true,  tip: "用刚学的 tall 点单并确认理解，活学活用" },
              { text: "One large tall grande cup.",                                ok: false, tip: "tall=中杯、grande=大杯，别搞混啦" },
              { text: "Venti tiny coffee please.",                                  ok: false, tip: "venti 是超大杯，tall 才是中杯" },
            ],
            phrase: { en: "I'll have a tall ___.", zh: "我要一杯中杯……", note: "咖啡店点单黑话：tall/grande/venti 三连" },
            adds: [{ emoji: "🥛", label: "Tall Flat White", badge: true, wordId: "tall" }],
          },
          {
            npcLines: [
              "Tall flat white, you got it — you speak coffee fluently now! By the way, your drink comes with free Wi-Fi. Need the password?",
              "A tall flat white for the coffee scholar! Oh — want the Wi-Fi password? Free with any drink!",
              "Medium flat white coming up! You're basically fluent in café now. Wi-Fi password, while you're at it?",
            ],
            npcZh: "中杯 flat white，没问题——您现在咖啡语十级了！对了，饮品附赠免费 Wi-Fi，要密码吗？",
            task: "要 Wi-Fi 密码",
            options: [
              { text: "Yes please! Could I get the Wi-Fi password?",  ok: true,  tip: "Could I get...? 礼貌索取信息的万能句" },
              { text: "Internet magic word give me.",                ok: false, tip: "说 Could I get the Wi-Fi password?" },
              { text: "No phone me no need.",                         ok: false, tip: "连 Wi-Fi 是刚需，问：Could I get the password?" },
            ],
            phrase: { en: "Could I get the Wi-Fi password?", zh: "能告诉我 Wi-Fi 密码吗？", note: "咖啡店求生第一句：Could I get + 任何东西" },
            adds: [{ emoji: "📶", label: "Wi-Fi ✓", badge: true, wordId: "wifi" }],
          },
          {
            npcLines: [
              "It's 'sunnycafe2026' — all one word, lowercase. Everything alright with your connection?",
              "Password's 'sunnycafe2026', all lowercase, no spaces. Connection working okay?",
              "It's sunnycafe2026 — one word, lowercase. You all connected?",
            ],
            npcZh: "密码是 sunnycafe2026——连写，全小写。连接还好吗？",
            task: "确认连接，再问洗手间",
            options: [
              { text: "All connected, thanks! Oh, could you point me to the restroom?",  ok: true,  tip: "point me to = 给我指个方向，问路神器" },
              { text: "Toilet where is location now.",                                 ok: false, tip: "更地道：Could you point me to the restroom?" },
              { text: "Bathroom find me emergency.",                                    ok: false, tip: "问法：Could you point me to the restroom?" },
            ],
            phrase: { en: "Could you point me to the restroom?", zh: "能给我指下洗手间吗？", note: "point me to + 地点：问方向的标准句（restroom 比 toilet 更礼貌）" },
            adds: [{ emoji: "🚻", label: "Restroom ✓", badge: true, wordId: "restroom" }],
          },
          {
            npcLines: [
              "Sure! It's down the hall, past the bookshelf, on your left. Oh — while you're here, I noticed you never use the tip jar. Just so you know, it's totally optional!",
              "Right down the hall, left after the bookshelf! Hey, by the way — no pressure on the tip jar, it's fully optional here!",
              "Down the hall, left at the bookshelf! Oh and FYI — tipping is totally up to you, no obligation!",
            ],
            npcZh: "当然！沿走廊走，过书架后左手边。对了——我注意到您从来不碰小费罐。说明一下，完全是自愿的！",
            task: "了解小费文化",
            options: [
              { text: "Oh interesting! How does tipping work here? I never know the custom.",  ok: true,  tip: "主动了解文化习俗，How does...work? 万能提问" },
              { text: "Tip is money trap yes?",                                            ok: false, tip: "小费是文化习俗，问：How does tipping work?" },
              { text: "No tip country rules.",                                              ok: false, tip: "了解清楚更好：How does tipping work here?" },
            ],
            phrase: { en: "How does ___ work?", zh: "……是怎么运作的？", note: "文化/规则/流程万能提问句" },
          },
          {
            npcLines: [
              "Great question! At cafés like this, it's casual — a dollar in the jar is a nice gesture, but nobody expects it. At sit-down restaurants, it's different — 15 to 20 percent is the norm!",
              "So here's the deal: café tipping is chill — a buck in the jar is sweet, but optional! Restaurants are a whole different story — 15 to 20 percent expected!",
              "Here: casual! A dollar in the jar is appreciated but never required. Sit-down restaurants though — 15 to 20 percent is basically mandatory!",
            ],
            npcZh: "好问题！像这样的咖啡店比较随意——往罐里放一美元是好意，但没人强求。堂食餐厅就不同了——15% 到 20% 是惯例！",
            task: "表示感谢讲解并给小费",
            options: [
              { text: "That's really helpful, thanks! Here's a little something for the jar.",  ok: true,  tip: "文化知识 + 实践：a little something 表示\"一点心意\"" },
              { text: "Still no understand, keep money.",                                    ok: false, tip: "店员解释了惯例，可以实践一下" },
              { text: "Restaurant percent too much scary.",                                  ok: false, tip: "了解文化是好事，也可以给点小费试试" },
            ],
            phrase: { en: "Here's a little something.", zh: "一点小意思", note: "给小费的轻巧说法：a little something = 一点心意" },
            adds: [{ emoji: "💰", label: "Tipped $1", badge: true, wordId: "tip" }],
          },
          {
            npcLines: [
              "Oh, you didn't have to! Thank you, Alex — you just made my day. Your flat white's ready, by the way!",
              "Aww, thank you so much! That's so kind. Oh — your flat white is up!",
              "You're the best, Alex! Thanks a million. And hey — flat white's ready!",
            ],
            npcZh: "哎呀，您不必的！谢谢 Alex——你让我今天特别开心。对了，您的 flat white 好了！",
            task: "取餐",
            options: [
              { text: "My pleasure! Thanks for the coffee lesson today!",  ok: true,  tip: "coffee lesson 幽默总结今天所学" },
              { text: "Yes coffee now mine.",                            ok: false, tip: "更友好：Thanks for the coffee lesson!" },
              { text: "Money for knowledge trade.",                      ok: false, tip: "知识是无价的，幽默道谢即可" },
            ],
            phrase: { en: "Thanks for the ___ lesson!", zh: "谢谢你的……课！", note: "幽默致谢句式：把日常帮助说成一堂课" },
          },
          {
            npcLines: [
              "Anytime, Alex — you're my favorite student! Enjoy the flat white, and the Wi-Fi!",
              "Always happy to teach! Enjoy the coffee and the free internet, professor!",
              "Anytime! Enjoy the flat white and your coffee-fluent day, Alex!",
            ],
            npcZh: "随时来问 Alex——您是我最喜欢的学生！享用您的 flat white 和 Wi-Fi 吧！",
            task: "完成文化深潜，幽默道别",
            options: [
              { text: "Ha! Coffee scholar signing off. See you next lesson!",  ok: true,  tip: "signing off 电台用语，幽默收尾" },
              { text: "Bye teacher coffee man.",                             ok: false, tip: "更幽默：Coffee scholar signing off!" },
              { text: "School over for today.",                              ok: false, tip: "俏皮一点：Signing off! See you!" },
            ],
            phrase: { en: "Signing off!", zh: "下线啦/告退啦！", note: "电台/直播用语：幽默的\"我先撤了\"" },
          },
        ],
      },
      {
        id: "v8",
        title: "第 8 次光顾 · 会员与优惠",
        titleEn: "Rewards & Deals",
        emoji: "💳",
        desc: "积分卡、礼品卡、今日特惠——用英语算清每一分钱。",
        reward: { en: "rewards", zh: "你已经是精通省钱之道的咖啡老江湖了！💰" },
        steps: [
          {
            npcLines: [
              "Morning, Alex! Hey — you're here almost every day. Have you thought about joining our rewards program?",
              "Hi Alex! You know, you're quite the regular. Ever considered our rewards program?",
              "Alex! Daily regular, I see you! Have I mentioned our rewards program yet?",
            ],
            npcZh: "早上好 Alex！嘿——您几乎天天来。考虑过加入我们的会员积分计划吗？",
            task: "了解积分计划",
            options: [
              { text: "Actually, tell me more! How does the rewards program work?",  ok: true,  tip: "How does...work? 了解规则万能句" },
              { text: "Free money where sign.",                                  ok: false, tip: "问清楚规则：How does it work?" },
              { text: "Cards are scams usually.",                                ok: false, tip: "先了解再判断：How does the program work?" },
            ],
            phrase: { en: "How does the rewards program work?", zh: "积分计划是怎么运作的？", note: "会员/积分/规则类万能问句" },
          },
          {
            npcLines: [
              "It's simple! You earn one point per dollar, and every fifty points gets you a free drink of any size. Plus, members get a free birthday drink!",
              "Super easy! One point per dollar spent, fifty points = one free drink — any size you want! Oh, and a free birthday drink too!",
              "Here's the deal: a dollar equals a point, fifty points equals a free drink — any size! Plus birthday freebies!",
            ],
            npcZh: "很简单！消费一美元得一积分，每 50 积分换一杯任意杯型免费饮品。另外，会员生日还送免费饮品！",
            task: "算一算再决定",
            options: [
              { text: "So if I spend about fifty dollars, I get a free drink? Sounds worth it — sign me up!",  ok: true,  tip: "复述规则确认理解 + 当场决策，精明消费者" },
              { text: "Math too hard, just do it.",                                                        ok: false, tip: "先复述确认：So fifty dollars gets me a free drink?" },
              { text: "Fifty points is one dollar yes?",                                                   ok: false, tip: "是一美元一积分、50 积分换免费饮品" },
            ],
            phrase: { en: "Sounds worth it — sign me up!", zh: "听起来划算——给我办一张！", note: "sign me up = 帮我注册/办理，干脆利落" },
            adds: [{ emoji: "💳", label: "Member ✓", badge: true }],
          },
          {
            npcLines: [
              "Welcome to the club! Just your phone number or email, and you're in. Every purchase now earns points automatically!",
              "You're in! Phone number or email is all I need. Points will rack up automatically from now on!",
              "New member alert! Just need a phone number or email — then automatic points on everything!",
            ],
            npcZh: "欢迎加入！只需手机号或邮箱就办好了。以后每次消费自动累计积分！",
            task: "提供手机号",
            options: [
              { text: "Sure, it's 555-0123.",  ok: true,  tip: "报号码直接说 it's + 号码，简洁自然" },
              { text: "Number privacy no give.", ok: false, tip: "注册会员需要联系方式，报一下即可" },
              { text: "Phone secret forever.",   ok: false, tip: "it's + 号码，直接报出" },
            ],
            phrase: { en: "It's 555-0123.", zh: "是 555-0123", note: "报号码/名字万能句：It's + 信息" },
          },
          {
            npcLines: [
              "Perfect, you're all signed up! Now, what can I get you? Oh wait — did you see today's special? Two dollars off any iced drink!",
              "You're in the system! So what'll it be? Hold on — today's special is two dollars off any iced drink. Interested?",
              "All set, welcome aboard! Ready to order? Oh — quick heads up, iced drinks are two dollars off today!",
            ],
            npcZh: "好了，注册完成！来点什么？等等——看到今日特惠了吗？任意冰饮减 2 美元！",
            task: "问特惠详情",
            options: [
              { text: "Ooh, is there a deal on the iced latte too? How much would I save?",  ok: true,  tip: "How much would I save? 精明确认省多少" },
              { text: "Discount everything free?",                                        ok: false, tip: "问清楚：How much would I save?" },
              { text: "Ice coffee cheap how much is?",                                    ok: false, tip: "更自然：How much would I save?" },
            ],
            phrase: { en: "How much would I save?", zh: "我能省多少？", note: "省钱必备句：deal/discount 场景通用" },
            adds: [{ emoji: "🏷️", label: "Deal: −$2", badge: true, wordId: "deal" }],
          },
          {
            npcLines: [
              "The iced latte is normally five fifty, so with the deal it's three fifty! Plus you'll earn points on it — double win!",
              "Iced latte's usually five fifty, today just three fifty! And it earns points too — win-win!",
              "Normally five fifty, with the special just three fifty! And don't forget the points — double victory!",
            ],
            npcZh: "冰拿铁平时 5 美元 50 美分，今天特惠价只要 3 美元 50 美分！还能累计积分——双赢！",
            task: "决定来一杯",
            options: [
              { text: "Three fifty and I earn points? Great deal — I'll take an iced latte!",  ok: true,  tip: "确认价格 + 复述划算 + 下单，完整消费决策链" },
              { text: "Cold coffee yes give.",                                              ok: false, tip: "说 I'll take an iced latte, please" },
              { text: "Too cheap suspicious.",                                              ok: false, tip: "今日特惠很正常，放心点" },
            ],
            phrase: { en: "Great deal — I'll take it!", zh: "真划算——就它了！", note: "确认划算后的果断下单句" },
            adds: [{ emoji: "🧊", label: "Iced Latte −$2", wordId: "iced" }],
          },
          {
            npcLines: [
              "One iced latte with the deal! Now, how would you like to pay — card, cash, or do you have a gift card?",
              "Iced latte, deal price applied! Payment — card, cash, or gift card?",
              "Deal applied! One iced latte coming up. Card, cash, or gift card today?",
            ],
            npcZh: "一杯特惠冰拿铁！怎么付款——刷卡、现金，还是您有礼品卡？",
            task: "用礼品卡付款",
            options: [
              { text: "Can I pay with a gift card? I got one for my birthday.",  ok: true,  tip: "pay with a gift card 礼品卡付款" },
              { text: "Birthday money card use.",                              ok: false, tip: "说 Can I pay with a gift card?" },
              { text: "Free money card special.",                               ok: false, tip: "礼品卡叫 gift card：Can I pay with one?" },
            ],
            phrase: { en: "Can I pay with a gift card?", zh: "能用礼品卡付款吗？", note: "付款三件套：by card / in cash / with a gift card" },
            adds: [{ emoji: "🎁", label: "Gift Card", badge: true, wordId: "giftcard" }],
          },
          {
            npcLines: [
              "Absolutely! Let's see... you've got twenty dollars on this card. After the three fifty, you'll have sixteen fifty left!",
              "Sure thing! Ooh, twenty dollars on here. The latte takes it to sixteen fifty remaining!",
              "Gift card it is! Twenty dollar balance — after today, sixteen fifty left over!",
            ],
            npcZh: "当然可以！看看……这张卡里有 20 美元。付掉 3 美元 50 美分后，还剩 16 美元 50 美分！",
            task: "确认余额并付款",
            options: [
              { text: "Sixteen fifty left — got it. Thank you!",  ok: true,  tip: "复述余额确认理解：数字听力实战" },
              { text: "Money numbers confusing.",               ok: false, tip: "复述确认：Sixteen fifty left, right?" },
              { text: "Card still has money yes much.",         ok: false, tip: "复述具体数字：Sixteen fifty" },
            ],
            phrase: { en: "___ left — got it.", zh: "还剩……，明白了", note: "复述数字确认理解：防算错钱的保险栓" },
            adds: [{ emoji: "💳", label: "Paid $3.50", badge: true }],
          },
          {
            npcLines: [
              "And with your new membership, that three fifty just earned you three points! You're at three out of fifty already.",
              "By the way — three points earned just now with your membership! Three down, forty-seven to go!",
              "Membership bonus: three points from this drink! Only forty-seven more until a free one!",
            ],
            npcZh: "而且用您的新会员身份，这 3.5 美元刚赚了 3 个积分！已经有 3 分了，离 50 分还差 47。",
            task: "感叹积分进度",
            options: [
              { text: "Only forty-seven to go! I'll get there in no time. Thanks!",  ok: true,  tip: "Only...to go 还差多少，进度表达神器" },
              { text: "Forty seven is long time sad.",                           ok: false, tip: "乐观一点：I'll get there in no time!" },
              { text: "Free drink never coming.",                                ok: false, tip: "常来很快就到了：in no time!" },
            ],
            phrase: { en: "Only ___ to go!", zh: "只差……了！", note: "进度倒计时表达：减肥、攒钱、集邮通用" },
            adds: [{ emoji: "⭐", label: "3 Points", badge: true, wordId: "point" }],
          },
          {
            npcLines: [
              "Here's your iced latte, and your receipt shows your points balance. Welcome again to the Sunny family, Alex!",
              "One iced latte, and the receipt has your points on it! Officially a Sunny Café member, Alex!",
              "Iced latte and receipt — points are printed at the bottom! Welcome to the family, Alex!",
            ],
            npcZh: "您的冰拿铁，小票上印着积分余额。欢迎正式加入 Sunny 大家庭，Alex！",
            task: "完成会员之旅，道别",
            options: [
              { text: "Thanks! See you tomorrow — I've got points to earn!",  ok: true,  tip: "幽默道别 + 积分梗，圆满收官" },
              { text: "Bye points coffee shop.",                            ok: false, tip: "更俏皮：I've got points to earn!" },
              { text: "Leaving now forever maybe.",                          ok: false, tip: "常客道别：See you tomorrow!" },
            ],
            phrase: { en: "I've got points to earn!", zh: "我还有积分要赚呢！", note: "幽默道别：把回访理由说成任务" },
          },
        ],
      },
    ],
  },
  {
    id: "market",
    name: "超市",
    nameEn: "Supermarket",
    emoji: "🛒",
    iconId: "cart",
    cover: "🛒🍎🥦",
    theme: "market",
    accent: "#4d8b3a",
    accentSoft: "#e4f2dc",
    deco: "🍃",
    deco2: "🦋",
    intro: "你带着一张英文购物清单走进超市。跟着引导，把清单上的东西买齐吧！",
    orderLabel: "🧾 购物清单",
    items: [
      { id: "apple",  en: "apple",  zh: "苹果",   phon: "/ˈæpl/",  emoji: "🍎", sent: "An apple a day." },
      { id: "banana", en: "banana", zh: "香蕉",   phon: "/bəˈnɑːnə/", emoji: "🍌", sent: "Monkeys love bananas." },
      { id: "grape",  en: "grapes", zh: "葡萄",   phon: "/ɡreɪps/", emoji: "🍇", sent: "These grapes are sweet." },
      { id: "milk",   en: "milk",   zh: "牛奶",   phon: "/mɪlk/",  emoji: "🥛", sent: "I drink milk every morning." },
      { id: "bread",  en: "bread",  zh: "面包",   phon: "/bred/",  emoji: "🍞", sent: "Fresh bread smells good." },
      { id: "egg",    en: "eggs",   zh: "鸡蛋",   phon: "/eɡz/",   emoji: "🥚", sent: "I want two eggs." },
      { id: "fish",   en: "fish",   zh: "鱼",     phon: "/fɪʃ/",   emoji: "🐟", sent: "Fish is good for you." },
      { id: "cheese", en: "cheese", zh: "奶酪",   phon: "/tʃiːz/", emoji: "🧀", sent: "Cheese on bread, yummy." },
      { id: "carrot", en: "carrot", zh: "胡萝卜", phon: "/ˈkærət/", emoji: "🥕", sent: "Rabbits eat carrots." },
      { id: "broccoli",en: "broccoli", zh: "西兰花", phon: "/ˈbrɒkəli/", emoji: "🥦", sent: "Eat your broccoli!" },
      { id: "tomato", en: "tomato", zh: "番茄",   phon: "/təˈmɑːtəʊ/", emoji: "🍅", sent: "Is it a fruit or a vegetable?" },
      { id: "cart",   en: "cart",   zh: "购物车", phon: "/kɑːt/",  emoji: "🛒", sent: "Push the cart down the aisle." },
    ],
    // 单轮结构（向后兼容字段 steps）
    steps: [
      {
        npcLines: [
          "Hi there! Welcome to Fresh Mart. Do you need a shopping cart?",
          "Hello, welcome to Fresh Mart! Can I get you a shopping cart?",
          "Welcome in! Would you like a cart for your shopping?",
        ],
        npcZh: "您好！欢迎来到 Fresh 超市。您需要购物车吗？",
        task: "要一辆购物车",
        options: [
          { text: "Yes, please. Thank you!",  ok: true,  tip: "Yes, please 简洁礼貌地接受" },
          { text: "I want car.",             ok: false, tip: "是购物车 cart 不是 car，说 a cart please" },
          { text: "No, I am cart.",          ok: false, tip: "哈哈，说自己要一辆：Yes, please" },
        ],
        phrase: { en: "Yes, please.", zh: "好的，麻烦了", note: "接受提议的标准回答，和 No, thanks 配对使用" },
        adds: [{ emoji: "🛒", label: "Cart", badge: true }],
      },
      {
        npcLines: [
          "Here you go. If you need anything, just ask! What are you looking for today?",
          "There you go! Just holler if you need help. What are you shopping for today?",
          "You're all set! I'm around if you need me. What can I help you find?",
        ],
        npcZh: "给您。有任何需要随时问我！您今天想买什么？",
        task: "问苹果在哪个通道",
        options: [
          { text: "Where can I find the apples?",       ok: true,  tip: "Where can I find...? 找东西万能句" },
          { text: "Apple where where?",                 ok: false, tip: "用 Where can I find the apples? 提问" },
          { text: "Give me apples now.",                ok: false, tip: "先问位置：Where can I find...?" },
        ],
        phrase: { en: "Where can I find the ___?", zh: "……在哪里能找到？", note: "超市/商场找东西万能句，套任何商品" },
      },
      {
        npcLines: [
          "The apples are in aisle 3, right next to the bananas. How many would you like?",
          "You'll find the apples in aisle 3, by the bananas. How many can I get you?",
          "Apples are in aisle 3, next to the bananas. How many would you like?",
        ],
        npcZh: "苹果在 3 号通道，就在香蕉旁边。您要几个？",
        task: "要六个苹果",
        options: [
          { text: "Six apples, please.",   ok: true,  tip: "数词 + 名词，直接说数量" },
          { text: "Apple six number.",     ok: false, tip: "语序：Six apples, please" },
          { text: "I want apple many.",    ok: false, tip: "说清楚数量：Six apples, please" },
        ],
        phrase: { en: "Six ___, please.", zh: "请给我六个……", note: "报数量直说：数字 + 名词复数 + please" },
        adds: [{ emoji: "🍎", label: "Apples ×6", wordId: "apple" }],
      },
      {
        npcLines: [
          "Great! Our bread is on sale today — fresh from the bakery. Would you like a loaf?",
          "Good pick! Hey, our bread's on sale today, fresh from the bakery. Want a loaf?",
          "Nice! Just so you know, today's bread is on sale — bakery fresh. Care for a loaf?",
        ],
        npcZh: "好的！我们的面包今天特价——烘焙区新鲜出炉的。您要来一条吗？",
        task: "要一条面包",
        options: [
          { text: "Yes, a loaf of bread, please.",  ok: true,  tip: "一条面包的量词是 loaf，a loaf of bread" },
          { text: "I want one bread.",              ok: false, tip: "面包的量词是 loaf：a loaf of bread" },
          { text: "Bread yes give.",                ok: false, tip: "说 A loaf of bread, please" },
        ],
        phrase: { en: "A loaf of bread, please.", zh: "请给我一条面包", note: "loaf 是面包的量词，切片面包叫 a slice" },
        adds: [{ emoji: "🍞", label: "Bread", wordId: "bread" }],
      },
      {
        npcLines: [
          "Good choice! The milk is in the dairy section, aisle 5. Do you also need eggs?",
          "Nice! Milk's in aisle 5, dairy section. Would you like some eggs too?",
          "You got it! For milk, head to aisle 5, dairy section. Need any eggs while you're at it?",
        ],
        npcZh: "好选择！牛奶在乳制品区，5 号通道。您还需要鸡蛋吗？",
        task: "需要一打鸡蛋",
        options: [
          { text: "Yes, a dozen eggs, please.",  ok: true,  tip: "a dozen = 一打（12 个），常用量词" },
          { text: "Twelve egg please.",          ok: false, tip: "对的说法：a dozen eggs，注意复数" },
          { text: "I need egg one.",             ok: false, tip: "一打鸡蛋说 a dozen eggs" },
        ],
        phrase: { en: "A dozen ___, please.", zh: "请给我一打……", note: "a dozen = 12 个，鸡蛋/甜甜圈等都这么数" },
        adds: [{ emoji: "🥚", label: "Eggs ×12", wordId: "egg" }],
      },
      {
        npcLines: [
          "Sure thing. Is there anything else on your list? We have fresh fish and cheese today.",
          "No problem. Anything else you need? Today we've got fresh fish and cheese in stock.",
          "You bet! What else is on your list? Fresh fish and cheese just came in today.",
        ],
        npcZh: "没问题。您清单上还有别的吗？我们今天有新鲜的鱼和奶酪。",
        task: "问奶酪多少钱",
        options: [
          { text: "How much is the cheese?",   ok: true,  tip: "How much is...? 问价格万能句" },
          { text: "Cheese money how?",         ok: false, tip: "问价格用 How much is the cheese?" },
          { text: "What price cheese has?",    ok: false, tip: "自然说法：How much is the cheese?" },
        ],
        phrase: { en: "How much is the ___?", zh: "……多少钱？", note: "问价万能句；复数用 How much are..." },
      },
      {
        npcLines: [
          "The cheese is five dollars. And there's a 20% discount on all vegetables today!",
          "That cheese is five bucks. Oh, and all vegetables are 20% off today!",
          "Cheese's five dollars. Heads up — every vegetable is 20% off today!",
        ],
        npcZh: "奶酪 5 美元。而且今天所有蔬菜都有 8 折优惠！",
        task: "趁打折买西兰花",
        options: [
          { text: "I'll take the broccoli then, it's a good deal!",  ok: true,  tip: "a good deal = 划算，购物常用表达" },
          { text: "Discount me broccoli.",                            ok: false, tip: "说 I'll take the broccoli 就好" },
          { text: "I buy cheap vegetable now.",                       ok: false, tip: "更自然：I'll take the broccoli" },
        ],
        phrase: { en: "It's a good deal!", zh: "真划算！", note: "deal = 交易，a good deal 买到就是赚到的感觉" },
        adds: [{ emoji: "🥦", label: "Broccoli −20%", wordId: "broccoli" }],
      },
      {
        npcLines: [
          "Excellent! You've got apples, bread, eggs, cheese, and broccoli. Is that everything?",
          "Great haul! Apples, bread, eggs, cheese, broccoli — is that everything on your list?",
          "Perfect! So that's apples, bread, eggs, cheese, and broccoli. Did you get everything?",
        ],
        npcZh: "太好了！您买了苹果、面包、鸡蛋、奶酪和西兰花。就这些了吗？",
        task: "确认买齐了，准备结账",
        options: [
          { text: "Yes, that's everything. I'm ready to check out.",  ok: true,  tip: "check out = 结账，超市购物必备词" },
          { text: "Finish buy me.",                                   ok: false, tip: "说 I'm ready to check out" },
          { text: "No more thing.",                                   ok: false, tip: "更自然：That's everything" },
        ],
        phrase: { en: "I'm ready to check out.", zh: "我可以结账了", note: "check out 超市结账；退货说 return / exchange" },
      },
      {
        npcLines: [
          "Great! The checkout is right over there. Did you bring your own bag, or would you like to buy one?",
          "Perfect! Checkout's just over there. Did you bring a bag, or would you like to purchase one?",
          "Awesome! The registers are right there. Got your own bag, or do you need to buy one today?",
        ],
        npcZh: "好的！收银台就在那边。您自带购物袋了吗，还是需要买一个？",
        task: "需要买一个袋子",
        options: [
          { text: "I'd like to buy a bag, please.",  ok: true,  tip: "buy a bag 买个袋子，环保话题常用" },
          { text: "Bag me one give.",                ok: false, tip: "说 I'd like to buy a bag, please" },
          { text: "I have bag no.",                  ok: false, tip: "更自然：I'd like to buy one, please" },
        ],
        phrase: { en: "I'd like to buy a ___, please.", zh: "我想买一个……", note: "I'd like to buy 万能购物句，后接任何商品" },
        adds: [{ emoji: "👜", label: "Bag", badge: true }],
      },
      {
        npcLines: [
          "No problem, that's one bag. Your total comes to twenty-three dollars. How would you like to pay?",
          "Sure, one bag it is! That'll be twenty-three dollars altogether. How are you paying today?",
          "Got it, one bag. Your total is twenty-three dollars. Will that be cash or card?",
        ],
        npcZh: "没问题，一个袋子。您一共消费 23 美元。您想怎么付款？",
        task: "用现金付款",
        options: [
          { text: "I'll pay in cash. Here you go.",  ok: true,  tip: "pay in cash 现金付款，Here you go 递钱时说" },
          { text: "Cash money give you.",            ok: false, tip: "说 I'll pay in cash" },
          { text: "Here is paper.",                  ok: false, tip: "纸币不是 paper，说 I'll pay in cash" },
        ],
        phrase: { en: "I'll pay in cash.", zh: "我付现金", note: "in cash 现金 / by card 刷卡，付款二选一" },
        adds: [{ emoji: "💵", label: "Paid $23", badge: true }],
      },
      {
        npcLines: [
          "Thank you! Here's your change and receipt. Have a great day, and see you next time!",
          "Thanks a bunch! Here's your change and receipt. Have a wonderful day — see you again!",
          "Appreciate it! Your change and receipt, right here. Great seeing you — come back soon!",
        ],
        npcZh: "谢谢！这是找您的零钱和小票。祝您有美好的一天，下次再见！",
        task: "道谢告别",
        options: [
          { text: "Thank you! See you next time!",  ok: true,  tip: "See you next time! 告别+再来意向，很友好" },
          { text: "Bye market person.",             ok: false, tip: "说 See you next time 更自然" },
          { text: "Money bye.",                     ok: false, tip: "简单说 Thank you! See you!" },
        ],
        phrase: { en: "See you next time!", zh: "下次再见！", note: "告别 + 表达再来意向，店员听了会很开心" },
      },
    ],
    reward: { en: "cart", zh: "你完成了一次完整的英文超市购物！🛒" },
  },
];
