// 英语世界 - 慢速生活频道（Slow Vlog）数据
// 借鉴 TikTok 慢 vlog：拿起一样东西/做一个动作 + 慢速英语讲解
// 每张卡：emoji 舞台 + 动作动词（教学重点）+ 慢速朗读 + 中文（默认折叠）
// media 字段预留升级接口：emoji（默认）/ image / video
const VLOGS = [
  {
    id: "morning",
    title: "Morning Routine",
    titleZh: "早晨的一小时",
    emoji: "🌅",
    desc: "从闹钟响到出门——一天中动作动词最密集的时刻。",
    linkedScene: "cafe",
    cards: [
      {
        emoji: "⏰", anim: "ring",
        en: "This is my alarm clock. It's seven in the morning. Time to wake up!",
        zh: "这是我的闹钟。早上七点了。该起床啦！",
        words: ["alarm clock", "wake up"],
      },
      {
        emoji: "🪟", anim: "curtain",
        en: "I open the curtains. Look — the sun is coming up. What a beautiful morning!",
        zh: "我拉开窗帘。看——太阳升起来了。多美的早晨！",
        words: ["open", "curtain"],
      },
      {
        emoji: "🪥", anim: "brush",
        en: "Now I brush my teeth. I squeeze a little toothpaste onto my brush.",
        zh: "现在我刷牙。往牙刷上挤一点牙膏。",
        words: ["brush", "squeeze", "toothpaste"],
      },
      {
        emoji: "🍞", anim: "toast",
        en: "Time for breakfast! I put two slices of bread into the toaster.",
        zh: "早餐时间！我放两片面包进烤面包机。",
        words: ["slice", "toaster"],
      },
      {
        emoji: "☕", anim: "pour",
        en: "Then I pour myself a cup of coffee. The smell wakes me up better than the alarm!",
        zh: "然后给自己倒一杯咖啡。咖啡的香味比闹钟更能叫醒我！",
        words: ["pour", "cup"],
      },
      {
        emoji: "🧥", anim: "wear",
        en: "I put on my jacket and grab my keys. Almost ready to go!",
        zh: "我穿上外套，拿上钥匙。差不多可以出门了！",
        words: ["put on", "grab"],
      },
      {
        emoji: "👟", anim: "step",
        en: "Last step — I put on my shoes and step outside. Have a great day!",
        zh: "最后一步——穿上鞋子，走出门。祝今天愉快！",
        words: ["step outside"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! If someone is grumpy in the morning, you can say they 'woke up on the wrong side of the bed'!",
        zh: "冷知识！如果有人早上脾气不好，可以说他 woke up on the wrong side of the bed（从床的错误一侧醒来）！",
        words: ["grumpy"],
      },
    ],
  },
  {
    id: "cooking",
    title: "Cooking Breakfast",
    titleZh: "做一份早餐",
    emoji: "🍳",
    desc: "打蛋、搅拌、煎、翻面——厨房是最棒的英语教室。",
    linkedScene: "restaurant",
    cards: [
      {
        emoji: "🥚", anim: "crack",
        en: "First, I crack two eggs into a bowl. Careful — don't get any shells in!",
        zh: "首先，我往碗里打两个鸡蛋。小心——别把蛋壳弄进去！",
        words: ["crack", "bowl", "shell"],
      },
      {
        emoji: "🥄", anim: "stir",
        en: "I stir the eggs with a fork. Round and round, until they're all yellow.",
        zh: "我用叉子搅拌鸡蛋。一圈一圈，直到完全变成黄色。",
        words: ["stir", "fork"],
      },
      {
        emoji: "🍳", anim: "heat",
        en: "Now I heat up the pan and add a little butter. Listen — it sizzles!",
        zh: "现在我把锅烧热，加一点黄油。听——滋滋响！",
        words: ["heat up", "pan", "sizzle"],
      },
      {
        emoji: "🫗", anim: "pour",
        en: "I pour the eggs into the pan. Watch them turn from liquid to solid. It's like magic!",
        zh: "我把蛋液倒进锅里。看它从液体变成固体。像魔法一样！",
        words: ["liquid", "solid"],
      },
      {
        emoji: "🍳", anim: "flip",
        en: "Time to flip! I flip the omelette like a chef. Okay... almost like a chef.",
        zh: "翻面的时间到了！我像大厨一样翻蛋。好吧……差不多像大厨。",
        words: ["flip", "omelette"],
      },
      {
        emoji: "🥓", anim: "fry",
        en: "The bacon is frying too. It gets crispy and the whole kitchen smells amazing.",
        zh: "培根也在煎。变得脆脆的，整个厨房都是香味。",
        words: ["crispy", "bacon"],
      },
      {
        emoji: "🍽️", anim: "plate",
        en: "Everything is ready! I plate the eggs and bacon. Breakfast is served!",
        zh: "都好了！我把鸡蛋和培根装盘。早餐上桌！",
        words: ["plate"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! Chefs say 'mise en place' — a French phrase that means 'everything in its place' before you start cooking!",
        zh: "冷知识！大厨会说 mise en place——法语短语，意思是下厨前\"一切就位\"！",
        words: ["mise en place"],
      },
    ],
  },
  {
    id: "coffee",
    title: "Making Coffee",
    titleZh: "手冲一杯咖啡",
    emoji: "☕",
    desc: "磨豆、烧水、绕圈注水——和咖啡店场景联动的输入训练。",
    linkedScene: "cafe",
    cards: [
      {
        emoji: "🫘", anim: "grind",
        en: "These are coffee beans. I grind them into powder. The fresh smell is the best part!",
        zh: "这些是咖啡豆。我把它们磨成粉。新鲜的香味是最棒的部分！",
        words: ["coffee bean", "grind"],
      },
      {
        emoji: "🫖", anim: "boil",
        en: "While the beans grind, I boil some water. Not too hot — just below boiling.",
        zh: "磨豆的同时我烧一些水。不能太烫——略低于沸点。",
        words: ["boil", "below"],
      },
      {
        emoji: "☕", anim: "place",
        en: "I place a paper filter in the dripper and rinse it with hot water.",
        zh: "我在滤杯里放一张滤纸，用热水润湿它。",
        words: ["filter", "rinse"],
      },
      {
        emoji: "🫗", anim: "pour",
        en: "Now the fun part — I pour the water in slow circles. Round and round, over the coffee.",
        zh: "现在是有趣的部分——我绕圈缓慢注水。一圈一圈，淋在咖啡粉上。",
        words: ["in circles"],
      },
      {
        emoji: "⏳", anim: "drip",
        en: "Then I wait. The coffee drips slowly, drop by drop. Good things take time!",
        zh: "然后我等待。咖啡慢慢地滴落，一滴一滴。好东西需要时间！",
        words: ["drip", "drop by drop"],
      },
      {
        emoji: "👃", anim: "smell",
        en: "I smell the coffee. Mmm — nutty, a little sweet. This is going to be a good cup.",
        zh: "我闻闻咖啡。嗯——坚果香，还有点甜。这会是很好的一杯。",
        words: ["nutty"],
      },
      {
        emoji: "😋", anim: "sip",
        en: "Finally, I take my first sip. Warm, smooth, perfect. Good morning to me!",
        zh: "最后，喝第一口。温润、顺滑、完美。祝我早安！",
        words: ["sip", "smooth"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! Coffee people say a perfect cup has 'balance' — not too bitter, not too sour, just right!",
        zh: "冷知识！咖啡人说好咖啡讲究 balance（平衡）——不太苦、不太酸，刚刚好！",
        words: ["bitter", "balance"],
      },
    ],
  },
  {
    id: "grocery",
    title: "Grocery Run",
    titleZh: "去超市采购",
    emoji: "🛒",
    desc: "列清单、挑水果、排队结账——和超市场景联动的输入训练。",
    linkedScene: "market",
    cards: [
      {
        emoji: "📝", anim: "place",
        en: "First, I write a shopping list. Milk, eggs, bread — so I don't forget anything.",
        zh: "首先，我写一张购物清单。牛奶、鸡蛋、面包——这样就不会忘东西。",
        words: ["shopping list", "forget"],
      },
      {
        emoji: "🛒", anim: "step",
        en: "I grab a cart at the entrance. The wheels squeak a little, but it still works.",
        zh: "我在入口处推一辆购物车。轮子有点响，但还能用。",
        words: ["cart", "entrance", "wheel", "squeak"],
      },
      {
        emoji: "🍎", anim: "wear",
        en: "In the fruit section, I pick out some red apples. I give each one a little squeeze.",
        zh: "在水果区，我挑选一些红苹果。每一个都轻轻捏一捏。",
        words: ["fruit section", "pick out"],
      },
      {
        emoji: "🥛", anim: "place",
        en: "Next, the dairy aisle. I grab a carton of milk and check the date on it.",
        zh: "接下来是乳制品货架。我拿一盒牛奶，看看上面的日期。",
        words: ["dairy", "aisle", "carton"],
      },
      {
        emoji: "🧊", anim: "wear",
        en: "I pick up some frozen vegetables from the freezer. Quick — don't let them melt!",
        zh: "我从冰柜拿一些冷冻蔬菜。快点——别让它们化了！",
        words: ["frozen", "freezer", "melt"],
      },
      {
        emoji: "🏷️", anim: "step",
        en: "This bread is on sale — thirty percent off! What a deal. Into the cart it goes.",
        zh: "这个面包在打折——七折！真划算。放进购物车。",
        words: ["on sale", "percent off", "deal"],
      },
      {
        emoji: "💳", anim: "place",
        en: "Time to check out. I stand in line, put everything on the belt, and pay by card.",
        zh: "结账时间。我排队，把所有东西放上传送带，刷卡付款。",
        words: ["check out", "stand in line", "belt"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! In English, a quick trip to buy a few things is called a 'quick run' — like 'a grocery run'!",
        zh: "冷知识！英语里快去快回买点东西叫 a quick run——比如 a grocery run（跑一趟超市）！",
        words: ["quick run"],
      },
    ],
  },
  {
    id: "laundry",
    title: "Doing Laundry",
    titleZh: "洗衣服",
    emoji: "🧺",
    desc: "分类、倒洗衣液、烘干、叠好——洗衣房全流程动词课。",
    linkedScene: "hotel",
    cards: [
      {
        emoji: "🧺", anim: "wear",
        en: "Laundry day! I carry my basket of dirty clothes to the washing machine.",
        zh: "洗衣日！我把一篮脏衣服搬到洗衣机前。",
        words: ["laundry", "basket", "dirty", "washing machine"],
      },
      {
        emoji: "👔", anim: "place",
        en: "First, I sort the clothes — whites in one pile, dark colors in another.",
        zh: "首先，我给衣服分类——白色一堆，深色一堆。",
        words: ["sort", "pile", "whites"],
      },
      {
        emoji: "🧴", anim: "pour",
        en: "I pour the detergent into the machine. One cap is enough — not too much!",
        zh: "我把洗衣液倒进机器。一盖就够了——别倒太多！",
        words: ["detergent", "cap"],
      },
      {
        emoji: "🫧", anim: "wash",
        en: "I press the start button. Look at all those bubbles! The machine spins round and round.",
        zh: "我按下启动键。看这些泡泡！机器一圈一圈地转。",
        words: ["press", "bubble", "spin"],
      },
      {
        emoji: "⏲️", anim: "ring",
        en: "The cycle takes forty minutes. While I wait, I fold the towels from last time.",
        zh: "一轮要四十分钟。等待时，我把上次的毛巾叠好。",
        words: ["cycle", "fold", "towel"],
      },
      {
        emoji: "🔥", anim: "drip",
        en: "Now into the dryer. It tumbles with hot air until everything is dry and warm.",
        zh: "现在放进烘干机。它用热风翻滚，直到所有东西又干又暖。",
        words: ["dryer", "tumble"],
      },
      {
        emoji: "👕", anim: "fold",
        en: "Last step — I fold the clean clothes neatly and put them away. Done!",
        zh: "最后一步——我把干净衣服叠整齐收好。完成！",
        words: ["neatly", "put away"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! Americans say 'do the laundry', but British people often say 'do the washing'!",
        zh: "冷知识！美国人说 do the laundry，英国人常说说 do the washing！",
        words: ["do the laundry"],
      },
    ],
  },
  {
    id: "cleaning",
    title: "Cleaning the House",
    titleZh: "大扫除",
    emoji: "🧹",
    desc: "吸尘、擦灰、拖地、倒垃圾——把家变干净的一套动词。",
    linkedScene: "hotel",
    cards: [
      {
        emoji: "🧹", anim: "sweep",
        en: "Cleaning day! I grab the broom and sweep the floor, corner to corner.",
        zh: "大扫除日！我拿起扫把扫地，一个角落都不放过。",
        words: ["broom", "sweep", "corner"],
      },
      {
        emoji: "🧽", anim: "brush",
        en: "Next, I wipe the table with a wet sponge. Crumbs, be gone!",
        zh: "接下来，我用湿海绵擦桌子。面包屑，消失吧！",
        words: ["wipe", "sponge", "crumb"],
      },
      {
        emoji: "🥛", anim: "wash",
        en: "The sink is full of dishes. I wash them with dish soap, then rinse them clean.",
        zh: "水槽里堆满了碗碟。我用洗洁精洗，然后冲干净。",
        words: ["sink", "dish soap", "rinse"],
      },
      {
        emoji: "🪣", anim: "pour",
        en: "I fill the bucket with warm water and add a little floor cleaner.",
        zh: "我往桶里接温水，加一点地板清洁剂。",
        words: ["bucket", "fill", "floor cleaner"],
      },
      {
        emoji: "🧹", anim: "sweep",
        en: "Then I mop the floor, back and forth. Squeeze the mop first — don't flood the house!",
        zh: "然后我来回拖地。先拧干拖把——别把家淹了！",
        words: ["mop", "back and forth", "flood"],
      },
      {
        emoji: "🗑️", anim: "step",
        en: "The trash is full. I tie up the bag and take it outside to the bin.",
        zh: "垃圾满了。我把袋子系好，拎出去扔进垃圾桶。",
        words: ["trash", "tie up", "bin"],
      },
      {
        emoji: "✨", anim: "wear",
        en: "I vacuum the sofa, fluff the pillows, and... done! The house looks brand new.",
        zh: "我给沙发吸尘，把抱枕拍松，然后……完成！家里焕然一新。",
        words: ["vacuum", "fluff", "brand new"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! A big, deep cleaning is called 'spring cleaning' — even if you do it in autumn!",
        zh: "冷知识！大规模深度打扫叫 spring cleaning（春季大扫除）——哪怕你秋天做！",
        words: ["spring cleaning"],
      },
    ],
  },
{
    id: "commute",
    title: "The Morning Commute",
    titleZh: "早晨通勤",
    emoji: "🚇",
    desc: "赶地铁、刷卡进站、让座下车——通勤路上的高频英语。",
    linkedScene: "transport",
    cards: [
      {
        emoji: "🚪", anim: "step",
        en: "I leave home at eight. The morning commute begins! Let's catch the subway.",
        zh: "我八点出门。早晨通勤开始了！去赶地铁吧。",
        words: ["commute", "catch"],
      },
      {
        emoji: "🏃", anim: "step",
        en: "I walk fast to the station. Don't run — just power-walk with the crowd.",
        zh: "我快步走向车站。不用跑——跟着人流疾走就行。",
        words: ["station", "crowd"],
      },
      {
        emoji: "🎫", anim: "place",
        en: "At the gate, I tap my card. Beep! The door opens, and I'm through.",
        zh: "在闸机口，我刷一下卡。哔！门开了，我过去了。",
        words: ["gate", "tap", "beep"],
      },
      {
        emoji: "🚇", anim: "step",
        en: "The train pulls in. Stand behind the yellow line, and let people off first.",
        zh: "列车进站了。站在黄线后面，先下后上。",
        words: ["pull in", "yellow line", "get off"],
      },
      {
        emoji: "💺", anim: "wear",
        en: "Lucky me — there's one empty seat! I sit down and put my bag on my lap.",
        zh: "真幸运——还有一个空座！我坐下，把包放在腿上。",
        words: ["empty", "lap"],
      },
      {
        emoji: "👵", anim: "place",
        en: "An old lady gets on. I stand up and offer her my seat. She smiles and says thanks.",
        zh: "一位老奶奶上车了。我站起来把座位让给她。她笑着道谢。",
        words: ["get on", "offer"],
      },
      {
        emoji: "🔔", anim: "ring",
        en: "My stop is next. 'Excuse me, this is my stop.' I squeeze through and step off.",
        zh: "下一站是我下车。『借过一下，我到站了。』我挤过去下了车。",
        words: ["stop", "squeeze through", "step off"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! 'Commute' comes from an old ticket: a 'commutation ticket' — a monthly pass for regular travelers!",
        zh: "冷知识！commute 来源于一种旧车票——commutation ticket，就是给天天坐车的人的月票！",
        words: ["monthly pass"],
      },
    ],
  },
{
    id: "dogwalk",
    title: "Walking the Dog",
    titleZh: "遛狗",
    emoji: "🐕",
    desc: "系牵引绳、捡便便、交狗友——遛狗遛出地道英语。",
    linkedScene: "transport",
    cards: [
      {
        emoji: "🦮", anim: "step",
        en: "My dog knows the word 'walk'. The moment I pick up the leash, she starts to spin in circles!",
        zh: "我家狗听得懂 walk 这个词。我一拿起牵引绳，她就开始原地转圈！",
        words: ["leash", "spin in circles"],
      },
      {
        emoji: "🚪", anim: "step",
        en: "Leash on, and out we go. She pulls me down the stairs — slow down, girl!",
        zh: "系好绳，出发。她拽着我下楼——慢点儿，姑娘！",
        words: ["slow down"],
      },
      {
        emoji: "🌳", anim: "wear",
        en: "First stop: her favorite tree. She sniffs it very carefully, like she's reading the news.",
        zh: "第一站：她最爱的那棵树。她非常认真地闻，像在读新闻。",
        words: ["sniff", "carefully"],
      },
      {
        emoji: "🎒", anim: "place",
        en: "When she does her business, I pick it up with a poop bag. Always clean up!",
        zh: "她方便完，我用捡便袋收拾干净。一定要清理！",
        words: ["poop bag", "clean up"],
      },
      {
        emoji: "🐕", anim: "step",
        en: "Uh-oh, a squirrel! She barks and pulls hard. I hold the leash tight and say 'Leave it!'",
        zh: "哎呀，一只松鼠！她狂叫猛拽。我抓紧绳子喊『不许追！』",
        words: ["squirrel", "bark", "leave it"],
      },
      {
        emoji: "🦮", anim: "wear",
        en: "At the park, I let her off the leash in the dog run. She zooms around with other dogs.",
        zh: "到了公园，我在狗狗活动区解开她的绳。她和其他狗一起疯跑。",
        words: ["dog run", "zoom"],
      },
      {
        emoji: "💧", anim: "pour",
        en: "After all that running, she drinks a lot of water. Then we head home, tired and happy.",
        zh: "跑完之后，她喝了好多水。然后我们回家，又累又开心。",
        words: ["head home", "tired"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! Dogs' 'walkies' is British slang for a walk — and it makes every dog in the room go crazy!",
        zh: "冷知识！walkies 是英式俚语『去遛弯』——屋里每只狗听到都会激动到失控！",
        words: ["walkies", "slang"],
      },
    ],
  },
{
    id: "errands",
    title: "Weekend Errands",
    titleZh: "周末办事",
    emoji: "🧾",
    desc: "取干洗衣、下馆子、买药办事——周末跑腿一整套英语。",
    linkedScene: "market",
    cards: [
      {
        emoji: "📝", anim: "place",
        en: "Saturday morning! I make a list of errands: dry cleaner, bank, pharmacy, and lunch out.",
        zh: "周六早上！我列一张办事清单：干洗店、银行、药店，再下馆子吃午饭。",
        words: ["errands", "dry cleaner", "pharmacy"],
      },
      {
        emoji: "👕", anim: "fold",
        en: "First stop, the dry cleaner's. I pick up my clean shirts and pay with exact change.",
        zh: "第一站，干洗店。我取回洗好的衬衫，用零钱正好付清。",
        words: ["pick up", "exact change"],
      },
      {
        emoji: "🏦", anim: "step",
        en: "Next, the bank. I deposit a check at the counter. It only takes two minutes.",
        zh: "下一站，银行。我在柜台存一张支票。只花了两分钟。",
        words: ["deposit", "check", "counter"],
      },
      {
        emoji: "💊", anim: "place",
        en: "At the pharmacy, I refill my prescription. The pharmacist tells me to take it with food.",
        zh: "在药店，我续配处方药。药剂师叮嘱我要随餐服用。",
        words: ["refill", "prescription", "pharmacist"],
      },
      {
        emoji: "☕", anim: "sip",
        en: "Halfway done! I grab a coffee to go and take a short break on a park bench.",
        zh: "任务过半！我买杯外带咖啡，在公园长椅上小歇一会儿。",
        words: ["halfway", "to go", "bench"],
      },
      {
        emoji: "🍜", anim: "smell",
        en: "For lunch, I try that new noodle place. I order at the counter and eat in — no dishes today!",
        zh: "午饭去试试那家新开的面馆。我在柜台点单堂食——今天不用洗碗！",
        words: ["noodle", "eat in"],
      },
      {
        emoji: "✅", anim: "place",
        en: "Last errand: mailing a birthday card at the post office. Everything on the list — done!",
        zh: "最后一件事：去邮局寄一张生日卡。清单上的事——全部搞定！",
        words: ["mail", "birthday card"],
      },
      {
        type: "fun-fact", emoji: "💡",
        en: "Fun fact! 'Errand' means a short trip for a small task. Doing many errands in one trip is called an 'errand run'!",
        zh: "冷知识！errand 指为一桩小事出的门。一趟出门办完一堆事就叫 an errand run！",
        words: ["errand run"],
      },
    ],
  },
];
