// 银行场景头 + 词条
{
  id: "bank",
  name: "银行",
  nameEn: "Bank",
  emoji: "🏦",
  iconId: "bank",
  cover: "🏦💳💵",
  theme: "bank",
  accent: "#2f6b4f",
  accentSoft: "#e2f0e8",
  deco: "✨",
  deco2: "🪙",
  intro: "你需要处理各种银行业务。从开户到换汇，从取款到银行卡出问题——用英文搞定一切！",
  orderLabel: "🏦 业务进度",
  items: [
    { id: "account",    en: "account",    zh: "账户", phon: "/əˈkaʊnt/", emoji: "🧾", sent: "I'd like to open an account." },
    { id: "checking",   en: "checking account", zh: "活期账户", phon: "/ˈtʃekɪŋ əˈkaʊnt/", emoji: "💰", sent: "I need a checking account for daily use." },
    { id: "savings",    en: "savings account", zh: "储蓄账户", phon: "/ˈseɪvɪŋz əˈkaʊnt/", emoji: "🐖", sent: "Put your money in a savings account." },
    { id: "deposit",    en: "deposit",    zh: "存款", phon: "/dɪˈpɒzɪt/", emoji: "📥", sent: "I'd like to make a deposit." },
    { id: "withdraw",   en: "withdraw",   zh: "取款", phon: "/wɪðˈdrɔː/", emoji: "📤", sent: "I need to withdraw some cash." },
    { id: "exchange",   en: "exchange rate", zh: "汇率", phon: "/ɪksˈtʃeɪndʒ reɪt/", emoji: "💱", sent: "What's the exchange rate today?" },
    { id: "teller",     en: "teller",     zh: "柜员", phon: "/ˈtelə/", emoji: "🧑‍💼", sent: "Please wait for the next available teller." },
    { id: "pin",        en: "PIN",        zh: "密码", phon: "/pɪn/", emoji: "🔐", sent: "Enter your PIN on the keypad." },
    { id: "sign",       en: "signature",  zh: "签名", phon: "/ˈsɪɡnətʃə/", emoji: "✍️", sent: "Please sign on the dotted line." },
    { id: "balance",    en: "balance",    zh: "余额", phon: "/ˈbæləns/", emoji: "⚖️", sent: "You can check your balance at the ATM." },
    { id: "fee",        en: "fee",        zh: "手续费", phon: "/fiː/", emoji: "🧾", sent: "Is there a fee for international transfers?" },
    { id: "statement",  en: "statement",  zh: "账单/流水", phon: "/ˈsteɪtmənt/", emoji: "📊", sent: "I'd like a copy of my bank statement." },
    { id: "bill",       en: "bill",       zh: "纸币", phon: "/bɪl/", emoji: "💵", sent: "The ATM gives out twenty-dollar bills." },
    { id: "passport2",  en: "passport",   zh: "护照", phon: "/ˈpɑːspɔːt/", emoji: "🛂", sent: "May I see your passport, please?" },
    { id: "card",       en: "debit card", zh: "借记卡", phon: "/ˈdebɪt kɑːd/", emoji: "💳", sent: "Pay with your debit card or credit card." },
    { id: "fraud",      en: "fraud",      zh: "欺诈", phon: "/frɔːd/", emoji: "🚨", sent: "Someone used my card — I think it's fraud!" },
    { id: "freeze",     en: "freeze the card", zh: "冻结银行卡", phon: "/friːz ðə kɑːd/", emoji: "🧊", sent: "Please freeze my card right away!" },
    { id: "transfer",   en: "transfer",   zh: "转账", phon: "/ˈtrænsfɜː/", emoji: "🔁", sent: "I'd like to transfer money to my friend." },
    { id: "branch",     en: "branch",     zh: "分行", phon: "/brɑːntʃ/", emoji: "🏢", sent: "This branch opens at nine a.m." },
    { id: "atm",        en: "ATM",        zh: "自动取款机", phon: "/ˌeɪ tiː ˈem/", emoji: "🏧", sent: "You can withdraw cash at any ATM." },
    { id: "transaction", en: "transaction", zh: "交易记录", phon: "/trænˈzækʃn/", emoji: "📋", sent: "Check your recent transactions online." },
    { id: "daily",      en: "daily limit", zh: "每日限额", phon: "/ˈdeɪli ˈlɪmɪt/", emoji: "🚧", sent: "There's a five-hundred-dollar daily limit." },
    { id: "cash",       en: "cash",       zh: "现金", phon: "/kæʃ/", emoji: "💵", sent: "I'd like two hundred in cash." },
    { id: "receipt",    en: "receipt",    zh: "回执/收据", phon: "/rɪˈsiːt/", emoji: "🧾", sent: "Do you want a receipt for your deposit?" },
    { id: "id",         en: "ID",         zh: "身份证件", phon: "/ˌaɪ ˈdiː/", emoji: "🪪", sent: "You need two forms of ID to open an account." },
  ],
