// 银行场景头 + 词条
{
  id: "bank",
  name: "银行",
  nameEn: "Bank",
  emoji: "🏦",
  iconId: "bank",
  cover: "🏦💳💵",
  theme: "bank",
  accent: "#2f6b4f",
  accentSoft: "#e2f0e8",
  deco: "✨",
  deco2: "🪙",
  intro: "你需要处理各种银行业务。从开户到换汇，从取款到银行卡出问题——用英文搞定一切！",
  orderLabel: "🏦 业务进度",
  items: [
    { id: "account",    en: "account",    zh: "账户", phon: "/əˈkaʊnt/", emoji: "🧾", sent: "I'd like to open an account." },
    { id: "checking",   en: "checking account", zh: "活期账户", phon: "/ˈtʃekɪŋ əˈkaʊnt/", emoji: "💰", sent: "I need a checking account for daily use." },
    { id: "savings",    en: "savings account", zh: "储蓄账户", phon: "/ˈseɪvɪŋz əˈkaʊnt/", emoji: "🐖", sent: "Put your money in a savings account." },
    { id: "deposit",    en: "deposit",    zh: "存款", phon: "/dɪˈpɒzɪt/", emoji: "📥", sent: "I'd like to make a deposit." },
    { id: "withdraw",   en: "withdraw",   zh: "取款", phon: "/wɪðˈdrɔː/", emoji: "📤", sent: "I need to withdraw some cash." },
    { id: "exchange",   en: "exchange rate", zh: "汇率", phon: "/ɪksˈtʃeɪndʒ reɪt/", emoji: "💱", sent: "What's the exchange rate today?" },
    { id: "teller",     en: "teller",     zh: "柜员", phon: "/ˈtelə/", emoji: "🧑‍💼", sent: "Please wait for the next available teller." },
    { id: "pin",        en: "PIN",        zh: "密码", phon: "/pɪn/", emoji: "🔐", sent: "Enter your PIN on the keypad." },
    { id: "sign",       en: "signature",  zh: "签名", phon: "/ˈsɪɡnətʃə/", emoji: "✍️", sent: "Please sign on the dotted line." },
    { id: "balance",    en: "balance",    zh: "余额", phon: "/ˈbæləns/", emoji: "⚖️", sent: "You can check your balance at the ATM." },
    { id: "fee",        en: "fee",        zh: "手续费", phon: "/fiː/", emoji: "🧾", sent: "Is there a fee for international transfers?" },
    { id: "statement",  en: "statement",  zh: "账单/流水", phon: "/ˈsteɪtmənt/", emoji: "📊", sent: "I'd like a copy of my bank statement." },
    { id: "bill",       en: "bill",       zh: "纸币", phon: "/bɪl/", emoji: "💵", sent: "The ATM gives out twenty-dollar bills." },
    { id: "passport2",  en: "passport",   zh: "护照", phon: "/ˈpɑːspɔːt/", emoji: "🛂", sent: "May I see your passport, please?" },
    { id: "card",       en: "debit card", zh: "借记卡", phon: "/ˈdebɪt kɑːd/", emoji: "💳", sent: "Pay with your debit card or credit card." },
    { id: "fraud",      en: "fraud",      zh: "欺诈", phon: "/frɔːd/", emoji: "🚨", sent: "Someone used my card — I think it's fraud!" },
    { id: "freeze",     en: "freeze the card", zh: "冻结银行卡", phon: "/friːz ðə kɑːd/", emoji: "🧊", sent: "Please freeze my card right away!" },
    { id: "transfer",   en: "transfer",   zh: "转账", phon: "/ˈtrænsfɜː/", emoji: "🔁", sent: "I'd like to transfer money to my friend." },
    { id: "branch",     en: "branch",     zh: "分行", phon: "/brɑːntʃ/", emoji: "🏢", sent: "This branch opens at nine a.m." },
    { id: "atm",        en: "ATM",        zh: "自动取款机", phon: "/ˌeɪ tiː ˈem/", emoji: "🏧", sent: "You can withdraw cash at any ATM." },
    { id: "transaction", en: "transaction", zh: "交易记录", phon: "/trænˈzækʃn/", emoji: "📋", sent: "Check your recent transactions online." },
    { id: "daily",      en: "daily limit", zh: "每日限额", phon: "/ˈdeɪli ˈlɪmɪt/", emoji: "🚧", sent: "There's a five-hundred-dollar daily limit." },
    { id: "cash",       en: "cash",       zh: "现金", phon: "/kæʃ/", emoji: "💵", sent: "I'd like two hundred in cash." },
    { id: "receipt",    en: "receipt",    zh: "回执/收据", phon: "/rɪˈsiːt/", emoji: "🧾", sent: "Do you want a receipt for your deposit?" },
    { id: "id",         en: "ID",         zh: "身份证件", phon: "/ˌaɪ ˈdiː/", emoji: "🪪", sent: "You need two forms of ID to open an account." },
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 开户",
      titleEn: "Opening an Account",
      emoji: "🧾",
      desc: "刚到这个城市，需要一个银行账户。选账户类型、交证件、设密码、拿借记卡——全流程英文开户。",
      reward: { en: "account", zh: "你用英文开好了自己的银行账户！🏦" },
      steps: [
        {
          npcLines: [
            "Good morning! Welcome to First City Bank. What can I do for you today?",
            "Hi there! Welcome in. How may I help you?",
            "Good morning! You look like you have a mission — what can I do for you?",
          ],
          npcZh: "早上好！欢迎来到第一城市银行。今天有什么可以帮您？",
          task: "说明来意：开一个账户",
          options: [
            { text: "Hi! I'd like to open a checking account, please.", ok: true,  tip: "I'd like to open an account 开户标准句；checking account 活期账户" },
            { text: "I want bank. Give me bank account thing.",        ok: false, tip: "说 I'd like to open a checking account" },
            { text: "Account! Me! New! Now!",                          ok: false, tip: "礼貌完整：I'd like to open an account, please" },
          ],
          phrase: { en: "I'd like to open a(n) ___ account.", zh: "我想开一个……账户。", note: "checking 活期（日常消费）/ savings 储蓄（存钱生息）" },
        },
        {
          npcLines: [
            "Great choice! May I see your passport and a second form of ID?",
            "Perfect. I'll need your passport, plus one more ID — a student card works.",
            "Sure thing! Passport and one other form of ID, please.",
          ],
          npcZh: "好选择！请出示您的护照和第二种身份证件。",
          task: "递上护照，说明没带第二种证件",
          options: [
            { text: "Here's my passport. I'm afraid I don't have a second ID on me — is that a problem?", ok: true, tip: "Here's my passport 递证件 + I'm afraid... 委婉说明 + Is that a problem? 礼貌询问" },
            { text: "Passport here. No other paper. Deal with it.",   ok: false, tip: "委婉表达：I'm afraid I don't have a second ID on me" },
            { text: "Why two IDs? One ID enough in my country.",      ok: false, tip: "入乡随俗，先说明情况：Is that a problem?" },
          ],
          phrase: { en: "I'm afraid I don't have ___ on me.", zh: "恐怕我没带……在身上。", note: "on me = 随身携带；委婉承认没带某物" },
        },
        {
          npcLines: [
            "No problem at all — your passport will do for today, just bring the second one later. Now, would you also like a savings account?",
            "That's fine! Passport alone works for now. Say — want a savings account to go with it?",
            "Not an issue! We can start with the passport. Quick question: any interest in a savings account too?",
          ],
          npcZh: "完全没问题——今天护照就行，第二种证件之后补上。对了，您还需要一个储蓄账户吗？",
          task: "接受捆绑建议，同时问清有没有费用",
          options: [
            { text: "Sure, that sounds useful. Are there any monthly fees I should know about?", ok: true,  tip: "Are there any fees? 问费用——开户必问" },
            { text: "Yes yes whatever, next question fast.",         ok: false, tip: "接受前问清条件：Are there any monthly fees?" },
            { text: "Fees? Nobody mentioned fees! This is a trap!",  ok: false, tip: "冷静核实：Are there any monthly fees I should know about?" },
          ],
          phrase: { en: "Are there any fees I should know about?", zh: "有什么我该知道的手续费吗？", note: "礼貌挖坑式提问：让对方主动交代所有费用" },
        },
        {
          npcLines: [
            "Good news — no monthly fee for students! Now, please choose a four-digit PIN for your debit card.",
            "You're in luck — the student account is free! Time to pick a four-digit PIN.",
            "No fees for you! Last step before the card: choose a four-digit PIN.",
          ],
          npcZh: "好消息——学生账户免月费！现在请为您的借记卡设置一个四位密码。",
          task: "在密码键盘上设置密码",
          options: [
            { text: "Got it — a four-digit PIN. Should I just type it in on the keypad?", ok: true,  tip: "type it in on the keypad 在键盘上输入 + PIN = Personal Identification Number" },
            { text: "Here is my password: one two three four.",       ok: false, tip: "密码不能口头说出：在键盘上静默输入" },
            { text: "I tell you number, you type it for me.",        ok: false, tip: "密码必须本人输入：on the keypad" },
          ],
          phrase: { en: "a four-digit PIN", zh: "四位密码", note: "digit = 数字；银行场景高频：四位数密码" },
        },
        {
          npcLines: [
            "Perfect, your card is ready! It'll arrive by mail in about a week. Would you like online banking too?",
            "All set! The card comes in the mail within seven days. How about online banking — want me to set that up?",
            "Done! Expect the card in your mailbox in a week. Shall I activate online banking for you as well?",
          ],
          npcZh: "完美，卡片办好！一周左右邮寄到您家。需要开通网上银行吗？",
          task: "同意开通，并询问如何查余额",
          options: [
            { text: "Yes, please! And how can I check my balance — is there an app for that?", ok: true, tip: "check my balance 查余额 + Is there an app? 问工具" },
            { text: "Online banking yes. Money see where? Tell me.",  ok: false, tip: "问余额：How can I check my balance?" },
            { text: "No app. I will come to bank every day to ask.", ok: false, tip: "更高效：Is there an app for that?" },
          ],
          phrase: { en: "How can I check my balance?", zh: "我怎么查余额？", note: "balance = 账户余额；ATM/柜员/APP 都能查" },
        },
        {
          npcLines: [
            "Absolutely — everything's in the app: balance, statements, transfers. Here's your welcome packet. Welcome to First City Bank!",
            "Of course! The app does it all — balances, transfers, even deposits. Here's your paperwork. Welcome aboard!",
            "You bet! Balance, transfer, pay bills — all in the app. Welcome to the family!",
          ],
          npcZh: "当然——APP 里什么都有：余额、流水、转账。这是您的欢迎资料包。欢迎加入第一城市银行！",
          task: "感谢柜员，完成开户",
          options: [
            { text: "That's very convenient! Thank you so much for your help — have a great day!", ok: true, tip: "That's very convenient + Thank you so much 圆满收尾" },
            { text: "OK bye.",                                       ok: false, tip: "完整致谢：Thank you so much for your help!" },
            { text: "Finally! That took forever, goodbye.",           ok: false, tip: "礼貌收尾：Have a great day!" },
          ],
          phrase: { en: "Thank you for your help!", zh: "谢谢你的帮助！", note: "业务办完的万能收尾句" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 换汇与取现",
      titleEn: "Exchange & Withdrawal",
      emoji: "💱",
      desc: "要出国旅行了！换外币、问汇率、ATM 取现、要小面额纸币——和钱打交道的英语。",
      reward: { en: "cash", zh: "你搞定了换汇取现全套英语！💱" },
      steps: [
        {
          npcLines: [
            "Good afternoon! Number 42 at window three, please. How can I help you?",
            "Hi there, window three — what can I do for you today?",
            "Afternoon! You're up. What do you need?",
          ],
          npcZh: "下午好！42 号请到 3 号窗口。有什么可以帮您？",
          task: "说明要换欧元，询问今天的汇率",
          options: [
            { text: "Hi! I'd like to exchange some dollars for euros. What's the exchange rate today?", ok: true, tip: "exchange A for B 换汇 + exchange rate 汇率" },
            { text: "I need Europe money. Give me good rate.",        ok: false, tip: "说 I'd like to exchange dollars for euros" },
            { text: "Change money now. How much profit for you?",     ok: false, tip: "问汇率：What's the exchange rate today?" },
          ],
          phrase: { en: "I'd like to exchange ___ for ___.", zh: "我想把……换成……。", note: "换汇万能句；也可说 Do you exchange...?" },
        },
        {
          npcLines: [
            "Today's rate is one dollar to ninety-two euro cents. How much would you like to exchange?",
            "The rate right now is zero point nine two euros per dollar. How much are we talking?",
            "Ninety-two euro cents for one dollar — not bad, right? How much do you need?",
          ],
          npcZh: "今天汇率是 1 美元换 0.92 欧元。您想换多少？",
          task: "表达换 500 美元",
          options: [
            { text: "Five hundred dollars, please. Could I get some of that in smaller bills?", ok: true,  tip: "smaller bills 小面额纸币——出行实用需求" },
            { text: "Five hundred. All big money only.",             ok: false, tip: "出行更需要零钱：Could I get some in smaller bills?" },
            { text: "Give maximum money minimum paper.",             ok: false, tip: "清楚表达：Five hundred dollars, please" },
          ],
          phrase: { en: "Could I get it in smaller bills?", zh: "能给我小面额的纸币吗？", note: "bill = 纸币；小面额 = smaller/smaller bills" },
        },
        {
          npcLines: [
            "Sure thing — I'll do four sixty in euros. There's a three-dollar service fee, is that okay?",
            "No problem. That comes to four hundred sixty euros. Just a heads-up: three-dollar service fee.",
            "You got it — four sixty in euros, minus the usual three-dollar fee. Still good?",
          ],
          npcZh: "没问题——您可以换 460 欧元。有 3 美元手续费，可以吗？",
          task: "确认手续费并完成交易",
          options: [
            { text: "That's fine, thank you. Could I also get a receipt for the exchange?", ok: true,  tip: "That's fine 确认 + receipt 回执——报销/留证要收好" },
            { text: "Fee?! Surprise fee is illegal fee!",            ok: false, tip: "手续费已明示，确认即可：That's fine" },
            { text: "No receipt. Receipts are for weak people.",     ok: false, tip: "换汇回执务必保留：Could I also get a receipt?" },
          ],
          phrase: { en: "Could I get a receipt?", zh: "能给我一张回执吗？", note: "银行业务万能句——存款、换汇、转账都该拿回执" },
        },
        {
          npcLines: [
            "Here's your receipt and your euros. Anything else for you today?",
            "Receipt's printing... and there's your euros! Anything else I can help with?",
            "All done — receipt and four sixty in euros. What else can I do for you?",
          ],
          npcZh: "这是您的回执和欧元。今天还有其他业务吗？",
          task: "询问 ATM 取现每日限额",
          options: [
            { text: "Yes — what's the daily limit for ATM withdrawals? I'm traveling and might need cash.", ok: true, tip: "daily limit 每日限额 + ATM withdrawals 取款机取现" },
            { text: "Machine money how much maximum?",              ok: false, tip: "标准问法：What's the daily limit for ATM withdrawals?" },
            { text: "ATM infinite money yes? I hope?",               ok: false, tip: "ATM 有每日限额：What's the daily limit?" },
          ],
          phrase: { en: "What's the daily limit?", zh: "每日限额是多少？", note: "取现/转账都有 daily limit；旅行前务必问清" },
        },
        {
          npcLines: [
            "Your account allows five hundred a day. Oh — and a travel tip: tell us your travel dates, so we don't freeze your card abroad!",
            "Five hundred daily. Pro tip: file a travel notice before your trip, or security might freeze your card overseas!",
            "You can take out five hundred per day. Heads-up: set a travel notice, or the fraud system might block you in Europe!",
          ],
          npcZh: "您的账户每天可取 500。对了——旅行提示：告诉我们您的出行日期，免得您的卡在国外被冻结！",
          task: "感谢提醒，登记出行日期",
          options: [
            { text: "Oh, good to know! I'm traveling to Europe next week — June 10th to 20th. Could you add a travel notice?", ok: true, tip: "travel notice 出行登记——防卡被风控冻结" },
            { text: "Freeze my card? Do your worst, machine!",      ok: false, tip: "海外用卡前登记：Could you add a travel notice?" },
            { text: "I love surprises. No notice needed.",          ok: false, tip: "被冻结很麻烦：主动登记出行日期" },
          ],
          phrase: { en: "Could you add a travel notice?", zh: "能帮我登记出行通知吗？", note: "出国用卡前必做；否则银行风控可能冻结你的卡" },
        },
        {
          npcLines: [
            "Done! Travel notice added for June 10 to 20. Have a wonderful trip — and enjoy those euros!",
            "All set, June 10th through 20th on file. Safe travels, and enjoy Europe!",
            "Notice is in! You're covered for the whole trip. Bon voyage!",
          ],
          npcZh: "搞定！6 月 10 日到 20 日的出行通知已登记。旅途愉快——好好享受那些欧元吧！",
          task: "告别柜员",
          options: [
            { text: "You've been super helpful. Thanks a lot — have a great day!", ok: true,  tip: "You've been super helpful 夸赞帮助 + 道别" },
            { text: "Bye bank person.",                             ok: false, tip: "热情收尾：You've been super helpful!" },
            { text: "OK. Leaving now. Fast.",                        ok: false, tip: "完整道别：Thanks a lot — have a great day!" },
          ],
          phrase: { en: "You've been super helpful.", zh: "你帮了大忙。", note: "对服务人员的真诚夸赞，道别前的好句子" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 银行卡出问题了",
      titleEn: "Card Trouble",
      emoji: "🚨",
      desc: "刷卡被拒、卡被吞、发现可疑交易？银行卡出状况时，冷静+准确描述问题的应急英语。",
      reward: { en: "freeze the card", zh: "你解锁了银行卡应急英语，卡出问题不慌！🚨➡️😌" },
      steps: [
        {
          npcLines: [
            "Bank hotline, this is Sarah speaking. How can I help you?",
            "Thanks for calling First City Bank — Sarah here. What seems to be the problem?",
            "Good evening, this is Sarah from the bank's help line. What can I do for you?",
          ],
          npcZh: "银行热线，我是 Sarah。有什么可以帮您？",
          task: "描述问题：网上支付时刷卡被拒",
          options: [
            { text: "Hi, my debit card was declined when I tried to pay online. It worked fine yesterday.", ok: true, tip: "My card was declined 卡被拒了 + It worked fine yesterday 提供关键信息" },
            { text: "Card broken! Website mean to me!",            ok: false, tip: "准确描述：My card was declined when I tried to pay online" },
            { text: "Your bank hates me. Card no work.",           ok: false, tip: "陈述事实不指责：My card was declined" },
          ],
          phrase: { en: "My card was declined.", zh: "我的卡被拒了。", note: "declined = 被拒绝（银行/商家用语），不是 broken" },
        },
        {
          npcLines: [
            "I'm sorry to hear that! Let me check your account... Hmm, it says here the card was blocked by our security system.",
            "Oh no! Give me a second to pull up your account... Interesting — security flagged and blocked your card.",
            "Sorry about that! Checking now... Ah, I see it: our fraud system blocked the card this morning.",
          ],
          npcZh: "很抱歉！让我查一下您的账户……嗯，这里显示您的卡被我们的安全系统拦截了。",
          task: "想知道原因，询问如何解冻",
          options: [
            { text: "I see. Why was it blocked, and how can I unblock it?", ok: true,  tip: "unblock 解冻 + 直接问原因和解决方案" },
            { text: "Unblock now please. I am angry customer.",     ok: false, tip: "先了解原因：Why was it blocked, and how can I unblock it?" },
            { text: "Security? I am not criminal! Apologize!",      ok: false, tip: "风控拦截是保护机制：冷静问 Why was it blocked?" },
          ],
          phrase: { en: "Why was it blocked?", zh: "为什么被拦截了？", note: "blocked = 被冻结/拦截；问清原因再解决" },
        },
        {
          npcLines: [
            "There was a suspicious charge from another country — ninety-nine dollars from a store you've never used. Did you make that purchase?",
            "We caught a fishy transaction: ninety-nine dollars, overseas merchant, first-time store. Was that you?",
            "Here's the issue — a ninety-nine-dollar charge from abroad at a store you've never shopped at. Sound familiar?",
          ],
          npcZh: "有一笔来自其他国家的可疑扣款——一家您从没用过的商店扣了 99 美元。这笔消费是您本人操作吗？",
          task: "否认消费，确认这是欺诈",
          options: [
            { text: "No, that wasn't me! I've never heard of that store. I think that's fraud — what should I do?", ok: true, tip: "That wasn't me 明确否认 + fraud 欺诈 + What should I do? 求方案" },
            { text: "Ninety-nine dollars? Maybe? I buy many things.", ok: false, tip: "不确定时核实：That wasn't me — I've never heard of that store" },
            { text: "Yes was me! Wait... no... maybe... yes?",       ok: false, tip: "欺诈处理最忌含糊：No, that wasn't me!" },
          ],
          phrase: { en: "That wasn't me — I think it's fraud.", zh: "那不是我——我觉得是欺诈。", note: "fraud = 欺诈；盗刷处理第一步：明确否认" },
        },
        {
          npcLines: [
            "Thank you for confirming. I'll freeze the card right away so no more charges can go through. Then we'll issue you a new card.",
            "Got it — freezing your card this second! Nothing else can touch your money. New card's on the way.",
            "Perfect. Card frozen as we speak. Let's get a replacement card sent out to you today.",
          ],
          npcZh: "感谢确认。我马上冻结该卡，防止更多扣款。然后给您补发一张新卡。",
          task: "询问被盗款项能否追回",
          options: [
            { text: "Thank you. Will I get the ninety-nine dollars back? It was fraud, after all.", ok: true, tip: "get the money back 追回款项——盗刷维权关键问题" },
            { text: "New card fast. Money also new. Refund all now.", ok: false, tip: "准确提问：Will I get the ninety-nine dollars back?" },
            { text: "Don't care about money, just make card work.",  ok: false, tip: "盗刷款项可争议退款：Will I get it back?" },
          ],
          phrase: { en: "Will I get my money back?", zh: "我的钱能退回来吗？", note: "盗刷维权核心句；银行有争议处理流程（dispute）" },
        },
        {
          npcLines: [
            "Yes — we'll open a dispute for that charge, and most fraud cases are refunded within ten business days.",
            "You'll get it back! We file a dispute today; refunds usually land within ten business days.",
            "Absolutely. I'm opening the dispute now — expect the refund in about ten business days.",
          ],
          npcZh: "会的——我们会为那笔扣款发起争议处理，多数欺诈案件在 10 个工作日内退款。",
          task: "确认新卡邮寄时间",
          options: [
            { text: "That's a relief. When will the new card arrive, and how do I activate it?", ok: true,  tip: "That's a relief 松了口气 + activate the card 激活新卡" },
            { text: "Ten days too slow! Money now now now!",         ok: false, tip: "流程已有明确时限：When will the new card arrive?" },
            { text: "Activate? Cards activate themselves, obviously.", ok: false, tip: "新卡需激活：How do I activate it?" },
          ],
          phrase: { en: "How do I activate it?", zh: "怎么激活它？", note: "新卡到手先激活（activate）：APP 或电话都能办" },
        },
        {
          npcLines: [
            "The card arrives in five to seven days — activate it right in our app. Is there anything else I can help you with today?",
            "Five to seven business days for the card, and activation takes one tap in the app. Anything else for you?",
            "Expect it within a week — app activation, super easy. Any other questions before you go?",
          ],
          npcZh: "新卡 5-7 天寄到——直接在 APP 里激活。今天还有其他需要帮助的吗？",
          task: "感谢客服，结束通话",
          options: [
            { text: "You've been a huge help. Thanks for handling this so quickly — goodbye!", ok: true, tip: "You've been a huge help + 匆匆收尾，电话道别用 goodbye" },
            { text: "Bye Sarah! You get promotion, I decide this.", ok: false, tip: "真诚致谢即可：You've been a huge help!" },
            { text: "Click. Done talking.",                          ok: false, tip: "电话礼貌收尾：Thanks for handling this so quickly — goodbye!" },
          ],
          phrase: { en: "Thanks for handling this so quickly.", zh: "谢谢你这么快就处理好了。", note: "对客服/柜员的高频致谢；handle = 处理" },
        },
      ],
    },
  ],
},
