// 理发店场景头 + 词条
{
  id: "barber",
  name: "理发店",
  nameEn: "Barbershop",
  emoji: "💈",
  iconId: "barber",
  cover: "💈✂️🪞",
  theme: "barber",
  accent: "#8a4fbd",
  accentSoft: "#f0e6fa",
  deco: "✨",
  deco2: "💫",
  intro: "头发长了该剪了！描述想要的发型、沟通长度、看效果、办卡——用英文搞定头等大事。",
  orderLabel: "💇 美发进度",
  items: [
    { id: "haircut",    en: "haircut",        zh: "理发", phon: "/ˈheəkʌt/", emoji: "✂️", sent: "I need a haircut." },
    { id: "trim",       en: "just a trim",    zh: "只修一下", phon: "/dʒʌst ə trɪm/", emoji: "✂️", sent: "Just a trim, please — half an inch off." },
    { id: "bangs",      en: "bangs",          zh: "刘海", phon: "/bæŋz/", emoji: "💇", sent: "Could you cut my bangs a little shorter?" },
    { id: "fade",       en: "fade",           zh: "渐变推剪", phon: "/feɪd/", emoji: "🪒", sent: "I'll take a fade on the sides." },
    { id: "part",       en: "side part",      zh: "侧分", phon: "/saɪd pɑːt/", emoji: "↔️", sent: "I usually wear a side part." },
    { id: "layers",     en: "layers",         zh: "打层次", phon: "/ˈleɪəz/", emoji: "📐", sent: "Could you add some layers?" },
    { id: "shampoo",    en: "shampoo",        zh: "洗发", phon: "/ʃæmˈpuː/", emoji: "🧴", sent: "Would you like a shampoo first?" },
    { id: "stylist",    en: "stylist",        zh: "发型师", phon: "/ˈstaɪlɪst/", emoji: "💇‍♀️", sent: "My stylist knows exactly what I like." },
    { id: "mirror",     en: "the back",       zh: "后脑勺（发型）", phon: "/ðə bæk/", emoji: "🪞", sent: "Let me check the back in the mirror." },
    { id: "thinner",    en: "thin it out",    zh: "打薄", phon: "/θɪn ɪt aʊt/", emoji: "🌱", sent: "My hair is thick — could you thin it out?" },
    { id: "color",      en: "dye my hair",    zh: "染发", phon: "/daɪ maɪ heə/", emoji: "🎨", sent: "I'm thinking about dyeing my hair brown." },
    { id: "highlight",  en: "highlights",     zh: "挑染", phon: "/ˈhaɪlaɪts/", emoji: "✨", sent: "Could I get some highlights?" },
    { id: "roots",      en: "roots",          zh: "发根", phon: "/ruːts/", emoji: "🌱", sent: "My roots are showing — time to touch up." },
    { id: "bleach",     en: "bleach",         zh: "漂发", phon: "/bliːtʃ/", emoji: "🧪", sent: "Bleaching can damage your hair." },
    { id: "treatment",  en: "deep treatment", zh: "深度护理", phon: "/diːp ˈtriːtmənt/", emoji: "🧖", sent: "Your hair is dry — try a deep treatment." },
    { id: "split",      en: "split ends",     zh: "分叉", phon: "/splɪt endz/", emoji: "🪓", sent: "I have a lot of split ends." },
    { id: "curly",      en: "curly hair",     zh: "卷发", phon: "/ˈkɜːli heə/", emoji: "🌀", sent: "How should I take care of curly hair?" },
    { id: "frizzy",     en: "frizzy",         zh: "毛躁的", phon: "/ˈfrɪzi/", emoji: "☁️", sent: "My hair gets frizzy in humid weather." },
    { id: "blowdry",    en: "blow-dry",       zh: "吹干造型", phon: "/ˈbləʊ draɪ/", emoji: "💨", sent: "Could you blow-dry it straight?" },
    { id: "product",    en: "styling product", zh: "造型产品", phon: "/ˈstaɪlɪŋ ˈprɒdʌkt/", emoji: "🧴", sent: "Which styling product do you recommend?" },
    { id: "member",     en: "membership card", zh: "会员卡", phon: "/ˈmembəʃɪp kɑːd/", emoji: "💳", sent: "With the membership card, haircuts are twenty percent off." },
    { id: "appointment2", en: "book an appointment", zh: "预约", phon: "/bʊk ən əˈpɔɪntmənt/", emoji: "📅", sent: "I'd like to book an appointment for Saturday." },
    { id: "walkin",     en: "walk-in",        zh: "无预约直接来", phon: "/ˈwɔːk ɪn/", emoji: "🚶", sent: "Do you take walk-ins, or do I need an appointment?" },
    { id: "growout",    en: "grow out",       zh: "留长", phon: "/ɡrəʊ aʊt/", emoji: "📏", sent: "I'm growing out my hair, so don't cut too much." },
  ],
