// 理发店场景头 + 词条
{
  id: "barber",
  name: "理发店",
  nameEn: "Barbershop",
  emoji: "💈",
  iconId: "barber",
  cover: "💈✂️🪞",
  theme: "barber",
  accent: "#8a4fbd",
  accentSoft: "#f0e6fa",
  deco: "✨",
  deco2: "💫",
  intro: "头发长了该剪了！描述想要的发型、沟通长度、看效果、办卡——用英文搞定头等大事。",
  orderLabel: "💇 美发进度",
  items: [
    { id: "haircut",    en: "haircut",        zh: "理发", phon: "/ˈheəkʌt/", emoji: "✂️", sent: "I need a haircut." },
    { id: "trim",       en: "just a trim",    zh: "只修一下", phon: "/dʒʌst ə trɪm/", emoji: "✂️", sent: "Just a trim, please — half an inch off." },
    { id: "bangs",      en: "bangs",          zh: "刘海", phon: "/bæŋz/", emoji: "💇", sent: "Could you cut my bangs a little shorter?" },
    { id: "fade",       en: "fade",           zh: "渐变推剪", phon: "/feɪd/", emoji: "🪒", sent: "I'll take a fade on the sides." },
    { id: "part",       en: "side part",      zh: "侧分", phon: "/saɪd pɑːt/", emoji: "↔️", sent: "I usually wear a side part." },
    { id: "layers",     en: "layers",         zh: "打层次", phon: "/ˈleɪəz/", emoji: "📐", sent: "Could you add some layers?" },
    { id: "shampoo",    en: "shampoo",        zh: "洗发", phon: "/ʃæmˈpuː/", emoji: "🧴", sent: "Would you like a shampoo first?" },
    { id: "stylist",    en: "stylist",        zh: "发型师", phon: "/ˈstaɪlɪst/", emoji: "💇‍♀️", sent: "My stylist knows exactly what I like." },
    { id: "mirror",     en: "the back",       zh: "后脑勺（发型）", phon: "/ðə bæk/", emoji: "🪞", sent: "Let me check the back in the mirror." },
    { id: "thinner",    en: "thin it out",    zh: "打薄", phon: "/θɪn ɪt aʊt/", emoji: "🌱", sent: "My hair is thick — could you thin it out?" },
    { id: "color",      en: "dye my hair",    zh: "染发", phon: "/daɪ maɪ heə/", emoji: "🎨", sent: "I'm thinking about dyeing my hair brown." },
    { id: "highlight",  en: "highlights",     zh: "挑染", phon: "/ˈhaɪlaɪts/", emoji: "✨", sent: "Could I get some highlights?" },
    { id: "roots",      en: "roots",          zh: "发根", phon: "/ruːts/", emoji: "🌱", sent: "My roots are showing — time to touch up." },
    { id: "bleach",     en: "bleach",         zh: "漂发", phon: "/bliːtʃ/", emoji: "🧪", sent: "Bleaching can damage your hair." },
    { id: "treatment",  en: "deep treatment", zh: "深度护理", phon: "/diːp ˈtriːtmənt/", emoji: "🧖", sent: "Your hair is dry — try a deep treatment." },
    { id: "split",      en: "split ends",     zh: "分叉", phon: "/splɪt endz/", emoji: "🪓", sent: "I have a lot of split ends." },
    { id: "curly",      en: "curly hair",     zh: "卷发", phon: "/ˈkɜːli heə/", emoji: "🌀", sent: "How should I take care of curly hair?" },
    { id: "frizzy",     en: "frizzy",         zh: "毛躁的", phon: "/ˈfrɪzi/", emoji: "☁️", sent: "My hair gets frizzy in humid weather." },
    { id: "blowdry",    en: "blow-dry",       zh: "吹干造型", phon: "/ˈbləʊ draɪ/", emoji: "💨", sent: "Could you blow-dry it straight?" },
    { id: "product",    en: "styling product", zh: "造型产品", phon: "/ˈstaɪlɪŋ ˈprɒdʌkt/", emoji: "🧴", sent: "Which styling product do you recommend?" },
    { id: "member",     en: "membership card", zh: "会员卡", phon: "/ˈmembəʃɪp kɑːd/", emoji: "💳", sent: "With the membership card, haircuts are twenty percent off." },
    { id: "appointment2", en: "book an appointment", zh: "预约", phon: "/bʊk ən əˈpɔɪntmənt/", emoji: "📅", sent: "I'd like to book an appointment for Saturday." },
    { id: "walkin",     en: "walk-in",        zh: "无预约直接来", phon: "/ˈwɔːk ɪn/", emoji: "🚶", sent: "Do you take walk-ins, or do I need an appointment?" },
    { id: "growout",    en: "grow out",       zh: "留长", phon: "/ɡrəʊ aʊt/", emoji: "📏", sent: "I'm growing out my hair, so don't cut too much." },
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 剪发沟通",
      titleEn: "Getting a Haircut",
      emoji: "✂️",
      desc: "走进理发店，说清楚自己要什么发型——长度、层次、刘海、后脑勺，理发沟通零翻车。",
      reward: { en: "haircut", zh: "你用英文剪出了满意的发型！✂️" },
      steps: [
        {
          npcLines: [
            "Hey! Welcome in — take a seat. What are we doing today?",
            "Hi there! Chair's all yours. What can I do for you?",
            "Hello hello! Ready for a fresh look? What are you thinking?",
          ],
          npcZh: "嘿！欢迎光临——请坐。今天剪什么样式？",
          task: "说明想剪头发，大致修短",
          options: [
            { text: "Hi! I'd like a haircut — just a trim, about half an inch off the sides and the top.", ok: true, tip: "just a trim 只修剪 + half an inch off 剪掉半英寸（约1.3cm）" },
            { text: "Cut hair. Small cut. Not bald.",     ok: false, tip: "精确描述：Just a trim, about half an inch off" },
            { text: "Do the normal thing you do to heads.", ok: false, tip: "没有『标准头』：说明长度 half an inch off" },
          ],
          phrase: { en: "Just a trim, please.", zh: "只修一下就好。", note: "trim = 小修剪；怕剪太短的保命句" },
        },
        {
          npcLines: [
            "Got it, half an inch. What about the top — same length, or a little shorter?",
            "Half an inch on the sides. And up top — keep the length or take some off?",
            "Sure! Sides, half inch. Top — what are we thinking, same or shorter?",
          ],
          npcZh: "明白，半英寸。头顶呢——同样长度，还是稍微剪短点？",
          task: "描述头顶处理方式",
          options: [
            { text: "Keep the top a bit longer, please. I usually wear a side part.", ok: true,  tip: "side part 侧分发型 + keep it longer 保留长度" },
            { text: "Top same like sides. All one army style.", ok: false, tip: "说清造型：Keep the top longer — I wear a side part" },
            { text: "Top is top, do whatever tops do.",   ok: false, tip: "发型师需要明确指令：Keep it longer, I wear a side part" },
          ],
          phrase: { en: "I usually wear a side part.", zh: "我平时梳侧分。", note: "wear = 留（发型）；side part 侧分 / middle part 中分" },
        },
        {
          npcLines: [
            "Nice, classic look. Would you like a shampoo first? It's included.",
            "A side part — good taste! Shampoo before we start? On the house!",
            "Love it. Quick shampoo first? It comes with the haircut.",
          ],
          npcZh: "好看，经典造型。先洗个头吗？这是包含在内的。",
          task: "接受洗头服务",
          options: [
            { text: "Sure, that sounds nice. Thank you!", ok: true,  tip: "接受服务的礼貌回应 + on the house = 免费" },
            { text: "No wash. Dirty hair is strong hair.", ok: false, tip: "先洗头更卫生好剪：Sure, thank you!" },
            { text: "Water expensive? I pay extra?",      ok: false, tip: "已说明 included（包含）：Sure, that sounds nice!" },
          ],
          phrase: { en: "It's on the house.", zh: "这是免费的（店里请客）。", note: "店家免费赠送的说法；house = 店家" },
        },
        {
          npcLines: [
            "Alright, I'm going in with the scissors! How do the sides look so far?",
            "Here we go — snip snip! Check out the sides — how are we doing?",
            "Scissors time! Take a look at the sides. Good so far?",
          ],
          npcZh: "好，我要动剪刀了！两侧目前看着怎么样？",
          task: "中途查看效果，提出小调整",
          options: [
            { text: "Looking good! Could you take a little more off around the ears, though?", ok: true, tip: "Looking good 肯定 + take a little more off 剪掉一点（around the ears 耳周）" },
            { text: "Perfect. Change nothing. Genius work.",  ok: false, tip: "有需求及时提：A little more off around the ears" },
            { text: "Too late for opinion, I wait for end.",  ok: false, tip: "中途沟通好过事后后悔：Could you take a little more off?" },
          ],
          phrase: { en: "Could you take a little more off ___?", zh: "能把……再剪掉一点吗？", note: "中途调整万能句：around the ears / in the back / on the top" },
        },
        {
          npcLines: [
            "You got it. Okay — I'm done! Take a look in the mirror. How's the back?",
            "Done and done! Mirror check — how does the back look to you?",
            "All finished! Have a look — is the back okay?",
          ],
          npcZh: "没问题。好——剪完了！照照镜子，后脑勺怎么样？",
          task: "检查后脑勺，确认满意",
          options: [
            { text: "The back looks great — nice and clean. I'm happy with it!", ok: true,  tip: "the back 后脑勺（发型用语）+ nice and clean 干净利落" },
            { text: "Cannot see back. Back is mystery forever.",  ok: false, tip: "发型师会拿镜子帮你照后脑勺：The back looks great!" },
            { text: "Back OK. Front bad. All bad. Start over.",   ok: false, tip: "整体满意就明确说：I'm happy with it!" },
          ],
          phrase: { en: "How's the back?", zh: "后脑勺怎么样？", note: "理发必查项；镜子 + 手持镜看背面" },
        },
        {
          npcLines: [
            "Glad you like it! Any styling product today? This pomade works great for a side part.",
            "Awesome! Before you go — want some pomade? Perfect for holding that side part.",
            "Excellent! One last thing: a bit of pomade keeps the part in place all day. Interested?",
          ],
          npcZh: "您喜欢就好！今天要来点造型产品吗？这款发蜡对侧分造型特别好用。",
          task: "礼貌拒绝推销，只付剪发钱",
          options: [
            { text: "Not today, thanks — maybe next time. How much for the haircut?", ok: true,  tip: "Not today, thanks 婉拒推销 + 问价格自然衔接结账" },
            { text: "No pomade ever. Pomade is lies.",       ok: false, tip: "婉拒但留余地：Not today, thanks — maybe next time" },
            { text: "You already ask me things too many times.", ok: false, tip: "礼貌拒绝 + 转移话题：How much for the haircut?" },
          ],
          phrase: { en: "Not today, thanks.", zh: "今天就不必了，谢谢。", note: "婉拒推销万能句——礼貌、明确、留余地" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 染发与护理",
      titleEn: "Color & Treatment",
      emoji: "🎨",
      desc: "想换发色！挑染还是全染？漂不漂？发质干枯怎么办？美发进阶英语一次学会。",
      reward: { en: "dye my hair", zh: "你解锁了染发护理英语，换发色不踩坑！🎨" },
      steps: [
        {
          npcLines: [
            "Welcome back! Ooh, are we doing something adventurous today?",
            "Back again! You have that look — the 'I want a change' look. Am I right?",
            "Hey, welcome back! Something tells me you're ready for something new!",
          ],
          npcZh: "欢迎回来！哦，今天要来点大胆的尝试吗？",
          task: "说明想染发，但还没定颜色",
          options: [
            { text: "Yes! I'm thinking about dyeing my hair, but I'm not sure about the color. What do you recommend?", ok: true, tip: "dye my hair 染发 + What do you recommend? 让专业的人给建议" },
            { text: "Color! Hair! New! Surprise me completely!",  ok: false, tip: "先沟通方向再动手：I'm thinking about dyeing my hair" },
            { text: "Dye everything rainbow colors.",            ok: false, tip: "大改动前先咨询：What do you recommend?" },
          ],
          phrase: { en: "I'm thinking about dyeing my hair.", zh: "我在考虑染头发。", note: "dye = 染；进行时表\"考虑中\"，留商量空间" },
        },
        {
          npcLines: [
            "With your skin tone, a warm brown would look amazing. Full color, or just some highlights?",
            "Ooh, warm brown would suit you perfectly! Question is — all over, or highlights?",
            "I'd say warm brown for you! Now, full dye or just a few highlights?",
          ],
          npcZh: "以您的肤色，暖棕色会非常好看。全染，还是只做挑染？",
          task: "询问两者区别后再决定",
          options: [
            { text: "What's the difference in maintenance? I've never colored my hair before.", ok: true, tip: "maintenance 保养/维护成本 + never done it before 让对方解释基础概念" },
            { text: "Which one is less money? Money decides all.", ok: false, tip: "问维护成本更专业：What's the difference in maintenance?" },
            { text: "Highlight like Instagram. Do Instagram.",  ok: false, tip: "说清自身情况：I've never colored my hair before" },
          ],
          phrase: { en: "What's the difference?", zh: "两者有什么区别？", note: "二选一纠结时的万能提问" },
        },
        {
          npcLines: [
            "Highlights grow out more naturally — you only need touch-ups every three months. Full color shows roots in four weeks!",
            "Highlights are low-maintenance — roots barely show. Full color? You'll see roots in a month!",
            "Highlights are easier to keep up — no obvious roots. Full dye needs touch-ups every few weeks!",
          ],
          npcZh: "挑染长出来更自然——三个月补一次就行。全染的话，四个星期就见发根了！",
          task: "理解后选择挑染，并提出加护理",
          options: [
            { text: "Highlights it is! My hair is a bit dry though — could I add a deep treatment?", ok: true,  tip: "My hair is dry 头发干 + deep treatment 深度护理" },
            { text: "Roots are natural, roots are beautiful. No treatment, roots only.", ok: false, tip: "发干可加护理：Could I add a deep treatment?" },
            { text: "Four weeks?! Cancel all plans forever!",  ok: false, tip: "选挑染+护理：Highlights it is! Could I add a deep treatment?" },
          ],
          phrase: { en: "My hair is a bit dry.", zh: "我头发有点干。", note: "描述发质基础句：dry 干 / oily 油 / frizzy 毛躁" },
        },
        {
          npcLines: [
            "Smart choice — treatment first, then color. Speaking of which: any chance you'd want to go lighter? That needs bleach.",
            "Good call! We'll treat, then highlight. Say — want to go lighter than your natural color? That means bleach.",
            "Treatment and highlights, perfect combo! Quick question — lighter than natural? That requires bleaching.",
          ],
          npcZh: "聪明——先护理再上色。对了，您想染得更浅吗？那需要漂发。",
          task: "担心伤发，询问漂发伤害",
          options: [
            { text: "Hmm, doesn't bleach damage your hair? I'd rather keep it healthy.", ok: true,  tip: "bleach 漂发 + damage 伤害 + would rather 更愿意（健康优先）" },
            { text: "Bleach? Like cleaning bleach? On head?!",  ok: false, tip: "漂发是常规美发项目：Doesn't bleach damage your hair?" },
            { text: "Damage whatever, beauty is pain.",         ok: false, tip: "顾虑正当且该表达：I'd rather keep it healthy" },
          ],
          phrase: { en: "Doesn't ___ damage your hair?", zh: "……不会伤头发吗？", note: "提出顾虑的标准句式；发型师会据此调整方案" },
        },
        {
          npcLines: [
            "Totally — bleach is rough on hair. We'll stay close to your natural shade, just a touch lighter. No bleach needed!",
            "You're right to ask! Let's skip the bleach — a shade close to natural, slightly brighter. Healthy and pretty!",
            "Smart customer! No bleach today — just lift it a little with gentle color. Your hair will thank you!",
          ],
          npcZh: "完全正确——漂发很伤头发。我们就用接近您自然发色的色号，只提亮一点。不用漂！",
          task: "同意方案，询问日常护理建议",
          options: [
            { text: "Perfect, let's do that. Any tips for taking care of colored hair at home?", ok: true,  tip: "taking care of colored hair 染后护理 + Any tips? 求建议" },
            { text: "Yes. Do everything now. Talking overrated.", ok: false, tip: "问护理建议：Any tips for taking care of colored hair?" },
            { text: "Home tips? I never wash hair anyway.",  ok: false, tip: "染后护理保色关键：Any tips for colored hair at home?" },
          ],
          phrase: { en: "Any tips for ___?", zh: "关于……有什么建议吗？", note: "求实用建议万能句，哪儿都能用" },
        },
        {
          npcLines: [
            "Wash with cool water, use color-safe shampoo, and come back in three months for a touch-up. Ready when you are!",
            "Cool water, purple shampoo, less heat — that's the secret! See you in three months!",
            "Three rules: cool water, color-safe shampoo, easy on the heat. Let's get you started!",
          ],
          npcZh: "用凉水洗、用固色洗发水、少加热——三个月后回来补染。随时开始！",
          task: "复述确认护理要点，避免理解偏差",
          options: [
            { text: "Got it — cool water, color-safe shampoo, and less heat. Let's start!", ok: true,  tip: "复述确认 = 把听到的信息用自己的话说一遍，理解零偏差" },
            { text: "Cool water. Got. Other things. Forgot.",   ok: false, tip: "复述全部要点确认：Cool water, color-safe shampoo, less heat" },
            { text: "Yes yes whatever you say, begin.",         ok: false, tip: "护理要点值得记牢：复述一遍确认" },
          ],
          phrase: { en: "Got it — ___. Let's start!", zh: "明白了——……。开始吧！", note: "复述确认（active listening）：把要点复述一遍再行动" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 办卡与预约",
      titleEn: "Membership & Booking",
      emoji: "💳",
      desc: "成了常客！无预约直接来、指定发型师、办会员卡算优惠、预约下次——理发店的金钱与时间英语。",
      reward: { en: "membership card", zh: "你解锁了办卡预约英语，常客当得明明白白！💳" },
      steps: [
        {
          npcLines: [
            "Hey, it's you again! Welcome back — do you have an appointment today?",
            "My favorite customer! Do you have a booking, or are we feeling spontaneous?",
            "Well well, look who's back! Appointment today, or flying free?",
          ],
          npcZh: "嘿，又是你！欢迎回来——今天有预约吗？",
          task: "没有预约，询问能否直接剪",
          options: [
            { text: "No appointment — do you take walk-ins today? I'd like a quick trim.", ok: true,  tip: "walk-in 无预约顾客 + quick trim 快速修剪" },
            { text: "No book. Just hair luck today?",        ok: false, tip: "标准问法：Do you take walk-ins today?" },
            { text: "Appointment? I don't even know that word.", ok: false, tip: "直接说明来意：Do you take walk-ins? I'd like a quick trim" },
          ],
          phrase: { en: "Do you take walk-ins?", zh: "你们接受没预约直接来的客人吗？", note: "walk-in = 直接上门；美式服务行业高频词" },
        },
        {
          npcLines: [
            "For you? Always! Your usual stylist, Maria, is free in ten minutes. Want to wait?",
            "You know we always fit you in! Maria can take you in ten — okay to wait?",
            "For a regular like you? No problem! Maria's free in ten minutes. Hang tight?",
          ],
          npcZh: "对你？永远有空！你常约的发型师 Maria 十分钟后有空。等一下可以吗？",
          task: "接受等待，指定发型师",
          options: [
            { text: "Perfect, I'll wait for Maria — she knows exactly how I like my hair.", ok: true,  tip: "she knows how I like my hair 常客指定发型师的经典理由" },
            { text: "Any person with scissors is fine.",    ok: false, tip: "指定熟手更稳：I'll wait for Maria" },
            { text: "Ten minutes?! My time is very expensive!", ok: false, tip: "等十分钟合理：Perfect, I'll wait for Maria" },
          ],
          phrase: { en: "She knows how I like my hair.", zh: "她知道我想要什么发型。", note: "常客忠的表达；指定发型师时自然说出来" },
        },
        {
          npcLines: [
            "She'll be thrilled to hear that! While you wait — can I tell you about our membership card? Twenty percent off every visit.",
            "Aww, she'll love that! Say, quick pitch while you wait: our membership card — twenty percent off, every single visit.",
            "That'll make her day! Oh — one thing: membership card. Twenty percent off all haircuts. Want to hear more?",
          ],
          npcZh: "她听到会开心的！等待时——给你介绍下我们的会员卡吗？每次剪发八折。",
          task: "询问办卡费用再决定",
          options: [
            { text: "That sounds interesting. How much is the card, and how long does it last?", ok: true,  tip: "How much / how long 问清成本与期限——办卡两问" },
            { text: "Twenty percent! Card! Where sign? Fast!",  ok: false, tip: "先问成本：How much is the card, and how long does it last?" },
            { text: "Membership is a trap for weak minds.",     ok: false, tip: "划算与否算一算：How much is the card?" },
          ],
          phrase: { en: "How much is it, and how long does it last?", zh: "多少钱？有效期多久？", note: "一切会员卡/套餐的必问两句" },
        },
        {
          npcLines: [
            "Fifty dollars for a year. Haircuts are thirty, so with twenty percent off you'd save six dollars a visit — it pays for itself in nine visits!",
            "Fifty bucks a year. Thirty-dollar cuts, twenty percent off — six bucks saved each time. Nine visits and you're ahead!",
            "Annual card, fifty dollars. Save six dollars per thirty-dollar cut — break even by visit nine!",
          ],
          npcZh: "年费 50 美元。剪发 30 美元，八折每次省 6 美元——剪 9 次就回本了！",
          task: "算账后决定办理",
          options: [
            { text: "I come about every five weeks, so that's worth it. I'll take the card!", ok: true,  tip: "按自己的频率算账（every five weeks）+ 做决定 I'll take it" },
            { text: "Math too hard. Card yes. Money no matter.", ok: false, tip: "算清频率再决定：I come every five weeks — I'll take it!" },
            { text: "Nine visits is too many. Card rejected.",    ok: false, tip: "5 周一次 = 一年 10 次，已回本：I'll take the card!" },
          ],
          phrase: { en: "It pays for itself.", zh: "它自己就把本钱赚回来了（回本）。", note: "算账常用语；earns back the cost" },
        },
        {
          npcLines: [
            "Excellent choice! Just fill this out... and done! Would you like to book your next appointment before you leave?",
            "Welcome to the club! Form's all filled. Want to lock in your next appointment now?",
            "You're officially a member! Last thing — shall we book your next visit today?",
          ],
          npcZh: "好选择！填一下这张表……好了！走之前要把下次预约定下来吗？",
          task: "预约五周后的周六",
          options: [
            { text: "Sure — could I book for Saturday in five weeks? Morning, if possible.", ok: true,  tip: "book for + 时间 预约 + morning, if possible 上午优先（if possible 委婉）" },
            { text: "Book future Saturday of all Saturdays.", ok: false, tip: "说清具体：Saturday in five weeks, morning if possible" },
            { text: "Book? I live in the present moment only.", ok: false, tip: "常客锁位更省心：Could I book for Saturday in five weeks?" },
          ],
          phrase: { en: "Could I book for ___?", zh: "我能预约……吗？", note: "预约万能句；补 if possible 更灵活" },
        },
        {
          npcLines: [
            "Saturday in five weeks, ten a.m., with Maria — you're all set! See you then, member!",
            "Done! Saturday, ten a.m., Maria's chair. See you in five weeks, VIP!",
            "Booked and locked! Ten a.m. Saturday, five weeks out. Enjoy the trim today!",
          ],
          npcZh: "五周后的周六上午十点，Maria——都定好了！到时见，会员！",
          task: "感谢接待，结束本轮",
          options: [
            { text: "You've been so helpful — see you in five weeks. Have a great day!", ok: true,  tip: "see you then 预约道别 + have a great day 收尾" },
            { text: "Bye shop! Bye card! Bye everything!",   ok: false, tip: "自然道别：See you in five weeks. Have a great day!" },
            { text: "Five weeks is so long. Goodbye forever maybe.", ok: false, tip: "有约在身：See you in five weeks!" },
          ],
          phrase: { en: "See you then!", zh: "到时候见！", note: "预约告别语——then = 约定的那个时间" },
        },
      ],
    },
  ],
},
