// 健身房场景头 + 词条
{
  id: "gym",
  name: "健身房",
  nameEn: "Gym",
  emoji: "🏋️",
  iconId: "gym",
  cover: "🏋️🏃💪",
  theme: "gym",
  accent: "#d2691e",
  accentSoft: "#faeedd",
  deco: "✨",
  deco2: "💪",
  intro: "新年新气象，该锻炼了！办卡、参观、第一次训练、请私教——用英文开启健身生活。",
  orderLabel: "🏋️ 训练进度",
  items: [
    { id: "membership", en: "membership", zh: "会员资格", phon: "/ˈmembəʃɪp/", emoji: "💳", sent: "How much is the monthly membership?" },
    { id: "signup",     en: "sign up",    zh: "报名，注册", phon: "/saɪn ʌp/", emoji: "📝", sent: "I'd like to sign up for a membership." },
    { id: "tour",       en: "tour",       zh: "参观", phon: "/tʊə/", emoji: "🚶", sent: "Could I get a tour of the gym first?" },
    { id: "equipment",  en: "equipment",  zh: "器械", phon: "/ɪˈkwɪpmənt/", emoji: "🏋️", sent: "All the equipment is brand new." },
    { id: "treadmill",  en: "treadmill",  zh: "跑步机", phon: "/ˈtredmɪl/", emoji: "🏃", sent: "The treadmills are on the second floor." },
    { id: "dumbbell",   en: "dumbbell",   zh: "哑铃", phon: "/ˈdʌmbel/", emoji: "🏋️", sent: "Start with lighter dumbbells." },
    { id: "locker",     en: "locker",     zh: "储物柜", phon: "/ˈlɒkə/", emoji: "🔐", sent: "You get a locker with your membership." },
    { id: "towel",      en: "towel service", zh: "毛巾服务", phon: "/ˈtaʊəl ˈsɜːvɪs/", emoji: "🧻", sent: "Towel service is included." },
    { id: "trainer",    en: "personal trainer", zh: "私人教练", phon: "/ˈpɜːsənl ˈtreɪnə/", emoji: "🧑‍🏫", sent: "Could I book a personal trainer?" },
    { id: "session",    en: "session",    zh: "（训练）课", phon: "/ˈseʃn/", emoji: "📅", sent: "My first session is on Monday." },
    { id: "warmup",     en: "warm up",    zh: "热身", phon: "/wɔːm ʌp/", emoji: "🔥", sent: "Always warm up before lifting." },
    { id: "stretch",    en: "stretch",    zh: "拉伸", phon: "/stretʃ/", emoji: "🤸", sent: "Stretch after your workout." },
    { id: "reps",       en: "reps",       zh: "次数（repetitions）", phon: "/reps/", emoji: "🔢", sent: "Three sets of ten reps." },
    { id: "sets",       en: "sets",       zh: "组数", phon: "/sets/", emoji: "📊", sent: "Do three sets of each exercise." },
    { id: "form",       en: "form",       zh: "动作姿势", phon: "/fɔːm/", emoji: "🎯", sent: "Your form is more important than weight." },
    { id: "spot",       en: "spot me",    zh: "帮我保护（杠铃）", phon: "/spɒt miː/", emoji: "🤝", sent: "Could you spot me on the bench press?" },
    { id: "benchpress", en: "bench press", zh: "卧推", phon: "/bentʃ pres/", emoji: "🛏️", sent: "The bench press is taken right now." },
    { id: "cardio",     en: "cardio",     zh: "有氧运动", phon: "/ˈkɑːdiəʊ/", emoji: "❤️", sent: "I do cardio on Mondays." },
    { id: "weights",    en: "lift weights", zh: "举铁，力量训练", phon: "/lɪft weɪts/", emoji: "🏋️", sent: "I lift weights three times a week." },
    { id: "sore",       en: "sore",       zh: "（肌肉）酸痛", phon: "/sɔː/", emoji: "😖", sent: "My legs are so sore today!" },
    { id: "muscles",    en: "muscles",    zh: "肌肉", phon: "/ˈmʌslz/", emoji: "💪", sent: "Feel those muscles working!" },
    { id: "hydrate",    en: "stay hydrated", zh: "保持水分", phon: "/steɪ haɪˈdreɪtɪd/", emoji: "💧", sent: "Stay hydrated during your workout." },
    { id: "cancel",     en: "cancel my membership", zh: "取消会员", phon: "/ˈkænsl/", emoji: "🚪", sent: "I'd like to cancel my membership." },
    { id: "freeze2",    en: "freeze my membership", zh: "冻结会员（暂停）", phon: "/friːz/", emoji: "🧊", sent: "Can I freeze my membership while traveling?" },
    { id: "peak",       en: "peak hours", zh: "高峰时段", phon: "/piːk ˈaʊəz/", emoji: "⏰", sent: "Avoid the gym during peak hours." },
    { id: "trial",      en: "free trial", zh: "免费体验", phon: "/friː traɪəl/", emoji: "🎁", sent: "We offer a one-day free trial." }
  ],
