// 健身房场景头 + 词条
{
  id: "gym",
  name: "健身房",
  nameEn: "Gym",
  emoji: "🏋️",
  iconId: "gym",
  cover: "🏋️🏃💪",
  theme: "gym",
  accent: "#d2691e",
  accentSoft: "#faeedd",
  deco: "✨",
  deco2: "💪",
  intro: "新年新气象，该锻炼了！办卡、参观、第一次训练、请私教——用英文开启健身生活。",
  orderLabel: "🏋️ 训练进度",
  items: [
    { id: "membership", en: "membership", zh: "会员资格", phon: "/ˈmembəʃɪp/", emoji: "💳", sent: "How much is the monthly membership?" },
    { id: "signup",     en: "sign up",    zh: "报名，注册", phon: "/saɪn ʌp/", emoji: "📝", sent: "I'd like to sign up for a membership." },
    { id: "tour",       en: "tour",       zh: "参观", phon: "/tʊə/", emoji: "🚶", sent: "Could I get a tour of the gym first?" },
    { id: "equipment",  en: "equipment",  zh: "器械", phon: "/ɪˈkwɪpmənt/", emoji: "🏋️", sent: "All the equipment is brand new." },
    { id: "treadmill",  en: "treadmill",  zh: "跑步机", phon: "/ˈtredmɪl/", emoji: "🏃", sent: "The treadmills are on the second floor." },
    { id: "dumbbell",   en: "dumbbell",   zh: "哑铃", phon: "/ˈdʌmbel/", emoji: "🏋️", sent: "Start with lighter dumbbells." },
    { id: "locker",     en: "locker",     zh: "储物柜", phon: "/ˈlɒkə/", emoji: "🔐", sent: "You get a locker with your membership." },
    { id: "towel",      en: "towel service", zh: "毛巾服务", phon: "/ˈtaʊəl ˈsɜːvɪs/", emoji: "🧻", sent: "Towel service is included." },
    { id: "trainer",    en: "personal trainer", zh: "私人教练", phon: "/ˈpɜːsənl ˈtreɪnə/", emoji: "🧑‍🏫", sent: "Could I book a personal trainer?" },
    { id: "session",    en: "session",    zh: "（训练）课", phon: "/ˈseʃn/", emoji: "📅", sent: "My first session is on Monday." },
    { id: "warmup",     en: "warm up",    zh: "热身", phon: "/wɔːm ʌp/", emoji: "🔥", sent: "Always warm up before lifting." },
    { id: "stretch",    en: "stretch",    zh: "拉伸", phon: "/stretʃ/", emoji: "🤸", sent: "Stretch after your workout." },
    { id: "reps",       en: "reps",       zh: "次数（repetitions）", phon: "/reps/", emoji: "🔢", sent: "Three sets of ten reps." },
    { id: "sets",       en: "sets",       zh: "组数", phon: "/sets/", emoji: "📊", sent: "Do three sets of each exercise." },
    { id: "form",       en: "form",       zh: "动作姿势", phon: "/fɔːm/", emoji: "🎯", sent: "Your form is more important than weight." },
    { id: "spot",       en: "spot me",    zh: "帮我保护（杠铃）", phon: "/spɒt miː/", emoji: "🤝", sent: "Could you spot me on the bench press?" },
    { id: "benchpress", en: "bench press", zh: "卧推", phon: "/bentʃ pres/", emoji: "🛏️", sent: "The bench press is taken right now." },
    { id: "cardio",     en: "cardio",     zh: "有氧运动", phon: "/ˈkɑːdiəʊ/", emoji: "❤️", sent: "I do cardio on Mondays." },
    { id: "weights",    en: "lift weights", zh: "举铁，力量训练", phon: "/lɪft weɪts/", emoji: "🏋️", sent: "I lift weights three times a week." },
    { id: "sore",       en: "sore",       zh: "（肌肉）酸痛", phon: "/sɔː/", emoji: "😖", sent: "My legs are so sore today!" },
    { id: "muscles",    en: "muscles",    zh: "肌肉", phon: "/ˈmʌslz/", emoji: "💪", sent: "Feel those muscles working!" },
    { id: "hydrate",    en: "stay hydrated", zh: "保持水分", phon: "/steɪ haɪˈdreɪtɪd/", emoji: "💧", sent: "Stay hydrated during your workout." },
    { id: "cancel",     en: "cancel my membership", zh: "取消会员", phon: "/ˈkænsl/", emoji: "🚪", sent: "I'd like to cancel my membership." },
    { id: "freeze2",    en: "freeze my membership", zh: "冻结会员（暂停）", phon: "/friːz/", emoji: "🧊", sent: "Can I freeze my membership while traveling?" },
    { id: "peak",       en: "peak hours", zh: "高峰时段", phon: "/piːk ˈaʊəz/", emoji: "⏰", sent: "Avoid the gym during peak hours." },
    { id: "trial",      en: "free trial", zh: "免费体验", phon: "/friː traɪəl/", emoji: "🎁", sent: "We offer a one-day free trial." }
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 办卡与参观",
      titleEn: "Membership & Tour",
      emoji: "💳",
      desc: "第一次走进健身房：问价格、免费体验、参观器械区、签合同——办卡全流程。",
      reward: { en: "membership", zh: "你办好了健身卡，新生活开始了！🏋️" },
      steps: [
        {
          npcLines: [
            "Welcome to Iron Paradise! Looking to join, or just checking us out?",
            "Hey there, welcome! Are you here to sign up, or just browsing?",
            "Hi! First time at Iron Paradise? Joining us today or just looking around?",
          ],
          npcZh: "欢迎来到铁馆天堂！是想入会，还是先看看？",
          task: "询问会员价格与套餐选项",
          options: [
            { text: "Hi! I'm interested in joining. Could you tell me about your membership options and prices?", ok: true,  tip: "interested in joining 表达意向 + membership options and prices 问套餐与价格" },
            { text: "How much money for muscle place?", ok: false, tip: "说 I'm interested in joining. What are the membership options?" },
            { text: "Give me cheapest body. Price of cheapest body.", ok: false, tip: "标准问法：membership options and prices" },
          ],
          phrase: { en: "I'm interested in joining.", zh: "我有兴趣入会。", note: "interested in + 动名词——表达意向不承诺，进可攻退可守" },
        },
        {
          npcLines: [
            "Sure! We have monthly at forty bucks, or annual at three-sixty — that's like getting three months free. Want the full tour before deciding?",
            "Great! Monthly is forty, annual is three-sixty — three months free, basically. Shall I show you around first?",
            "Here's the deal: forty a month, or three-sixty a year. Tour first? Decision after — that's my motto!",
          ],
          npcZh: "当然！月卡 40 美元，年卡 360——相当于白送三个月。决定前先来个全程参观？",
          task: "接受参观，同时确认有无隐藏费用",
          options: [
            { text: "A tour sounds great. Are there any extra fees beyond the membership — like enrollment or cancellation fees?", ok: true,  tip: "enrollment fee 注册费 + cancellation fee 取消费——办卡防坑两问" },
            { text: "Tour yes. Fees no. Only membership price forever.", ok: false, tip: "先问清：Any extra fees — enrollment or cancellation?" },
            { text: "Three months free? Free things scare me.", ok: false, tip: "合理核实条款：Are there any extra fees?" },
          ],
          phrase: { en: "Are there any extra fees?", zh: "还有其他额外费用吗？", note: "办任何卡的第一问—— enrollment/cancellation 都要问" },
        },
        {
          npcLines: [
            "No enrollment fee this month — promotion! Cancellation needs thirty days' notice, no penalty. Now, the tour: cardio upstairs, weights down here.",
            "Zero enrollment this month — it's promo season! Cancel anytime with thirty days' notice. Okay: cardio's up top, weights are down here!",
            "This month: no enrollment fee! Thirty-day notice to cancel, that's it. Tour time — follow me, cardio first!",
          ],
          npcZh: "本月免注册费——促销期！取消需提前 30 天通知，无违约金。好，参观：楼上有氧，楼下力量区。",
          task: "参观时询问器械使用是否需要预约",
          options: [
            { text: "Nice! Do I need to book the equipment in advance, or is it first come, first served?", ok: true,  tip: "book in advance 提前预约 + first come, first served 先到先得" },
            { text: "Machines fight for? I fight machine for turn?", ok: false, tip: "问规则：Do I need to book in advance?" },
            { text: "Book equipment? Machines have calendars now?", ok: false, tip: "高峰期可能要等：Is it first come, first served?" },
          ],
          phrase: { en: "first come, first served", zh: "先到先得。", note: "资源分配高频表达；健身房、餐厅、商店通用" },
        },
        {
          npcLines: [
            "No booking needed — first come, first served. Peak hours are five to seven, so come earlier if you hate waiting! And yes, towel service is included.",
            "Just show up and hop on! Rush hour is five to seven — early birds win. Oh, and towels are on us!",
            "No reservations here — fastest feet win! Five to seven is madness, come at lunch instead. Towels? Included!",
          ],
          npcZh: "不需要预约——先到先得。高峰是 5 点到 7 点，不想排队就早点来！毛巾服务包含在内。",
          task: "询问储物柜与淋浴设施",
          options: [
            { text: "Good to know. What about lockers and showers — do I need to bring my own lock?", ok: true,  tip: "bring my own lock 自带锁——健身房储物柜经典问题" },
            { text: "Locker? I will guard bag with my body.", ok: false, tip: "有储物柜：What about lockers — my own lock?" },
            { text: "Shower at gym? I shower at home only, forever.", ok: false, tip: "问清设施：What about lockers and showers?" },
          ],
          phrase: { en: "Do I need to bring my own lock?", zh: "我需要自己带锁吗？", note: "自备 vs 提供——健身房/青旅通用问句" },
        },
        {
          npcLines: [
            "Lockers are free with digital codes — no lock needed! Showers have shampoo and soap. So, are you ready to sign up?",
            "Digital locks, fresh towels, shower stuff — we thought of everything! Ready to make it official?",
            "Keypad lockers, all shower supplies — you just bring you! So — shall we do paperwork?",
          ],
          npcZh: "储物柜免费，数字密码锁——不用自带锁！淋浴间有洗发水和沐浴露。那么，准备好签约入会了吗？",
          task: "先要一次免费体验再决定",
          options: [
            { text: "Almost! Could I try a free trial session first? I'd like to feel the place before committing.", ok: true,  tip: "free trial session 免费体验 + before committing 承诺之前——理性决策" },
            { text: "Yes sign now! No thinking! Paper fast!",       ok: false, tip: "先体验：Could I try a free trial session first?" },
            { text: "Committing? I fear commitment and treadmills.", ok: false, tip: "体验降低决策压力：before committing" },
          ],
          phrase: { en: "Could I try a free trial first?", zh: "我能先免费体验一次吗？", note: "trial = 试用；大额消费前的标准缓冲动作" },
        },
        {
          npcLines: [
            "Smart shopper — one-day free trial, no strings attached! Here's your guest pass. See you tomorrow?",
            "I respect that! Day pass on the house, no commitment. Tomorrow, same time?",
            "Trial it is! Guest pass for one full day. Come break a sweat and then decide!",
          ],
          npcZh: "精明的顾客——一天免费体验，无任何附加条件！这是您的体验券。明天见？",
          task: "感谢并确认明天来体验",
          options: [
            { text: "Perfect, thank you! I'll come tomorrow morning. See you then!", ok: true,  tip: "确认时间（tomorrow morning）+ See you then 预约式道别" },
            { text: "Tomorrow maybe. Or next year. Time is mystery.", ok: false, tip: "定下具体时间：Tomorrow morning — see you then!" },
            { text: "Guest pass received. Departing now.",           ok: false, tip: "收尾确认：I'll come tomorrow morning. See you then!" },
          ],
          phrase: { en: "See you then!", zh: "到时候见！", note: "约好时间后的道别；then = 刚约定的那个时间" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 第一次训练",
      titleEn: "First Workout",
      emoji: "💪",
      desc: "办卡后第一次正式训练：热身、用跑步机、举哑铃、找人数组、练完拉伸——健身英语实战。",
      reward: { en: "warm up", zh: "你完成了第一次英文环境训练！💪" },
      steps: [
        {
          npcLines: [
            "Welcome back — you came! Nice. First workout? Start light, okay?",
            "Hey, you showed up! That's half the battle. First time on the floor? Go easy today!",
            "Look who's back! First workout is the most important one — let's make it count, but gently!",
          ],
          npcZh: "欢迎回来——你真的来了！好样的。第一次训练？从轻量开始，好吗？",
          task: "请教今天的训练流程",
          options: [
            { text: "Thanks! What's a good routine for a beginner? I don't even know where to start.", ok: true,  tip: "routine 训练流程 + don't know where to start 坦白新手身份" },
            { text: "Routine? I know everything. Watch and learn.",  ok: false, tip: "新手求教不吃亏：What's a good routine for a beginner?" },
            { text: "Just point at biggest machine. I do biggest machine.", ok: false, tip: "循序渐进：I don't know where to start" },
          ],
          phrase: { en: "I don't know where to start.", zh: "我不知道从哪儿开始。", note: "求助万能句——坦白新手的最佳开场" },
        },
        {
          npcLines: [
            "Classic beginner day: five minutes of cardio to warm up, then some light weights, then stretch. Treadmill's right there — do you know how it works?",
            "The formula: five cardio minutes, light weights, stretching. The treadmill's free — need a quick tutorial?",
            "Beginner blueprint: warm up on the treadmill, light dumbbells, stretch it out. Ever used one of these bad boys?",
          ],
          npcZh: "经典新手日：5 分钟有氧热身，然后轻量力量，最后拉伸。跑步机在那边——您会用吗？",
          task: "询问跑步机操作",
          options: [
            { text: "A quick tutorial would be great. How do I set the speed and the incline?", ok: true,  tip: "set the speed and the incline 调速度和坡度——跑步机两大参数" },
            { text: "Treadmill simple. Feet go, machine follow.",   ok: false, tip: "问操作：How do I set the speed and the incline?" },
            { text: "Speed maximum please. Incline maximum. Everything maximum.", ok: false, tip: "新手从低速开始：How do I set the speed?" },
          ],
          phrase: { en: "How do I set the speed?", zh: "怎么调速度？", note: "set = 设置/调节；跑步机、健身车、椭圆机通用" },
        },
        {
          npcLines: [
            "Speed's the big buttons, incline is the little ones. Start at three — that's a brisk walk. Now let's grab some dumbbells!",
            "Big buttons: speed. Little ones: incline. Level three to start — walking pace! Now, dumbbell time!",
            "Speed on the left, incline on the right. Start at three, walk it out. Then we lift small things!",
          ],
          npcZh: "大按钮是速度，小按钮是坡度。从 3 开始——快走速度。现在去拿哑铃！",
          task: "选择合适重量的哑铃",
          options: [
            { text: "Got it. Which weight should I start with? I'd rather go lighter and keep good form.", ok: true,  tip: "keep good form 保持标准姿势——宁轻勿歪，健身第一原则" },
            { text: "Heaviest dumbbell. I lift heaviest for respect.", ok: false, tip: "姿势>重量：I'd rather go lighter and keep good form" },
            { text: "Form? I have many forms. All forms good.",        ok: false, tip: "form 指动作标准度：Lighter weight, good form" },
          ],
          phrase: { en: "I'd rather go lighter.", zh: "我宁愿用轻一点的。", note: "would rather 宁愿；健身 humility 是安全的第一步" },
        },
        {
          npcLines: [
            "Perfect attitude — form over weight, every time! Try these ten-pounders: three sets of ten reps. Rest one minute between sets.",
            "That's the spirit! Ten-pound dumbbells: three sets, ten reps each, one minute of rest between. Simple math!",
            "Smart lifter! Grab the tens: three sets of ten, minute rest between. You'll feel it tomorrow!",
          ],
          npcZh: "完美的态度——永远姿势优先于重量！试试这副 10 磅的：3 组，每组 10 次，组间休息 1 分钟。",
          task: "复述训练参数确认理解",
          options: [
            { text: "So: three sets of ten reps, one minute rest in between. Got it!", ok: true,  tip: "复述 sets/reps/rest 三要素——健身房沟通的数字骨架" },
            { text: "Three tens of ten threes. Or ten threes of three tens.", ok: false, tip: "准确复述：Three sets of ten reps, one minute rest" },
            { text: "Sets, reps, rest — too much math for muscles.", ok: false, tip: "记住三要素：3 sets, 10 reps, 1 min rest" },
          ],
          phrase: { en: "Three sets of ten reps.", zh: "三组，每组十次。", note: "训练计划万能格式：sets 组 / reps 次数" },
        },
        {
          npcLines: [
            "Exactly! Last thing — don't skip stretching after. And drink plenty of water. Feeling okay so far?",
            "Perfect recall! Stretch when you're done, and stay hydrated. How're you feeling?",
            "You got it! After-workout stretch, water all day. Surviving the beginner day?",
          ],
          npcZh: "完全正确！最后——练完别跳过拉伸，多喝水。目前感觉还好吗？",
          task: "表达肌肉有点酸但感觉不错",
          options: [
            { text: "My arms are a little sore, but it feels great! I'll definitely be back.", ok: true,  tip: "sore 酸痛 + I'll be back 我会再来——正向反馈闭环" },
            { text: "Arms broken. Life broken. Never return.",       ok: false, tip: "酸痛是正常适应：A little sore, but it feels great!" },
            { text: "No feeling. Muscles sleeping. Wake muscles never.", ok: false, tip: "描述真实感受：A little sore, but it feels great!" },
          ],
          phrase: { en: "I'm a little sore, but it feels great!", zh: "有点酸，但感觉真好！", note: "sore = 迟发性肌肉酸痛；健身人的自豪宣言" },
        },
        {
          npcLines: [
            "That's the beginner glow! See you next workout — and remember, the soreness means it's working!",
            "Sore today, strong tomorrow! Welcome to the family — see you soon!",
            "That soreness? That's progress you can feel! Great work today. See you next time!",
          ],
          npcZh: "这就是新手光环！下次训练见——记住，酸痛说明训练起效了！",
          task: "感谢教练，结束首次训练",
          options: [
            { text: "Thanks for all the help today — you made my first workout way less scary!", ok: true,  tip: "way less scary 没那么可怕了——way + 比较级强化语气" },
            { text: "Bye scary gym man!",                              ok: false, tip: "真诚感谢：You made my first workout way less scary!" },
            { text: "First workout done. Scary level unchanged.",       ok: false, tip: "夸对方帮助：Thanks — you made it way less scary!" },
          ],
          phrase: { en: "way less scary", zh: "没那么可怕了。", note: "way + 形容词比较级 = 「……多了」；口语强化神器" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 会员问题与私教",
      titleEn: "Membership Issues & Trainer",
      emoji: "📋",
      desc: "出差两个月想冻结会员？高峰期卧推被占？想请私教？健身房进阶事务英语。",
      reward: { en: "personal trainer", zh: "你解锁了健身房进阶英语，会员私教都能搞定！📋" },
      steps: [
        {
          npcLines: [
            "Hey, familiar face! What can I do for you today — workout stuff or account stuff?",
            "Welcome back! Are we lifting today, or is this an admin day?",
            "Hi again! Gym time or paperwork time?",
          ],
          npcZh: "嘿，熟面孔！今天办什么——训练还是账户业务？",
          task: "说明要出差，想冻结会员两个月",
          options: [
            { text: "Account stuff, actually. I'm traveling for two months — could I freeze my membership while I'm away?", ok: true,  tip: "freeze my membership 冻结会员（暂停计费）——出差旅行必备" },
            { text: "Travel two months. Membership sleep time, please.", ok: false, tip: "准确说法：Could I freeze my membership?" },
            { text: "I leave. You stop charging. This is fair deal.",  ok: false, tip: "有正式流程：Could I freeze my membership while I'm away?" },
          ],
          phrase: { en: "Could I freeze my membership?", zh: "我能冻结会员吗？", note: "freeze = 暂停不取消；多数健身房每月可冻结 1-3 个月" },
        },
        {
          npcLines: [
            "Absolutely — we can freeze up to three months a year, just ten bucks a month while frozen. Want me to set that up?",
            "You bet! Up to three months a year, ten dollars monthly freeze fee. Shall I?",
            "No problem — three months max per year, ten a month to freeze. Good to go?",
          ],
          npcZh: "当然——每年最多可冻结三个月，冻结期间每月 10 美元。要我现在帮您设置吗？",
          task: "确认冻结，顺便问恢复手续",
          options: [
            { text: "That works. When I come back, do I just unfreeze it, or do I need to do anything?", ok: true,  tip: "unfreeze 解冻 + or do I need to do anything 问全流程" },
            { text: "Freeze now. Unfreeze is future problem.",       ok: false, tip: "问清恢复流程：Do I just unfreeze it?" },
            { text: "Ten dollars to NOT use gym? Bold business model.", ok: false, tip: "行业惯例，确认即可：That works. How do I unfreeze it?" },
          ],
          phrase: { en: "Do I need to do anything?", zh: "我还需要做什么吗？", note: "流程确认收尾句——防隐藏步骤" },
        },
        {
          npcLines: [
            "Just message us when you're back — one click on my end and you're active again! Now, anything else? You look like you want to ask something.",
            "Shoot me a text when you return — reactivation takes ten seconds! What else is on your mind? I sense a question...",
            "Ping us and you're back in business! Okay, spill it — you've got trainer questions, don't you?",
          ],
          npcZh: "回来时给我们发个消息——我这边一键激活！还有别的吗？您看起来有问题想问。",
          task: "询问私教服务的价格与内容",
          options: [
            { text: "You read my mind! I'm thinking about a personal trainer. What do the sessions cost, and what's included?", ok: true,  tip: "You read my mind 你猜到我了 + what's included 问包含内容" },
            { text: "Personal trainer! Muscles rental price?",       ok: false, tip: "问价格与服务：What do sessions cost, and what's included?" },
            { text: "Yes question. But now shy. Forget question.",   ok: false, tip: "直接问：What do the sessions cost?" },
          ],
          phrase: { en: "You read my mind!", zh: "你猜到我心坎里了！", note: "对方抢先说出你想说的话时的幽默回应" },
        },
        {
          npcLines: [
            "Sessions are fifty each, or a package of ten for four-fifty. That includes a custom plan, form checks, and nutrition basics. First session's half off!",
            "Fifty a session, or ten for four-fifty — plan, form coaching, nutrition guide included. First one's fifty percent off!",
            "Single: fifty. Ten-pack: four-fifty. Custom plan, form fixes, food wisdom — and your first session is half price!",
          ],
          npcZh: "单节课 50 美元，10 节套餐 450。含定制计划、动作纠正和营养建议。首节课半价！",
          task: "先约一节体验课试试",
          options: [
            { text: "Let me start with one session at the intro price. If we click, I'll consider the package.", ok: true,  tip: "intro price 体验价 + if we click 如果合得来——先试后买" },
            { text: "Package of ten. No trial. Maximum commitment.", ok: false, tip: "先试一节：Let me start with one session first" },
            { text: "Half price is suspicious price. Why half?",     ok: false, tip: "首单优惠是行业惯例：One session at the intro price, please" },
          ],
          phrase: { en: "If we click, I'll consider it.", zh: "如果合得来，我会考虑的。", note: "click = 合拍（人与人）；进可攻退可守的表态" },
        },
        {
          npcLines: [
            "Fair enough — intro session Saturday at ten with Coach Alex. Oh, one heads-up for your regular workouts: the bench press gets busy around six.",
            "Deal! Saturday, ten a.m., Coach Alex. Quick tip: skip six p.m. on the bench — chaos hour!",
            "Booked! Saturday ten, Coach Alex. Pro tip: bench press at six p.m. is a battlefield. Come earlier!",
          ],
          npcZh: "合理——周六上午 10 点，Alex 教练的体验课。对了，提醒一句：卧推架 6 点左右很抢手。",
          task: "询问器械被占时的礼貌做法",
          options: [
            { text: "Good to know. If the equipment is taken, is it okay to ask to work in, or should I just wait?", ok: true,  tip: "work in 轮流共用器械——健身房重要社交礼仪" },
            { text: "If taken, I take by force. Gym law.",          ok: false, tip: "礼貌询问：Is it okay to ask to work in?" },
            { text: "Wait forever? I wait like furniture?",         ok: false, tip: "可以轮换用：Is it okay to ask to work in?" },
          ],
          phrase: { en: "Can I work in?", zh: "我能跟你轮流用吗？", note: "work in = 组间轮换共用器械；健身房最实用社交句" },
        },
        {
          npcLines: [
            "Working in is totally fine — just ask between their sets, and re-rack your weights after! That's gym etiquette 101. See you Saturday!",
            "Asking to work in is normal — between sets, be friendly, rack your weights! Etiquette gold. Saturday it is!",
            "Work in away! Ask between sets, wipe down, re-rack — that's all the rules. See you Saturday, champ!",
          ],
          npcZh: "轮流用完全没问题——在别人组间问就行，用完把杠铃片归位！这是健身房礼仪第一课。周六见！",
          task: "复述健身房礼仪要点，结束",
          options: [
            { text: "Got it: ask between sets, wipe down the equipment, and re-rack the weights. See you Saturday!", ok: true,  tip: "复述礼仪三件套（ask/wipe/re-rack）——健身房文明人认证" },
            { text: "Rules memorized. Partially. Some rules.",       ok: false, tip: "礼仪要点复述完整：ask between sets, wipe down, re-rack" },
            { text: "Wipe equipment? I spread germs for friendship.", ok: false, tip: "擦器械是基本礼仪：Wipe down the equipment" },
          ],
          phrase: { en: "re-rack your weights", zh: "把器械归位。", note: "re-rack = 放回架子；健身房最看重的公德" },
        },
      ],
    },
  ],
},
