// 医院/药房 第 1 轮：挂号问诊（8 步）
{
  id: "hospital",
  name: "医院",
  nameEn: "Hospital",
  emoji: "🏥",
  iconId: "hospital",
  cover: "🏥💊🩺",
  theme: "hospital",
  accent: "#4a7f9e",
  accentSoft: "#dceaf2",
  deco: "✨",
  deco2: "🫧",
  intro: "你不舒服需要看医生。从挂号到描述症状，完成一次完整的英文就诊！",
  orderLabel: "🩺 就诊进度",
  items: [
    { id: "appointment", en: "appointment", zh: "预约", phon: "/əˈpɔɪntmənt/", emoji: "📅", sent: "I'd like to make an appointment." },
    { id: "reception",   en: "reception",   zh: "挂号处/前台", phon: "/rɪˈsepʃn/", emoji: "🛎️", sent: "Please register at reception first." },
    { id: "symptom",     en: "symptom",     zh: "症状", phon: "/ˈsɪmptəm/", emoji: "🤒", sent: "Describe your symptoms to the doctor." },
    { id: "fever",       en: "fever",       zh: "发烧", phon: "/ˈfiːvə(r)/", emoji: "🌡️", sent: "I have a fever and a headache." },
    { id: "sorethroat",  en: "sore throat", zh: "喉咙痛", phon: "/sɔː θrəʊt/", emoji: "😷", sent: "My sore throat makes it hard to swallow." },
    { id: "cough",       en: "cough",       zh: "咳嗽", phon: "/kɒf/", emoji: "💨", sent: "I've had a cough for three days." },
    { id: "doctor",      en: "doctor",      zh: "医生", phon: "/ˈdɒktə(r)/", emoji: "🧑‍⚕️", sent: "The doctor will see you now." },
    { id: "insurance",   en: "insurance",   zh: "保险", phon: "/ɪnˈʃʊərəns/", emoji: "🪪", sent: "Do you have medical insurance?" },
    { id: "waitingroom", en: "waiting room", zh: "候诊室", phon: "/ˈweɪtɪŋ ruːm/", emoji: "🪑", sent: "Please wait in the waiting room." },
    { id: "form",        en: "form",        zh: "表格", phon: "/fɔːm/", emoji: "📋", sent: "Please fill in this form." },
    // 第 2 轮（药房）新词
    { id: "pharmacy",    en: "pharmacy",    zh: "药房", phon: "/ˈfɑːməsi/", emoji: "💊", sent: "Take this prescription to the pharmacy." },
    { id: "prescription",en: "prescription",zh: "处方", phon: "/prɪˈskrɪpʃn/", emoji: "📝", sent: "The doctor wrote me a prescription." },
    { id: "medicine",    en: "medicine",    zh: "药", phon: "/ˈmedsn/", emoji: "💊", sent: "Take this medicine twice a day." },
    { id: "pill",        en: "pill",        zh: "药片", phon: "/pɪl/", emoji: "⚪", sent: "Take one pill after meals." },
    { id: "dosage",      en: "dosage",      zh: "剂量", phon: "/ˈdəʊsɪdʒ/", emoji: "⏱️", sent: "What's the recommended dosage?" },
    // 第 3 轮（复诊）新词
    { id: "checkup",     en: "check-up",    zh: "复查", phon: "/ˈtʃekʌp/", emoji: "🔁", sent: "I'm here for a follow-up check-up." },
    { id: "better",      en: "better",      zh: "好转", phon: "/ˈbetə(r)/", emoji: "😊", sent: "I feel much better than last week." },
    { id: "bloodpressure", en: "blood pressure", zh: "血压", phon: "/ˈblʌd preʃə(r)/", emoji: "🩸", sent: "Your blood pressure is normal." },
    { id: "allergic",    en: "allergic",    zh: "过敏的", phon: "/əˈlɜːdʒɪk/", emoji: "⚠️", sent: "Are you allergic to any medicine?" },
    { id: "recovered",   en: "recovered",   zh: "康复", phon: "/rɪˈkʌvəd/", emoji: "🎉", sent: "You have fully recovered. Well done!" },
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 挂号问诊",
      titleEn: "Seeing a Doctor",
      emoji: "🩺",
      desc: "你发烧了还咳嗽。挂号、等叫号、向医生描述症状——第一次用英文看病。",
      reward: { en: "doctor", zh: "你用英文完成了一次完整的问诊！🩺" },
      steps: [
        {
          npcLines: [
            "Good morning! Welcome to City Clinic. How can I help you today?",
            "Good morning! Do you have an appointment, or is this a walk-in?",
            "Hello there! What brings you to the clinic today?",
          ],
          npcZh: "早上好！欢迎来到城市诊所。今天有什么可以帮您？",
          task: "说明想看医生",
          options: [
            { text: "Hi, I'd like to see a doctor, please.", ok: true,  tip: "I'd like to see a doctor——最通用的挂号开口句" },
            { text: "I want doctor now sick.",               ok: false, tip: "说 I'd like to see a doctor" },
            { text: "Doctor me look at.",                    ok: false, tip: "更自然：I'd like to see a doctor" },
          ],
          phrase: { en: "I'd like to see a doctor.", zh: "我想看医生", note: "诊所/医院前台的第一句，礼貌万能" },
        },
        {
          npcLines: [
            "Of course. May I see your ID or passport, please?",
            "Sure thing! Could I see some identification?",
            "No problem. I'll just need your ID or passport first.",
          ],
          npcZh: "当然可以。请出示您的身份证件好吗？",
          task: "递上证件",
          options: [
            { text: "Sure, here you are.", ok: true,  tip: "Here you are——递东西给对方的标准句" },
            { text: "Take this my card.", ok: false, tip: "说 Here you are 或 Here it is" },
            { text: "You look card yes.", ok: false, tip: "更自然：Sure, here you are" },
          ],
          phrase: { en: "Here you are.", zh: "给您", note: "递证件/物品万能句，也可说 Here it is" },
        },
        {
          npcLines: [
            "Thank you. Could you fill in this form? We need your name, address, and phone number.",
            "Great, thanks! Please fill out this registration form — name, address, and contact number.",
            "Got it. Just this quick form to fill in: your details and a contact number.",
          ],
          npcZh: "谢谢。请填一下这张表格：姓名、住址和电话。",
          task: "回应填表请求",
          options: [
            { text: "No problem. Where do I sign?", ok: true,  tip: "痛快答应 + Where do I sign 追问签字处，自然又高效" },
            { text: "I no write English.",          ok: false, tip: "可以请求帮助：Could you help me with the form?" },
            { text: "Form is too much many.",       ok: false, tip: "更自然：No problem. Where do I sign?" },
          ],
          phrase: { en: "Where do I sign?", zh: "我在哪里签字？", note: "填表的实用追问，sign 也可换 write" },
          adds: [ { emoji: "📋", label: "Filled Form", wordId: "form" } ],
        },
        {
          npcLines: [
            "Perfect. Do you have medical insurance?",
            "All done! And do you have insurance coverage?",
            "Great. Last thing — are you insured?",
          ],
          npcZh: "完美。您有医疗保险吗？",
          task: "说明有保险并出示保险卡",
          options: [
            { text: "Yes, I have insurance. Here's my card.", ok: true,  tip: "出示证件用 Here's my card，简洁明确" },
            { text: "Insurance have yes card.",               ok: false, tip: "说 Yes, I have insurance" },
            { text: "My card you take it.",                   ok: false, tip: "更自然：Here's my insurance card" },
          ],
          phrase: { en: "Here's my card.", zh: "这是我的卡", note: "递卡/证件的万能句，比 give you 更礼貌" },
          adds: [ { emoji: "🪪", label: "Insurance", wordId: "insurance" } ],
        },
        {
          npcLines: [
            "Great, you're all registered. Please have a seat in the waiting room — the doctor will call your name.",
            "You're all set! Take a seat in the waiting room and the doctor will call you shortly.",
            "All registered! Please wait in the waiting room; it shouldn't be long.",
          ],
          npcZh: "好了，挂号完成。请在候诊室就座，医生会叫您的名字。",
          task: "表示明白并找到座位",
          options: [
            { text: "Thank you. Which way is the waiting room?", ok: true,  tip: "Which way is...——问地点方向的标准句" },
            { text: "Where I sit find place?",                  ok: false, tip: "说 Which way is the waiting room?" },
            { text: "Room wait where at?",                      ok: false, tip: "更自然：Which way is the waiting room?" },
          ],
          phrase: { en: "Which way is ___?", zh: "……往哪边走？", note: "问路/问方向，比 Where is 更具体" },
          adds: [ { emoji: "🪑", label: "Waiting", wordId: "waitingroom" } ],
        },
        {
          npcLines: [
            "Alex? The doctor will see you now. Room 3, please.",
            "Alex! You're up — the doctor is ready for you in Room 3.",
            "Alex, the doctor can see you now. This way to Room 3, please.",
          ],
          npcZh: "Alex？医生现在可以看诊了，请到 3 号诊室。",
          task: "进入诊室并和医生打招呼",
          options: [
            { text: "Good morning, doctor.", ok: true,  tip: "称呼医生用 doctor，简洁礼貌" },
            { text: "Hello medicine man.",  ok: false, tip: "医生就是 doctor，不用 medicine man" },
            { text: "Hi hospital person.",  ok: false, tip: "更自然：Good morning, doctor" },
          ],
          phrase: { en: "Good morning, doctor.", zh: "早上好，医生", note: "见医生第一句，直接称呼 doctor" },
        },
        {
          npcLines: [
            "Good morning, I'm Dr. Lee. So, what seems to be the problem?",
            "Hello, I'm Dr. Lee. Tell me — what's troubling you today?",
            "Good morning, Alex. What brings you in today?",
          ],
          npcZh: "早上好，我是李医生。说说看，哪里不舒服？",
          task: "描述症状：发烧、喉咙痛、咳嗽三天",
          options: [
            { text: "I have a fever, a sore throat, and I've had a cough for three days.", ok: true,  tip: "I have a... + I've had a... for + 时间——描述症状的标准结构" },
            { text: "I am hot and throat pain cough three day.",                          ok: false, tip: "发烧说 have a fever，不说 I am hot" },
            { text: "Body bad feeling since some days sick.",                              ok: false, tip: "更自然：I have a fever and a sore throat" },
          ],
          phrase: { en: "I have a ___ and I've had a ___ for ___.", zh: "我有……症状，……持续了……", note: "描述症状万能句型：have + 症状，for + 持续时间" },
          adds: [ { emoji: "🌡️", label: "Fever", wordId: "fever" }, { emoji: "😷", label: "Sore Throat", wordId: "sorethroat" }, { emoji: "💨", label: "Cough", wordId: "cough" } ],
        },
        {
          npcLines: [
            "I see. Let me take a look... It looks like a mild infection. I'll prescribe some medicine for you.",
            "Okay, let's check... It seems to be a throat infection. Nothing serious — I'll write you a prescription.",
            "Hmm, your throat is a bit red. It's a mild infection, easily treated with medicine.",
          ],
          npcZh: "我看看……是轻微感染。我给你开点药。",
          task: "询问药怎么吃",
          options: [
            { text: "Thank you. How should I take the medicine?", ok: true,  tip: "How should I take...——问服药方法的标准句" },
            { text: "Medicine how eat when?",                    ok: false, tip: "吃药用 take medicine，不用 eat" },
            { text: "I eat the pill how many time?",             ok: false, tip: "更自然：How should I take the medicine?" },
          ],
          phrase: { en: "How should I take the medicine?", zh: "这药我怎么吃？", note: "take medicine 是固定搭配，问药用 how" },
        },
      ],
    },
