// 图书馆场景头 + v1-v3 词条（34 个，lib- 前缀）
{
  id: "library",
  name: "图书馆",
  nameEn: "Library",
  emoji: "📚",
  iconId: "books",
  cover: "📚🤫✨",
  theme: "library",
  accent: "#3d6b5e",
  accentSoft: "#e2efe9",
  deco: "📖",
  deco2: "安静",
  intro: "办借书证、找书借书、预约自习——图书馆的每个环节都有地道表达，还有独特的安静文化。一次学会图书馆英语！",
  orderLabel: "📚 借阅进度",
  items: [
    { id: "lib-card",     en: "library card",   zh: "借书证", phon: "/ˈlaɪbrəri kɑːd/", emoji: "💳", sent: "I'd like to get a library card." },
    { id: "lib-apply",    en: "apply for",      zh: "申请", phon: "/əˈplaɪ fɔː/", emoji: "📝", sent: "How do I apply for a card?" },
    { id: "lib-proof",    en: "proof of address", zh: "住址证明", phon: "/pruːf əv əˈdres/", emoji: "🏠", sent: "You need proof of address." },
    { id: "lib-borrow",   en: "borrow",         zh: "借（入）", phon: "/ˈbɒrəʊ/", emoji: "🫳", sent: "You can borrow up to ten books." },
    { id: "lib-loan",     en: "loan",           zh: "借出；借期", phon: "/ləʊn/", emoji: "📅", sent: "The loan period is three weeks." },
    { id: "lib-renew",    en: "renew",          zh: "续借", phon: "/rɪˈnjuː/", emoji: "🔄", sent: "Can I renew this book online?" },
    { id: "lib-due",      en: "due",            zh: "到期（应还）", phon: "/djuː/", emoji: "⏰", sent: "When is it due back?" },
    { id: "lib-return",   en: "return",         zh: "归还", phon: "/rɪˈtɜːn/", emoji: "↩️", sent: "I'm here to return some books." },
    { id: "lib-checkout", en: "check out",      zh: "借出（图书馆）", phon: "/tʃek aʊt/", emoji: "✅", sent: "You can check out five at a time." },
    { id: "lib-catalog",  en: "catalog",        zh: "馆藏目录", phon: "/ˈkætəlɒɡ/", emoji: "🗂️", sent: "Search the catalog first." },
    { id: "lib-search",   en: "search",         zh: "检索，搜索", phon: "/sɜːtʃ/", emoji: "🔎", sent: "Search by title or author." },
    { id: "lib-title",    en: "title",          zh: "书名", phon: "/ˈtaɪtl/", emoji: "🔤", sent: "I forgot the title of the book." },
    { id: "lib-author",   en: "author",         zh: "作者", phon: "/ˈɔːθə/", emoji: "✍️", sent: "Do you know the author's name?" },
    { id: "lib-shelf",    en: "shelf",          zh: "书架", phon: "/ʃelf/", emoji: "🗄️", sent: "The book is on the third shelf." },
    { id: "lib-aisle",    en: "stacks",         zh: "书库书架区", phon: "/stæks/", emoji: "📚", sent: "The history books are in the stacks." },
    { id: "lib-callnum",  en: "call number",    zh: "索书号", phon: "/ˈkɔːl ˈnʌmbə/", emoji: "🔖", sent: "Write down the call number." },
    { id: "lib-selfcheck",en: "self-checkout machine", zh: "自助借书机", phon: "/self ˈtʃekaʊt məˈʃiːn/", emoji: "🤖", sent: "Use the self-checkout machine to borrow." },
    { id: "lib-desk",     en: "front desk",     zh: "服务台", phon: "/frʌnt desk/", emoji: "🏛️", sent: "Ask at the front desk." },
    { id: "lib-notify",   en: "notify",         zh: "通知", phon: "/ˈnəʊtɪfaɪ/", emoji: "🔔", sent: "We'll notify you when it's ready." },
    { id: "lib-hold",     en: "place a hold",   zh: "预约（图书）", phon: "/pleɪs ə həʊld/", emoji: "🤙", sent: "I'd like to place a hold on this book." },
    { id: "lib-ready",    en: "ready for pickup", zh: "可取", phon: "/ˈredi fɔː ˈpɪkʌp/", emoji: "📦", sent: "Your hold is ready for pickup." },
    { id: "lib-dvd",      en: "DVD",            zh: "影碟", phon: "/ˌdiː viː ˈdiː/", emoji: "📀", sent: "DVDs are on the second floor." },
    { id: "lib-fiction",  en: "fiction",        zh: "小说（虚构）", phon: "/ˈfɪkʃn/", emoji: "📕", sent: "Fiction is arranged by the author's last name." },
    { id: "lib-nonfic",   en: "nonfiction",     zh: "非虚构", phon: "/ˌnɒnˈfɪkʃn/", emoji: "📘", sent: "Nonfiction uses call numbers." },
    { id: "lib-silent",   en: "quiet zone",     zh: "安静区", phon: "/ˈkwaɪət zəʊn/", emoji: "🤫", sent: "The third floor is a quiet zone." },
    { id: "lib-study",    en: "study room",     zh: "自习室", phon: "/ˈstʌdi ruːm/", emoji: "🚪", sent: "Book a study room for two hours." },
    { id: "lib-booking",  en: "book a room",    zh: "预订房间", phon: "/bʊk ə ruːm/", emoji: "📅", sent: "Can I book a room for tomorrow?" },
    { id: "lib-overdue",  en: "overdue",        zh: "逾期的", phon: "/ˌəʊvəˈdjuː/", emoji: "🚨", sent: "This book is two days overdue." },
    { id: "lib-fine",     en: "fine",           zh: "罚款", phon: "/faɪn/", emoji: "💸", sent: "There's a small fine for late returns." },
    { id: "lib-waive",    en: "waive",          zh: "免除", phon: "/weɪv/", emoji: "🙏", sent: "Can you waive the fine this once?" },
    { id: "lib-lost",     en: "lost",           zh: "丢失的", phon: "/lɒst/", emoji: "😱", sent: "I think I lost a library book." },
    { id: "lib-replace",  en: "replacement fee", zh: "赔偿费", phon: "/rɪˈpleɪsmənt fiː/", emoji: "💰", sent: "The replacement fee is twenty dollars." },
    { id: "lib-damage",   en: "damaged",        zh: "损坏的", phon: "/ˈdæmɪdʒd/", emoji: "🩹", sent: "The book came back damaged." },
    { id: "lib-spill",    en: "spill",          zh: "洒，溅出", phon: "/spɪl/", emoji: "🥤", sent: "Sorry, I spilled coffee on a book." },
    { id: "lib-cite",     en: "citation",       zh: "引文，引用", phon: "/saɪˈteɪʃn/", emoji: "📑", sent: "Check your citation format." },
    { id: "lib-plagiarize",en: "plagiarize",    zh: "抄袭", phon: "/ˈpleɪdʒəraɪz/", emoji: "🚫", sent: "Plagiarism can get you expelled." },
    { id: "lib-database", en: "database",       zh: "数据库", phon: "/ˈdeɪtəbeɪs/", emoji: "🗄️", sent: "Search the academic databases first." }
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 办证与借书",
      titleEn: "Getting a Card & Checking Out",
      emoji: "💳",
      desc: "第一次来图书馆：办借书证、查目录、找书架、自助借书——完整走一遍借书流程。",
      reward: { en: "library card", zh: "你拿到了借书证并借出第一本书！💳" },
      steps: [
        {
          npcLines: [
            "Hi there! Welcome to the library. How can I help you today?",
            "Good afternoon! First time here? What can I do for you?",
            "Hello! Welcome in — what brings you to the library?",
          ],
          npcZh: "您好！欢迎来到图书馆。今天有什么可以帮您？",
          task: "说明来意：办一张借书证",
          options: [
            { text: "Hi! I'd like to get a library card, please.", ok: true,  tip: "I'd like to get a library card 办证标准句；library card 借书证" },
            { text: "I want book permission paper.",               ok: false, tip: "借书证是 library card：I'd like to get a library card" },
            { text: "Give me all the books. For free. Forever.",   ok: false, tip: "先办证：get a library card" },
          ],
          phrase: { en: "I'd like to get a library card.", zh: "我想办一张借书证。", note: "get/apply for a library card 都地道；办证是使用图书馆的第一步" },
        },
        {
          npcLines: [
            "Great choice! Do you have proof of address with you — a bill or a lease?",
            "Perfect! I just need proof of address. A utility bill works.",
            "Wonderful! May I see proof of address, like a bill or lease?",
          ],
          npcZh: "好选择！您带住址证明了吗——账单或租约都行？",
          task: "出示证件并递上",
          options: [
            { text: "Sure, here's my lease and my ID.", ok: true,  tip: "Here's my lease 递证件标准动作；proof of address 住址证明" },
            { text: "Address? I live here. Just look at me.", ok: false, tip: "出示文件：Here's my lease and my ID" },
            { text: "What's a lease? I pay cash for everything.", ok: false, tip: "递上能证明住址的文件：lease / bill / ID" },
          ],
          phrase: { en: "Here's my ___ and my ID.", zh: "这是我的……和身份证件。", note: "办证/办手续万能递件句；Here you are 也可以" },
        },
        {
          npcLines: [
            "All set! Here's your card. You can borrow up to ten items at a time.",
            "You're all set! Ten items at once with this card.",
            "Here you go — one library card! The limit is ten items at a time.",
          ],
          npcZh: "办好了！这是您的卡。一次最多可以借十件。",
          task: "询问借期多长",
          options: [
            { text: "Ten items, great! How long is the loan period?", ok: true, tip: "loan period 借期——借书必问" },
            { text: "Ten? Can I borrow a hundred?", ok: false, tip: "先问借期：How long is the loan period?" },
            { text: "Loan? I will return them never.", ok: false, tip: "礼貌询问借期：How long is the loan period?" },
          ],
          phrase: { en: "How long is the loan period?", zh: "借期是多长时间？", note: "loan /ləʊn/ 在图书馆语境 = 借出、借期" },
        },
        {
          npcLines: [
            "Three weeks, and you can renew twice if no one's waiting. Looking for anything today?",
            "Three weeks with two renewals. Are you after a particular book?",
            "Three weeks, renewable twice. What are you looking for today?",
          ],
          npcZh: "三周，无人预约可续借两次。今天想找什么书吗？",
          task: "说明想找的书：一本小说，忘了书名，记得作者",
          options: [
            { text: "I'm looking for a novel. I forgot the title, but I remember the author.", ok: true, tip: "I forgot the title, but I remember the author 检索信息不全时的标准表达" },
            { text: "A book. A good one. You choose.",  ok: false, tip: "提供线索：title 书名 / author 作者" },
            { text: "The book with the red cover. Famous one.", ok: false, tip: "检索要靠 title 或 author，颜色封面查不到" },
          ],
          phrase: { en: "I'm looking for a book about / by ___.", zh: "我在找一本关于……/……写的书。", note: "look for = 寻找；about 主题 / by 作者，两个检索维度" },
        },
        {
          npcLines: [
            "No problem — let's search the catalog by author... Found it! The call number is FIC C-H-E.",
            "We can do that! Searching by author... There it is. FIC C-H-E, in the fiction stacks.",
            "Easy! The catalog lists it under the author. Call number FIC C-H-E.",
          ],
          npcZh: "没问题——按作者检索目录……找到了！索书号是 FIC C-H-E。",
          task: "确认信息并询问去哪里找",
          options: [
            { text: "Got it, FIC C-H-E. Which floor are the fiction stacks on?", ok: true, tip: "复述 call number 索书号 + 问楼层——找书两步走" },
            { text: "F-C-C? Okay, whatever that means.", ok: false, tip: "复述确认索书号：FIC C-H-E, which floor?" },
            { text: "Just bring me the book. My feet are tired.", ok: false, tip: "自助找书是惯例：Which floor are the stacks on?" },
          ],
          phrase: { en: "Which floor is ___ on?", zh: "……在几楼？", note: "馆藏分区问法：fiction stacks / nonfiction / DVDs 各有楼层" },
        },
        {
          npcLines: [
            "Second floor, past the reading tables. You can check out at the front desk or the self-checkout machine.",
            "Second floor! On your way back, borrow at the desk or the self-checkout machine.",
            "Up one floor. When you're ready, the self-checkout machines are right by the stairs.",
          ],
          npcZh: "二楼，穿过阅读区。可以在服务台或自助借书机办理借出。",
          task: "找到书后去自助机借出（表达求助）",
          options: [
            { text: "Excuse me, how do I use the self-checkout machine?", ok: true, tip: "how do I use... 求助万能句；self-checkout machine 自助借书机" },
            { text: "This machine is broken. It hates me.",  ok: false, tip: "礼貌求助：Excuse me, how do I use this machine?" },
            { text: "I will just take the book home. Trust system.", ok: false, tip: "必须办理借出：How do I use the self-checkout machine?" },
          ],
          phrase: { en: "Excuse me, how do I use this?", zh: "打扰一下，这个怎么用？", note: "对机器/流程不熟时的万能求助句" },
        },
        {
          npcLines: [
            "Easy! Scan your card, then the book's barcode — and done. Due date is printed on the receipt.",
            "Super simple: card first, then the barcode on the back cover. Your receipt shows the due date.",
            "Scan your card, lay the book flat, scan the barcode. The due date prints right out.",
          ],
          npcZh: "很简单！先扫您的卡，再扫书的条码——就好了。收据上印着应还日期。",
          task: "操作成功，确认应还日期",
          options: [
            { text: "All done — due on the 21st. Thanks so much for your help!", ok: true, tip: "复述 due date 应还日期 + 道谢收尾" },
            { text: "Twenty-one? Twenty-one what? Dogs? Years?", ok: false, tip: "确认日期：Due on the 21st, got it" },
            { text: "Receipt goes in the trash. Bye machine.",   ok: false, tip: "收据记日期：Thanks so much for your help!" },
          ],
          phrase: { en: "When is it due back?", zh: "这本书应该什么时候还？", note: "due = 到期应还；借书核心三问之一" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 预约热门书",
      titleEn: "Placing a Hold",
      emoji: "🤙",
      desc: "想借的书全被借走了？学会预约（place a hold）、等通知、到馆取书——热门书这样借。",
      reward: { en: "place a hold", zh: "你学会了预约热门书，不用白跑！🤙" },
      steps: [
        {
          npcLines: [
            "Welcome back! What can I do for you today?",
            "Hi again! Back for more books?",
            "Good to see you again! What are we looking for today?",
          ],
          npcZh: "欢迎回来！今天有什么可以帮您？",
          task: "说明来意：找一本烹饪书",
          options: [
            { text: "Hi! I'm looking for a cookbook — the Italian one that everyone's talking about.", ok: true, tip: "I'm looking for... + 描述书的特征，馆员帮你查" },
            { text: "The famous book. Cooking one. Hurry.",  ok: false, tip: "礼貌+信息：I'm looking for a cookbook about Italian food" },
            { text: "I want the book that everyone has but me.", ok: false, tip: "说出具体类型：I'm looking for a cookbook" },
          ],
          phrase: { en: "I'm looking for ___.", zh: "我在找……。", note: "找书万能开场；配上书名/类型/作者更高效" },
        },
        {
          npcLines: [
            "Oh, that one! Let me check the catalog... All copies are checked out right now. The wait is about two weeks.",
            "The famous Italian cookbook! Good news and bad news — it's super popular. Every copy is out.",
            "Let me look... Yep, all copies are borrowed. It's a hot one right now!",
          ],
          npcZh: "哦，那本！我查查目录……现在所有副本都借出去了。等待期大约两周。",
          task: "询问能否预约排队",
          options: [
            { text: "That's okay — can I place a hold on it?", ok: true,  tip: "place a hold 预约排队——热门书标准操作" },
            { text: "Two weeks?! I will cry in the corner now.", ok: false, tip: "预约排队：Can I place a hold on it?" },
            { text: "Tell the borrowers to give it back today.", ok: false, tip: "图书馆管不了别人：place a hold 排队等" },
          ],
          phrase: { en: "Can I place a hold on it?", zh: "我可以预约这本书吗？", note: "hold = 预留；place/put a hold on 都地道" },
        },
        {
          npcLines: [
            "Of course! I just need your card... Done. You're number three in line.",
            "Absolutely — scanning your card... There, you're third on the waitlist.",
            "Sure thing! You're number three in the queue. It'll move fast, I promise.",
          ],
          npcZh: "当然可以！扫一下您的卡……好了，您排在第三位。",
          task: "询问到书后会怎样通知",
          options: [
            { text: "Number three — got it. How will I know when it's ready?", ok: true, tip: "How will I know when...? 问通知方式" },
            { text: "Three people before me? Cancel everything.", ok: false, tip: "问通知方式：How will I know when it's ready?" },
            { text: "I will come every day and ask you. Every hour.", ok: false, tip: "不用跑腿：会自动通知，How will I know?" },
          ],
          phrase: { en: "How will I know when it's ready?", zh: "到书了我怎么知道？", note: "预约后必问；图书馆一般发短信或邮件 notify" },
        },
        {
          npcLines: [
            "We'll notify you by text or email — you can pick how in your account. Holds go on the shelf behind me for seven days.",
            "You'll get a text or email — your choice. Once it's in, we keep it for a week.",
            "We'll send a notification! Books wait on the hold shelf for seven days before going to the next person.",
          ],
          npcZh: "我们会短信或邮件通知您——在账户里可以选。预约的书在后面书架保留七天。",
          task: "确认取书流程",
          options: [
            { text: "Perfect — so I come to the hold shelf with my card within seven days?", ok: true, tip: "复述流程确认理解——hold shelf 预约架 + 七天期限" },
            { text: "Seven days? I will come in seven months.", ok: false, tip: "确认期限：within seven days, right?" },
            { text: "Text me the book itself. Books fit in phones.", ok: false, tip: "取书流程：到馆 hold shelf + 出示卡" },
          ],
          phrase: { en: "Just to confirm, ___.", zh: "确认一下，……。", note: "复述关键流程防误会——办事标准动作" },
        },
        {
          npcLines: [
            "Exactly! Anything else today? Our cookbook section is right over there, by the way — other titles are available now.",
            "That's it! And hey, the cookbook shelf's right there if you want something to read while you wait.",
            "You got it! By the way, other cookbooks are on shelf three — no waiting on those.",
          ],
          npcZh: "正是！今天还有其他需要吗？顺便说，烹饪书区就在那边——其他书现在就能借。",
          task: "顺势借一本当下能借的烹饪书",
          options: [
            { text: "Actually, yes — I'll grab a baking book while I wait for the hold. Thanks for the tip!", ok: true, tip: " Thanks for the tip 谢谢指点；顺势满足需求是高效沟通" },
            { text: "No. I only want the famous one. All or nothing.", ok: false, tip: "灵活变通：I'll grab a baking book while I wait" },
            { text: "Baking is for cowards. Real cooks boil pasta.",   ok: false, tip: "接受推荐：I'll grab one while I wait, thanks!" },
          ],
          phrase: { en: "I'll grab ___ while I wait.", zh: "等的时间我先拿……。", note: "grab = 随手拿（口语）；while I wait 表时间差" },
        },
        {
          npcLines: [
            "Smart move! That's everything on this book — enjoy your baking, and we'll text you soon!",
            "Great pick! We'll be in touch about your hold. Happy baking!",
            "Love it! You'll hear from us the moment the Italian one comes back. Enjoy!",
          ],
          npcZh: "聪明！这本书就办这些——祝您烘焙愉快，我们会尽快短信通知您！",
          task: "礼貌告别",
          options: [
            { text: "Will do — thanks so much for your help!", ok: true,  tip: "Will do 好的（答应动作）+ 道谢收尾" },
            { text: "Whatever. Textbook me the book.",         ok: false, tip: "自然告别：Thanks so much for your help!" },
            { text: "You too enjoy. Bye house of books.",      ok: false, tip: "标准收尾：Will do, thanks a lot!" },
          ],
          phrase: { en: "Will do!", zh: "好的，就这么办！", note: "答应对方建议的爽快回答，美式口语高频" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 还书与过期",
      titleEn: "Returns & Overdue Books",
      emoji: "⏰",
      desc: "还书去哪儿还？书过期了有罚款吗？逾期、丢书、损坏的处理流程全在这轮。",
      reward: { en: "fine", zh: "你搞定了过期罚款，还书流程门儿清！⏰" },
      steps: [
        {
          npcLines: [
            "Hello! What can I do for you today?",
            "Hi there! Returns? Questions? Fire away.",
            "Good afternoon! What brings you in?",
          ],
          npcZh: "您好！今天有什么可以帮您？",
          task: "说明来意：还两本书，另外有件事想问",
          options: [
            { text: "Hi! I'm returning two books — and I have a quick question about one of them.", ok: true, tip: "I'm returning... + I have a quick question——先还书再提问，结构清晰" },
            { text: "Book. Here. Take.",  ok: false, tip: "完整句：I'm returning two books" },
            { text: "These books chased me here. Keep them away.", ok: false, tip: "正常表达：I'm returning two books, and I have a question" },
          ],
          phrase: { en: "I'm returning ___.", zh: "我来还……。", note: "return 归还；I'm returning 用进行时表达当前目的" },
        },
        {
          npcLines: [
            "Perfect, I'll check those in... Hmm, this first one is three days overdue. There's a small fine — one dollar fifty.",
            "Let me scan these... Oh — this one's three days late. That's a dollar fifty.",
            "Checking them in... This first one's overdue by three days. Small fine: a dollar fifty.",
          ],
          npcZh: "好的，我登记一下……嗯，第一本逾期三天了。有个小罚款——一美元五十美分。",
          task: "道歉并询问怎么交罚款",
          options: [
            { text: "Oh, my bad — totally slipped my mind. How do I pay the fine?", ok: true,  tip: "my bad 口语认错 + slipped my mind 忘了；直接问怎么交" },
            { text: "Three days late? The book needed me more.", ok: false, tip: "认错+处理：My bad, how do I pay the fine?" },
            { text: "No fine. We are friends now, you and I.",  ok: false, tip: "逾期罚款照交：How do I pay the fine?" },
          ],
          phrase: { en: "It totally slipped my mind.", zh: "我完全忘了。", note: "slip one's mind = 忘掉（不是故意）；认错的体面说法" },
        },
        {
          npcLines: [
            "No worries — happens all the time! You can pay here by card, or online through your account.",
            "All good, it's common! Card here at the desk, or online anytime.",
            "Not a problem! Right here with a card, or online in your account — dealer's choice.",
          ],
          npcZh: "没事——这种事常发生！可以在前台刷卡，或在账户里线上支付。",
          task: "前台交罚款",
          options: [
            { text: "I'll pay here by card, please.", ok: true,  tip: "I'll pay here by card 前台刷卡付款" },
            { text: "Can I pay in spaghetti?",  ok: false, tip: "付款方式：I'll pay here by card" },
            { text: "Card online here desk now?", ok: false, tip: "完整句：I'll pay here by card, please" },
          ],
          phrase: { en: "I'll pay by card / in cash.", zh: "我刷卡/现金付款。", note: "by card 刷卡 / in cash 现金——介词不同" },
        },
        {
          npcLines: [
            "Done! Now — you mentioned a question about one of the books?",
            "All settled! What was that question you wanted to ask?",
            "Great, fine's cleared! Now, about that question of yours?",
          ],
          npcZh: "好了！那么——您说关于其中一本书有问题想问？",
          task: "坦白：另一本书洒了咖啡，问怎么处理",
          options: [
            { text: "Yes — I accidentally spilled coffee on the other book. The cover is stained. What should I do?", ok: true, tip: "spill 洒了 + stained 有污渍；主动坦白是诚信第一步" },
            { text: "The book came to me like that. Coffee rain, very sad.",  ok: false, tip: "诚实说明：I spilled coffee on it, what should I do?" },
            { text: "What other book? I see no book. I am a book ghost.",     ok: false, tip: "主动坦白：I spilled coffee on the book" },
          ],
          phrase: { en: "I accidentally spilled ___ on it.", zh: "我不小心把……洒在上面了。", note: "accidentally /ˌæksɪˈdentəli/ 不小心地；诚实+补救=好结果" },
        },
        {
          npcLines: [
            "Thanks for being honest! Let me take a look... It's mostly the cover. We'll charge a small cleaning fee — three dollars. No replacement needed.",
            "I appreciate you telling me! Hmm, the damage is minor. Just a three-dollar cleaning fee — no big deal.",
            "Honesty is the best policy! This is light damage — three bucks for cleaning and we're square.",
          ],
          npcZh: "谢谢您的诚实！我看看……主要污在封面。我们收三美元清洁费，不用赔偿整本。",
          task: "接受处理并道谢",
          options: [
            { text: "That's fair — three dollars it is. Thank you for being so understanding!", ok: true, tip: "That's fair 接受处理 + 感谢通情达理——坦白换来轻处理" },
            { text: "Three dollars?! The coffee was premium!", ok: false, tip: "接受合理处理：That's fair, thank you" },
            { text: "No pay. The stain is modern art now.",    ok: false, tip: "照章处理：Three dollars it is, thanks" },
          ],
          phrase: { en: "That's fair.", zh: "这很合理。", note: "对处理结果表示认可的爽快说法" },
        },
        {
          npcLines: [
            "You're welcome! Last thing — next time, you can use the book drop outside for returns, even when we're closed.",
            "Anytime! Oh, and heads-up: the outside book drop takes returns 24/7.",
            "My pleasure! Quick tip — the book drop by the front door works around the clock.",
          ],
          npcZh: "不客气！最后一件事——下次还书可以用门口的还书箱，闭馆后也能还。",
          task: "确认还书箱用法并告别",
          options: [
            { text: "Oh nice, the book drop — good to know. Thanks, have a great day!", ok: true, tip: "good to know 记下了；book drop 还书箱" },
            { text: "I will return books by pigeon from now on.", ok: false, tip: "实用信息：the book drop, good to know!" },
            { text: "Twenty-four seven? Math is hard.",  ok: false, tip: "自然回应：Good to know, thanks a lot!" },
          ],
          phrase: { en: "Good to know!", zh: "这信息很有用，记下了！", note: "接收新信息的地道回应；比 Thank you 更显你在认真听" },
        },
      ],
    },
    {
      id: "v4",
      title: "第 4 次光顾 · 图书馆礼仪",
      titleEn: "Library Etiquette",
      emoji: "🤫",
      desc: "安静区能不能说话？手机响了怎么办？为什么不能占座？美国图书馆的潜规则一次讲透。",
      reward: { en: "quiet zone", zh: "你掌握了图书馆潜规则，融入无声世界！🤫" },
      steps: [
        {
          npcLines: [
            "Psst — welcome! Keep it down, we're near the quiet zone. How can I help?",
            "*whispers* Hi there! This is the whisper floor. What do you need?",
            "Hey — quiet voice please! What can I do for you?",
          ],
          npcZh: "嘘——欢迎！小声点，我们在安静区旁边。有什么可以帮您？",
          task: "压低声音询问：想找能小组讨论的地方",
          options: [
            { text: "*whispers* Sorry! Is there a place where my group can talk out loud?", ok: true, tip: "顺应当下氛围（低声）+ 说明需求——情境智慧" },
            { text: "HELLO! I NEED A PLACE TO TALK VERY LOUDLY!", ok: false, tip: "在安静区要低声：Is there a place where we can talk?" },
            { text: "Why whisper? Library is basically a concert hall.", ok: false, tip: "入乡随俗压低音量，再问需求" },
          ],
          phrase: { en: "Is there a place where we can talk?", zh: "有没有可以说话的地方？", note: "quiet zone 安静区外的讨论区/自习室可以出声" },
        },
        {
          npcLines: [
            "Great question! Study rooms are on the first floor — bookable for two-hour slots. Or the café corner allows normal voices.",
            "The study rooms downstairs! Two-hour bookings, soundproof-ish. The café corner works too.",
            "Group study rooms, floor one! Reserve two-hour slots online. The café corner is the chill option.",
          ],
          npcZh: "问得好！自习室在一楼——可以预订两小时的时段。咖啡角也可以正常说话。",
          task: "预订明天的自习室",
          options: [
            { text: "A study room sounds perfect. Can I book one for tomorrow, around 2 p.m.?", ok: true, tip: "book a study room 预订自习室 + 给出时间" },
            { text: "I'll take the loudest room. The loudest you have.", ok: false, tip: "正常预订：Can I book one for tomorrow at 2 p.m.?" },
            { text: "Two hours? I need ten. Minimum.", ok: false, tip: "按规则来：two-hour slots, tomorrow around 2 p.m." },
          ],
          phrase: { en: "Can I book ___ for tomorrow?", zh: "我能预订明天……吗？", note: "book = 预订；图书馆房间、设备都能 book" },
        },
        {
          npcLines: [
            "Booked! Room 3, two to four. Now, a few house rules — food is a no-go except in the café, but covered drinks are fine.",
            "You're in — Room 3, 2 to 4! House rules: no food outside the café, but covered drinks are OK.",
            "Done! Room 3, two to four. Rules of the house: café-only food, covered drinks welcome.",
          ],
          npcZh: "订好了！三号房，两点到四点。馆规：除了咖啡区不能吃食物，但有盖的饮料可以。",
          task: "确认规则细节",
          options: [
            { text: "Got it — no food, but covered drinks are fine. And what about phone calls?", ok: true, tip: "复述规则 + 追问细节（电话）——规则确认三连" },
            { text: "So I can eat a hot dog if I whisper?",  ok: false, tip: "食物规则与音量无关：no food outside the café" },
            { text: "Rules? Books fear me. I fear nothing.", ok: false, tip: "遵守馆规：Got it — and what about phone calls?" },
          ],
          phrase: { en: "What about ___?", zh: "那……呢？", note: "追问同类事项的万能句；what about = how about" },
        },
        {
          npcLines: [
            "Calls go to the lobby or stairwell — anywhere but the reading rooms. And one more thing: please don't save seats with your stuff.",
            "Take calls in the lobby! Also — we've had issues with seat-saving. Books can't hold chairs for hours.",
            "Lobby for calls! And a gentle reminder: saving seats with bags or books is frowned upon.",
          ],
          npcZh: "打电话去大厅或楼梯间——阅读区不行。还有一件事：请别用东西占座。",
          task: "询问占座规则的具体细节（离开多久算放弃）",
          options: [
            { text: "Fair enough — so if I step away for more than, say, thirty minutes, my seat is fair game?", ok: true, tip: "fair enough 行吧 + fair game 可被他人使用——追问规则细节" },
            { text: "My laptop is my baby. It stays. Forever.",  ok: false, tip: "理解规则：if I step away, my seat is fair game?" },
            { text: "I will hire a person to sit in my seat.",   ok: false, tip: "现实做法：step away 30 分钟即视为放弃" },
          ],
          phrase: { en: "Fair enough.", zh: "有道理，行吧。", note: "对规则/解释表示接受的常用口语" },
        },
        {
          npcLines: [
            "Exactly — thirty minutes and it's anyone's game. Oh, one more cultural thing: if someone's phone goes off, just give them a look. No need to say anything.",
            "You got it! Cultural tip: a phone rings, you don't call people out — a look does the talking.",
            "That's the rule! And the unwritten one: silence violations get the polite stare, not a lecture.",
          ],
          npcZh: "正是——三十分钟后谁都能坐。还有个文化点：别人手机响了，看一眼就行，不用说什么。",
          task: "表达理解（无声社会的默契）",
          options: [
            { text: "Ha — the polite stare. I've been on the receiving end of that already!", ok: true, tip: "the polite stare 礼貌凝视 + on the receiving end 被如此对待过——幽默共情" },
            { text: "A look? I will write them a formal letter.",  ok: false, tip: "文化默契：a look does the talking 看一眼足矣" },
            { text: "I will scream at phone people. Loudly. In quiet zone.", ok: false, tip: "以噪制噪不行：the polite stare 就够了" },
          ],
          phrase: { en: "on the receiving end of ___", zh: "被……过（承受方）", note: "receive end 接收端；幽默自嘲常用" },
        },
        {
          npcLines: [
            "Ha! We've all been there. You'll fit right in here. Enjoy Room 3 tomorrow!",
            "Every one of us, friend! See you at 2 p.m. tomorrow. Happy studying!",
            "Welcome to the club! Good luck with the group project tomorrow!",
          ],
          npcZh: "哈哈，我们都经历过！您会很快融入的。明天三号房见！",
          task: "轻声道别",
          options: [
            { text: "*whispers* Thanks — see you tomorrow!", ok: true,  tip: "轻声告别呼应开场的 whisper 梗——情境闭环" },
            { text: "GOODBYE FOREVER, LIBRARY FRIEND!",      ok: false, tip: "保持低声：Thanks, see you tomorrow!" },
            { text: "Bye. I will miss this conversation loudly.", ok: false, tip: "轻声收尾：See you tomorrow!" },
          ],
          phrase: { en: "See you tomorrow!", zh: "明天见！", note: "有了明确约定（Room 3, 2 p.m.）后的自然告别" },
        },
      ],
    },
    {
      id: "v5",
      title: "第 5 次光顾 · 研究服务深潜",
      titleEn: "Research Help & Beyond",
      emoji: "🎓",
      desc: "写论文要用学术数据库？引文格式怎么标？图书馆员其实是隐藏的免费研究顾问——这轮解锁全部技能。",
      reward: { en: "citation", zh: "你解锁了图书馆员的研究外援技能！🎓" },
      steps: [
        {
          npcLines: [
            "Hi! You look like you're on a mission. How can I help?",
            "Hello! Big project energy today — what do you need?",
            "Hey there! What are we digging into today?",
          ],
          npcZh: "您好！您看起来任务在身。有什么可以帮您？",
          task: "说明需求：写课程论文，需要学术资料",
          options: [
            { text: "Hi! I'm writing a term paper and I need academic sources — not just websites.", ok: true, tip: "academic sources 学术资料；term paper 课程论文" },
            { text: "I need the smartest books. The smartest you have.",  ok: false, tip: "说明用途：I'm writing a term paper, I need academic sources" },
            { text: "Give me websites. Only the fastest websites.",       ok: false, tip: "论文要学术资料：academic sources, not just websites" },
          ],
          phrase: { en: "I'm working on a paper about ___.", zh: "我在写一篇关于……的论文。", note: "work on = 从事；先说清项目再提需求" },
        },
        {
          npcLines: [
            "Great — you'll want our research databases, then. JSTOR, ProQuest... Have you used those before?",
            "Perfect use case for the databases! JSTOR, ProQuest — familiar with them?",
            "You need scholarly articles — that's database territory. Ever used JSTOR or ProQuest?",
          ],
          npcZh: "好——那您需要我们的研究数据库，JSTOR、ProQuest……您以前用过吗？",
          task: "承认没用过，询问怎么访问",
          options: [
            { text: "Honestly, no — how do I get access to them?", ok: true, tip: "Honestly, no 坦诚 + how do I get access 怎么访问——数据库要图书馆账号" },
            { text: "Yes. I know all databases. I invented JSTOR.", ok: false, tip: "不会就问：How do I get access to them?" },
            { text: "Database? Like a data monster?",              ok: false, tip: "直接问用法：How do I get access?" },
          ],
          phrase: { en: "How do I get access to ___?", zh: "我怎么才能使用……？", note: "get access to = 获得使用权限；学术数据库多需机构订阅" },
        },
        {
          npcLines: [
            "Easy! Log in with your library card through our website — databases are free with your card. You can even use them from home.",
            "Simple: our website, log in with your card, done. Home access included, twenty-four seven.",
            "Your card is the key! Sign in on our site and every database opens up — even from your couch.",
          ],
          npcZh: "简单！用借书证登录我们的网站——数据库凭卡免费。在家也能用。",
          task: "询问找文章的具体方法",
          options: [
            { text: "That's great! Any tips for finding the right articles?", ok: true, tip: "Any tips for...? 求经验技巧——馆员最擅长的部分" },
            { text: "Free? Then everything must be bad.",  ok: false, tip: "求检索技巧：Any tips for finding the right articles?" },
            { text: "I will read all articles. All of them.", ok: false, tip: "检索要技巧：Any tips for finding the right articles?" },
          ],
          phrase: { en: "Any tips for ___?", zh: "……有什么技巧吗？", note: "求实用建议的万能句，比 How do I do it 更讨喜" },
        },
        {
          npcLines: [
            "Sure! Use quotation marks for exact phrases, filter by peer-reviewed, and check the reference lists of good articles — they lead to more good articles.",
            "Big three: quotes for exact phrases, peer-reviewed filter, and mine the reference lists. That last one's gold.",
            "Pro tips: exact phrases in quotes, peer-reviewed only, and follow the citations. One good article feeds you ten more.",
          ],
          npcZh: "当然！用引号搜精确短语，按『同行评审』筛选，再看好文章的参考文献列表——它们会引出更多好文章。",
          task: "追问引用规范（避免抄袭）",
          options: [
            { text: "Smart — I'll follow the citations. One more thing: how do I cite sources properly? I don't want to plagiarize by accident.", ok: true, tip: "cite sources 引用出处 + plagiarize 抄袭——学术诚信核心问题" },
            { text: "Citations? I will just hide my sources like a magician.", ok: false, tip: "学术诚信：How do I cite sources properly?" },
            { text: "Plagiarism is just sharing, right?",  ok: false, tip: "必须规范引用：How do I cite sources properly?" },
          ],
          phrase: { en: "How do I cite this properly?", zh: "这个要怎么规范引用？", note: "cite /saɪt/ 引用； MLA / APA 是常见引文格式" },
        },
        {
          npcLines: [
            "Excellent question! Your professor will specify a style — MLA or APA, usually. We have citation guides, and most databases generate citations automatically.",
            "So glad you asked! Check your syllabus for the style — MLA or APA. The databases can auto-generate citations, and we have print guides.",
            "The best question! Style depends on your professor — often APA or MLA. Auto-cite buttons live in every database, plus our printed guides.",
          ],
          npcZh: "问得好！教授会指定格式——通常是 MLA 或 APA。我们有引用指南，而且大多数数据库能自动生成引文。",
          task: "确认可用资源并感谢",
          options: [
            { text: "Perfect — auto-generated citations sound like a lifesaver. Where are the citation guides?", ok: true, tip: "lifesaver 救命稻草；追问资源位置" },
            { text: "My professor is a format god. I fear styles.", ok: false, tip: "务实做法：Where are the citation guides?" },
            { text: "I will cite everything. Even this conversation.", ok: false, tip: "聚焦论文需求：Where are the guides?" },
          ],
          phrase: { en: "That sounds like a lifesaver!", zh: "那真是救了我！/ 太有用了！", note: "lifesaver /ˈlaɪfseɪvə(r)/ 救命之物；夸张式感谢" },
        },
        {
          npcLines: [
            "Aisle four, reference section — help yourself. And if you get stuck at any point, ask for the research desk. That's literally our job. Good luck with the paper!",
            "Reference section, aisle four! And remember — the research desk exists for exactly this. Go crush that paper!",
            "Aisle four, right side! The research desk has your back anytime. Happy writing!",
          ],
          npcZh: "四号过道，参考区——随便取用。任何环节卡住了，就来研究服务台。这正是我们的工作。论文顺利！",
          task: "感谢并告别",
          options: [
            { text: "That's literally your job — best job ever. Thanks a million!", ok: true, tip: "幽默回应 + thanks a million 万分感谢——研究服务深潜毕业" },
            { text: "You are too kind. I will name my paper after you.",  ok: false, tip: "表达感谢：Thanks a million!" },
            { text: "Good luck to you too. With what? Unknown.",         ok: false, tip: "收下祝福并道谢：Thanks a million!" },
          ],
          phrase: { en: "Thanks a million!", zh: "万分感谢！", note: "比 Thank you 更热情的口语道谢" },
        },
      ],
    },
  ],
},
