// 图书馆场景头 + v1-v3 词条（34 个，lib- 前缀）
{
  id: "library",
  name: "图书馆",
  nameEn: "Library",
  emoji: "📚",
  iconId: "books",
  cover: "📚🤫✨",
  theme: "library",
  accent: "#3d6b5e",
  accentSoft: "#e2efe9",
  deco: "📖",
  deco2: "安静",
  intro: "办借书证、找书借书、预约自习——图书馆的每个环节都有地道表达，还有独特的安静文化。一次学会图书馆英语！",
  orderLabel: "📚 借阅进度",
  items: [
    { id: "lib-card",     en: "library card",   zh: "借书证", phon: "/ˈlaɪbrəri kɑːd/", emoji: "💳", sent: "I'd like to get a library card." },
    { id: "lib-apply",    en: "apply for",      zh: "申请", phon: "/əˈplaɪ fɔː/", emoji: "📝", sent: "How do I apply for a card?" },
    { id: "lib-proof",    en: "proof of address", zh: "住址证明", phon: "/pruːf əv əˈdres/", emoji: "🏠", sent: "You need proof of address." },
    { id: "lib-borrow",   en: "borrow",         zh: "借（入）", phon: "/ˈbɒrəʊ/", emoji: "🫳", sent: "You can borrow up to ten books." },
    { id: "lib-loan",     en: "loan",           zh: "借出；借期", phon: "/ləʊn/", emoji: "📅", sent: "The loan period is three weeks." },
    { id: "lib-renew",    en: "renew",          zh: "续借", phon: "/rɪˈnjuː/", emoji: "🔄", sent: "Can I renew this book online?" },
    { id: "lib-due",      en: "due",            zh: "到期（应还）", phon: "/djuː/", emoji: "⏰", sent: "When is it due back?" },
    { id: "lib-return",   en: "return",         zh: "归还", phon: "/rɪˈtɜːn/", emoji: "↩️", sent: "I'm here to return some books." },
    { id: "lib-checkout", en: "check out",      zh: "借出（图书馆）", phon: "/tʃek aʊt/", emoji: "✅", sent: "You can check out five at a time." },
    { id: "lib-catalog",  en: "catalog",        zh: "馆藏目录", phon: "/ˈkætəlɒɡ/", emoji: "🗂️", sent: "Search the catalog first." },
    { id: "lib-search",   en: "search",         zh: "检索，搜索", phon: "/sɜːtʃ/", emoji: "🔎", sent: "Search by title or author." },
    { id: "lib-title",    en: "title",          zh: "书名", phon: "/ˈtaɪtl/", emoji: "🔤", sent: "I forgot the title of the book." },
    { id: "lib-author",   en: "author",         zh: "作者", phon: "/ˈɔːθə/", emoji: "✍️", sent: "Do you know the author's name?" },
    { id: "lib-shelf",    en: "shelf",          zh: "书架", phon: "/ʃelf/", emoji: "🗄️", sent: "The book is on the third shelf." },
    { id: "lib-aisle",    en: "stacks",         zh: "书库书架区", phon: "/stæks/", emoji: "📚", sent: "The history books are in the stacks." },
    { id: "lib-callnum",  en: "call number",    zh: "索书号", phon: "/ˈkɔːl ˈnʌmbə/", emoji: "🔖", sent: "Write down the call number." },
    { id: "lib-selfcheck",en: "self-checkout machine", zh: "自助借书机", phon: "/self ˈtʃekaʊt məˈʃiːn/", emoji: "🤖", sent: "Use the self-checkout machine to borrow." },
    { id: "lib-desk",     en: "front desk",     zh: "服务台", phon: "/frʌnt desk/", emoji: "🏛️", sent: "Ask at the front desk." },
    { id: "lib-notify",   en: "notify",         zh: "通知", phon: "/ˈnəʊtɪfaɪ/", emoji: "🔔", sent: "We'll notify you when it's ready." },
    { id: "lib-hold",     en: "place a hold",   zh: "预约（图书）", phon: "/pleɪs ə həʊld/", emoji: "🤙", sent: "I'd like to place a hold on this book." },
    { id: "lib-ready",    en: "ready for pickup", zh: "可取", phon: "/ˈredi fɔː ˈpɪkʌp/", emoji: "📦", sent: "Your hold is ready for pickup." },
    { id: "lib-dvd",      en: "DVD",            zh: "影碟", phon: "/ˌdiː viː ˈdiː/", emoji: "📀", sent: "DVDs are on the second floor." },
    { id: "lib-fiction",  en: "fiction",        zh: "小说（虚构）", phon: "/ˈfɪkʃn/", emoji: "📕", sent: "Fiction is arranged by the author's last name." },
    { id: "lib-nonfic",   en: "nonfiction",     zh: "非虚构", phon: "/ˌnɒnˈfɪkʃn/", emoji: "📘", sent: "Nonfiction uses call numbers." },
    { id: "lib-silent",   en: "quiet zone",     zh: "安静区", phon: "/ˈkwaɪət zəʊn/", emoji: "🤫", sent: "The third floor is a quiet zone." },
    { id: "lib-study",    en: "study room",     zh: "自习室", phon: "/ˈstʌdi ruːm/", emoji: "🚪", sent: "Book a study room for two hours." },
    { id: "lib-booking",  en: "book a room",    zh: "预订房间", phon: "/bʊk ə ruːm/", emoji: "📅", sent: "Can I book a room for tomorrow?" },
    { id: "lib-overdue",  en: "overdue",        zh: "逾期的", phon: "/ˌəʊvəˈdjuː/", emoji: "🚨", sent: "This book is two days overdue." },
    { id: "lib-fine",     en: "fine",           zh: "罚款", phon: "/faɪn/", emoji: "💸", sent: "There's a small fine for late returns." },
    { id: "lib-waive",    en: "waive",          zh: "免除", phon: "/weɪv/", emoji: "🙏", sent: "Can you waive the fine this once?" },
    { id: "lib-lost",     en: "lost",           zh: "丢失的", phon: "/lɒst/", emoji: "😱", sent: "I think I lost a library book." },
    { id: "lib-replace",  en: "replacement fee", zh: "赔偿费", phon: "/rɪˈpleɪsmənt fiː/", emoji: "💰", sent: "The replacement fee is twenty dollars." },
    { id: "lib-damage",   en: "damaged",        zh: "损坏的", phon: "/ˈdæmɪdʒd/", emoji: "🩹", sent: "The book came back damaged." },
    { id: "lib-spill",    en: "spill",          zh: "洒，溅出", phon: "/spɪl/", emoji: "🥤", sent: "Sorry, I spilled coffee on a book." },
    { id: "lib-cite",     en: "citation",       zh: "引文，引用", phon: "/saɪˈteɪʃn/", emoji: "📑", sent: "Check your citation format." },
    { id: "lib-plagiarize",en: "plagiarize",    zh: "抄袭", phon: "/ˈpleɪdʒəraɪz/", emoji: "🚫", sent: "Plagiarism can get you expelled." },
    { id: "lib-database", en: "database",       zh: "数据库", phon: "/ˈdeɪtəbeɪs/", emoji: "🗄️", sent: "Search the academic databases first." }
  ],
  visits: [
