// 邮局场景头 + 词条
{
  id: "postoffice",
  name: "邮局",
  nameEn: "Post Office",
  emoji: "📮",
  iconId: "postbox",
  cover: "📮📦✉️",
  theme: "postoffice",
  accent: "#8a4b2f",
  accentSoft: "#f6e8de",
  deco: "📦",
  deco2: "邮票",
  intro: "寄包裹、寄信、取件查询——邮局的每个环节都有固定流程和地道表达。一次搞定邮寄英语！",
  orderLabel: "📮 邮寄进度",
  items: [
    { id: "po-package",   en: "package",    zh: "包裹", phon: "/ˈpækɪdʒ/", emoji: "📦", sent: "I'd like to ship this package." },
    { id: "po-ship",      en: "ship",       zh: "寄送（美式）", phon: "/ʃɪp/", emoji: "🚚", sent: "I need to ship it to New York." },
    { id: "po-scale",     en: "scale",      zh: "秤", phon: "/skeɪl/", emoji: "⚖️", sent: "Please put the package on the scale." },
    { id: "po-weight",    en: "weight",     zh: "重量", phon: "/weɪt/", emoji: "🏋️", sent: "The weight is two kilos." },
    { id: "po-fragile",   en: "fragile",    zh: "易碎的", phon: "/ˈfrædʒaɪl/", emoji: "🥛", sent: "It's fragile — please handle it with care." },
    { id: "po-cushion",   en: "cushion",    zh: "缓冲填充物", phon: "/ˈkʊʃn/", emoji: "🫧", sent: "Use bubble wrap as cushion." },
    { id: "po-label",     en: "shipping label", zh: "快递面单", phon: "/ˈʃɪpɪŋ ˈleɪbl/", emoji: "🏷️", sent: "Print the shipping label first." },
    { id: "po-form",      en: "customs form", zh: "海关申报单", phon: "/ˈkʌstəmz fɔːm/", emoji: "📝", sent: "Fill out the customs form for international mail." },
    { id: "po-declare",   en: "declare",    zh: "申报", phon: "/dɪˈkleə/", emoji: "📣", sent: "You must declare what's inside." },
    { id: "po-tracking",  en: "tracking number", zh: "追踪单号", phon: "/ˈtrækɪŋ ˈnʌmbə/", emoji: "🔎", sent: "Here's your tracking number." },
    { id: "po-envelope",  en: "envelope",   zh: "信封", phon: "/ˈenvələʊp/", emoji: "✉️", sent: "I need an envelope, please." },
    { id: "po-letter",    en: "letter",     zh: "信", phon: "/ˈletə/", emoji: "💌", sent: "I'm sending a letter to my parents." },
    { id: "po-stamp",     en: "stamp",      zh: "邮票", phon: "/stæmp/", emoji: "🎫", sent: "How much are the stamps?" },
    { id: "po-postage",   en: "postage",    zh: "邮资/邮费", phon: "/ˈpəʊstɪdʒ/", emoji: "💰", sent: "The postage is one dollar." },
    { id: "po-airmail",   en: "airmail",    zh: "航空邮件", phon: "/ˈeəmeɪl/", emoji: "✈️", sent: "Send it by airmail, please." },
    { id: "po-address",   en: "return address", zh: "回信地址", phon: "/rɪˈtɜːn əˈdres/", emoji: "🏠", sent: "Write your return address on the back." },
    { id: "po-zip",       en: "ZIP code",   zh: "邮政编码", phon: "/zɪp kəʊd/", emoji: "🔢", sent: "Don't forget the ZIP code." },
    { id: "po-pickup",    en: "pick up",    zh: "取（件）", phon: "/pɪk ʌp/", emoji: "🫳", sent: "I'm here to pick up a package." },
    { id: "po-counter",   en: "counter",    zh: "柜台", phon: "/ˈkaʊntə/", emoji: "🏛️", sent: "Please come to the counter." },
    { id: "po-notice",    en: "delivery notice", zh: "取件通知单", phon: "/dɪˈlɪvəri ˈnəʊtɪs/", emoji: "📄", sent: "I got a delivery notice in my mailbox." },
    { id: "po-sign",      en: "sign",       zh: "签名", phon: "/saɪn/", emoji: "✍️", sent: "Please sign here to confirm." },
    { id: "po-ID",        en: "ID",         zh: "身份证件", phon: "/ˌaɪ ˈdiː/", emoji: "🪪", sent: "May I see your ID, please?" },
    { id: "po-receipt",   en: "receipt",    zh: "收据", phon: "/rɪˈsiːt/", emoji: "🧾", sent: "Could I get a receipt, please?" },
    { id: "po-insure",    en: "insure",     zh: "保价/投保", phon: "/ɪnˈʃʊə/", emoji: "🛡️", sent: "I'd like to insure the package." }
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 寄包裹",
      titleEn: "Shipping a Package",
      emoji: "📦",
      desc: "给朋友寄一箱家乡零食。称重、选服务、填面单、付款——完整走一遍寄包裹流程。",
      reward: { en: "package", zh: "你用英文寄出了第一个包裹！📦" },
      steps: [
        {
          npcLines: [
            "Hi there! Welcome to the post office. What can I do for you?",
            "Good afternoon! How may I help you today?",
            "Hello! Front of the line — what are we shipping today?",
          ],
          npcZh: "您好！欢迎来到邮局。有什么可以帮您？",
          task: "说明来意：寄一个包裹",
          options: [
            { text: "Hi! I'd like to ship this package, please.", ok: true,  tip: "I'd like to ship this package 寄包裹标准句；ship = 寄送（美式最常用）" },
            { text: "I have box. Box go far away.",                ok: false, tip: "完整句：I'd like to ship this package" },
            { text: "Give me ship service for this thing.",        ok: false, tip: "ship 直接作动词：I'd like to ship this package" },
          ],
          phrase: { en: "I'd like to ship this ___.", zh: "我想寄这个……。", note: "ship 比 send 更专指物流寄送；英式也说 post a package" },
        },
        {
          npcLines: [
            "Sure! Let's put it on the scale first... Okay, it weighs two kilos.",
            "No problem. On the scale it goes... Two kilos exactly.",
            "Of course! Scale first... Looks like two kilos.",
          ],
          npcZh: "好的！先放上秤……好，重量是两公斤。",
          task: "询问可以接受的重量上限",
          options: [
            { text: "Two kilos — got it. Is there a weight limit I should know about?", ok: true, tip: "weight limit 重量上限——先问规则防白跑" },
            { text: "Two? Is that too heavy? Tell me now!",   ok: false, tip: "礼貌询问：Is there a weight limit?" },
            { text: "Kilos? I only understand pounds.",       ok: false, tip: "metric 与英制并用很常见，问规则即可" },
          ],
          phrase: { en: "Is there a weight limit?", zh: "有重量限制吗？", note: "limit = 上限；超重可以说 It's over the limit" },
        },
        {
          npcLines: [
            "Thirty kilos is the max for standard service, so you're fine. What's inside, if I may ask?",
            "You're way under the limit! Now — what's in the box?",
            "Plenty of room to spare. What are the contents?",
          ],
          npcZh: "标准服务上限三十公斤，您没问题。方便问一下里面装的是什么吗？",
          task: "如实说明内容物：零食和茶叶",
          options: [
            { text: "Just some snacks and tea — nothing fragile.", ok: true, tip: "如实申报内容物是寄件基本义务；fragile 易碎" },
            { text: "It's a secret. Don't open it, ever.",  ok: false, tip: "内容物必须如实说明：It's snacks and tea" },
            { text: "Nothing! Empty box, very light magic.", ok: false, tip: "邮局需要知道内容物：some snacks and tea" },
          ],
          phrase: { en: "Nothing fragile.", zh: "没有易碎品。", note: "fragile /ˈfrædʒaɪl/ 易碎；柜台会问 Anything fragile or liquid?" },
        },
        {
          npcLines: [
            "Snacks and tea — lovely. Where's it headed?",
            "Sounds delicious! And where is it going?",
            "Nice! Destination?",
          ],
          npcZh: "零食和茶——不错。寄到哪里？",
          task: "说明目的地：纽约，并问有哪几种服务",
          options: [
            { text: "It's going to New York. What are my shipping options?", ok: true, tip: "shipping options 服务选项——先问清再选，省钱标准动作" },
            { text: "New York. Fastest one, whatever it costs.", ok: false, tip: "先问选项比价比时效：What are my options?" },
            { text: "Far east. Very far. You figure it out.",   ok: false, tip: "给明确目的地：It's going to New York" },
          ],
          phrase: { en: "What are my shipping options?", zh: "我有哪些寄送方式可选？", note: "标准服务 vs 快递：先问时效和价格再决定" },
        },
        {
          npcLines: [
            "For two kilos: standard takes five days at eight dollars, express gets there in two days at twenty.",
            "Two choices — five days for eight bucks, or two days for twenty.",
            "We've got standard, five days, eight dollars. Express is two days, twenty dollars.",
          ],
          npcZh: "两公斤的话：标准件五天八美元，快递两天二十美元。",
          task: "选标准件，并确认是否含追踪",
          options: [
            { text: "Standard is fine. Does that come with a tracking number?", ok: true, tip: "tracking number 追踪单号——确认能否查件" },
            { text: "Standard. If it gets lost, that's fate.",   ok: false, tip: "确认追踪：Does it come with a tracking number?" },
            { text: "What is tracking? I don't need numbers.",   ok: false, tip: "追踪单号几乎必问：tracking number" },
          ],
          phrase: { en: "Does it come with a tracking number?", zh: "这个包含追踪单号吗？", note: "come with = 自带、包含；比 Is there a tracking number 更地道" },
        },
        {
          npcLines: [
            "Yes, tracking is included. Now for the label — could you spell the street name for me?",
            "Tracking's included. One more thing: spell the street name for me?",
            "Sure does! Last bit — the street name, letter by letter, please.",
          ],
          npcZh: "含追踪。接下来打面单——能帮我拼一下街道名吗？",
          task: "逐字母拼出街道名",
          options: [
            { text: "Sure — E-L-M, Elm Street. E-L-M.", ok: true,  tip: "报地址逐字母拼写：E-L-M Elm Street——拼错必丢件" },
            { text: "Elm. You know, like the tree.",    ok: false, tip: "口头描述不行，逐字母拼：E-L-M" },
            { text: "Just write Elm, everyone knows it.", ok: false, tip: "拼写要主动给出：E-L-M, Elm Street" },
          ],
          phrase: { en: "Let me spell that for you.", zh: "我来给您拼写一下。", note: "报地址/姓名主动拼说：避免同名混淆，邮局高频动作" },
        },
        {
          npcLines: [
            "Perfect. That'll be eight dollars exactly. How would you like to pay?",
            "Elm Street, got it. Eight dollars even — card or cash?",
            "All set on the label! Eight fifty... just kidding, eight flat. How are you paying?",
          ],
          npcZh: "完美。一共八美元整。您怎么付款？",
          task: "付款并索取收据",
          options: [
            { text: "Card, please. Could I get a receipt?", ok: true,  tip: "Could I get a receipt? 索取收据——寄件凭证" },
            { text: "Card. No paper, save the trees.",      ok: false, tip: "收据是寄件凭证：Could I get a receipt?" },
            { text: "Pay? I thought shipping was free.",    ok: false, tip: "服务有价，付款+要收据一气呵成" },
          ],
          phrase: { en: "Could I get a receipt?", zh: "能给我一张收据吗？", note: "receipt /rɪˈsiːt/——注意 p 不发音" },
        },
        {
          npcLines: [
            "Here's your receipt and tracking number. Anything else today?",
            "Receipt and tracking number, coming right up. Anything more I can do?",
            "One receipt, one tracking number. Have a great day — anything else?",
          ],
          npcZh: "这是您的收据和追踪单号。今天还有其他需要吗？",
          task: "告别并表示感谢",
          options: [
            { text: "That's everything. Thanks so much — have a great day!", ok: true, tip: "That's everything 收尾 + have a great day 道别" },
            { text: "Bye bye now.", ok: false, tip: "可以更完整：That's everything, thanks a lot!" },
            { text: "Money. Give money back. No.", ok: false, tip: "正常告别：Thanks so much, have a great day" },
          ],
          phrase: { en: "That's everything, thanks!", zh: "就这些了，谢谢！", note: "柜台告别万能收尾；也可说 That'll be all" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 寄信与邮票",
      titleEn: "Mailing a Letter",
      emoji: "💌",
      desc: "给爸妈手写一封信。买信封邮票、算邮资、写回信地址、选航空——复古又实用的寄信英语。",
      reward: { en: "stamp", zh: "你亲手寄出了一封国际信件！💌" },
      steps: [
        {
          npcLines: [
            "Welcome back! What brings you in today?",
            "Hey, familiar face! What can I do for you?",
            "Good to see you again! What's on the agenda?",
          ],
          npcZh: "欢迎回来！今天来办什么？",
          task: "说明来意：寄一封信到国外",
          options: [
            { text: "Hi! I'd like to mail a letter overseas.", ok: true,  tip: "mail a letter 寄信；overseas = 到国外" },
            { text: "I want to send paper to other country.",  ok: false, tip: "地道说法：mail a letter overseas" },
            { text: "One letter service please, international size.", ok: false, tip: "简单直接：I'd like to mail a letter overseas" },
          ],
          phrase: { en: "I'd like to mail a letter ___.", zh: "我想寄一封信到……。", note: "overseas / abroad 都表示国外；国际信件常配 airmail" },
        },
        {
          npcLines: [
            "Lovely — a real handwritten letter! Do you have an envelope, or do you need one?",
            "How nice, a paper letter! Got an envelope with you?",
            "Old school — I love it. Do you have your own envelope?",
          ],
          npcZh: "真好——一封真正的手写信！您有信封吗，还是需要一个？",
          task: "购买一个信封",
          options: [
            { text: "I need one, please. How much is the envelope?", ok: true, tip: "How much is...? 问价——小额消费直接礼貌询价" },
            { text: "Give envelope. Free one, I hope.",       ok: false, tip: "礼貌询价：How much is the envelope?" },
            { text: "No envelope. Use your box instead.",     ok: false, tip: "信封单独购买：I need one, please" },
          ],
          phrase: { en: "How much is the ___?", zh: "……多少钱？", note: "最基础的问价句型，任何柜台通用" },
        },
        {
          npcLines: [
            "Fifty cents for the envelope. Do you know how much postage you'll need?",
            "That'll be fifty cents. Now — do you know your postage?",
            "Fifty cents, please. Any idea how much postage this letter needs?",
          ],
          npcZh: "信封五十美分。您知道需要多少邮资吗？",
          task: "不知道邮资，请对方帮忙计算",
          options: [
            { text: "I'm not sure — could you help me figure out the postage?", ok: true, tip: "figure out 搞清楚/算出来——请柜台代算邮资" },
            { text: "You tell me. That is your job.",       ok: false, tip: "礼貌请求：Could you help me figure it out?" },
            { text: "One million stamps please.",           ok: false, tip: "如实说明：I'm not sure, could you help me?" },
          ],
          phrase: { en: "Could you help me figure out ___?", zh: "能帮我算一下……吗？", note: "figure out = 弄明白；邮局/银行/办事窗口万能句" },
        },
        {
          npcLines: [
            "Let me weigh it... One ounce, so that's a dollar twenty in postage for international airmail.",
            "On the scale... one ounce. A dollar twenty for international airmail.",
            "Weighing it now... one ounce even. A dollar twenty to fly it overseas.",
          ],
          npcZh: "我称一下……一盎司，国际航空邮件邮资一美元二十美分。",
          task: "购买邮票，顺便问邮票种类",
          options: [
            { text: "I'll take it. Do you have any special stamps, or just the standard ones?", ok: true, tip: "special stamps 纪念邮票——集邮/寄信文化彩蛋" },
            { text: "One stamp. The cheapest and ugliest one.", ok: false, tip: "可以问问种类：Do you have special stamps?" },
            { text: "Stamps are all the same, aren't they?",    ok: false, tip: "其实有纪念版：special/commemorative stamps" },
          ],
          phrase: { en: "Do you have any ___ stamps?", zh: "有……样的邮票吗？", note: "纪念邮票 = commemorative/special stamps，常比面值更好看" },
        },
        {
          npcLines: [
            "We've got a butterfly series and the standard flag stamps. Which would you like?",
            "Butterfly series or the regular flag stamps — your call!",
            "There's a butterfly series just in, or the classic flags. What'll it be?",
          ],
          npcZh: "我们有蝴蝶系列和标准国旗邮票，您要哪种？",
          task: "选择蝴蝶系列邮票",
          options: [
            { text: "Butterflies, please — they're for my parents, so I want them to look nice.", ok: true, tip: "说明选择理由让表达更自然——寄给爸妈想要好看的邮票" },
            { text: "Butterfly. Fly letter like butterfly flies.",  ok: false, tip: "正常表达理由：they're for my parents" },
            { text: "Whatever sticks the letter down best.",       ok: false, tip: "大方选择：Butterflies, please" },
          ],
          phrase: { en: "They're for my parents.", zh: "这是寄给我父母的。", note: "for + 收件人——寄东西/买礼物时说明用途的高频句" },
        },
        {
          npcLines: [
            "Sweet. Before you seal it — did you write a return address on the back?",
            "Great choice! Quick check: return address on the envelope?",
            "Butterflies coming up. One thing — does the envelope have your return address?",
          ],
          npcZh: "真贴心。封口前——您在背面写回信地址了吗？",
          task: "还没写，询问写在哪里",
          options: [
            { text: "Oh, not yet — where should I put it?", ok: true,  tip: "Where should I put it? 位置确认——回信地址通常在信封背面或左上角" },
            { text: "Return address? Is that my email?",    ok: false, tip: "return address = 回信地址，写在信封上" },
            { text: "No address. It's a mystery letter.",   ok: false, tip: "没回信地址无法退回：Where should I put it?" },
          ],
          phrase: { en: "Where should I put the return address?", zh: "回信地址写在哪里？", note: "return address 寄不出去时退回的地址——国际寄件强烈建议写" },
        },
        {
          npcLines: [
            "Top-left corner on the front, or anywhere on the back is fine. Pen's right there if you need it.",
            "Front top-left or the back — either works. There's a pen on the counter.",
            "Left corner up front, or flip it to the back. Grab that pen!",
          ],
          npcZh: "正面左上角，或者背面任何位置都行。柜台有笔可以用。",
          task: "借笔写好地址，最后确认航空标识",
          options: [
            { text: "Thanks! All done. Should I mark it 'airmail' anywhere?", ok: true, tip: "mark it airmail 标注航空——国际信件贴 AIR MAIL 标更稳妥" },
            { text: "Wrote it. Now throw letter into sky for airmail.", ok: false, tip: "航空件贴标识：Should I mark it 'airmail'?" },
            { text: "Airmail happens automatically, like magic.",  ok: false, tip: "标注 AIR MAIL：Should I mark it anywhere?" },
          ],
          phrase: { en: "Should I mark it ___?", zh: "我需要标注……吗？", note: "mark = 做标记；AIR MAIL 标识让分拣更快" },
        },
        {
          npcLines: [
            "Just drop it in the blue box outside — airmail sticker's already on the stamp. Safe travels to your letter!",
            "The blue collection box out front will do it. Your letter's ready for takeoff!",
            "Blue box, front door. Tell your parents to watch the mailbox!",
          ],
          npcZh: "投到外面的蓝色邮筒就行——航空标识已经在邮票上了。祝您的信一路顺风！",
          task: "完成寄信，感谢道别",
          options: [
            { text: "Will do. Thank you so much for your help!", ok: true,  tip: "Will do. 简洁应允 + 感谢收尾" },
            { text: "OK. Leave now.",                     ok: false, tip: "更礼貌：Will do, thank you so much!" },
            { text: "You should pay me for this letter.", ok: false, tip: "正常道谢：Thanks for your help" },
          ],
          phrase: { en: "Will do. Thanks!", zh: "好的，这就去。谢谢！", note: "Will do = 我会照做的——应允对方指示的口语高频句" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 取件与查询",
      titleEn: "Picking Up & Tracking",
      emoji: "📮",
      desc: "收到取件通知单，来邮局取一个包裹，再顺手查另一个包裹的物流。取件、核对、签收全流程。",
      reward: { en: "pick up", zh: "你用英文顺利取到了包裹！📮" },
      steps: [
        {
          npcLines: [
            "Good morning! What can I do for you?",
            "Hi there! How can I help today?",
            "Hello! What brings you in?",
          ],
          npcZh: "早上好！有什么可以帮您？",
          task: "说明来意：凭取件通知单取包裹",
          options: [
            { text: "Hi! I got a delivery notice — I'm here to pick up a package.", ok: true, tip: "delivery notice 取件通知单 + pick up 取件——取件双关键词" },
            { text: "Package! Give me my package now.",      ok: false, tip: "说明凭据：I got a delivery notice, I'm here to pick up a package" },
            { text: "The mailman kidnapped my box. Rescue it.", ok: false, tip: "正常表述：I'm here to pick up a package" },
          ],
          phrase: { en: "I'm here to pick up ___.", zh: "我来取……。", note: "pick up = 取走；也可取快递、取票、取洗好的衣服" },
        },
        {
          npcLines: [
            "Sure! Do you have the notice with you?",
            "Of course — got the notice handy?",
            "No problem. May I have your delivery notice?",
          ],
          npcZh: "好的！通知单带了吗？",
          task: "递上通知单和证件",
          options: [
            { text: "Here's the notice, and here's my ID.", ok: true,  tip: "Here's... 递物万能句——取件通常通知单+证件一起给" },
            { text: "No paper. But I am the package owner.", ok: false, tip: "取件要凭证：Here's the notice and my ID" },
            { text: "Take my face as my ID.",               ok: false, tip: "出示证件：Here's my ID" },
          ],
          phrase: { en: "Here's my ID.", zh: "这是我的证件。", note: "Here's/Here are... 递东西标准句；ID = 身份证件" },
        },
        {
          npcLines: [
            "Perfect, let me check the back... Yes, we have a package under your name. One moment.",
            "Everything checks out! There's a box waiting for you. I'll grab it.",
            "Found you in the system! One package, held at the counter. Be right back.",
          ],
          npcZh: "没问题，我查一下后面……有的，有一个以您姓名留存的包裹。稍等。",
          task: "等待时确认柜台取件的存放时长",
          options: [
            { text: "Great! Just out of curiosity — how long do you hold packages here?", ok: true, tip: "hold = 暂存；how long do you hold... 问存放期限——晚取会被退回" },
            { text: "Hurry up, I have no time for waiting.",  ok: false, tip: "取件窗口耐心等待，可顺便问：How long do you hold packages?" },
            { text: "How many years can it stay here?",       ok: false, tip: "问期限：How long do you hold packages?" },
          ],
          phrase: { en: "How long do you hold ___?", zh: "……可以存放多久？", note: "hold 暂存；包裹通常存 15 天左右，逾期退回" },
        },
        {
          npcLines: [
            "Fifteen days, then it goes back to the sender. Here's your package — just need your signature.",
            "Two weeks is the limit. Found it! Sign right here for me, please.",
            "We keep them fifteen days. And... here it is! Just sign on the line.",
          ],
          npcZh: "十五天，之后退回寄件人。您的包裹来了——请签个名。",
          task: "签收前先检查包裹是否完好",
          options: [
            { text: "Before I sign — could I check if the package is intact?", ok: true, tip: "intact 完好无损；签收前验货是正当权利" },
            { text: "Sign first, think later. Always.",  ok: false, tip: "先验后签：Could I check if it's intact?" },
            { text: "No sign. Signature is for lawyers only.", ok: false, tip: "签收确认：Could I check it first, then sign?" },
          ],
          phrase: { en: "Before I sign, could I check ___?", zh: "签字前我能先检查一下……吗？", note: "Before I sign... 先验后签——收贵重/易碎品的自我保护句" },
        },
        {
          npcLines: [
            "Of course — give it a once-over. All good? Then just sign and print your name here.",
            "Go right ahead! Looks fine? Sign on the bottom line, and print your name next to it.",
            "Absolutely, take a look. Happy with it? I just need your signature, and your name in print.",
          ],
          npcZh: "当然——您检查一下。没问题的话在这里签名，旁边再正楷写一遍姓名。",
          task: "签名并用正楷写出姓名",
          options: [
            { text: "Looks good. Signed and printed — like this?", ok: true, tip: "print (your name) = 用印刷体正楷书写（非打印）——美国签字文化" },
            { text: "I signed. My name is printed on my face.",    ok: false, tip: "print your name = 正楷誊写姓名" },
            { text: "Why write name two times? One time enough.",  ok: false, tip: "签名+正楷姓名是惯例：signed and printed" },
          ],
          phrase: { en: "Sign here and print your name.", zh: "这里签名，并在旁边正楷写姓名。", note: "print = 工整手写（非连笔）；官方表格标准要求" },
        },
        {
          npcLines: [
            "Perfect, all done! Anything else for you today?",
            "You're all set! Anything else I can help with?",
            "That does it! One more thing before you go?",
          ],
          npcZh: "完美，办好了！今天还有其他事吗？",
          task: "顺便查询另一个包裹的物流",
          options: [
            { text: "Actually yes — could you check the status of another package for me?", ok: true, tip: "check the status 查状态/进度——查物流标准句" },
            { text: "Yes. Find my other package too. It is lost, probably.", ok: false, tip: "先查状态再下结论：Could you check its status?" },
            { text: "No. Actually yes. Actually no. Bye.",       ok: false, tip: "说明需求：Could you check another package's status?" },
          ],
          phrase: { en: "Could you check the status of ___?", zh: "能帮我查一下……的状态吗？", note: "status /ˈsteɪtəs/ 状态；查物流也常说 track a package" },
        },
        {
          npcLines: [
            "Sure, do you have the tracking number handy?",
            "No problem! Tracking number, please?",
            "Happy to! Just need that tracking number.",
          ],
          npcZh: "好的，您手边有追踪单号吗？",
          task: "报出追踪单号",
          options: [
            { text: "Yes, let me read it out: 9-4-0-7-1... and the ZIP is 10001.", ok: true, tip: "read it out 读出来——数字逐位报，单号+邮编一起给" },
            { text: "The number is... some numbers. Many numbers.", ok: false, tip: "准确逐位报出：Let me read it out" },
            { text: "Tracking number is written on the package you just gave me.", ok: false, tip: "查件通常查另一个：准确报出单号" },
          ],
          phrase: { en: "Let me read it out.", zh: "我念出来。", note: "read out = 读出来；报单号/电话/账号逐位念，避免听错" },
        },
        {
          npcLines: [
            "Let's see... it says 'out for delivery' — you should get it today before six.",
            "Good news — it's on the truck! Delivery by six p.m. today.",
            "Tracking says out for delivery. Keep an ear out for the doorbell!",
          ],
          npcZh: "我看一下……显示『派送中』——今天六点前应该能送到。",
          task: "确认理解并感谢",
          options: [
            { text: "Out for delivery today — got it. Thanks so much for checking!", ok: true, tip: "复述确认 + 感谢——out for delivery = 派送中" },
            { text: "Out for... what? Explain every word.",  ok: false, tip: "复述确认即可：Out for delivery today, got it" },
            { text: "Six o'clock. I will wait forever until then.", ok: false, tip: "自然收尾：Thanks so much for checking!" },
          ],
          phrase: { en: "It's out for delivery.", zh: "包裹正在派送中。", note: "物流状态高频词：out for delivery = 已装车派送，当日可达" },
        },
      ],
    },
  ],
},
