// 邮局场景头 + 词条
{
  id: "postoffice",
  name: "邮局",
  nameEn: "Post Office",
  emoji: "📮",
  iconId: "postbox",
  cover: "📮📦✉️",
  theme: "postoffice",
  accent: "#8a4b2f",
  accentSoft: "#f6e8de",
  deco: "📦",
  deco2: "邮票",
  intro: "寄包裹、寄信、取件查询——邮局的每个环节都有固定流程和地道表达。一次搞定邮寄英语！",
  orderLabel: "📮 邮寄进度",
  items: [
    { id: "po-package",   en: "package",    zh: "包裹", phon: "/ˈpækɪdʒ/", emoji: "📦", sent: "I'd like to ship this package." },
    { id: "po-ship",      en: "ship",       zh: "寄送（美式）", phon: "/ʃɪp/", emoji: "🚚", sent: "I need to ship it to New York." },
    { id: "po-scale",     en: "scale",      zh: "秤", phon: "/skeɪl/", emoji: "⚖️", sent: "Please put the package on the scale." },
    { id: "po-weight",    en: "weight",     zh: "重量", phon: "/weɪt/", emoji: "🏋️", sent: "The weight is two kilos." },
    { id: "po-fragile",   en: "fragile",    zh: "易碎的", phon: "/ˈfrædʒaɪl/", emoji: "🥛", sent: "It's fragile — please handle it with care." },
    { id: "po-cushion",   en: "cushion",    zh: "缓冲填充物", phon: "/ˈkʊʃn/", emoji: "🫧", sent: "Use bubble wrap as cushion." },
    { id: "po-label",     en: "shipping label", zh: "快递面单", phon: "/ˈʃɪpɪŋ ˈleɪbl/", emoji: "🏷️", sent: "Print the shipping label first." },
    { id: "po-form",      en: "customs form", zh: "海关申报单", phon: "/ˈkʌstəmz fɔːm/", emoji: "📝", sent: "Fill out the customs form for international mail." },
    { id: "po-declare",   en: "declare",    zh: "申报", phon: "/dɪˈkleə/", emoji: "📣", sent: "You must declare what's inside." },
    { id: "po-tracking",  en: "tracking number", zh: "追踪单号", phon: "/ˈtrækɪŋ ˈnʌmbə/", emoji: "🔎", sent: "Here's your tracking number." },
    { id: "po-envelope",  en: "envelope",   zh: "信封", phon: "/ˈenvələʊp/", emoji: "✉️", sent: "I need an envelope, please." },
    { id: "po-letter",    en: "letter",     zh: "信", phon: "/ˈletə/", emoji: "💌", sent: "I'm sending a letter to my parents." },
    { id: "po-stamp",     en: "stamp",      zh: "邮票", phon: "/stæmp/", emoji: "🎫", sent: "How much are the stamps?" },
    { id: "po-postage",   en: "postage",    zh: "邮资/邮费", phon: "/ˈpəʊstɪdʒ/", emoji: "💰", sent: "The postage is one dollar." },
    { id: "po-airmail",   en: "airmail",    zh: "航空邮件", phon: "/ˈeəmeɪl/", emoji: "✈️", sent: "Send it by airmail, please." },
    { id: "po-address",   en: "return address", zh: "回信地址", phon: "/rɪˈtɜːn əˈdres/", emoji: "🏠", sent: "Write your return address on the back." },
    { id: "po-zip",       en: "ZIP code",   zh: "邮政编码", phon: "/zɪp kəʊd/", emoji: "🔢", sent: "Don't forget the ZIP code." },
    { id: "po-pickup",    en: "pick up",    zh: "取（件）", phon: "/pɪk ʌp/", emoji: "🫳", sent: "I'm here to pick up a package." },
    { id: "po-counter",   en: "counter",    zh: "柜台", phon: "/ˈkaʊntə/", emoji: "🏛️", sent: "Please come to the counter." },
    { id: "po-notice",    en: "delivery notice", zh: "取件通知单", phon: "/dɪˈlɪvəri ˈnəʊtɪs/", emoji: "📄", sent: "I got a delivery notice in my mailbox." },
    { id: "po-sign",      en: "sign",       zh: "签名", phon: "/saɪn/", emoji: "✍️", sent: "Please sign here to confirm." },
    { id: "po-ID",        en: "ID",         zh: "身份证件", phon: "/ˌaɪ ˈdiː/", emoji: "🪪", sent: "May I see your ID, please?" },
    { id: "po-receipt",   en: "receipt",    zh: "收据", phon: "/rɪˈsiːt/", emoji: "🧾", sent: "Could I get a receipt, please?" },
    { id: "po-insure",    en: "insure",     zh: "保价/投保", phon: "/ɪnˈʃʊə/", emoji: "🛡️", sent: "I'd like to insure the package." }
  ],
  visits: [
