// 学校场景头 + v1-v3 词条（34 个，sch- 前缀）
{
  id: "school",
  name: "学校",
  nameEn: "School",
  emoji: "🎓",
  iconId: "school",
  cover: "🎓📚✏️",
  theme: "school",
  accent: "#2f6fa3",
  accentSoft: "#e3eef7",
  deco: "🎓",
  deco2: "开学",
  intro: "新学期报到、选课、找教室、办公室时间——校园生活的每个环节都有固定流程和地道表达。",
  orderLabel: "🎓 学业进度",
  items: [
    { id: "sch-register",   en: "register",       zh: "注册（课程）", phon: "/ˈredʒɪstə/", emoji: "📝", sent: "You need to register before Friday." },
    { id: "sch-enroll",     en: "enroll in",      zh: "报名修读", phon: "/ɪnˈrəʊl ɪn/", emoji: "➕", sent: "I want to enroll in this course." },
    { id: "sch-deadline",   en: "deadline",       zh: "截止日期", phon: "/ˈdedlaɪn/", emoji: "⏳", sent: "The registration deadline is Friday." },
    { id: "sch-semester",   en: "semester",       zh: "学期", phon: "/sɪˈmestə/", emoji: "🗓️", sent: "The fall semester starts in August." },
    { id: "sch-course",     en: "course",         zh: "课程", phon: "/kɔːs/", emoji: "📘", sent: "How many courses are you taking?" },
    { id: "sch-credit",     en: "credit",         zh: "学分", phon: "/ˈkredɪt/", emoji: "🎯", sent: "This course is worth three credits." },
    { id: "sch-prereq",     en: "prerequisite",   zh: "先修课程", phon: "/ˌpriːˈrekwɪzɪt/", emoji: "🪜", sent: "Biology 101 is a prerequisite." },
    { id: "sch-schedule",   en: "schedule",       zh: "课表", phon: "/ˈʃedjuːl/", emoji: "📅", sent: "Check your schedule online." },
    { id: "sch-section",    en: "section",        zh: "课次（同一门课的不同班）", phon: "/ˈsekʃn/", emoji: "🔢", sent: "Section B meets on Tuesdays." },
    { id: "sch-waitlist",   en: "waitlist",       zh: "候补名单", phon: "/ˈweɪtlɪst/", emoji: "⏳", sent: "I'm on the waitlist for Psychology." },
    { id: "sch-full",       en: "full",           zh: "满员（课）", phon: "/fʊl/", emoji: "🚫", sent: "Sorry, that section is full." },
    { id: "sch-drop",       en: "drop",           zh: "退课", phon: "/drɒp/", emoji: "➖", sent: "You can drop the course by Monday." },
    { id: "sch-swap",       en: "swap",           zh: "换（课）", phon: "/swɒp/", emoji: "🔄", sent: "Can I swap to Section B?" },
    { id: "sch-advisor",    en: "advisor",        zh: "学业导师", phon: "/ədˈvaɪzə/", emoji: "🧑‍🏫", sent: "Talk to your advisor first." },
    { id: "sch-building",   en: "building",       zh: "教学楼", phon: "/ˈbɪldɪŋ/", emoji: "🏢", sent: "The class is in the Science Building." },
    { id: "sch-room",       en: "room number",    zh: "教室号", phon: "/ruːm ˈnʌmbə/", emoji: "🚪", sent: "What's the room number?" },
    { id: "sch-locate",     en: "find my way",    zh: "找路", phon: "/faɪnd maɪ weɪ/", emoji: "🧭", sent: "I'm trying to find my way around." },
    { id: "sch-campus",     en: "campus",         zh: "校园", phon: "/ˈkæmpəs/", emoji: "🏫", sent: "The campus is huge." },
    { id: "sch-syllabus",   en: "syllabus",       zh: "课程大纲", phon: "/ˈsɪləbəs/", emoji: "📄", sent: "Everything is in the syllabus." },
    { id: "sch-officehours",en: "office hours",   zh: "答疑时间", phon: "/ˈɒfɪs ˈaʊəz/", emoji: "🕒", sent: "Come during office hours." },
    { id: "sch-professor",  en: "professor",      zh: "教授", phon: "/prəˈfesə/", emoji: "👨‍🏫", sent: "Email your professor beforehand." },
    { id: "sch-assignment", en: "assignment",     zh: "作业", phon: "/əˈsaɪnmənt/", emoji: "📑", sent: "The assignment is due Monday." },
    { id: "sch-extension",  en: "extension",      zh: "延期", phon: "/ɪkˈstenʃn/", emoji: "📆", sent: "Can I get an extension?" },
    { id: "sch-grade",      en: "grade",          zh: "成绩；评分", phon: "/ɡreɪd/", emoji: "💯", sent: "What's your grade so far?" },
    { id: "sch-partial",    en: "partial credit", zh: "部分得分", phon: "/ˈpɑːʃl ˈkredɪt/", emoji: "🩹", sent: "You still get partial credit." },
    { id: "sch-appeal",     en: "appeal",         zh: "申诉", phon: "/əˈpiːl/", emoji: "⚖️", sent: "You have the right to appeal." },
    { id: "sch-email",      en: "formal email",   zh: "正式邮件", phon: "/ˈfɔːml ˈiːmeɪl/", emoji: "📧", sent: "Write a formal email to the professor." },
    { id: "sch-group",      en: "group project",  zh: "小组作业", phon: "/ɡruːp ˈprɒdʒekt/", emoji: "👥", sent: "We have a group project." },
    { id: "sch-freerider",  en: "free rider",     zh: "搭便车的人", phon: "/friː ˈraɪdə/", emoji: "🛋️", sent: "Talk to the professor about the free rider." },
    { id: "sch-presentation",en: "presentation",  zh: "课堂展示", phon: "/ˌpreznˈteɪʃn/", emoji: "🎤", sent: "Our presentation is on Friday." },
    { id: "sch-plagiarism", en: "academic integrity", zh: "学术诚信", phon: "/ˌækəˈdemɪk ɪnˈteɡrəti/", emoji: "🚫", sent: "Academic integrity matters." },
    { id: "sch-cite",       en: "cite",           zh: "引用", phon: "/saɪt/", emoji: "📑", sent: "Cite every source you use." },
    { id: "sch-club",       en: "club",           zh: "社团", phon: "/klʌb/", emoji: "⛹️", sent: "Join a club to make friends." },
    { id: "sch-orientation",en: "orientation",    zh: "迎新周", phon: "/ˌɔːriənˈteɪʃn/", emoji: "🎉", sent: "Orientation week is packed with events." }
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 新生报到",
      titleEn: "First Day on Campus",
      emoji: "🎉",
      desc: "迎新周第一天：报到注册、见学业导师、弄懂课表——校园生活开场全流程。",
      reward: { en: "semester", zh: "你的新学期正式开始了！🎓" },
      steps: [
        {
          npcLines: [
            "Good morning! Welcome to orientation! Are you a new student?",
            "Hi there! You look new — first day? Welcome!",
            "Welcome, welcome! New student check-in is right here. How's it going?",
          ],
          npcZh: "早上好！欢迎来到迎新周！您是新生吗？",
          task: "自我介绍：新生，来报到注册",
          options: [
            { text: "Yes, I'm a new student. Where do I register for classes?", ok: true, tip: "register for classes 选课注册——开学第一问" },
            { text: "I am new. Very new. I know nothing. Help.",  ok: false, tip: "具体提问：Where do I register for classes?" },
            { text: "New? I've been here twenty years. I just look young.", ok: false, tip: "正常报到：I'm a new student, where do I register?" },
          ],
          phrase: { en: "Where do I register for ___?", zh: "我在哪里注册……？", note: "register 注册；选课系统注册是开学第一道门槛" },
        },
        {
          npcLines: [
            "Great! Registration is all online this year, but you'll want to meet your academic advisor first. Have you been assigned one?",
            "Perfect! Everything's online now — but see your advisor before you pick anything. Do you know who your advisor is?",
            "Welcome aboard! Registration's digital this year. Step one: meet your academic advisor. Got one yet?",
          ],
          npcZh: "好的！今年注册全在线上，但您得先见学业导师。给您分配了吗？",
          task: "询问去哪见导师",
          options: [
            { text: "Not yet — where can I find them?", ok: true,  tip: "Where can I find them? 问地点——简洁直接" },
            { text: "Advisor? I make my own decisions. Alone. Forever.", ok: false, tip: "问位置：Where can I find them?" },
            { text: "Find them? They should find me. I'm new.", ok: false, tip: "主动询问：Where can I find my advisor?" },
          ],
          phrase: { en: "Where can I find ___?", zh: "我在哪能找到……？", note: "找人/找地点/找部门通用；校园日常第一句" },
        },
        {
          npcLines: [
            "Advising office, second floor of this building. Tell them your major and they'll walk you through everything. What are you studying, by the way?",
            "Upstairs, room 210! Tell them your major and they'll set you up. So — what's your major?",
            "Advising is upstairs. Say your major, they handle the rest. Which is...?",
          ],
          npcZh: "导师办公室在本栋二楼。告诉他们您的专业，他们会带您走完全部流程。顺便问，您学什么专业？",
          task: "回答专业：还没定，正在探索",
          options: [
            { text: "I'm undecided — still exploring. Is that okay?", ok: true, tip: "undecided 未定专业（美式大学常态）+ Is that okay? 求确认" },
            { text: "My major is chaos, with a minor in confusion.",  ok: false, tip: "正常回答：I'm undecided, still exploring" },
            { text: "I will decide by reading every book in the library.", ok: false, tip: "未定很正常：I'm undecided — is that okay?" },
          ],
          phrase: { en: "I'm undecided.", zh: "我还没定专业。", note: "undecided 是正式用词；约两成美国新生如此入学" },
        },
        {
          npcLines: [
            "Totally fine — half the students here started undecided! You have two years to declare. Now, one pro tip: register early. Popular classes fill up fast!",
            "Completely normal! Half of us started that way. You've got two years. Big tip: register ASAP — the good classes go quick!",
            "The most normal thing in the world! Two years to decide. Pro tip from a veteran: register early, or cry later!",
          ],
          npcZh: "完全没问题——这里一半学生入学时都没定专业！您有两年时间。一个忠告：尽早注册，热门课满得很快！",
          task: "询问注册截止时间",
          options: [
            { text: "Good to know — when's the registration deadline?", ok: true, tip: "registration deadline 注册截止——时间线必问" },
            { text: "I registered yesterday. Wait, can I register twice?", ok: false, tip: "问截止日：When's the registration deadline?" },
            { text: "Deadlines are for people with plans.",  ok: false, tip: "确认时间线：When's the deadline?" },
          ],
          phrase: { en: "When's the deadline?", zh: "截止日期是什么时候？", note: "deadline /ˈdedlaɪn/；错过它 = 进候补名单" },
        },
        {
          npcLines: [
            "Friday at five — put it in your phone right now! And join the campus tour this afternoon. It's cheesy, but you'll learn where everything is!",
            "Friday, five p.m. — set an alarm! Also: campus tour at two. It's dorky but genuinely useful!",
            "This Friday, five sharp! Phone reminder, do it now! And take the two o'clock campus tour — silly but worth it!",
          ],
          npcZh: "周五下午五点——现在就记到手机里！另外参加今天下午的校园导览。虽然有点傻，但您能知道所有地方在哪！",
          task: "答应参加，询问集合地点",
          options: [
            { text: "Alarm set! Where does the campus tour meet?", ok: true, tip: "Alarm set（提醒设好了）+ Where does it meet? 集合点" },
            { text: "Tours are for tourists. I am a scholar.", ok: false, tip: "实用主义：Where does the campus tour meet?" },
            { text: "I will find the tour by wandering. Spiritually.", ok: false, tip: "问集合点：Where does the tour meet?" },
          ],
          phrase: { en: "Where does it meet?", zh: "在哪儿集合？", note: "meet 作动词表集合地点；校园活动通用" },
        },
        {
          npcLines: [
            "Main gate, two o'clock — look for the blue umbrella! Last thing: the club fair starts tomorrow. Trust me, that's where you'll make your real friends. Enjoy your first week!",
            "Main gate, blue umbrella, two p.m.! And don't sleep on the club fair tomorrow — friendships live there. Have a great first week!",
            "Two o'clock, main gate, blue umbrella! Oh, and the club fair tomorrow? Life-changing. Go. Make friends. Be happy!",
          ],
          npcZh: "正门，两点——找蓝色雨伞！最后一件事：社团集市明天开始。相信我，真正的朋友都是在那儿交到的。第一周愉快！",
          task: "感谢并告别",
          options: [
            { text: "Blue umbrella, club fair — got it all. Thanks, you've been super helpful!", ok: true, tip: "复述两件事+道谢——信息密集时复述防遗忘" },
            { text: "Friends? I have books. Books are friends.",   ok: false, tip: "接受建议并道谢：Got it, thanks a lot!" },
            { text: "You talk too much. Just kidding. Thanks!",    ok: false, tip: "礼貌收尾：You've been super helpful!" },
          ],
          phrase: { en: "You've been super helpful!", zh: "你帮了大忙！", note: "比 Thank you 更具体的热情感谢" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 选课风波",
      titleEn: "Course Registration Drama",
      emoji: "⏳",
      desc: "想选的课满了？被塞进候补名单？想换课时段？选课系统的攻防战全在这一轮。",
      reward: { en: "waitlist", zh: "你搞定了选课危机，候补名单也不慌！⏳" },
      steps: [
        {
          npcLines: [
            "Hi! You look like a student with a schedule problem. What can I do for you?",
            "Hello! What's the crisis today — scheduling? It's always scheduling.",
            "Hey there! Registration office. What seems to be the trouble?",
          ],
          npcZh: "您好！您看起来像个被课表难住的学生。有什么可以帮您？",
          task: "说明问题：想选的心理学课满了",
          options: [
            { text: "The psychology class I need is full. Is there anything I can do?", ok: true, tip: "is full 满员 + Is there anything I can do? 还有办法吗——选课危机标准表达" },
            { text: "The class rejected me. Psychology is my enemy now.",  ok: false, tip: "客观陈述：The class is full, anything I can do?" },
            { text: "I clicked enroll. It laughed at me. Explain.",       ok: false, tip: "说明情况：The class I need is full" },
          ],
          phrase: { en: "Is there anything I can do?", zh: "我还有什么办法吗？", note: "问题无解时的黄金问句；请对方给路径" },
        },
        {
          npcLines: [
            "You can join the waitlist — number twelve right now. People do drop classes in the first two weeks, so it's not hopeless.",
            "Waitlist is the move! You'd be thirteenth... no wait, twelfth. First two weeks always shuffle.",
            "Hop on the waitlist! You're number twelve. Lots of movement happens early — people drop like flies.",
          ],
          npcZh: "您可以进候补名单——现在排第十二位。前两周常有人退课，所以不是没希望。",
          task: "确认候补机制，同时问有没有别的时段",
          options: [
            { text: "I'll join — and is there another section that's open?", ok: true, tip: "another section 另一课次——候补之外的 Plan B" },
            { text: "Number twelve? I am patient. I will wait forever.",  ok: false, tip: "找备选：Is there another section that's open?" },
            { text: "Twelve people before me? Sabotage. Pure sabotage.",  ok: false, tip: "双轨策略：Join the waitlist + ask for another section" },
          ],
          phrase: { en: "Is there another section?", zh: "有其他课次吗？", note: "section = 同一门课的不同时段/班；换时段不换课" },
        },
        {
          npcLines: [
            "Let me check... Section B is open, but it meets at eight a.m. on Tuesdays and Thursdays. Early bird special!",
            "Good news: Section B has seats! Bad news: eight a.m., Tuesday-Thursday. Are you a morning person?",
            "Section B's wide open — if you can survive 8 a.m. twice a week. Your call!",
          ],
          npcZh: "我查查……B 班还有位置，但是周二周四早上八点上课。早鸟特供！",
          task: "权衡后决定：选 B 班，同时留在候补名单",
          options: [
            { text: "Eight a.m. is rough, but I'll take it — and keep me on the waitlist too, just in case.", ok: true, tip: "rough 艰难（口语）+ just in case 以防万一——双保险策略" },
            { text: "Eight a.m.? I don't even exist at eight a.m.",  ok: false, tip: "务实选择：I'll take it, and keep me on the waitlist" },
            { text: "No. Wake me when there's a 2 p.m. option.",     ok: false, tip: "先上保险：Take Section B + stay on the waitlist" },
          ],
          phrase: { en: "Just in case.", zh: "以防万一。", note: "口语万能后缀；双保险思维的表达" },
        },
        {
          npcLines: [
            "Smart — you're set either way. Oh, and heads-up: your biology lab has a prerequisite. Did you take Bio 101 already?",
            "Done — belt and suspenders! One flag though: your bio lab needs Bio 101 first. Did you take it?",
            "All locked in! One thing on your record — the bio lab requires Bio 101 as a prerequisite. Done already?",
          ],
          npcZh: "聪明——两头都有着落。对了，提醒：您的生物实验课有先修要求。您修过生物 101 吗？",
          task: "回答：修过，询问怎么提交证明",
          options: [
            { text: "Yes, I took it at my community college. How do I get that counted?", ok: true, tip: "How do I get that counted? 怎么算学分——转学分核心问句" },
            { text: "I took something like it. Close enough?",   ok: false, tip: "转学分要正式认定：How do I get that counted?" },
            { text: "I watched a documentary about biology once.", ok: false, tip: "提交成绩单认证：How do I get it counted?" },
          ],
          phrase: { en: "How do I get that counted?", zh: "怎么让这个被认可计入？", note: "get sth. counted = 使被计入；转学分/免修认定通用" },
        },
        {
          npcLines: [
            "Send your transcript to the registrar's office — there's a form online. It takes about a week, so don't wait!",
            "Transcript to the registrar, my friend! Online form, one-week processing. Do it today, not 'eventually'!",
            "Easy: transcript plus the online form, straight to the registrar. Week-long turnaround. Sooner started, sooner done!",
          ],
          npcZh: "把成绩单发到教务处——网上有表格。大概要一周，别拖着！",
          task: "确认流程细节（表格在哪）",
          options: [
            { text: "A week — I'll do it today. Where exactly is the form on the website?", ok: true, tip: "确认表格位置——流程最后一块拼图" },
            { text: "Eventually is my middle name though.",  ok: false, tip: "行动派：I'll do it today. Where's the form?" },
            { text: "The registrar sounds like a dragon. I must slay it.", ok: false, tip: "问具体位置：Where is the form on the website?" },
          ],
          phrase: { en: "I'll do it today.", zh: "我今天就去办。", note: "I'll + 动词原形 表承诺；办事高效的人设发言" },
        },
        {
          npcLines: [
            "Student portal, under 'Records,' then 'Transfer Credits.' Big green button — you can't miss it! Anything else today?",
            "Student portal → Records → Transfer Credits. Giant green button! What else can I do for you?",
            "Portal, Records tab, Transfer Credits. The button is huge! More questions, or are we done?",
          ],
          npcZh: "学生门户，『记录』栏目，然后『转学分』。大大的绿色按钮——不会错过的！今天还有别的吗？",
          task: "复述路径并道谢告别",
          options: [
            { text: "Portal, Records, Transfer Credits — got it. That's everything. Thank you so much!", ok: true, tip: "三连复述路径 + 道谢——选课危机毕业" },
            { text: "Green button. I fear no buttons.",  ok: false, tip: "复述防遗忘：Portal, Records, Transfer Credits. Thanks!" },
            { text: "That's everything, and also nothing. Goodbye.", ok: false, tip: "确认+感谢：Got it, that's everything, thank you!" },
          ],
          phrase: { en: "That's everything.", zh: "就这些了。", note: "办事收尾万能句；配 Thank you 完整闭环" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 办公室时间与邮件礼仪",
      titleEn: "Office Hours & Email Etiquette",
      emoji: "📧",
      desc: "找教授有讲究：怎么写正式邮件？答疑时间该聊什么？错过 deadline 怎么补救？校园沟通潜规则。",
      reward: { en: "office hours", zh: "你解锁了和教授打交道的正确姿势！📧" },
      steps: [
        {
          npcLines: [
            "Hi, come on in! You look like you have a question. Office hours are exactly for this!",
            "Hello hello! Office hours, my favorite time. What's on your mind?",
            "Come in! You've got the 'I have a question' face. Fire away!",
          ],
          npcZh: "您好，请进！您看起来有问题要问。答疑时间正是干这个的！",
          task: "说明来意：关于作业的一个问题，先道歉打扰",
          options: [
            { text: "Thanks for seeing me! I have a question about the essay assignment — is this a good time?", ok: true, tip: "Is this a good time? 现在方便吗——办公室时间也要礼貌开场" },
            { text: "Sorry to bother you. I'll just stand here silently.", ok: false, tip: "自然开场：I have a question about the assignment" },
            { text: "Your office has many books. Anyway, homework.",      ok: false, tip: "直入主题：A question about the essay assignment — is this a good time?" },
          ],
          phrase: { en: "Is this a good time?", zh: "现在方便吗？", note: "打扰前确认时间的礼貌句；对方多半会说 of course" },
        },
        {
          npcLines: [
            "Perfect time! What's the question about the essay?",
            "It's always a good time for questions! What's up with the essay?",
            "The best time! Tell me about this essay problem.",
          ],
          npcZh: "正是时候！论文有什么问题？",
          task: "提问：参考文献数量要求",
          options: [
            { text: "How many sources do we need to cite? The guidelines just say 'multiple.'", ok: true, tip: "cite 引用 + 指出大纲模糊处——具体清晰的问题" },
            { text: "The essay is hard. How do I make it easy?",  ok: false, tip: "问具体标准：How many sources do we need to cite?" },
            { text: "What's an essay, really, when you think about it?", ok: false, tip: "具体提问：How many sources, and what counts as one?" },
          ],
          phrase: { en: "How many ___ do we need?", zh: "我们需要多少……？", note: "要求模糊（multiple/several）时问清数字" },
        },
        {
          npcLines: [
            "Great question! Five minimum, but I'd say eight to ten for a strong paper. Quality over quantity, though — a weak source hurts more than it helps!",
            "Five is the floor, eight to ten is the sweet spot! And pick strong sources — filler sources drag you down!",
            "Minimum five, but eight to ten shows real research! Weak sources are worse than no sources, honestly.",
          ],
          npcZh: "问得好！最少五个，但想写好论文我建议八到十个。不过质量重于数量——糟糕的引用还不如不引！",
          task: "追问：什么算好来源",
          options: [
            { text: "What counts as a strong source? I want to do this right.", ok: true, tip: "What counts as...? 什么算……——定义边界的万能问句" },
            { text: "So Wikipedia is my best friend, correct?",  ok: false, tip: "问标准：What counts as a strong source?" },
            { text: "I will cite my cousin. He is very smart.",  ok: false, tip: "问来源标准：What counts as strong?" },
          ],
          phrase: { en: "What counts as ___?", zh: "什么才算……？", note: "count as = 算作；学术/行政场景判断标准必问" },
        },
        {
          npcLines: [
            "Peer-reviewed journals, published books, reputable news. Library databases are your friend! Now, I have a meeting soon — anything else?",
            "Journals, books, solid journalism. And the library databases — gold! Okay, I've got a meeting. Last questions?",
            "Peer-reviewed stuff, books, legit news outlets. The databases through the library! I must run soon — anything else?",
          ],
          npcZh: "同行评审期刊、出版书籍、可靠新闻。图书馆数据库是您的好帮手！我马上有个会——还有其他问题吗？",
          task: "还有最后一件事：错过了一个小作业截止",
          options: [
            { text: "Just one more thing — I missed a small deadline this week. Is there any way to still submit it?", ok: true, tip: "Is there any way to still...? 还能……吗——deadline 补救标准句" },
            { text: "What meeting? Talk to me forever instead.",  ok: false, tip: "尊重对方时间：Just one more thing, I missed a deadline..." },
            { text: "I missed a deadline. My excuse is... creative.", ok: false, tip: "简洁求补救：Is there any way to still submit it?" },
          ],
          phrase: { en: "Is there any way to still ___?", zh: "还有办法……吗？", note: "any way = 任何可能；配 still 强调'为时未晚'" },
        },
        {
          npcLines: [
            "Ah, the discussion post? I accept late submissions for partial credit — seventy percent max. Submit it by tonight!",
            "The Tuesday post, right? Late is fine, but partial credit — up to a seventy. Get it in tonight!",
            "That one? I take it late with a cap at seventy percent. Tonight's the cutoff for that cutoff, ha!",
          ],
          npcZh: "啊，讨论帖？迟交我收，算部分得分——最高七十分。今晚之前交！",
          task: "感谢通融，追问以后有事怎么联系（邮件礼仪）",
          options: [
            { text: "That's more than fair — thank you! Going forward, is email the best way to reach you?", ok: true, tip: "Going forward 今后 + is email the best way 确认联系渠道" },
            { text: "Seventy percent? Justice demands one hundred.",  ok: false, tip: "接受规则并问沟通渠道：Is email the best way to reach you?" },
            { text: "I will communicate through interpretive dance.", ok: false, tip: "问联系方式：Is email the best way to reach you?" },
          ],
          phrase: { en: "Going forward, ___.", zh: "往后看的话，……。", note: "going forward = 从今以后；职场校园通用衔接词" },
        },
        {
          npcLines: [
            "Yes, email is best — and here's a pro tip: address me as 'Professor Chen,' skip the 'hey,' and lead with your course number. Professors teach four classes; we need the context!",
            "Email, always! Pro tip from the trenches: 'Dear Professor Chen,' never 'hey,' and your course code goes first. We teach four sections — help us help you!",
            "Email me! And a gift: start with 'Dear Professor Chen,' include the course number up top. We juggle hundreds of students — context is kindness!",
          ],
          npcZh: "邮件最好——送您一个忠告：称呼我『陈教授』，别用『嘿』，开头先写课程编号。教授们教四门课，我们需要背景信息！",
          task: "总结邮件三要素并道谢",
          options: [
            { text: "Dear Professor, course number, no 'hey' — got it. Thank you, this was really helpful!", ok: true, tip: "三要素复述 + 道谢——办公室时间毕业" },
            { text: "But what if my email is just one big 'hey'?",  ok: false, tip: "复述要点：Dear Professor, course number, no 'hey'" },
            { text: "Professors are people too? Shocking. Thanks!", ok: false, tip: "复述+感谢：Got it, this was really helpful!" },
          ],
          phrase: { en: "This was really helpful!", zh: "这次交流真的很有帮助！", note: "对老师/前辈表达具体受益；比 thanks 更走心" },
        },
      ],
    },
    {
      id: "v4",
      title: "第 4 次光顾 · 小组作业风波",
      titleEn: "Group Project Drama",
      emoji: "👥",
      desc: "小组作业组员玩消失？分数被拖累怎么办？presentation 紧张到发抖？团队协作全场景英语。",
      reward: { en: "group project", zh: "你扛住了小组作业，团队合作英语满级！👥" },
      steps: [
        {
          npcLines: [
            "Come in! Oh — you have the group project thousand-yard stare. What happened?",
            "Hi! That face says group project trouble. Am I right?",
            "Hello! Let me guess: group project? Take a seat, tell me everything.",
          ],
          npcZh: "请进！哦——您这是小组作业 PTSD 的眼神。怎么了？",
          task: "说明情况：组员消失了，作业周五截止",
          options: [
            { text: "You guessed it. One of my group members has gone completely silent, and the project is due Friday.", ok: true, tip: "gone completely silent 彻底失联 + due Friday 周五截止——情况汇报两要素" },
            { text: "My group is three people. Two are ghosts. I am alone.",  ok: false, tip: "说清时间线：gone silent + due Friday" },
            { text: "Group projects were invented by villains.",             ok: false, tip: "陈述事实：One member has gone silent, due Friday" },
          ],
          phrase: { en: "The project is due ___.", zh: "作业……截止。", note: "due + 时间 = 截止；最简洁的 deadline 表达" },
        },
        {
          npcLines: [
            "The classic free rider! Have you tried emailing them directly, with a clear deadline and a list of their tasks?",
            "Ah, the free rider special! Did you email them directly — tasks listed, deadline in bold?",
            "Every semester, the same story! First step: a direct email. Their tasks, their deadline, in writing.",
          ],
          npcZh: "经典搭便车！您试过直接发邮件吗——写清任务清单和截止时间？",
          task: "回答：发过两封了，石沉大海",
          options: [
            { text: "Two emails already, both ignored. It's all documented.", ok: true, tip: "both ignored 都没回 + It's all documented 都有记录——申诉前的证据意识" },
            { text: "Emails? I sent a message in a bottle.",   ok: false, tip: "说明已努力：Two emails, both ignored and documented" },
            { text: "I emails him. He no reply. English hard.", ok: false, tip: "正式表达：Two emails already, both ignored" },
          ],
          phrase: { en: "It's all documented.", zh: "这些都有记录。", note: "documented = 有书面记录；处理纠纷的底气所在" },
        },
        {
          npcLines: [
            "Perfect — that's exactly what I need to hear. Bring the emails to me and I'll reach out. If they don't respond to me by Wednesday, we redo the group split and you're not penalized for their share.",
            "Documentation! My favorite word. Forward me the emails — if they ghost me too by Wednesday, I'll restructure the groups and grade your work separately.",
            "You've done everything right! Send me the email trail. No response by Wednesday means new groups, and you'll be graded on your parts only.",
          ],
          npcZh: "很好——这正是我想听到的。把邮件转给我，我来联系他。如果他周三前连我都不回，我们就重组分组，您不用为他的部分扣分。",
          task: "确认理解：自己的分数不受影响",
          options: [
            { text: "So my grade won't suffer because of their part — that's a huge relief.", ok: true, tip: "So... 复述确认 + that's a huge relief——重大担忧解除" },
            { text: "Their part was the fun part. Now I'm sad AND stressed.", ok: false, tip: "确认关键点：My grade won't suffer, right?" },
            { text: "Grade me on my genius alone. Correct choice.",  ok: false, tip: "复述确认：So my grade won't suffer because of them?" },
          ],
          phrase: { en: "That's a huge relief.", zh: "那真是让我松了一大口气。", note: "relief /rɪˈliːf/ 放心；担忧解除的标准感叹" },
        },
        {
          npcLines: [
            "Exactly. Now, the presentation part — I saw your name as the speaker. How do you feel about presenting?",
            "Your grade is safe! One more thing: you're the presenter on Friday, yes? How do you feel about that?",
            "Not a point off your grade! So — the presentation. You're speaking? Nerves okay?",
          ],
          npcZh: "正是。还有，展示环节——我看到您是主讲人。对上台演讲感觉如何？",
          task: "坦白：紧张，特别是当众讲英语",
          options: [
            { text: "Honestly? Nervous — presenting in English in front of everyone is the hard part for me.", ok: true, tip: "Honestly? 说实话（自问自答式开场）+ 坦白具体难点" },
            { text: "I feel nothing. I am a presentation machine.",  ok: false, tip: "诚实求助：Nervous — presenting in English is the hard part" },
            { text: "My English hides when people look at me.",      ok: false, tip: "标准表达：Presenting in English is the hard part for me" },
          ],
          phrase: { en: "Honestly? ___.", zh: "说实话？……。", note: "自问自答引出真话；拉近距离的沟通技巧" },
        },
        {
          npcLines: [
            "That's so common, and you know what helps? Practice out loud — not in your head. Your notes are just safety nets. Want to run through your intro with me right now?",
            "Half my students feel that way! The fix: practice out loud, in the actual room if possible. Want to test your intro on me? Free audience!",
            "Totally normal! Speaking out loud is the only real practice. Try your opening line on me — right now, no stakes!",
          ],
          npcZh: "这太常见了，知道什么有用吗？大声练——不是在心里练。讲稿只是安全网。现在想不想对我过一遍开场白？",
          task: "现场演练开场白",
          options: [
            { text: "Okay... 'Good morning, everyone. Today we'll look at how social media changed sleep habits.'", ok: true, tip: "Good morning, everyone 开场 + 一句话说清主题——标准 presentation 开头" },
            { text: "Um... hi... so... yeah... social media... sleep... stuff.",  ok: false, tip: "完整开场：Good morning everyone, today we'll look at..." },
            { text: "Testing, one two three. Is this thing on?",    ok: false, tip: "正式演练：Today we'll look at how social media changed sleep habits" },
          ],
          phrase: { en: "Today we'll look at ___.", zh: "今天我们来看……。", note: "presentation 开场三件套：问好 + 主题句 + 预告结构" },
        },
        {
          npcLines: [
            "See? You've got this! Clear, confident, done. Do that on Friday and you'll shine. Anything else?",
            "That was excellent! Natural pace, clear thesis. Friday, same energy! More questions?",
            "Now THAT's an opening! Deliver that Friday and you're golden. Anything else on your mind?",
          ],
          npcZh: "看吧？您可以的！清晰、自信、完整。周五就这么讲，您会很出彩。还有别的吗？",
          task: "道谢告别",
          options: [
            { text: "That really boosted my confidence. Thank you so much, Professor!", ok: true,  tip: "boost my confidence 提升信心——小组作业风波毕业" },
            { text: "I came in broken and leave fixed. Thank you!",   ok: false, tip: "标准感谢：That boosted my confidence, thank you!" },
            { text: "I owe you my firstborn. Or a coffee.",           ok: false, tip: "真诚道谢：Thank you so much, Professor!" },
          ],
          phrase: { en: "That boosted my confidence.", zh: "这让我信心大增。", note: "boost = 提升；对帮助的具体反馈" },
        },
      ],
    },
    {
      id: "v5",
      title: "第 5 次光顾 · 学术诚信课",
      titleEn: "Academic Integrity",
      emoji: "⚖️",
      desc: "引用和抄袭的边界在哪？用 AI 工具算不算作弊？收到学术诚信指控怎么办？最高难度（B1+）一轮。",
      reward: { en: "academic integrity", zh: "你吃透了学术诚信规则，论文写得堂堂正正！⚖️" },
      steps: [
        {
          npcLines: [
            "Ah, come in! You emailed about an integrity question? Those are important — let's talk.",
            "Hello! Your email said 'urgent question about citations'? Pull up a chair!",
            "Right on time! You wanted to talk about academic integrity? A wise topic, truly.",
          ],
          npcZh: "啊，请进！您邮件里说有个学术诚信问题？这类问题很重要，我们聊聊。",
          task: "说明担忧：不确定引用边界在哪",
          options: [
            { text: "Yes — I want to understand where citing ends and plagiarism begins. I'm worried I might cross the line without knowing.", ok: true, tip: "where citing ends and plagiarism begins 引用与抄袭的边界——问题意识满分" },
            { text: "I copied a paragraph. It was a good paragraph. Now I panic.",  ok: false, tip: "预防式提问：Where does citing end and plagiarism begin?" },
            { text: "Plagiarism rules are confusing. Unrelated: can I borrow your essay?", ok: false, tip: "求边界认知：I might cross the line without knowing" },
          ],
          phrase: { en: "Where does ___ end and ___ begin?", zh: "……在哪里结束，……从哪里开始？", note: "边界探讨句式；学术/法律/伦理讨论通用" },
        },
        {
          npcLines: [
            "Best question a student has asked me all semester! Short version: if it's not your original idea or your original words, cite it. When in doubt, cite it.",
            "The question of the semester! Simple rule: not your idea, not your words? Cite. Unsure? Cite anyway!",
            "I love this question! The rule in one line: borrowed idea or borrowed words — cite. Still unsure? That means cite!",
          ],
          npcZh: "这是这学期学生问我的最好的问题！简版回答：如果不是您原创的观点或原创的文字，就引用。拿不准，就引用。",
          task: "追问：改写了别人的话还算吗",
          options: [
            { text: "What if I paraphrase — put it completely in my own words?", ok: true, tip: "paraphrase /ˈpærəfreɪz/ 改写——最容易被忽视的抄袭陷阱" },
            { text: "What if I change three words? Or seven words?",  ok: false, tip: "问改写规则：What if I paraphrase it?" },
            { text: "What if I memorize it and claim amnesia?",       ok: false, tip: "关键问题：Does paraphrasing still need a citation?" },
          ],
          phrase: { en: "What if I ___?", zh: "如果我……会怎样？", note: "what if 假设问句；探讨规则边界的主力句式" },
        },
        {
          npcLines: [
            "Even paraphrased ideas need citations! Changing the words doesn't change whose idea it was. And one more thing students ask about: AI tools. Using AI to write your paper is a violation here. Using it to brainstorm or check grammar? Usually fine — but check each syllabus.",
            "Paraphrase all you want — still cite! The idea belongs to someone. Now, the elephant in the room: AI. AI writing your paper? Violation. AI for brainstorming or grammar? Often fine — but every professor's syllabus differs!",
            "Paraphrasing changes words, not ownership — cite it! And since we're being honest: AI tools. AI-authored papers are violations here. AI as a brainstorm buddy or grammar check? Typically allowed — syllabus is the law, though!",
          ],
          npcZh: "就算改写了也要引用！换词不改变观点归属。还有一件学生常问的：AI 工具。用 AI 写论文在这里是违规。用它头脑风暴或查语法？一般没问题——但要看每门课的大纲。",
          task: "确认 AI 使用边界，问如何标注",
          options: [
            { text: "So AI for brainstorming is usually fine. How would I disclose that I used it?", ok: true, tip: "disclose /dɪsˈkləʊz/ 披露——透明使用是安全网" },
            { text: "So the robot does nothing? The robot is useless now?",  ok: false, tip: "问披露方式：How would I disclose that I used it?" },
            { text: "I will hide the AI. The AI and I have an understanding.", ok: false, tip: "透明使用：How do I disclose AI use?" },
          ],
          phrase: { en: "How do I disclose that ___?", zh: "我怎么说明/披露……？", note: "disclose = 披露；主动说明永远比被发现体面" },
        },
        {
          npcLines: [
            "Simple — add a line at the end: 'AI-assisted brainstorming on topic selection.' Honesty looks good on you! Now, worst-case scenario: if you ever get an integrity accusation, don't panic. You have the right to respond, and there's a formal appeal process.",
            "One sentence in your acknowledgments: 'Topic brainstormed with AI assistance.' Done! And hear me on this: an accusation isn't a verdict. You get to respond, and there's an appeals process — in writing, through the integrity office.",
            "A single honest line at the end of your paper — that's it! And should the worst happen — an accusation — remember: it's a process, not a sentence. Respond formally, appeal if needed. The system has your back when you're honest.",
          ],
          npcZh: "很简单——文末加一行：『选题阶段借助 AI 进行了头脑风暴』。诚实会让您显得更好！再说最坏情况：如果收到学术诚信指控，别慌。您有申辩权，还有正式申诉流程。",
          task: "确认：万一被误判该怎么办",
          options: [
            { text: "Good to know — and if the accusation is a misunderstanding, the appeal is where I'd explain my side?", ok: true, tip: "my side 我方说法——误判申辩的核心逻辑" },
            { text: "If accused, I will flee the country. Plan B.",  ok: false, tip: "制度内申辩：The appeal is where I'd explain my side?" },
            { text: "Accusations? I attract none. I am invisible.",  ok: false, tip: "确认流程：The appeal is where I explain my side, right?" },
          ],
          phrase: { en: "___ is where I'd ___.", zh: "……就是我……的地方。", note: "where 从句定位场景；我的主场/我的做法" },
        },
        {
          npcLines: [
            "Exactly — evidence first, calm response second. Keep your drafts; they're proof of your process! Guard them like treasure.",
            "Precisely! Evidence and composure. And those rough drafts of yours? They're receipts. Every version, dated — keep them all!",
            "That's the play! The appeal process loves documentation. Your drafts are your paper trail — never delete a single one!",
          ],
          npcZh: "正是——先摆证据，再冷静回应。保留您的草稿，那是您写作过程的证明！像宝贝一样存好。",
          task: "总结本轮收获并道谢",
          options: [
            { text: "Cite when in doubt, disclose AI use, keep my drafts — got it. Thank you, Professor. This might be the most useful conversation of my semester.", ok: true, tip: "三连复述 + 最高评价——学术诚信课毕业" },
            { text: "Rules understood. I will be extremely honest from now on. Mostly.", ok: false, tip: "复述三要点：Cite, disclose, keep drafts" },
            { text: "Most useful conversation? Higher than the pizza party?",     ok: false, tip: "真诚收尾：The most useful conversation of my semester, thank you!" },
          ],
          phrase: { en: "When in doubt, ___.", zh: "拿不准的时候，就……。", note: "when in doubt = 拿不准时；给简单规则的经典句式" },
        },
      ],
    },
  ],
},
