// 学校场景头 + v1-v3 词条（34 个，sch- 前缀）
{
  id: "school",
  name: "学校",
  nameEn: "School",
  emoji: "🎓",
  iconId: "school",
  cover: "🎓📚✏️",
  theme: "school",
  accent: "#2f6fa3",
  accentSoft: "#e3eef7",
  deco: "🎓",
  deco2: "开学",
  intro: "新学期报到、选课、找教室、办公室时间——校园生活的每个环节都有固定流程和地道表达。",
  orderLabel: "🎓 学业进度",
  items: [
    { id: "sch-register",   en: "register",       zh: "注册（课程）", phon: "/ˈredʒɪstə/", emoji: "📝", sent: "You need to register before Friday." },
    { id: "sch-enroll",     en: "enroll in",      zh: "报名修读", phon: "/ɪnˈrəʊl ɪn/", emoji: "➕", sent: "I want to enroll in this course." },
    { id: "sch-deadline",   en: "deadline",       zh: "截止日期", phon: "/ˈdedlaɪn/", emoji: "⏳", sent: "The registration deadline is Friday." },
    { id: "sch-semester",   en: "semester",       zh: "学期", phon: "/sɪˈmestə/", emoji: "🗓️", sent: "The fall semester starts in August." },
    { id: "sch-course",     en: "course",         zh: "课程", phon: "/kɔːs/", emoji: "📘", sent: "How many courses are you taking?" },
    { id: "sch-credit",     en: "credit",         zh: "学分", phon: "/ˈkredɪt/", emoji: "🎯", sent: "This course is worth three credits." },
    { id: "sch-prereq",     en: "prerequisite",   zh: "先修课程", phon: "/ˌpriːˈrekwɪzɪt/", emoji: "🪜", sent: "Biology 101 is a prerequisite." },
    { id: "sch-schedule",   en: "schedule",       zh: "课表", phon: "/ˈʃedjuːl/", emoji: "📅", sent: "Check your schedule online." },
    { id: "sch-section",    en: "section",        zh: "课次（同一门课的不同班）", phon: "/ˈsekʃn/", emoji: "🔢", sent: "Section B meets on Tuesdays." },
    { id: "sch-waitlist",   en: "waitlist",       zh: "候补名单", phon: "/ˈweɪtlɪst/", emoji: "⏳", sent: "I'm on the waitlist for Psychology." },
    { id: "sch-full",       en: "full",           zh: "满员（课）", phon: "/fʊl/", emoji: "🚫", sent: "Sorry, that section is full." },
    { id: "sch-drop",       en: "drop",           zh: "退课", phon: "/drɒp/", emoji: "➖", sent: "You can drop the course by Monday." },
    { id: "sch-swap",       en: "swap",           zh: "换（课）", phon: "/swɒp/", emoji: "🔄", sent: "Can I swap to Section B?" },
    { id: "sch-advisor",    en: "advisor",        zh: "学业导师", phon: "/ədˈvaɪzə/", emoji: "🧑‍🏫", sent: "Talk to your advisor first." },
    { id: "sch-building",   en: "building",       zh: "教学楼", phon: "/ˈbɪldɪŋ/", emoji: "🏢", sent: "The class is in the Science Building." },
    { id: "sch-room",       en: "room number",    zh: "教室号", phon: "/ruːm ˈnʌmbə/", emoji: "🚪", sent: "What's the room number?" },
    { id: "sch-locate",     en: "find my way",    zh: "找路", phon: "/faɪnd maɪ weɪ/", emoji: "🧭", sent: "I'm trying to find my way around." },
    { id: "sch-campus",     en: "campus",         zh: "校园", phon: "/ˈkæmpəs/", emoji: "🏫", sent: "The campus is huge." },
    { id: "sch-syllabus",   en: "syllabus",       zh: "课程大纲", phon: "/ˈsɪləbəs/", emoji: "📄", sent: "Everything is in the syllabus." },
    { id: "sch-officehours",en: "office hours",   zh: "答疑时间", phon: "/ˈɒfɪs ˈaʊəz/", emoji: "🕒", sent: "Come during office hours." },
    { id: "sch-professor",  en: "professor",      zh: "教授", phon: "/prəˈfesə/", emoji: "👨‍🏫", sent: "Email your professor beforehand." },
    { id: "sch-assignment", en: "assignment",     zh: "作业", phon: "/əˈsaɪnmənt/", emoji: "📑", sent: "The assignment is due Monday." },
    { id: "sch-extension",  en: "extension",      zh: "延期", phon: "/ɪkˈstenʃn/", emoji: "📆", sent: "Can I get an extension?" },
    { id: "sch-grade",      en: "grade",          zh: "成绩；评分", phon: "/ɡreɪd/", emoji: "💯", sent: "What's your grade so far?" },
    { id: "sch-partial",    en: "partial credit", zh: "部分得分", phon: "/ˈpɑːʃl ˈkredɪt/", emoji: "🩹", sent: "You still get partial credit." },
    { id: "sch-appeal",     en: "appeal",         zh: "申诉", phon: "/əˈpiːl/", emoji: "⚖️", sent: "You have the right to appeal." },
    { id: "sch-email",      en: "formal email",   zh: "正式邮件", phon: "/ˈfɔːml ˈiːmeɪl/", emoji: "📧", sent: "Write a formal email to the professor." },
    { id: "sch-group",      en: "group project",  zh: "小组作业", phon: "/ɡruːp ˈprɒdʒekt/", emoji: "👥", sent: "We have a group project." },
    { id: "sch-freerider",  en: "free rider",     zh: "搭便车的人", phon: "/friː ˈraɪdə/", emoji: "🛋️", sent: "Talk to the professor about the free rider." },
    { id: "sch-presentation",en: "presentation",  zh: "课堂展示", phon: "/ˌpreznˈteɪʃn/", emoji: "🎤", sent: "Our presentation is on Friday." },
    { id: "sch-plagiarism", en: "academic integrity", zh: "学术诚信", phon: "/ˌækəˈdemɪk ɪnˈteɡrəti/", emoji: "🚫", sent: "Academic integrity matters." },
    { id: "sch-cite",       en: "cite",           zh: "引用", phon: "/saɪt/", emoji: "📑", sent: "Cite every source you use." },
    { id: "sch-club",       en: "club",           zh: "社团", phon: "/klʌb/", emoji: "⛹️", sent: "Join a club to make friends." },
    { id: "sch-orientation",en: "orientation",    zh: "迎新周", phon: "/ˌɔːriənˈteɪʃn/", emoji: "🎉", sent: "Orientation week is packed with events." }
  ],
  visits: [
