// 网购退货场景头 + 词条
{
  id: "shopping",
  name: "网购与退货",
  nameEn: "Online Shopping & Returns",
  emoji: "📦",
  iconId: "shopping",
  cover: "📦🛒↩️",
  theme: "shopping",
  accent: "#c2571a",
  accentSoft: "#fbe8dc",
  deco: "✨",
  deco2: "📦",
  intro: "网购时代：下单前问尺码、催物流、收到残次品、无理由退货——客服英语全流程。",
  orderLabel: "📦 购物进度",
  items: [
    { id: "size",       en: "size chart",   zh: "尺码表", phon: "/saɪz tʃɑːt/", emoji: "📏", sent: "Check the size chart before ordering." },
    { id: "soldout",    en: "sold out",     zh: "售罄", phon: "/səʊld aʊt/", emoji: "🚫", sent: "Sorry, that color is sold out." },
    { id: "instock",    en: "back in stock", zh: "补货了", phon: "/bæk ɪn stɒk/", emoji: "📥", sent: "It'll be back in stock next week." },
    { id: "ship",       en: "shipping",     zh: "运费/配送", phon: "/ˈʃɪpɪŋ/", emoji: "🚚", sent: "Is shipping free over fifty dollars?" },
    { id: "track",      en: "track my order", zh: "查物流", phon: "/træk maɪ ˈɔːdə/", emoji: "📡", sent: "You can track your order online." },
    { id: "delay2",     en: "delayed",      zh: "延迟了", phon: "/dɪˈleɪd/", emoji: "⏰", sent: "My package is delayed." },
    { id: "wrongitem",  en: "wrong item",   zh: "发错货", phon: "/rɒŋ ˈaɪtəm/", emoji: "❌", sent: "They sent me the wrong item." },
    { id: "damaged",    en: "damaged",      zh: "破损的", phon: "/ˈdæmɪdʒd/", emoji: "💔", sent: "The box arrived damaged." },
    { id: "return",     en: "return policy", zh: "退货政策", phon: "/rɪˈtɜːn ˈpɒləsi/", emoji: "↩️", sent: "What's your return policy?" },
    { id: "refund",     en: "refund",       zh: "退款", phon: "/ˈriːfʌnd/", emoji: "💸", sent: "I'd like a refund, please." },
    { id: "exchange",   en: "exchange",     zh: "换货", phon: "/ɪksˈtʃeɪndʒ/", emoji: "🔄", sent: "Can I exchange it for a larger size?" },
    { id: "restockfee", en: "restocking fee", zh: "退货手续费", phon: "/ˌriːˈstɒkɪŋ fiː/", emoji: "🧾", sent: "There's no restocking fee." },
    { id: "label",      en: "return label", zh: "退货面单", phon: "/rɪˈtɜːn ˈleɪbl/", emoji: "🏷️", sent: "Print the return label and tape it on the box." },
    { id: "dropoff",    en: "drop-off point", zh: "代寄点", phon: "/ˈdrɒp ɒf pɔɪnt/", emoji: "📍", sent: "Take the box to any drop-off point." },
    { id: "process",    en: "process the refund", zh: "处理退款", phon: "/ˈprəʊses ðə ˈriːfʌnd/", emoji: "⚙️", sent: "We'll process the refund in three days." },
    { id: "original",   en: "original condition", zh: "原样（未使用）", phon: "/əˈrɪdʒənl kənˈdɪʃn/", emoji: "✨", sent: "Items must be in original condition." },
    { id: "review",     en: "leave a review", zh: "写评价", phon: "/liːv ə rɪˈvjuː/", emoji: "⭐", sent: "Could you leave a review?" },
    { id: "discount",   en: "discount code", zh: "折扣码", phon: "/ˈdɪskaʊnt kəʊd/", emoji: "🎟️", sent: "Enter the discount code at checkout." },
    { id: "checkout",   en: "checkout",     zh: "结账页", phon: "/ˈtʃekaʊt/", emoji: "🛍️", sent: "The discount applies at checkout." },
    { id: "confirm3",   en: "order confirmation", zh: "订单确认（邮件）", phon: "/ˈɔːdə ˌkɒnfəˈmeɪʃn/", emoji: "📧", sent: "You'll get an order confirmation email." },
    { id: "chat",       en: "live chat",    zh: "在线客服", phon: "/laɪv tʃæt/", emoji: "💬", sent: "Our live chat is open 24/7." },
    { id: "escalate",   en: "escalate the issue", zh: "升级处理（找上级）", phon: "/ˈeskəleɪt/", emoji: "⬆️", sent: "I'll need to escalate this issue to my supervisor." },
    { id: "coupon",     en: "coupon",       zh: "优惠券", phon: "/ˈkuːpɒn/", emoji: "🎫", sent: "Here's a coupon for your next order." },
    { id: "account",    en: "order number", zh: "订单号", phon: "/ˈɔːdə ˈnʌmbə/", emoji: "🔢", sent: "May I have your order number?" },
    { id: "arrive",     en: "arrive",       zh: "到达，送达", phon: "/əˈraɪv/", emoji: "📬", sent: "Your order will arrive on Tuesday." }
  ],
