// 网购退货场景头 + 词条
{
  id: "shopping",
  name: "网购与退货",
  nameEn: "Online Shopping & Returns",
  emoji: "📦",
  iconId: "shopping",
  cover: "📦🛒↩️",
  theme: "shopping",
  accent: "#c2571a",
  accentSoft: "#fbe8dc",
  deco: "✨",
  deco2: "📦",
  intro: "网购时代：下单前问尺码、催物流、收到残次品、无理由退货——客服英语全流程。",
  orderLabel: "📦 购物进度",
  items: [
    { id: "size",       en: "size chart",   zh: "尺码表", phon: "/saɪz tʃɑːt/", emoji: "📏", sent: "Check the size chart before ordering." },
    { id: "soldout",    en: "sold out",     zh: "售罄", phon: "/səʊld aʊt/", emoji: "🚫", sent: "Sorry, that color is sold out." },
    { id: "instock",    en: "back in stock", zh: "补货了", phon: "/bæk ɪn stɒk/", emoji: "📥", sent: "It'll be back in stock next week." },
    { id: "ship",       en: "shipping",     zh: "运费/配送", phon: "/ˈʃɪpɪŋ/", emoji: "🚚", sent: "Is shipping free over fifty dollars?" },
    { id: "track",      en: "track my order", zh: "查物流", phon: "/træk maɪ ˈɔːdə/", emoji: "📡", sent: "You can track your order online." },
    { id: "delay2",     en: "delayed",      zh: "延迟了", phon: "/dɪˈleɪd/", emoji: "⏰", sent: "My package is delayed." },
    { id: "wrongitem",  en: "wrong item",   zh: "发错货", phon: "/rɒŋ ˈaɪtəm/", emoji: "❌", sent: "They sent me the wrong item." },
    { id: "damaged",    en: "damaged",      zh: "破损的", phon: "/ˈdæmɪdʒd/", emoji: "💔", sent: "The box arrived damaged." },
    { id: "return",     en: "return policy", zh: "退货政策", phon: "/rɪˈtɜːn ˈpɒləsi/", emoji: "↩️", sent: "What's your return policy?" },
    { id: "refund",     en: "refund",       zh: "退款", phon: "/ˈriːfʌnd/", emoji: "💸", sent: "I'd like a refund, please." },
    { id: "exchange",   en: "exchange",     zh: "换货", phon: "/ɪksˈtʃeɪndʒ/", emoji: "🔄", sent: "Can I exchange it for a larger size?" },
    { id: "restockfee", en: "restocking fee", zh: "退货手续费", phon: "/ˌriːˈstɒkɪŋ fiː/", emoji: "🧾", sent: "There's no restocking fee." },
    { id: "label",      en: "return label", zh: "退货面单", phon: "/rɪˈtɜːn ˈleɪbl/", emoji: "🏷️", sent: "Print the return label and tape it on the box." },
    { id: "dropoff",    en: "drop-off point", zh: "代寄点", phon: "/ˈdrɒp ɒf pɔɪnt/", emoji: "📍", sent: "Take the box to any drop-off point." },
    { id: "process",    en: "process the refund", zh: "处理退款", phon: "/ˈprəʊses ðə ˈriːfʌnd/", emoji: "⚙️", sent: "We'll process the refund in three days." },
    { id: "original",   en: "original condition", zh: "原样（未使用）", phon: "/əˈrɪdʒənl kənˈdɪʃn/", emoji: "✨", sent: "Items must be in original condition." },
    { id: "review",     en: "leave a review", zh: "写评价", phon: "/liːv ə rɪˈvjuː/", emoji: "⭐", sent: "Could you leave a review?" },
    { id: "discount",   en: "discount code", zh: "折扣码", phon: "/ˈdɪskaʊnt kəʊd/", emoji: "🎟️", sent: "Enter the discount code at checkout." },
    { id: "checkout",   en: "checkout",     zh: "结账页", phon: "/ˈtʃekaʊt/", emoji: "🛍️", sent: "The discount applies at checkout." },
    { id: "confirm3",   en: "order confirmation", zh: "订单确认（邮件）", phon: "/ˈɔːdə ˌkɒnfəˈmeɪʃn/", emoji: "📧", sent: "You'll get an order confirmation email." },
    { id: "chat",       en: "live chat",    zh: "在线客服", phon: "/laɪv tʃæt/", emoji: "💬", sent: "Our live chat is open 24/7." },
    { id: "escalate",   en: "escalate the issue", zh: "升级处理（找上级）", phon: "/ˈeskəleɪt/", emoji: "⬆️", sent: "I'll need to escalate this issue to my supervisor." },
    { id: "coupon",     en: "coupon",       zh: "优惠券", phon: "/ˈkuːpɒn/", emoji: "🎫", sent: "Here's a coupon for your next order." },
    { id: "account",    en: "order number", zh: "订单号", phon: "/ˈɔːdə ˈnʌmbə/", emoji: "🔢", sent: "May I have your order number?" },
    { id: "arrive",     en: "arrive",       zh: "到达，送达", phon: "/əˈraɪv/", emoji: "📬", sent: "Your order will arrive on Tuesday." }
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 下单前咨询",
      titleEn: "Before You Order",
      emoji: "🛒",
      desc: "看中一双鞋：问尺码、问库存、问运费、找折扣码——下单前的精明买家英语。",
      reward: { en: "size chart", zh: "你解锁了下单咨询英语，网购不踩坑！🛒" },
      steps: [
        {
          npcLines: [
            "Thanks for contacting ShoeTop support! This is Maya. How can I help you today?",
            "ShoeTop live chat, Maya speaking! What can I do for you?",
            "Hi there, Maya from ShoeTop support! What's on your mind today?",
          ],
          npcZh: "感谢联系 ShoeTop 客服！我是 Maya。今天有什么可以帮您？",
          task: "询问心仪鞋款的尺码建议",
          options: [
            { text: "Hi! I'm looking at the Runner Pro shoes. I'm usually a size 9 — should I order my usual size, or size up?", ok: true,  tip: "size up 买大一号——网购鞋服关键问题" },
            { text: "Shoes! Feet! Number nine! Correct?!",         ok: false, tip: "问尺码建议：Should I order my usual size, or size up?" },
            { text: "Size 9 always fits all humans of size 9.",    ok: false, tip: "不同品牌尺码有差：Should I size up?" },
          ],
          phrase: { en: "Should I size up?", zh: "我要买大一号吗？", note: "size up 大一号 / size down 小一号；网购鞋服必问" },
        },
        {
          npcLines: [
            "Great question! The Runner Pro runs a little small — most customers size up half a size. I'd go with nine and a half for you!",
            "Heads-up: Runner Pros run small! Nine and a half is your safest bet based on the size chart.",
            "Good instinct to ask — this model runs small! The size chart says nine and a half for a true nine.",
          ],
          npcZh: "问得好！Runner Pro 偏小——多数客户会买大半码。建议您选 9.5 码！",
          task: "询问喜欢的颜色是否有货",
          options: [
            { text: "Perfect, nine and a half it is. Is the navy blue still in stock?", ok: true,  tip: "in stock 有货——下单前确认库存" },
            { text: "Navy blue shoes exist? Yes no maybe?",       ok: false, tip: "问库存：Is the navy blue still in stock?" },
            { text: "Stock check please. Blue navy color. Or navy blue. Same thing.", ok: false, tip: "标准问法：Is it still in stock?" },
          ],
          phrase: { en: "Is it still in stock?", zh: "还有货吗？", note: "in stock 有货 / sold out 售罄 / back in stock 补货" },
        },
        {
          npcLines: [
            "Oh, I'm sorry — navy is sold out right now! It'll be back in stock next Tuesday. Want me to notify you?",
            "Bad news: navy's gone for now! Restock lands Tuesday — shall I ping you when it's back?",
            "Navy flew off the shelves! Tuesday's the restock date — want a notification?",
          ],
          npcZh: "哦抱歉——藏青色现在售罄了！下周二补货。要我到货时通知您吗？",
          task: "接受通知，并问运费政策",
          options: [
            { text: "Yes, please notify me. Also, how much is shipping — is it free over a certain amount?", ok: true,  tip: "free over a certain amount 满额包邮——省钱关键" },
            { text: "Notify by telepathy please. Shipping money talk also.", ok: false, tip: "通知+运费一起问：Notify me. Is shipping free over a certain amount?" },
            { text: "Shipping free always? I only accept free.",     ok: false, tip: "问门槛：Is it free over a certain amount?" },
          ],
          phrase: { en: "Is shipping free over a certain amount?", zh: "满多少钱包邮？", note: "certain amount = 一定金额；凑单免运费的依据" },
        },
        {
          npcLines: [
            "Shipping's five ninety, but free over fifty dollars! The Runner Pros are fifty-nine, so you're covered. Oh — and there's a first-order discount code: WELCOME10!",
            "Five ninety shipping, free past fifty! The shoes are fifty-nine — free shipping unlocked! Plus, code WELCOME10 for ten percent off your first order!",
            "Shipping: five ninety, or free over fifty bucks. Shoes cost fifty-nine — you qualify! And use WELCOME10 at checkout for ten percent off!",
          ],
          npcZh: "运费 5.9 美元，满 50 美元包邮！这双鞋 59 美元，已经免运费了。对了——首单折扣码：WELCOME10！",
          task: "确认折扣码如何使用",
          options: [
            { text: "Nice, thank you! Where do I enter the WELCOME10 code — at checkout?", ok: true,  tip: "Where do I enter the code + at checkout 结账页——折扣码使用路径" },
            { text: "Code WELCOME10. I shout it at package when arrive?", ok: false, tip: "结账时输入：Where do I enter the code?" },
            { text: "Ten percent? Make it fifty percent, I am new customer.", ok: false, tip: "新手礼遇只有 10%：Where do I enter the code at checkout?" },
          ],
          phrase: { en: "Where do I enter the code?", zh: "我在哪里输入折扣码？", note: "enter = 输入；checkout = 结账页——电商两大高频词" },
        },
        {
          npcLines: [
            "Exactly — there's a promo code box at checkout, paste it there. Anything else I can help with before you order?",
            "You got it — promo box at checkout, paste away! Anything else before you hit that order button?",
            "Right at checkout, promo code field! Any other questions, smart shopper?",
          ],
          npcZh: "没错——结账页有个优惠码输入框，粘贴进去就行。下单前还有其他问题吗？",
          task: "确认下单后如何查物流",
          options: [
            { text: "Just one more thing — how do I track my order once it ships?", ok: true,  tip: "track my order 查物流 + once it ships 发货后" },
            { text: "Track order how? Package GPS where?",          ok: false, tip: "标准问法：How do I track my order?" },
            { text: "Tracking unnecessary. Packages find me eventually.", ok: false, tip: "查物流心里有数：How do I track my order once it ships?" },
          ],
          phrase: { en: "How do I track my order?", zh: "我怎么查我的订单物流？", note: "track = 追踪；订单邮件里一般有 tracking link" },
        },
        {
          npcLines: [
            "You'll get an order confirmation email right away, then a tracking link once it ships — usually within 24 hours. Happy shopping!",
            "Confirmation email immediately, tracking link within a day of shipping! Enjoy your new shoes!",
            "Email confirmation now, tracking link within 24 hours of shipping! Thanks for shopping with ShoeTop!",
          ],
          npcZh: "您马上会收到订单确认邮件，发货后（通常 24 小时内）会收到物流链接。购物愉快！",
          task: "感谢客服，结束咨询",
          options: [
            { text: "You've been super helpful, Maya — thanks! I'll order on Tuesday when navy is back.", ok: true,  tip: "点名感谢（Maya）+ 呼应前文（等周二补货）——完美的咨询收尾" },
            { text: "Bye chat person. Shoes Tuesday maybe.",        ok: false, tip: "点名致谢更真诚：You've been super helpful, Maya!" },
            { text: "OK ending chat now.",                          ok: false, tip: "完整收尾：Thanks, Maya — I'll order on Tuesday!" },
          ],
          phrase: { en: "You've been super helpful!", zh: "你帮了大忙！", note: "对客服的满分评价；super 加强语气" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 收货出问题了",
      titleEn: "Delivery Trouble",
      emoji: "📦",
      desc: "等了一周的包裹终于到了——但是发错货了！联系客服：报订单号、描述问题、要照片——维权第一步。",
      reward: { en: "wrong item", zh: "你解锁了收货问题处理英语！📦➡️🔄" },
      steps: [
        {
          npcLines: [
            "ShoeTop support, this is Leo. How can I help you today?",
            "Thanks for reaching out! Leo here — what seems to be the problem?",
            "Hi, ShoeTop live chat, Leo speaking. What can I do for you?",
          ],
          npcZh: "ShoeTop 客服，我是 Leo。今天有什么可以帮您？",
          task: "说明问题：收到了错的商品",
          options: [
            { text: "Hi Leo. I received my order today, but you sent me the wrong item — I got black shoes instead of navy.", ok: true,  tip: "you sent me the wrong item 发错货 + instead of 对比正确与错误" },
            { text: "WRONG SHOES. BLACK NOT NAVY. ANGRY!",            ok: false, tip: "说清事实：You sent me the wrong item — black instead of navy" },
            { text: "Shoes arrived. Color wrong. You fix now.",       ok: false, tip: "礼貌+具体：I got black shoes instead of navy" },
          ],
          phrase: { en: "You sent me the wrong item.", zh: "你们给我发错货了。", note: "wrong item = 发错货；网购三大问题之一（错发/破损/延误）" },
        },
        {
          npcLines: [
            "Oh no, I'm sorry about that! Let me pull up your order. Could I have your order number, please?",
            "That's on us — apologies! Let me check the order. Order number, please?",
            "Ugh, a mis-ship! My apologies. May I grab your order number to investigate?",
          ],
          npcZh: "哎呀，非常抱歉！让我调出您的订单。能提供一下订单号吗？",
          task: "提供订单号",
          options: [
            { text: "Sure, it's in my confirmation email — order number 55892. Take your time.", ok: true,  tip: "order number 订单号 + Take your time 不催促（对方查系统需要时间）" },
            { text: "Number 55892. Hurry hurry hurry.",              ok: false, tip: "给对方查库时间：Take your time" },
            { text: "Order number? I delete all emails immediately always.", ok: false, tip: "订单确认邮件要保留：It's in my confirmation email" },
          ],
          phrase: { en: "May I have your order number?", zh: "能告诉我您的订单号吗？", note: "客服必问；自己找单号 = 查 confirmation email" },
        },
        {
          npcLines: [
            "Found it — one pair of Runner Pro, navy, size nine and a half. You're right, black was sent by mistake. Could you send me a photo of what you received?",
            "Got it — navy Runner Pros, nine and a half. Yep, we shipped black by accident. Quick favor: a photo of the shoes you got?",
            "There it is! Navy nine-and-a-half — and you received black. To process this, could you snap a photo of the item?",
          ],
          npcZh: "找到了——Runner Pro 藏青色 9.5 码一双。您说得对，误发了黑色。能拍张收到的鞋的照片发我吗？",
          task: "理解需要照片作为凭证",
          options: [
            { text: "Of course — I'll upload a photo right now. Is that everything you need?", ok: true,  tip: "upload a photo 上传照片 + Is that everything you need? 主动确认材料齐全" },
            { text: "Photo of shoes? Shoes are ugly, photo will be ugly.", ok: false, tip: "照片是理赔凭证：I'll upload a photo right now" },
            { text: "No photo. Trust my words only.",                   ok: false, tip: "凭证必备：I'll upload a photo right now" },
          ],
          phrase: { en: "Is that everything you need?", zh: "您需要的材料都齐了吗？", note: "主动闭环——避免来回补材料的低效沟通" },
        },
        {
          npcLines: [
            "Photo received — perfect, that's all I need! Now, how would you like to fix this: an exchange for the navy pair, or a full refund?",
            "Got the photo — we're all set! So: exchange for the navy, or full refund? Your choice!",
            "Photo's in — case complete on my end! Pick your path: navy exchange, or money back?",
          ],
          npcZh: "照片收到——完美，材料齐了！那么，您想怎么解决：换藏青色那双，还是全额退款？",
          task: "选择换货，并确认运费承担方",
          options: [
            { text: "I'd like the exchange, please. Will you cover the return shipping for the black pair?", ok: true,  tip: "cover the return shipping 承担退货运费——发错货时商家应承担" },
            { text: "Exchange! Also I keep black shoes free, yes?",    ok: false, tip: "退货是必须的：Will you cover the return shipping?" },
            { text: "Exchange fine. I pay shipping because I am nice.", ok: false, tip: "商家过错商家付运费：Will you cover the return shipping?" },
          ],
          phrase: { en: "Will you cover the return shipping?", zh: "退货运费你们出吗？", note: "cover = 承担（费用）；错发货/质量问题商家必须承担运费" },
        },
        {
          npcLines: [
            "Absolutely — we'll email you a prepaid return label. Just tape it on the box and drop it at any pickup point. The navy pair ships as soon as we scan your return!",
            "Of course! Prepaid label coming to your inbox — tape, drop, done! Navy pair ships the moment your return scans in!",
            "You bet! We'll email a prepaid label — stick it on, drop it off. The navy ships the second your return hits our system!",
          ],
          npcZh: "当然——我们会给您发预付退货面单。贴箱子上，送到任意代寄点就行。您的藏青色会在收到退货扫描后立刻发出！",
          task: "确认退货操作细节",
          options: [
            { text: "Got it: tape the label on, drop it off, and the new pair ships once you receive the return. Easy!", ok: true,  tip: "复述退货三步（label/drop-off/ship）——流程确认" },
            { text: "Label on box. Then box where? Magic box portal?", ok: false, tip: "复述流程：Tape the label, drop it at a pickup point" },
            { text: "Too many steps. You send person to my house.",    ok: false, tip: "流程其实简单，复述确认：Label, drop-off, done!" },
          ],
          phrase: { en: "Got it: ___, ___, and ___.", zh: "明白了：……、……、然后……。", note: "复述三步曲的万能模板，确认理解零偏差" },
        },
        {
          npcLines: [
            "Exactly right! Sorry again for the mix-up — the navy pair will be worth the wait. Anything else today?",
            "Perfect summary! Apologies again for the hassle — navy's on its way soon. More questions?",
            "You've got the system down! Sorry for the mix-up, and enjoy the navys. Anything else?",
          ],
          npcZh: "完全正确！再次为失误道歉——藏青色值得等待。今天还有其他需要吗？",
          task: "结束对话，给客服好评",
          options: [
            { text: "That's all — you handled this really well, Leo. Thanks for the quick fix!", ok: true,  tip: "you handled this really well 夸处理能力 + quick fix 快速解决" },
            { text: "Goodbye Leo. You are adequate.",                     ok: false, tip: "真诚夸赞：You handled this really well!" },
            { text: "Fixed? Hardly. One star review coming!",             ok: false, tip: "对方快速解决了问题：Thanks for the quick fix!" },
          ],
          phrase: { en: "Thanks for the quick fix!", zh: "谢谢你快速解决！", note: "quick fix = 快速解决；对高效客服的专属夸奖" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 退货退款拉锯战",
      titleEn: "The Refund Battle",
      emoji: "💸",
      desc: "退款迟迟不到账、被收退货手续费、客服踢皮球？升级投诉、引用政策、要补偿——维权进阶英语。",
      reward: { en: "process the refund", zh: "你解锁了退款维权英语，拉锯战不输阵！💸" },
      steps: [
        {
          npcLines: [
            "ShoeTop support, this is Rita. How may I help you?",
            "Hi, Rita from ShoeTop support! What's the issue today?",
            "Thanks for contacting ShoeTop — Rita here. What can I do for you?",
          ],
          npcZh: "ShoeTop 客服，我是 Rita。有什么可以帮您？",
          task: "说明退款超过承诺期限仍未到账",
          options: [
            { text: "Hi Rita. I returned an item two weeks ago, and your policy says refunds process within five business days. Mine still hasn't arrived.", ok: true,  tip: "引用政策原文（policy says five business days）+ 陈述事实——维权最有力的组合" },
            { text: "Money late! Very late! Give money!",            ok: false, tip: "引用政策更有力：Your policy says five business days" },
            { text: "Two weeks waiting. I cry every night about refund.", ok: false, tip: "理性陈述：My refund still hasn't arrived" },
          ],
          phrase: { en: "Your policy says ___.", zh: "你们的政策写的是……。", note: "维权核武器——引用对方承诺；客服无法反驳自家政策" },
        },
        {
          npcLines: [
            "Let me check... I see the return was received on the 3rd. Hmm, it looks like the refund was processed to a card that's now expired. That's why it bounced.",
            "Checking now... return received on the 3rd. Ah — the refund went to an expired card and bounced back. That's the issue!",
            "Found it! Return landed on the 3rd, but the refund went to an expired card and bounced. Mystery solved!",
          ],
          npcZh: "让我查一下……退货 3 号已签收。嗯，退款打到了一张已过期的卡上，所以被退回了。原因找到了。",
          task: "理解原因，询问解决方案",
          options: [
            { text: "I see — I did replace that card. How do we fix this? Can you redirect the refund to my new card?", ok: true,  tip: "redirect the refund 改道退款——问题解决路径" },
            { text: "Expired card ate my money! Card thief!",         ok: false, tip: "钱会退回原账户：Can you redirect it to my new card?" },
            { text: "Not my fault card expired. You find money, I wait.", ok: false, tip: "配合解决：Can you redirect the refund?" },
          ],
          phrase: { en: "How do we fix this?", zh: "我们怎么解决这个问题？", note: "we = 双方共同面对——比 how do YOU fix 更易促成合作" },
        },
        {
          npcLines: [
            "I can resubmit it to your new card — three to five business days. But... my system shows a restocking fee of four ninety was deducted. I'm unable to remove it myself.",
            "New card refund, no problem — three to five days. One hiccup: the system auto-deducted a four-ninety restocking fee, and I can't remove it.",
            "Redirecting now — five days tops. But heads-up: a four-ninety restocking fee was applied, and that's above my pay grade to remove.",
          ],
          npcZh: "我可以重新提交到您的新卡——3-5 个工作日。但是……系统显示扣了 4.9 美元退货手续费，我个人权限无法取消。",
          task: "质疑手续费合理性（退货政策说免手续费）",
          options: [
            { text: "Wait — your return policy says there's no restocking fee. Could you double-check, or escalate this to someone who can waive it?", ok: true,  tip: "再次引用政策 + escalate 升级处理——层级突破" },
            { text: "Four ninety? Fine, take all my money, take my house too.", ok: false, tip: "据理力争：Your policy says no restocking fee" },
            { text: "Escalate? Like elevator? To boss floor?",        ok: false, tip: "escalate = 升级给上级：Could you escalate this?" },
          ],
          phrase: { en: "Could you escalate this?", zh: "能把这个问题升级处理吗？", note: "escalate = 上报上级；一线客服权限不够时的标准动作" },
        },
        {
          npcLines: [
            "You know what, you're right — let me check with my supervisor... Yes! She's waiving the fee as a one-time courtesy, since our policy does say no restocking fees. Full refund coming!",
            "Checking with the boss... She says yes! Fee waived — policy is policy, full refund to your new card!",
            "One supervisor chat later... fee waived! You knew the policy better than my system. Full refund, three to five days!",
          ],
          npcZh: "您说得对——我跟主管确认一下……好了！她特批免收手续费，因为我们的政策确实写着免退货手续费。全额退款马上到！",
          task: "确认最终金额与到账时间",
          options: [
            { text: "Thank you! Just to confirm: full refund of fifty-nine dollars, no fees, to my new card in three to five business days?", ok: true,  tip: "Just to confirm 复述确认——金额/费用/渠道/时限四要素闭环" },
            { text: "Confirm fast yes. Money words good.",            ok: false, tip: "关键信息复述：Full refund, no fees, new card, three to five days" },
            { text: "Fifty-nine? Was it not one hundred nine?",       ok: false, tip: "按订单实际金额确认：Full refund of fifty-nine dollars" },
          ],
          phrase: { en: "Just to confirm: ___?", zh: "确认一下：……，对吗？", note: "谈判收官句——把口头承诺钉死成具体数字" },
        },
        {
          npcLines: [
            "Exactly — fifty-nine, zero fees, new card, five days max! Again, apologies for the runaround. Is there anything else I can do?",
            "Confirmed on all counts! Fifty-nine bucks, no deductions, new card, within five days. Sorry for the hassle — anything else?",
            "That's the deal — full fifty-nine, fee-free, new card, five days! Apologies for the detour. What else can I help with?",
          ],
          npcZh: "完全正确——59 美元全额、零手续费、新卡、最多 5 天！再次为折腾道歉。还有其他需要吗？",
          task: "询问是否有补偿（折腾了两周）",
          options: [
            { text: "Well, I did spend two weeks on this. Is there any goodwill gesture — maybe a discount code for my next order?", ok: true,  tip: "goodwill gesture 善意补偿——合理维权的最后一问（不是索取，是惯例）" },
            { text: "Two weeks of my life! Cash compensation! Double refund!", ok: false, tip: "合理范围内：Any goodwill gesture — a discount code?" },
            { text: "No compensation wanted. I enjoy refund battles as hobby.", ok: false, tip: "行业惯例可以问：A discount code for my next order?" },
          ],
          phrase: { en: "Is there any goodwill gesture?", zh: "有没有什么善意补偿？", note: "goodwill gesture = 商家的歉意表达；维权收尾的体面一问" },
        },
        {
          npcLines: [
            "Actually, yes — I can offer you a twenty percent coupon for your next order. Thank you for your patience, and for knowing our policies better than our system did!",
            "Funny you ask — here's twenty percent off your next order! Thanks for the patience, and honestly, for schooling us on our own policy!",
            "Absolutely — twenty percent coupon, coming right up! You deserve it for the patience AND the policy knowledge!",
          ],
          npcZh: "还真有——下次购物给您 8 折优惠券。感谢您的耐心，也感谢您比我们的系统还熟悉我们的政策！",
          task: "接受补偿，幽默收尾",
          options: [
            { text: "Haha, I'll read the fine print next time too! Thanks for sorting everything out, Rita.", ok: true,  tip: "read the fine print 看小字条款——自嘲式幽默收尾 + 点名感谢" },
            { text: "Fine print is my full-time job now. Goodbye.",   ok: false, tip: "幽默+感谢：Thanks for sorting everything out, Rita!" },
            { text: "Twenty percent only? The battle continues!",     ok: false, tip: "见好就收：Thanks for sorting everything out!" },
          ],
          phrase: { en: "read the fine print", zh: "看清小字条款。", note: "fine print = 合同/政策的小字部分——维权高手的必备习惯" },
        },
      ],
    },
  ],
},
