// 宠物医院场景头 + v1-v3 词条（36 个，vet- 前缀）
{
  id: "vet",
  name: "宠物医院",
  nameEn: "Vet Clinic",
  emoji: "🐾",
  iconId: "paw",
  cover: "🐶🩺🐾",
  theme: "vet",
  accent: "#7a5a9e",
  accentSoft: "#efe8f6",
  deco: "🐾",
  deco2: "毛孩子",
  intro: "带毛孩子看兽医：预约体检、打疫苗、描述症状——宠物医疗英语全流程，还有美式宠物文化。",
  orderLabel: "🐾 就诊进度",
  items: [
    { id: "vet-appointment", en: "appointment",   zh: "预约", phon: "/əˈpɔɪntmənt/", emoji: "📅", sent: "I'd like to make an appointment." },
    { id: "vet-checkup",     en: "checkup",       zh: "体检", phon: "/ˈtʃekʌp/", emoji: "🩺", sent: "Max is here for a checkup." },
    { id: "vet-receptionist",en: "receptionist",  zh: "前台接待", phon: "/rɪˈsepʃənɪst/", emoji: "💁", sent: "The receptionist will check you in." },
    { id: "vet-checkin",     en: "check in",      zh: "报到登记", phon: "/tʃek ɪn/", emoji: "✅", sent: "Let's check in at the front desk." },
    { id: "vet-carrier",     en: "carrier",       zh: "宠物背包/航空箱", phon: "/ˈkæriə/", emoji: "🎒", sent: "Keep your cat in the carrier." },
    { id: "vet-leash",       en: "leash",         zh: "牵引绳", phon: "/liːʃ/", emoji: "🦮", sent: "Dogs must be on a leash." },
    { id: "vet-vaccine",     en: "vaccine",       zh: "疫苗", phon: "/ˈvæksiːn/", emoji: "💉", sent: "Is he up to date on vaccines?" },
    { id: "vet-shot",        en: "shot",          zh: "打针（口语）", phon: "/ʃɒt/", emoji: "💉", sent: "He needs his rabies shot." },
    { id: "vet-rabies",      en: "rabies",        zh: "狂犬病", phon: "/ˈreɪbiːz/", emoji: "🦠", sent: "The rabies vaccine is required by law." },
    { id: "vet-booster",     en: "booster",       zh: "加强针", phon: "/ˈbuːstə/", emoji: "🔁", sent: "He's due for a booster." },
    { id: "vet-record",      en: "record",        zh: "病历记录", phon: "/ˈrekɔːd/", emoji: "📋", sent: "We'll transfer his records." },
    { id: "vet-symptom",     en: "symptom",       zh: "症状", phon: "/ˈsɪmptəm/", emoji: "🤒", sent: "Describe his symptoms." },
    { id: "vet-lethargic",   en: "lethargic",     zh: "无精打采的", phon: "/ləˈθɑːdʒɪk/", emoji: "😴", sent: "He's been lethargic lately." },
    { id: "vet-appetite",    en: "appetite",      zh: "食欲", phon: "/ˈæpɪtaɪt/", emoji: "🍖", sent: "He's lost his appetite." },
    { id: "vet-vomit",       en: "vomit",         zh: "呕吐", phon: "/ˈvɒmɪt/", emoji: "🤮", sent: "She vomited twice this morning." },
    { id: "vet-diarrhea",    en: "diarrhea",      zh: "腹泻", phon: "/ˌdaɪəˈrɪə/", emoji: "🚽", sent: "The puppy has diarrhea." },
    { id: "vet-limp",        en: "limp",          zh: "跛行", phon: "/lɪmp/", emoji: "🦵", sent: "He's limping on his front leg." },
    { id: "vet-swallow",     en: "swallow",       zh: "吞下", phon: "/ˈswɒləʊ/", emoji: "😮", sent: "He swallowed a sock!" },
    { id: "vet-emergency",   en: "emergency",     zh: "急诊", phon: "/ɪˈmɜːdʒənsi/", emoji: "🚨", sent: "It's an emergency — come now!" },
    { id: "vet-xray",        en: "X-ray",         zh: "X 光", phon: "/ˈeks reɪ/", emoji: "🩻", sent: "We'll take an X-ray." },
    { id: "vet-surgery",     en: "surgery",       zh: "手术", phon: "/ˈsɜːdʒəri/", emoji: "🏥", sent: "She needs surgery right away." },
    { id: "vet-anesthesia",  en: "anesthesia",    zh: "麻醉", phon: "/ˌænəsˈθiːʒə/", emoji: "😴", sent: "He'll be under anesthesia." },
    { id: "vet-insurance",   en: "pet insurance", zh: "宠物保险", phon: "/pet ɪnˈʃʊərəns/", emoji: "🛡️", sent: "Pet insurance covers most of it." },
    { id: "vet-premium",     en: "premium",       zh: "保险费", phon: "/ˈpriːmiəm/", emoji: "💰", sent: "The monthly premium is thirty dollars." },
    { id: "vet-claim",       en: "claim",         zh: "理赔", phon: "/kleɪm/", emoji: "🧾", sent: "File a claim with your insurer." },
    { id: "vet-estimate",    en: "estimate",      zh: "费用预估", phon: "/ˈestɪmət/", emoji: "🧮", sent: "Ask for a cost estimate first." },
    { id: "vet-declined",    en: "declined",      zh: "拒绝的（申请被拒）", phon: "/dɪˈklaɪnd/", emoji: "❌", sent: "My claim was declined." },
    { id: "vet-deworm",      en: "deworming",     zh: "驱虫", phon: "/ˌdiːˈwɜːmɪŋ/", emoji: "🪱", sent: "Deworming is done every three months." },
    { id: "vet-flea",        en: "flea",          zh: "跳蚤", phon: "/fliː/", emoji: "🦗", sent: "Use monthly flea prevention." },
    { id: "vet-tick",        en: "tick",          zh: "蜱虫", phon: "/tɪk/", emoji: "🕷️", sent: "Check for ticks after hikes." },
    { id: "vet-prevention",  en: "preventive care", zh: "预防保健", phon: "/prɪˈventɪv keə/", emoji: "🛡️", sent: "Preventive care saves money." },
    { id: "vet-spay",        en: "spay",          zh: "绝育（母）", phon: "/speɪ/", emoji: "✂️", sent: "We recommend spaying at six months." },
    { id: "vet-neuter",      en: "neuter",        zh: "绝育（公）", phon: "/ˈnjuːtə/", emoji: "✂️", sent: "Neutering reduces health risks." },
    { id: "vet-fiber",       en: "fiber",         zh: "纤维", phon: "/ˈfaɪbə/", emoji: "🌾", sent: "This food has more fiber." },
    { id: "vet-dose",        en: "dose",          zh: "一剂药量", phon: "/dəʊs/", emoji: "💊", sent: "Give one dose twice a day." },
    { id: "vet-euthanasia",  en: "euthanasia",    zh: "安乐死", phon: "/ˌjuːθəˈneɪziə/", emoji: "🌈", sent: "We discussed humane euthanasia." }
  ],
  visits: [
    {
      id: "v1",
      title: "第 1 次光顾 · 预约体检",
      titleEn: "Annual Checkup",
      emoji: "🩺",
      desc: "带狗狗 Max 做年度体检：打电话预约、前台报到、向医生描述近况——宠物就诊第一步。",
      reward: { en: "appointment", zh: "你帮 Max 约上了体检，第一步完成！📅" },
      steps: [
        {
          npcLines: [
            "Good morning, Happy Paws Veterinary Clinic! How can I help you?",
            "Thanks for calling Happy Paws! What can I do for you?",
            "Happy Paws Vet Clinic, this is Amy speaking. How may I help?",
          ],
          npcZh: "早上好，欢乐爪爪兽医诊所！有什么可以帮您？",
          task: "说明来意：给狗狗预约年度体检",
          options: [
            { text: "Hi! I'd like to make an appointment for my dog's annual checkup.", ok: true,  tip: "make an appointment 预约 + annual checkup 年度体检——电话预约标准句" },
            { text: "My dog needs a doctor. Today. Right now. Hurry.",  ok: false, tip: "礼貌预约：I'd like to make an appointment for a checkup" },
            { text: "Hello. Dog exists. Please inspect the dog.",      ok: false, tip: "标准表达：make an appointment for my dog's annual checkup" },
          ],
          phrase: { en: "I'd like to make an appointment for ___.", zh: "我想给……预约一下。", note: "make an appointment 预约；医生/理发/宠物诊所通用" },
        },
        {
          npcLines: [
            "Of course! What's your pet's name, and what kind of dog is he?",
            "Sure thing! Who's the patient — name and breed, please?",
            "No problem! Dog's name and breed for the chart?",
          ],
          npcZh: "当然可以！您的宠物叫什么名字，是什么品种的狗？",
          task: "介绍宠物：Max，金毛，三岁",
          options: [
            { text: "His name is Max — he's a three-year-old golden retriever.", ok: true, tip: "报宠物信息：name + breed + age，病历建档需要" },
            { text: "He's Max. A very good boy. The best boy.",  ok: false, tip: "建档要具体信息：a three-year-old golden retriever" },
            { text: "Dog. Normal dog. Dog-shaped.",             ok: false, tip: "说明品种和年龄：golden retriever, three years old" },
          ],
          phrase: { en: "He's a ___-year-old ___.", zh: "它是一只……岁的……。", note: "age + breed 组合描述宠物；golden retriever 金毛" },
        },
        {
          npcLines: [
            "Max sounds lovely! We have openings Thursday at ten or Friday at two thirty. Which works better?",
            "A golden! Sweet. Thursday ten a.m. or Friday two thirty — your pick.",
            "Love goldens! We can do Thursday at ten or Friday at two thirty. What's best?",
          ],
          npcZh: "Max 听起来很可爱！周四上午十点或周五下午两点半有空位。哪个合适？",
          task: "选时间并确认",
          options: [
            { text: "Thursday at ten works great for us.", ok: true,  tip: "…works great for us 时间合适——选时段标准回应" },
            { text: "Give me Monday at midnight exactly.", ok: false, tip: "从给出的选项里选：Thursday at ten" },
            { text: "When is never o'clock?",              ok: false, tip: "选定时段：Thursday at ten works great" },
          ],
          phrase: { en: "___ works (great) for me.", zh: "……（非常）适合我。", note: "works = 行得通、合适；拒绝时说 That doesn't work for me" },
        },
        {
          npcLines: [
            "Booked — Thursday at ten for Max! Just a heads-up: dogs must be on a leash, and cats in carriers. See you then!",
            "You're all set, Thursday ten a.m.! Reminder: leashes for dogs, carriers for cats. See you Thursday!",
            "Done and done! Thursday, ten o'clock, Max the golden. Leash him up and we'll see you then!",
          ],
          npcZh: "订好了——周四十点，Max！提醒一下：狗必须戴牵引绳，猫要装背包。到时候见！",
          task: "确认要求并致谢",
          options: [
            { text: "Got it — leash for Max. Thank you so much, see you Thursday!", ok: true, tip: "Got it 复述确认 + 道谢——预约收尾" },
            { text: "Leash? Max walks me. It's fine.",    ok: false, tip: "遵守规定：Got it, leash for Max" },
            { text: "He will be free. Freedom Max.",      ok: false, tip: "接受规定：Thank you, see you Thursday!" },
          ],
          phrase: { en: "Just a heads-up: ___.", zh: "提醒一下：……。", note: "heads-up = 预先提醒（名词）；对方善意告知时回 Got it" },
        },
        {
          npcLines: [
            "Hi, welcome to Happy Paws! Checking in for Max?",
            "Hello! Max's ten o'clock, right? Let's get you checked in.",
            "Good morning! You must be Max's human. Check in right here, please.",
          ],
          npcZh: "您好，欢迎来到欢乐爪爪！是 Max 来报到吗？",
          task: "前台报到，说明有预约",
          options: [
            { text: "Yes, we have a ten o'clock appointment for a checkup.", ok: true, tip: "check in 报到 + 报上预约时间——到店第一步" },
            { text: "We are here. Witness us.",        ok: false, tip: "报到用语：We have a ten o'clock appointment" },
            { text: "Max made the appointment himself.", ok: false, tip: "替宠物说话：We have an appointment at ten" },
          ],
          phrase: { en: "We have an appointment at ___.", zh: "我们约了……点。", note: "报到万能句；前台会据此调出病历" },
        },
        {
          npcLines: [
            "Found it! The vet will call you in shortly. How's Max been doing — any changes since last year?",
            "All checked in! While we wait — how's he been? Anything new or different?",
            "You're in the system! Quick question while the vet finishes up: any changes with Max this year?",
          ],
          npcZh: "找到了！医生马上叫您。Max 最近怎么样——和去年比有什么变化吗？",
          task: "描述近况：一切都好，就是有点胖",
          options: [
            { text: "He's been great, just a little overweight — he loves treats too much.", ok: true, tip: "overweight 超重 + loves treats too much 幽默坦诚——描述近况" },
            { text: "He is perfect. A circle of perfection.",   ok: false, tip: "具体描述：a little overweight" },
            { text: "Changes? He changed my life. For the better.", ok: false, tip: "说健康近况：He's been great, just a little overweight" },
          ],
          phrase: { en: "He's been ___.", zh: "它最近……。", note: "been + 形容词描述状态；接 just 带出细节" },
        },
        {
          npcLines: [
            "Ha, classic golden! The vet will chat about his diet then. She's ready for you now — room two, please!",
            "Treats are life! Dr. Lee will go over a diet plan. Room two — she's ready for Max!",
            "A man after my own heart! Okay, Dr. Lee's ready — room two, on the left!",
          ],
          npcZh: "哈哈，典型金毛！医生会聊聊饮食方案。她现在有空——请去二号诊室！",
          task: "道谢并前往诊室",
          options: [
            { text: "Perfect, thank you! Come on, Max — let's go!", ok: true,  tip: "引导宠物+道谢——报到流程毕业" },
            { text: "Room two. Max, translate for me.",  ok: false, tip: "正常收尾：Thank you! Let's go, Max!" },
            { text: "I will carry Max like a suitcase.", ok: false, tip: "自然引导：Come on, Max, let's go!" },
          ],
          phrase: { en: "Come on, ___. Let's go!", zh: "来吧，……。我们走！", note: "呼唤宠物/孩子出发的口语；come on 表催促引导" },
        },
      ],
    },
    {
      id: "v2",
      title: "第 2 次光顾 · 疫苗与预防",
      titleEn: "Vaccines & Prevention",
      emoji: "💉",
      desc: "Max 该打疫苗了：狂犬加强针、驱虫、跳蚤预防——预防保健的全套英语。",
      reward: { en: "booster", zh: "Max 的疫苗本更新完毕，预防到位！💉" },
      steps: [
        {
          npcLines: [
            "Welcome back! Max's turn for vaccines today, right?",
            "Hi again! We've got boosters on the schedule for this handsome guy?",
            "Good to see you two! Vaccine day for Max, I believe?",
          ],
          npcZh: "欢迎回来！Max 今天是来打疫苗的吧？",
          task: "确认来意并问疫苗是否都齐全",
          options: [
            { text: "Yes! Is he due for any shots? I want to make sure he's up to date.", ok: true, tip: "be due for 到期该做 + up to date 最新状态——疫苗核对标准句" },
            { text: "Yes. Inject him with all vaccines. All of them.", ok: false, tip: "核对再打：Is he due for any shots?" },
            { text: "Shots? He fears nothing. Do his fears need shots?", ok: false, tip: "确认疫苗状态：make sure he's up to date" },
          ],
          phrase: { en: "Is he due for ___?", zh: "他是不是到时间该……了？", note: "due for = 到期该做（疫苗/体检/洗牙通用）" },
        },
        {
          npcLines: [
            "Let me pull up his record... He's due for the rabies booster — that one's required by law, by the way.",
            "Checking his chart... Rabies booster's due! And that one's not optional — it's the law.",
            "His file says... rabies booster time! Legally required, as always.",
          ],
          npcZh: "我调一下病历……他该打狂犬病加强针了——顺便说，这个是法律规定的。",
          task: "询问法律对疫苗的具体要求",
          options: [
            { text: "Required by law — good to know. How often does he need it?", ok: true, tip: "How often 频率必问；required by law 法律强制" },
            { text: "The law has opinions about my dog? Rude.",  ok: false, tip: "了解规定：How often does he need it?" },
            { text: "Rabies is a suggestion, surely.",           ok: false, tip: "狂犬疫苗是法律强制：required by law" },
          ],
          phrase: { en: "How often does he need it?", zh: "他需要多久打一次？", note: "How often 问频率；疫苗周期因种类而异" },
        },
        {
          npcLines: [
            "Every one to three years depending on the formula. Now, while he's here — is he current on deworming and flea prevention?",
            "One to three years, depends on the shot. Also — deworming and flea meds, is he up to date on those?",
            "Every one to three years. Quick check while we're at it: deworming and flea prevention — current?",
          ],
          npcZh: "一到三年一次，看具体药剂。趁他今天在——驱虫和跳蚤预防药也都用着吗？",
          task: "如实回答：驱虫做了，跳蚤药上个月用完了",
          options: [
            { text: "Deworming is done, but I ran out of his flea medication last month.", ok: true, tip: "ran out of 用完了——如实回答，方便医生补齐" },
            { text: "Yes to everything. All of it. Forever.",  ok: false, tip: "如实说明：I ran out of his flea medication" },
            { text: "Fleas? Max and I have an arrangement.",    ok: false, tip: "如实汇报：deworming yes, flea meds ran out" },
          ],
          phrase: { en: "I ran out of ___.", zh: "我的……用完了。", note: "run out of = 用完；报实情医生才能补上" },
        },
        {
          npcLines: [
            "Easy fix — we'll restock you today. One more thing: has he been scratching his ears or chewing his paws a lot?",
            "No worries, we'll send you home with more. Now — lots of ear scratching or paw chewing lately?",
            "We'll fix that right up! And how about this: been scratching his ears or biting his paws?",
          ],
          npcZh: "好办——今天给您补上。还有一件事：他最近经常挠耳朵或啃爪子吗？",
          task: "回答：偶尔挠耳朵，问是否正常",
          options: [
            { text: "He scratches his ears sometimes. Is that normal?", ok: true, tip: "Is that normal? 问正常与否——症状描述+求判断" },
            { text: "He never touches his ears. They are decorative.", ok: false, tip: "描述实情：He scratches his ears sometimes" },
            { text: "He chews everything. Including my sofa.",         ok: false, tip: "聚焦问到的症状：scratches his ears sometimes" },
          ],
          phrase: { en: "Is that normal?", zh: "这正常吗？", note: "描述现象后的求判断句；也可说 Should I be worried?" },
        },
        {
          npcLines: [
            "Occasional scratching is fine, but let's peek in those ears... A little wax buildup — nothing serious. I'll clean them while he's here.",
            "Let me see... Slight wax in the left ear, totally manageable. Ear cleaning, on the house with the visit!",
            "Checking... Just some wax. I'll give them a quick clean today — easy as that.",
          ],
          npcZh: "偶尔挠一下没事，不过我看看耳朵……有一点耳垢堆积——不严重。趁他在，我给清理一下。",
          task: "同意处理并询问在家护理建议",
          options: [
            { text: "That would be great. Anything I should do at home to keep his ears healthy?", ok: true, tip: "Anything I should do at home? 求居家护理建议——主动管理健康" },
            { text: "Clean them with my toothbrush?",  ok: false, tip: "问专业建议：Anything I should do at home?" },
            { text: "Ears clean themselves. Like cats.", ok: false, tip: "求护理建议：Anything I should do at home?" },
          ],
          phrase: { en: "Anything I should do at home?", zh: "我在家需要注意什么吗？", note: "就诊收尾万能问；医生/牙医/兽医都吃这套" },
        },
        {
          npcLines: [
            "Just a weekly check — sniff for anything odd, and dry his ears well after swims. Alright, Max is getting his shot now... And done! He didn't even flinch.",
            "Weekly sniff test, dry ears after swimming. Okay, little pinch coming... All done! What a brave boy.",
            "Check weekly, dry after swims. Here we go — one booster... Done! Didn't even blink, the legend.",
          ],
          npcZh: "每周检查一下——闻闻有没有异味，游泳后把耳朵擦干。好，现在打针……好了！他都没缩一下。",
          task: "安抚表扬 Max，确认后续安排",
          options: [
            { text: "Good boy, Max! So when should we come back for the next round?", ok: true, tip: "Good boy 表扬宠物 + 问下次时间——预约闭环" },
            { text: "Max, you have shamed our family name.",  ok: false, tip: "表扬勇敢的狗狗：Good boy! When should we come back?" },
            { text: "Next round? Of shots? Never again.",     ok: false, tip: "确认后续：When should we come back?" },
          ],
          phrase: { en: "When should we come back?", zh: "我们下次什么时候来？", note: "就诊收尾三问之一：下次时间/居家注意/怎么联系" },
        },
        {
          npcLines: [
            "See you in a year for his next checkup — unless anything comes up, of course. Flea meds and ear cleaner are at the front desk. Take care, you two!",
            "Annual visit next year, sooner if anything changes! His goodies are waiting up front. Bye, Max!",
            "One year from today — or any time you're worried! Meds at checkout. See you next year, big guy!",
          ],
          npcZh: "明年来做下一次体检——当然，有任何情况随时来。跳蚤药和耳部清洁剂在前台。你们俩保重！",
          task: "道谢告别",
          options: [
            { text: "Thank you so much — he's in great hands. Bye!", ok: true,  tip: "You're in great hands 夸医护+道别——疫苗轮毕业" },
            { text: "Farewell, needle person.",       ok: false, tip: "自然告别：Thank you so much, bye!" },
            { text: "Max says nothing. Max is stoic.", ok: false, tip: "替 Max 道别：Thank you, he's in great hands!" },
          ],
          phrase: { en: "He's in great hands.", zh: "有你照顾我很放心。", note: "in good/great hands = 被照顾得很好；夸奖医护的地道说法" },
        },
      ],
    },
    {
      id: "v3",
      title: "第 3 次光顾 · 急诊：Max 误食袜子",
      titleEn: "Emergency: The Sock Incident",
      emoji: "🚨",
      desc: "Max 吞了一只袜子！急诊电话、X 光、费用预估——最紧张的宠物急诊英语全流程。",
      reward: { en: "X-ray", zh: "你陪 Max 渡过了袜子危机，急诊英语通关！🚨" },
      steps: [
        {
          npcLines: [
            "Happy Paws Veterinary Clinic, emergency line — what's happening?",
            "Happy Paws, this is an emergency line. What's wrong?",
            "Emergency line, Happy Paws! Go ahead — what's going on?",
          ],
          npcZh: "欢乐爪爪诊所，急诊线——发生什么事了？",
          task: "紧急说明：狗狗吞了一只袜子",
          options: [
            { text: "My dog just swallowed a sock! Should I bring him in?", ok: true,  tip: "swallowed a sock 吞了袜子 + Should I bring him in? 要不要送来——急诊开场三要素：什么宠物+什么事+怎么办" },
            { text: "Emergency! Dog broken! Everything broken!",  ok: false, tip: "说清事件：He swallowed a sock, should I bring him in?" },
            { text: "He ate a sock and now he's smiling. Cute, right?", ok: false, tip: "误食是急事：Should I bring him in?" },
          ],
          phrase: { en: "My dog just swallowed ___!", zh: "我的狗刚吞了……！", note: "just 强调刚刚发生；swallow /ˈswɒləʊ/ 吞下" },
        },
        {
          npcLines: [
            "Yes — come in right away. Don't make him vomit at home. How long ago did he eat it?",
            "Come now! And no home remedies — no making him throw up. When did this happen?",
            "Head straight over! Don't induce vomiting. How long ago are we talking?",
          ],
          npcZh: "是的——马上过来。别在家催吐。他多久前吃的？",
          task: "回答时间：大概二十分钟前",
          options: [
            { text: "About twenty minutes ago. We're leaving the house right now.", ok: true, tip: "about twenty minutes ago 报时间 + 立即出发——急诊时间线很关键" },
            { text: "Time is a human concept. Dogs live in the now.",  ok: false, tip: "报准确时间：about twenty minutes ago" },
            { text: "Yesterday? No, today. Or yesterday. Both.",       ok: false, tip: "尽量准确：about twenty minutes ago" },
          ],
          phrase: { en: "About ___ ago.", zh: "大约……之前。", note: "about + 时间段 + ago 报时间；急诊句式越短越好" },
        },
        {
          npcLines: [
            "There you are! Bring him straight to room one. How's he acting — lethargic, drooling, trying to vomit?",
            "You made it! Room one, quick quick. Is he lethargic? Drooling? Retching?",
            "Right on time — room one, please! Symptoms check: sleepy? Drooling? Trying to throw up?",
          ],
          npcZh: "来了！直接去一号诊室。他状态怎么样——无精打采、流口水、干呕吗？",
          task: "描述症状：有点蔫，干呕了两次",
          options: [
            { text: "He seems lethargic and he's tried to vomit twice but nothing came out.", ok: true, tip: "lethargic 无精打采 + tried to vomit 干呕——急诊症状描述" },
            { text: "He's totally normal. Sock is his lifestyle now.",  ok: false, tip: "描述真实症状：lethargic, tried to vomit twice" },
            { text: "He is dramatic, like all of us.",                  ok: false, tip: "关键症状：lethargic + dry heaving" },
          ],
          phrase: { en: "He seems ___.", zh: "他看起来……。", note: "seem + 形容词描述观察到的状态；急诊信息越具体越好" },
        },
        {
          npcLines: [
            "Okay, we'll take an X-ray to see where the sock is. It might pass on its own — or he might need surgery. Let's look first.",
            "X-ray time! The sock may pass naturally, or it may not. Pictures before decisions.",
            "Let's get an X-ray. Best case, it passes on its own. Worst case, minor surgery. Images first, then we talk.",
          ],
          npcZh: "好，我们先拍个 X 光看看袜子在哪。可能自己排出来——也可能需要手术。先看片子。",
          task: "同意拍片，询问费用",
          options: [
            { text: "Please do. Could you give me a cost estimate for both scenarios?", ok: true, tip: "cost estimate 费用预估 + both scenarios 两种情况——急诊必备问法（美国医疗惯例）" },
            { text: "Money is no object. Sell my car if needed.",  ok: false, tip: "稳妥问法：a cost estimate for both scenarios" },
            { text: "No X-ray. Just guess where the sock is.",     ok: false, tip: "配合检查：Could you give me a cost estimate?" },
          ],
          phrase: { en: "Could you give me a cost estimate?", zh: "能给我一个费用预估吗？", note: "estimate 名词读 /ˈestɪmət/；兽医费高昂，先问价是惯例" },
        },
        {
          npcLines: [
            "Of course — X-ray is one-fifty. If it passes naturally, that's it. If we need endoscopy, around eight hundred. Surgery would be fifteen hundred, plus anesthesia.",
            "Totally fair to ask! X-ray: $150. Natural passage: no more cost. Endoscopy: about $800. Surgery: $1,500 plus anesthesia.",
            "Smart question! X-ray runs one-fifty. If it passes, done. Endoscopy ~$800, surgery up to $1,500 with anesthesia.",
          ],
          npcZh: "当然——X 光一百五。如果自然排出就这些钱。如果要做内镜约八百。手术要一千五，加麻醉。",
          task: "确认理解，询问是否有保险可用",
          options: [
            { text: "Understood. Do you take pet insurance? I have a policy with PawCover.", ok: true, tip: "take insurance 接受保险 + policy 保单——宠物保险救命问句" },
            { text: "Eight hundred dollars for a sock hunt?!",  ok: false, tip: "先确认保险：Do you take pet insurance?" },
            { text: "I will pay in socks. I have many.",        ok: false, tip: "问保险：Do you take pet insurance?" },
          ],
          phrase: { en: "Do you take ___ insurance?", zh: "你们接受……保险吗？", note: "take = 接受；宠物险多为先付后理赔（reimburse）" },
        },
        {
          npcLines: [
            "We work with all major insurers — you'd pay upfront and file a claim for reimbursement. X-ray's back! Good news: the sock is in the stomach, and it's small enough to pass. No surgery!",
            "PawCover's great — pay us, then claim it back. And... the X-ray's in! The sock's in his stomach but small enough to pass on its own. No surgery, my friend!",
            "You'd file for reimbursement — standard stuff. Okay, images are up... The sock will pass! It's small and already moving. Phew!",
          ],
          npcZh: "我们和主流保险公司都有合作——您先付款再申请理赔。X 光出来了！好消息：袜子在胃里，而且小到可以自己排出。不用手术！",
          task: "松一口气，确认居家观察注意事项",
          options: [
            { text: "What a relief! What should I watch for at home?", ok: true, tip: "What a relief 松口气 + What should I watch for 观察要点——回家护理必备" },
            { text: "Relief? I was ready for the fifteen dollar sock.", ok: false, tip: "居家观察：What should I watch for at home?" },
            { text: "So the sock will return to me. Poetic.",  ok: false, tip: "问观察事项：What should I watch for at home?" },
          ],
          phrase: { en: "What should I watch for?", zh: "我需要留意什么？", note: "watch for = 留意观察（异常信号）；急诊离院必问" },
        },
        {
          npcLines: [
            "Watch his poop for the next two or three days — the sock will show up, I promise. Call us if he vomits, stops eating, or seems in pain. And maybe... keep the laundry basket closed!",
            "Sock watch begins! Check his business for 48 to 72 hours. Any vomiting, appetite loss, or pain — call us. And buy a laundry basket with a lid!",
            "Poop patrol for two or three days! No eating, vomiting, or pain means call us right away. Basket with a lid, my friend. Learn from this!",
          ],
          npcZh: "接下来两三天观察他的便便——袜子会出来的，我保证。如果呕吐、不吃饭或看起来疼就打电话。还有……洗衣篮最好盖上盖！",
          task: "苦笑接受建议，道谢",
          options: [
            { text: "Poop patrol it is — and yes, a lid for the basket. Thank you so much, truly!", ok: true, tip: "Poop patrol it is 幽默接受 + 真诚道谢——急诊毕业" },
            { text: "I will watch nothing. Ignorance is bliss.",  ok: false, tip: "接受医嘱：Poop patrol it is, thank you!" },
            { text: "The basket has been judged. It will be punished.", ok: false, tip: "幽默+感谢：Thank you so much, truly!" },
          ],
          phrase: { en: "___ it is.", zh: "那就……吧。/ 就这么办。", note: "重复对方关键词表接受；laundry basket 洗衣篮" },
        },
      ],
    },
    {
      id: "v4",
      title: "第 4 次光顾 · 宠物文化课",
      titleEn: "Pet Culture Deep Dive",
      emoji: "🇺🇸",
      desc: "美国人是把宠物当家人的：宠物保险怎么选、绝育文化、狗狗公园潜规则——文化深潜一轮。",
      reward: { en: "pet insurance", zh: "你搞懂了美式宠物文化，毛孩子生活无障碍！🐾" },
      steps: [
        {
          npcLines: [
            "Back again! What's on the agenda today?",
            "Welcome back! What are we covering this time?",
            "My favorite regulars! What brings you in?",
          ],
          npcZh: "又来啦！今天聊点什么？",
          task: "说明来意：想了解宠物保险，身边人都在买",
          options: [
            { text: "Everyone at the dog park keeps telling me to get pet insurance. Where do I even start?", ok: true, tip: "Where do I even start? 从哪儿开始——求助开放式问题" },
            { text: "Insurance for a dog? Is the dog going to drive a car now?", ok: false, tip: "开放提问：Where do I even start?" },
            { text: "Sell me the best insurance. The dog insurance of dog insurances.", ok: false, tip: "先了解：Where do I even start?" },
          ],
          phrase: { en: "Where do I even start?", zh: "我该从哪儿入手呢？", note: "even 强调无从下手；求助万能开场" },
        },
        {
          npcLines: [
            "Great question! Most plans run thirty to fifty a month. The trick is: pet insurance works backwards — you pay us, then the insurer reimburses you.",
            "The classic question! Thirty to fifty bucks monthly, usually. Here's the catch: it's pay-first, get-reimbursed-later.",
            "Ah, insurance! Monthly premiums run thirty to fifty. Heads-up though — you pay the vet, then the insurance pays you back.",
          ],
          npcZh: "好问题！多数计划每月三十到五十美元。关键点：宠物保险是反过来的——您先付给我们，保险公司再赔付给您。",
          task: "确认理解：先垫付再理赔",
          options: [
            { text: "So I pay upfront and then file a claim — got it. What does a typical plan cover?", ok: true, tip: "复述机制（pay upfront + file a claim）+ 问覆盖范围" },
            { text: "Pay first? Insurance is a scam with extra steps.",  ok: false, tip: "理解机制后问覆盖：What does a plan cover?" },
            { text: "The dog pays. He has a job. He's a model.",       ok: false, tip: "确认细节：I pay upfront and file a claim, right?" },
          ],
          phrase: { en: "What does the plan cover?", zh: "这个计划保什么？", note: "cover = 覆盖、赔付；accident-only vs comprehensive 差别巨大" },
        },
        {
          npcLines: [
            "Accidents and illness mostly — like Max's sock adventure would qualify. Routine checkups usually aren't, unless you add a wellness package.",
            "Accidents and illness — sock incidents, broken legs, cancer treatment. Checkups need the wellness add-on.",
            "The big stuff: accidents, illness, surgeries. The sock situation? Covered. Annual checkups? That's the add-on package.",
          ],
          npcZh: "主要是意外和疾病——比如 Max 的袜子冒险就能赔。常规体检一般不保，除非加购保健套餐。",
          task: "结合自身经历感慨，追问预存在病症条款",
          options: [
            { text: "The sock adventure alone would've paid for a year of premiums! What about pre-existing conditions?", ok: true, tip: "pre-existing conditions 预存在病症——保险核心条款，人有宠物险都有" },
            { text: "So insurance only covers the fun disasters. Noted.", ok: false, tip: "问关键条款：What about pre-existing conditions?" },
            { text: "Define adventure. Legally.",  ok: false, tip: "问条款：pre-existing conditions 是否赔付？" },
          ],
          phrase: { en: "What about pre-existing conditions?", zh: "已有病症怎么算？", note: "pre-existing = 投保前已存在的；多数宠物险不赔，要如实告知" },
        },
        {
          npcLines: [
            "Sharp question! Pre-existing stuff is usually excluded — another reason to insure them young, before anything develops. Speaking of young: was Max neutered?",
            "The most important question! Pre-existing conditions don't get covered — insure early, before problems start. Which reminds me: is Max neutered?",
            "You'd make a great insurance agent! Pre-existing = excluded, always. Get coverage while they're young! Now — did you neuter Max?",
          ],
          npcZh: "问得犀利！预存在病症通常不赔——所以要趁年轻、还没生病时投保。说到年轻：Max 做绝育了吗？",
          task: "回答：做了，问这在美国家庭是否普遍",
          options: [
            { text: "Yes, he was neutered as a puppy. Is that the norm here?", ok: true, tip: "neuter 绝育（公）+ Is that the norm? 这是惯例吗——文化对照提问" },
            { text: "None of your business, actually. Oh wait, it is.",  ok: false, tip: "正常交流：He was neutered as a puppy — is that the norm?" },
            { text: "He refused. We respect his choices.",                ok: false, tip: "如实回答+问文化：Is that the norm here?" },
          ],
          phrase: { en: "Is that the norm here?", zh: "这里通常是这样吗？", note: "the norm = 惯例；了解当地标准的万能文化问句" },
        },
        {
          npcLines: [
            "Absolutely — it's standard practice. It reduces health risks and behavior problems. Here, that's just part of being a responsible pet owner. Dogs are family, you know!",
            "Totally the norm! Health benefits, behavior benefits — it's what responsible owners do. Pets are family in this country!",
            "Standard as it gets! Around here, pets are basically children with fur. Neutering is just part of the deal.",
          ],
          npcZh: "完全是惯例——这是标准操作。能降低健康风险和行为问题。在这里，这是负责任宠物主人的基本操作。狗就是家人！",
          task: "询问养狗人还应该知道的文化惯例",
          options: [
            { text: "Dogs as family — I love that. Any other unwritten rules I should know as a new dog owner?", ok: true, tip: "unwritten rules 不成文规则——文化深潜核心问句" },
            { text: "Family? Max pays no rent. Coincidence?",  ok: false, tip: "求文化建议：Any other unwritten rules?" },
            { text: "I know all rules. I am basically a dog.", ok: false, tip: "虚心求教：Any unwritten rules I should know?" },
          ],
          phrase: { en: "Any unwritten rules I should know?", zh: "有什么不成文的规矩我该知道的吗？", note: "unwritten rule = 潜规则；比 custom 更口语" },
        },
        {
          npcLines: [
            "Big one: always leash your dog outside dog parks, pick up the poop — non-negotiable — and ask before letting your dog greet another dog. Not every dog wants friends!",
            "The sacred three: leash everywhere except dog parks, scoop the poop always, and ask 'Is your dog friendly?' before meet-and-greets.",
            "Three commandments! Leash up, scoop up, and always ask before dogs meet. Consent applies to dogs too, ha!",
          ],
          npcZh: "最重要的一条：除非在狗狗公园，外出必须牵绳，便便必须捡——没商量——还有让狗狗打招呼前先问对方。不是每只狗都想交朋友！",
          task: "总结确认三条铁律并道谢",
          options: [
            { text: "Leash, scoop, ask first — got it. Thanks, this has been an education!", ok: true, tip: "三连复述总结 + This has been an education 受教了——文化课毕业" },
            { text: "Rules one through three memorized. Rule four?",  ok: false, tip: "复述三铁律：Leash, scoop, ask first!" },
            { text: "My dog decides his own rules. He's a free spirit.", ok: false, tip: "接受惯例：Got it, this has been an education!" },
          ],
          phrase: { en: "This has been an education!", zh: "真是受教了！", note: "对一次有益聊天的总结式感谢；半开玩笑语气" },
        },
      ],
    },
    {
      id: "v5",
      title: "第 5 次光顾 · 慢性病与处方粮",
      titleEn: "Chronic Care & Prescription Food",
      emoji: "💊",
      desc: "Max 体检出血糖偏高：慢性病管理、处方粮、长期用药——进阶医疗英语（B1 难度）。",
      reward: { en: "dose", zh: "你掌握了慢性病长期管理的英语表达！💊" },
      steps: [
        {
          npcLines: [
            "So, Max's bloodwork came back. Overall he's healthy, but his blood sugar is running a little high.",
            "Good news and watch-out news: Max is generally healthy, but we're seeing elevated blood sugar.",
            "Let's talk results. The big picture is good — one flag, though: his blood sugar is slightly high.",
          ],
          npcZh: "Max 的血检结果出来了。总体健康，但血糖偏高。",
          task: "询问严重程度和下一步",
          options: [
            { text: "How high are we talking? What's the next step?", ok: true, tip: "How high are we talking? 到底多高（口语）+ next step 下一步——医患沟通" },
            { text: "Blood sugar? He only drinks water. Plain water!",  ok: false, tip: "问严重程度：How high? What's the next step?" },
            { text: "Is he dying? Tell me everything at once.",        ok: false, tip: "理性问询：How high, and what's the next step?" },
          ],
          phrase: { en: "How ___ are we talking?", zh: "到底有多……？", note: "…are we talking 口语强调程度；先量化再决策" },
        },
        {
          npcLines: [
            "It's in the pre-diabetic range — not diabetes yet. Caught early like this, it's often manageable with diet alone.",
            "Pre-diabetic zone — not full diabetes. The early catch means diet could fix this without medication.",
            "Pre-diabetes territory. Great that we caught it — a strict diet often turns this around, no meds needed.",
          ],
          npcZh: "处于糖尿病前期——还不是糖尿病。这么早发现，通常仅靠饮食就能控制。",
          task: "询问具体饮食方案",
          options: [
            { text: "That's a relief. What changes should we make to his diet?", ok: true, tip: "What changes should we make? 具体怎么改——慢病管理第一步" },
            { text: "Diet? He will hunger strike for justice.", ok: false, tip: "问方案：What changes should we make to his diet?" },
            { text: "Can I just describe vegetables to him?",   ok: false, tip: "务实提问：What changes to his diet?" },
          ],
          phrase: { en: "What changes should we make?", zh: "我们需要做哪些改变？", note: "should 表征求专业意见；make changes 做调整" },
        },
        {
          npcLines: [
            "High-protein, low-carb, and portion control. I'd start him on a prescription diet — it's formulated exactly for this. It costs more than regular food, but it works.",
            "The formula: high protein, low carb, measured portions. There's a prescription food made precisely for this — pricier, but effective.",
            "Prescription diet is the move: high protein, low carb, strict portions. Costs more than kibble, but that's the trade-off for results.",
          ],
          npcZh: "高蛋白、低碳水、控制份量。我建议他吃处方粮——就是为这种情况配制的。比普通粮贵，但有效。",
          task: "确认处方粮的获取方式",
          options: [
            { text: "Prescription food — do I need a prescription every time, or can I reorder online?", ok: true, tip: "reorder 再订购 + online 线上——长期用药/粮的实操问题" },
            { text: "Prescription food. Like food with a diploma.",  ok: false, tip: "实操提问：Can I reorder it online?" },
            { text: "I will write the prescription myself. I have a pen.", ok: false, tip: "问流程：Do I need a prescription every time?" },
          ],
          phrase: { en: "Do I need a prescription for ___?", zh: "买……需要处方吗？", note: "prescription 处方；宠物处方粮确实需要兽医授权" },
        },
        {
          npcLines: [
            "The prescription stays on file with us — you can reorder from our online store anytime. Now, in case diet alone isn't enough, there's a medication option too, but let's try food first.",
            "We keep it on file — reorder online as much as you need. And if the diet doesn't do the trick, there's medicine as plan B. But food first, always.",
            "One-time authorization, unlimited refills through our site. If three months of food doesn't move the needle, we discuss medication. Food first, though!",
          ],
          npcZh: "处方留在我们这存档——您随时可以在我们的网店复购。万一单靠饮食不够，还有药物方案，但咱们先试饮食。",
          task: "同意先饮食干预，问复查频率",
          options: [
            { text: "Food first sounds right. When should we recheck his blood sugar?", ok: true, tip: "recheck 复查——慢病管理需要跟踪周期" },
            { text: "Medication later, food now, dessert never. When do we recheck?", ok: false, tip: "标准问法：When should we recheck?" },
            { text: "Recheck? I have trust issues with needles.",  ok: false, tip: "问复查时间：When should we recheck his blood sugar?" },
          ],
          phrase: { en: "When should we recheck?", zh: "什么时候复查？", note: "re- 前缀 = 重新；慢病管理三件套：饮食/用药/复查" },
        },
        {
          npcLines: [
            "Three months, then we retest. If the numbers improve, we stay the course. One more thing — treats count toward carbs, by the way. That's usually the hidden culprit!",
            "Three months and we test again. Numbers better? Keep going. Oh — and those treats? Pure carbs. Usually the secret saboteur!",
            "Retest in twelve weeks. Improvement means stay the course. And I'm obligated to say: treats are carbs. The couch-side snack tax is real!",
          ],
          npcZh: "三个月后复查。如果数值改善，就继续当前方案。另外——零食也算碳水。那通常才是隐藏的元凶！",
          task: "苦笑承认零食问题，问替代方案",
          options: [
            { text: "Guilty as charged — he gets treats daily. What can I use instead?", ok: true, tip: "Guilty as charged 我认罪（幽默）+ What can I use instead? 替代方案" },
            { text: "Treats are his only joy. I refuse.",  ok: false, tip: "问替代品：What can I use instead?" },
            { text: "I will eat the treats myself. Problem solved.", ok: false, tip: "求替代方案：What can I use instead?" },
          ],
          phrase: { en: "What can I use instead?", zh: "我可以用什么来替代？", note: "instead = 代替；换方案不改目标的务实问法" },
        },
        {
          npcLines: [
            "Baby carrots, green beans, small apple pieces — dogs love them and they're low-carb. Max won't even know the difference. Well... he'll know. But he'll forgive you!",
            "Carrots, green beans, apple bits — the diabetic-friendly snack squad! He'll notice the switch. He will not approve. But he'll adjust!",
            "The holy trinity: baby carrots, green beans, apple chunks. Low-carb and dog-approved-ish! He'll sulk for a week, then come around.",
          ],
          npcZh: "小胡萝卜、西兰花豆、苹果小块——狗狗爱吃而且低碳水。Max 会发现区别的……不过他会原谅您的！",
          task: "总结方案并道谢告别",
          options: [
            { text: "Carrots and green beans it is — a small price for more healthy years together. Thank you, Doc!", ok: true, tip: "a small price for... 用小代价换…… + Thank you, Doc——慢病管理毕业" },
            { text: "He will not forgive me. I accept this.",  ok: false, tip: "总结+感谢：Carrots it is. Thank you, Doc!" },
            { text: "Years together? He is immortal. We agreed.", ok: false, tip: "理性收尾：A small price for more healthy years, thanks!" },
          ],
          phrase: { en: "A small price to pay for ___.", zh: "换取……这点代价不算什么。", note: "a small price = 微小代价；表达价值排序的金句" },
        },
      ],
    },
  ],
},
