// 宠物医院场景头 + v1-v3 词条（36 个，vet- 前缀）
{
  id: "vet",
  name: "宠物医院",
  nameEn: "Vet Clinic",
  emoji: "🐾",
  iconId: "paw",
  cover: "🐶🩺🐾",
  theme: "vet",
  accent: "#7a5a9e",
  accentSoft: "#efe8f6",
  deco: "🐾",
  deco2: "毛孩子",
  intro: "带毛孩子看兽医：预约体检、打疫苗、描述症状——宠物医疗英语全流程，还有美式宠物文化。",
  orderLabel: "🐾 就诊进度",
  items: [
    { id: "vet-appointment", en: "appointment",   zh: "预约", phon: "/əˈpɔɪntmənt/", emoji: "📅", sent: "I'd like to make an appointment." },
    { id: "vet-checkup",     en: "checkup",       zh: "体检", phon: "/ˈtʃekʌp/", emoji: "🩺", sent: "Max is here for a checkup." },
    { id: "vet-receptionist",en: "receptionist",  zh: "前台接待", phon: "/rɪˈsepʃənɪst/", emoji: "💁", sent: "The receptionist will check you in." },
    { id: "vet-checkin",     en: "check in",      zh: "报到登记", phon: "/tʃek ɪn/", emoji: "✅", sent: "Let's check in at the front desk." },
    { id: "vet-carrier",     en: "carrier",       zh: "宠物背包/航空箱", phon: "/ˈkæriə/", emoji: "🎒", sent: "Keep your cat in the carrier." },
    { id: "vet-leash",       en: "leash",         zh: "牵引绳", phon: "/liːʃ/", emoji: "🦮", sent: "Dogs must be on a leash." },
    { id: "vet-vaccine",     en: "vaccine",       zh: "疫苗", phon: "/ˈvæksiːn/", emoji: "💉", sent: "Is he up to date on vaccines?" },
    { id: "vet-shot",        en: "shot",          zh: "打针（口语）", phon: "/ʃɒt/", emoji: "💉", sent: "He needs his rabies shot." },
    { id: "vet-rabies",      en: "rabies",        zh: "狂犬病", phon: "/ˈreɪbiːz/", emoji: "🦠", sent: "The rabies vaccine is required by law." },
    { id: "vet-booster",     en: "booster",       zh: "加强针", phon: "/ˈbuːstə/", emoji: "🔁", sent: "He's due for a booster." },
    { id: "vet-record",      en: "record",        zh: "病历记录", phon: "/ˈrekɔːd/", emoji: "📋", sent: "We'll transfer his records." },
    { id: "vet-symptom",     en: "symptom",       zh: "症状", phon: "/ˈsɪmptəm/", emoji: "🤒", sent: "Describe his symptoms." },
    { id: "vet-lethargic",   en: "lethargic",     zh: "无精打采的", phon: "/ləˈθɑːdʒɪk/", emoji: "😴", sent: "He's been lethargic lately." },
    { id: "vet-appetite",    en: "appetite",      zh: "食欲", phon: "/ˈæpɪtaɪt/", emoji: "🍖", sent: "He's lost his appetite." },
    { id: "vet-vomit",       en: "vomit",         zh: "呕吐", phon: "/ˈvɒmɪt/", emoji: "🤮", sent: "She vomited twice this morning." },
    { id: "vet-diarrhea",    en: "diarrhea",      zh: "腹泻", phon: "/ˌdaɪəˈrɪə/", emoji: "🚽", sent: "The puppy has diarrhea." },
    { id: "vet-limp",        en: "limp",          zh: "跛行", phon: "/lɪmp/", emoji: "🦵", sent: "He's limping on his front leg." },
    { id: "vet-swallow",     en: "swallow",       zh: "吞下", phon: "/ˈswɒləʊ/", emoji: "😮", sent: "He swallowed a sock!" },
    { id: "vet-emergency",   en: "emergency",     zh: "急诊", phon: "/ɪˈmɜːdʒənsi/", emoji: "🚨", sent: "It's an emergency — come now!" },
    { id: "vet-xray",        en: "X-ray",         zh: "X 光", phon: "/ˈeks reɪ/", emoji: "🩻", sent: "We'll take an X-ray." },
    { id: "vet-surgery",     en: "surgery",       zh: "手术", phon: "/ˈsɜːdʒəri/", emoji: "🏥", sent: "She needs surgery right away." },
    { id: "vet-anesthesia",  en: "anesthesia",    zh: "麻醉", phon: "/ˌænəsˈθiːʒə/", emoji: "😴", sent: "He'll be under anesthesia." },
    { id: "vet-insurance",   en: "pet insurance", zh: "宠物保险", phon: "/pet ɪnˈʃʊərəns/", emoji: "🛡️", sent: "Pet insurance covers most of it." },
    { id: "vet-premium",     en: "premium",       zh: "保险费", phon: "/ˈpriːmiəm/", emoji: "💰", sent: "The monthly premium is thirty dollars." },
    { id: "vet-claim",       en: "claim",         zh: "理赔", phon: "/kleɪm/", emoji: "🧾", sent: "File a claim with your insurer." },
    { id: "vet-estimate",    en: "estimate",      zh: "费用预估", phon: "/ˈestɪmət/", emoji: "🧮", sent: "Ask for a cost estimate first." },
    { id: "vet-declined",    en: "declined",      zh: "拒绝的（申请被拒）", phon: "/dɪˈklaɪnd/", emoji: "❌", sent: "My claim was declined." },
    { id: "vet-deworm",      en: "deworming",     zh: "驱虫", phon: "/ˌdiːˈwɜːmɪŋ/", emoji: "🪱", sent: "Deworming is done every three months." },
    { id: "vet-flea",        en: "flea",          zh: "跳蚤", phon: "/fliː/", emoji: "🦗", sent: "Use monthly flea prevention." },
    { id: "vet-tick",        en: "tick",          zh: "蜱虫", phon: "/tɪk/", emoji: "🕷️", sent: "Check for ticks after hikes." },
    { id: "vet-prevention",  en: "preventive care", zh: "预防保健", phon: "/prɪˈventɪv keə/", emoji: "🛡️", sent: "Preventive care saves money." },
    { id: "vet-spay",        en: "spay",          zh: "绝育（母）", phon: "/speɪ/", emoji: "✂️", sent: "We recommend spaying at six months." },
    { id: "vet-neuter",      en: "neuter",        zh: "绝育（公）", phon: "/ˈnjuːtə/", emoji: "✂️", sent: "Neutering reduces health risks." },
    { id: "vet-fiber",       en: "fiber",         zh: "纤维", phon: "/ˈfaɪbə/", emoji: "🌾", sent: "This food has more fiber." },
    { id: "vet-dose",        en: "dose",          zh: "一剂药量", phon: "/dəʊs/", emoji: "💊", sent: "Give one dose twice a day." },
    { id: "vet-euthanasia",  en: "euthanasia",    zh: "安乐死", phon: "/ˌjuːθəˈneɪziə/", emoji: "🌈", sent: "We discussed humane euthanasia." }
  ],
  visits: [
